SELECT
SEQN as respondent_sequence_number,
CASE
    WHEN WBXFEAR = 1 THEN 'Right Ear' 
WHEN WBXFEAR = 2 THEN 'Left Ear' 
WHEN WBXFEAR IS NULL THEN NULL 
ELSE NULL 
 END as ear_tested,
WHEN WBXF001 IS NOT NULL THEN SAFE_CAST(WBXF001 AS FLOAT64)WHEN WBXF001 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_001,
WHEN WBXF002 IS NOT NULL THEN SAFE_CAST(WBXF002 AS FLOAT64)WHEN WBXF002 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_002,
WHEN WBXF003 IS NOT NULL THEN SAFE_CAST(WBXF003 AS FLOAT64)WHEN WBXF003 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_003,
WHEN WBXF004 IS NOT NULL THEN SAFE_CAST(WBXF004 AS FLOAT64)WHEN WBXF004 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_004,
WHEN WBXF005 IS NOT NULL THEN SAFE_CAST(WBXF005 AS FLOAT64)WHEN WBXF005 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_005,
WHEN WBXF006 IS NOT NULL THEN SAFE_CAST(WBXF006 AS FLOAT64)WHEN WBXF006 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_006,
WHEN WBXF007 IS NOT NULL THEN SAFE_CAST(WBXF007 AS FLOAT64)WHEN WBXF007 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_007,
WHEN WBXF008 IS NOT NULL THEN SAFE_CAST(WBXF008 AS FLOAT64)WHEN WBXF008 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_008,
WHEN WBXF009 IS NOT NULL THEN SAFE_CAST(WBXF009 AS FLOAT64)WHEN WBXF009 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_009,
WHEN WBXF010 IS NOT NULL THEN SAFE_CAST(WBXF010 AS FLOAT64)WHEN WBXF010 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_010,
WHEN WBXF011 IS NOT NULL THEN SAFE_CAST(WBXF011 AS FLOAT64)WHEN WBXF011 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_011,
WHEN WBXF012 IS NOT NULL THEN SAFE_CAST(WBXF012 AS FLOAT64)WHEN WBXF012 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_012,
WHEN WBXF013 IS NOT NULL THEN SAFE_CAST(WBXF013 AS FLOAT64)WHEN WBXF013 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_013,
WHEN WBXF014 IS NOT NULL THEN SAFE_CAST(WBXF014 AS FLOAT64)WHEN WBXF014 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_014,
WHEN WBXF015 IS NOT NULL THEN SAFE_CAST(WBXF015 AS FLOAT64)WHEN WBXF015 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_015,
WHEN WBXF016 IS NOT NULL THEN SAFE_CAST(WBXF016 AS FLOAT64)WHEN WBXF016 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_016,
WHEN WBXF017 IS NOT NULL THEN SAFE_CAST(WBXF017 AS FLOAT64)WHEN WBXF017 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_017,
WHEN WBXF018 IS NOT NULL THEN SAFE_CAST(WBXF018 AS FLOAT64)WHEN WBXF018 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_018,
WHEN WBXF019 IS NOT NULL THEN SAFE_CAST(WBXF019 AS FLOAT64)WHEN WBXF019 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_019,
WHEN WBXF020 IS NOT NULL THEN SAFE_CAST(WBXF020 AS FLOAT64)WHEN WBXF020 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_020,
WHEN WBXF021 IS NOT NULL THEN SAFE_CAST(WBXF021 AS FLOAT64)WHEN WBXF021 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_021,
WHEN WBXF022 IS NOT NULL THEN SAFE_CAST(WBXF022 AS FLOAT64)WHEN WBXF022 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_022,
WHEN WBXF023 IS NOT NULL THEN SAFE_CAST(WBXF023 AS FLOAT64)WHEN WBXF023 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_023,
WHEN WBXF024 IS NOT NULL THEN SAFE_CAST(WBXF024 AS FLOAT64)WHEN WBXF024 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_024,
WHEN WBXF025 IS NOT NULL THEN SAFE_CAST(WBXF025 AS FLOAT64)WHEN WBXF025 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_025,
WHEN WBXF026 IS NOT NULL THEN SAFE_CAST(WBXF026 AS FLOAT64)WHEN WBXF026 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_026,
WHEN WBXF027 IS NOT NULL THEN SAFE_CAST(WBXF027 AS FLOAT64)WHEN WBXF027 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_027,
WHEN WBXF028 IS NOT NULL THEN SAFE_CAST(WBXF028 AS FLOAT64)WHEN WBXF028 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_028,
WHEN WBXF029 IS NOT NULL THEN SAFE_CAST(WBXF029 AS FLOAT64)WHEN WBXF029 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_029,
WHEN WBXF030 IS NOT NULL THEN SAFE_CAST(WBXF030 AS FLOAT64)WHEN WBXF030 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_030,
WHEN WBXF031 IS NOT NULL THEN SAFE_CAST(WBXF031 AS FLOAT64)WHEN WBXF031 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_031,
WHEN WBXF032 IS NOT NULL THEN SAFE_CAST(WBXF032 AS FLOAT64)WHEN WBXF032 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_032,
WHEN WBXF033 IS NOT NULL THEN SAFE_CAST(WBXF033 AS FLOAT64)WHEN WBXF033 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_033,
WHEN WBXF034 IS NOT NULL THEN SAFE_CAST(WBXF034 AS FLOAT64)WHEN WBXF034 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_034,
WHEN WBXF035 IS NOT NULL THEN SAFE_CAST(WBXF035 AS FLOAT64)WHEN WBXF035 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_035,
WHEN WBXF036 IS NOT NULL THEN SAFE_CAST(WBXF036 AS FLOAT64)WHEN WBXF036 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_036,
WHEN WBXF037 IS NOT NULL THEN SAFE_CAST(WBXF037 AS FLOAT64)WHEN WBXF037 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_037,
WHEN WBXF038 IS NOT NULL THEN SAFE_CAST(WBXF038 AS FLOAT64)WHEN WBXF038 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_038,
WHEN WBXF039 IS NOT NULL THEN SAFE_CAST(WBXF039 AS FLOAT64)WHEN WBXF039 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_039,
WHEN WBXF040 IS NOT NULL THEN SAFE_CAST(WBXF040 AS FLOAT64)WHEN WBXF040 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_040,
WHEN WBXF041 IS NOT NULL THEN SAFE_CAST(WBXF041 AS FLOAT64)WHEN WBXF041 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_041,
WHEN WBXF042 IS NOT NULL THEN SAFE_CAST(WBXF042 AS FLOAT64)WHEN WBXF042 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_042,
WHEN WBXF043 IS NOT NULL THEN SAFE_CAST(WBXF043 AS FLOAT64)WHEN WBXF043 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_043,
WHEN WBXF044 IS NOT NULL THEN SAFE_CAST(WBXF044 AS FLOAT64)WHEN WBXF044 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_044,
WHEN WBXF045 IS NOT NULL THEN SAFE_CAST(WBXF045 AS FLOAT64)WHEN WBXF045 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_045,
WHEN WBXF046 IS NOT NULL THEN SAFE_CAST(WBXF046 AS FLOAT64)WHEN WBXF046 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_046,
WHEN WBXF047 IS NOT NULL THEN SAFE_CAST(WBXF047 AS FLOAT64)WHEN WBXF047 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_047,
WHEN WBXF048 IS NOT NULL THEN SAFE_CAST(WBXF048 AS FLOAT64)WHEN WBXF048 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_048,
WHEN WBXF049 IS NOT NULL THEN SAFE_CAST(WBXF049 AS FLOAT64)WHEN WBXF049 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_049,
WHEN WBXF050 IS NOT NULL THEN SAFE_CAST(WBXF050 AS FLOAT64)WHEN WBXF050 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_050,
WHEN WBXF051 IS NOT NULL THEN SAFE_CAST(WBXF051 AS FLOAT64)WHEN WBXF051 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_051,
WHEN WBXF052 IS NOT NULL THEN SAFE_CAST(WBXF052 AS FLOAT64)WHEN WBXF052 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_052,
WHEN WBXF053 IS NOT NULL THEN SAFE_CAST(WBXF053 AS FLOAT64)WHEN WBXF053 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_053,
WHEN WBXF054 IS NOT NULL THEN SAFE_CAST(WBXF054 AS FLOAT64)WHEN WBXF054 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_054,
WHEN WBXF055 IS NOT NULL THEN SAFE_CAST(WBXF055 AS FLOAT64)WHEN WBXF055 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_055,
WHEN WBXF056 IS NOT NULL THEN SAFE_CAST(WBXF056 AS FLOAT64)WHEN WBXF056 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_056,
WHEN WBXF057 IS NOT NULL THEN SAFE_CAST(WBXF057 AS FLOAT64)WHEN WBXF057 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_057,
WHEN WBXF058 IS NOT NULL THEN SAFE_CAST(WBXF058 AS FLOAT64)WHEN WBXF058 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_058,
WHEN WBXF059 IS NOT NULL THEN SAFE_CAST(WBXF059 AS FLOAT64)WHEN WBXF059 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_059,
WHEN WBXF060 IS NOT NULL THEN SAFE_CAST(WBXF060 AS FLOAT64)WHEN WBXF060 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_060,
WHEN WBXF061 IS NOT NULL THEN SAFE_CAST(WBXF061 AS FLOAT64)WHEN WBXF061 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_061,
WHEN WBXF062 IS NOT NULL THEN SAFE_CAST(WBXF062 AS FLOAT64)WHEN WBXF062 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_062,
WHEN WBXF063 IS NOT NULL THEN SAFE_CAST(WBXF063 AS FLOAT64)WHEN WBXF063 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_063,
WHEN WBXF064 IS NOT NULL THEN SAFE_CAST(WBXF064 AS FLOAT64)WHEN WBXF064 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_064,
WHEN WBXF065 IS NOT NULL THEN SAFE_CAST(WBXF065 AS FLOAT64)WHEN WBXF065 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_065,
WHEN WBXF066 IS NOT NULL THEN SAFE_CAST(WBXF066 AS FLOAT64)WHEN WBXF066 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_066,
WHEN WBXF067 IS NOT NULL THEN SAFE_CAST(WBXF067 AS FLOAT64)WHEN WBXF067 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_067,
WHEN WBXF068 IS NOT NULL THEN SAFE_CAST(WBXF068 AS FLOAT64)WHEN WBXF068 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_068,
WHEN WBXF069 IS NOT NULL THEN SAFE_CAST(WBXF069 AS FLOAT64)WHEN WBXF069 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_069,
WHEN WBXF070 IS NOT NULL THEN SAFE_CAST(WBXF070 AS FLOAT64)WHEN WBXF070 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_070,
WHEN WBXF071 IS NOT NULL THEN SAFE_CAST(WBXF071 AS FLOAT64)WHEN WBXF071 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_071,
WHEN WBXF072 IS NOT NULL THEN SAFE_CAST(WBXF072 AS FLOAT64)WHEN WBXF072 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_072,
WHEN WBXF073 IS NOT NULL THEN SAFE_CAST(WBXF073 AS FLOAT64)WHEN WBXF073 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_073,
WHEN WBXF074 IS NOT NULL THEN SAFE_CAST(WBXF074 AS FLOAT64)WHEN WBXF074 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_074,
WHEN WBXF075 IS NOT NULL THEN SAFE_CAST(WBXF075 AS FLOAT64)WHEN WBXF075 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_075,
WHEN WBXF076 IS NOT NULL THEN SAFE_CAST(WBXF076 AS FLOAT64)WHEN WBXF076 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_076,
WHEN WBXF077 IS NOT NULL THEN SAFE_CAST(WBXF077 AS FLOAT64)WHEN WBXF077 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_077,
WHEN WBXF078 IS NOT NULL THEN SAFE_CAST(WBXF078 AS FLOAT64)WHEN WBXF078 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_078,
WHEN WBXF079 IS NOT NULL THEN SAFE_CAST(WBXF079 AS FLOAT64)WHEN WBXF079 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_079,
WHEN WBXF080 IS NOT NULL THEN SAFE_CAST(WBXF080 AS FLOAT64)WHEN WBXF080 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_080,
WHEN WBXF081 IS NOT NULL THEN SAFE_CAST(WBXF081 AS FLOAT64)WHEN WBXF081 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_081,
WHEN WBXF082 IS NOT NULL THEN SAFE_CAST(WBXF082 AS FLOAT64)WHEN WBXF082 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_082,
WHEN WBXF083 IS NOT NULL THEN SAFE_CAST(WBXF083 AS FLOAT64)WHEN WBXF083 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_083,
WHEN WBXF084 IS NOT NULL THEN SAFE_CAST(WBXF084 AS FLOAT64)WHEN WBXF084 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_084,
WHEN WBXF085 IS NOT NULL THEN SAFE_CAST(WBXF085 AS FLOAT64)WHEN WBXF085 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_085,
WHEN WBXF086 IS NOT NULL THEN SAFE_CAST(WBXF086 AS FLOAT64)WHEN WBXF086 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_086,
WHEN WBXF087 IS NOT NULL THEN SAFE_CAST(WBXF087 AS FLOAT64)WHEN WBXF087 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_087,
WHEN WBXF088 IS NOT NULL THEN SAFE_CAST(WBXF088 AS FLOAT64)WHEN WBXF088 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_088,
WHEN WBXF089 IS NOT NULL THEN SAFE_CAST(WBXF089 AS FLOAT64)WHEN WBXF089 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_089,
WHEN WBXF090 IS NOT NULL THEN SAFE_CAST(WBXF090 AS FLOAT64)WHEN WBXF090 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_090,
WHEN WBXF091 IS NOT NULL THEN SAFE_CAST(WBXF091 AS FLOAT64)WHEN WBXF091 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_091,
WHEN WBXF092 IS NOT NULL THEN SAFE_CAST(WBXF092 AS FLOAT64)WHEN WBXF092 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_092,
WHEN WBXF093 IS NOT NULL THEN SAFE_CAST(WBXF093 AS FLOAT64)WHEN WBXF093 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_093,
WHEN WBXF094 IS NOT NULL THEN SAFE_CAST(WBXF094 AS FLOAT64)WHEN WBXF094 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_094,
WHEN WBXF095 IS NOT NULL THEN SAFE_CAST(WBXF095 AS FLOAT64)WHEN WBXF095 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_095,
WHEN WBXF096 IS NOT NULL THEN SAFE_CAST(WBXF096 AS FLOAT64)WHEN WBXF096 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_096,
WHEN WBXF097 IS NOT NULL THEN SAFE_CAST(WBXF097 AS FLOAT64)WHEN WBXF097 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_097,
WHEN WBXF098 IS NOT NULL THEN SAFE_CAST(WBXF098 AS FLOAT64)WHEN WBXF098 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_098,
WHEN WBXF099 IS NOT NULL THEN SAFE_CAST(WBXF099 AS FLOAT64)WHEN WBXF099 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_099,
WHEN WBXF100 IS NOT NULL THEN SAFE_CAST(WBXF100 AS FLOAT64)WHEN WBXF100 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_100,
WHEN WBXF101 IS NOT NULL THEN SAFE_CAST(WBXF101 AS FLOAT64)WHEN WBXF101 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_101,
WHEN WBXF102 IS NOT NULL THEN SAFE_CAST(WBXF102 AS FLOAT64)WHEN WBXF102 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_102,
WHEN WBXF103 IS NOT NULL THEN SAFE_CAST(WBXF103 AS FLOAT64)WHEN WBXF103 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_103,
WHEN WBXF104 IS NOT NULL THEN SAFE_CAST(WBXF104 AS FLOAT64)WHEN WBXF104 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_104,
WHEN WBXF105 IS NOT NULL THEN SAFE_CAST(WBXF105 AS FLOAT64)WHEN WBXF105 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_105,
WHEN WBXF106 IS NOT NULL THEN SAFE_CAST(WBXF106 AS FLOAT64)WHEN WBXF106 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_106,
WHEN WBXF107 IS NOT NULL THEN SAFE_CAST(WBXF107 AS FLOAT64)WHEN WBXF107 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_107,
WHEN WBXA001 IS NOT NULL THEN SAFE_CAST(WBXA001 AS FLOAT64)WHEN WBXA001 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_001,
WHEN WBXA002 IS NOT NULL THEN SAFE_CAST(WBXA002 AS FLOAT64)WHEN WBXA002 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_002,
WHEN WBXA003 IS NOT NULL THEN SAFE_CAST(WBXA003 AS FLOAT64)WHEN WBXA003 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_003,
WHEN WBXA004 IS NOT NULL THEN SAFE_CAST(WBXA004 AS FLOAT64)WHEN WBXA004 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_004,
WHEN WBXA005 IS NOT NULL THEN SAFE_CAST(WBXA005 AS FLOAT64)WHEN WBXA005 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_005,
WHEN WBXA006 IS NOT NULL THEN SAFE_CAST(WBXA006 AS FLOAT64)WHEN WBXA006 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_006,
WHEN WBXA007 IS NOT NULL THEN SAFE_CAST(WBXA007 AS FLOAT64)WHEN WBXA007 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_007,
WHEN WBXA008 IS NOT NULL THEN SAFE_CAST(WBXA008 AS FLOAT64)WHEN WBXA008 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_008,
WHEN WBXA009 IS NOT NULL THEN SAFE_CAST(WBXA009 AS FLOAT64)WHEN WBXA009 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_009,
WHEN WBXA010 IS NOT NULL THEN SAFE_CAST(WBXA010 AS FLOAT64)WHEN WBXA010 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_010,
WHEN WBXA011 IS NOT NULL THEN SAFE_CAST(WBXA011 AS FLOAT64)WHEN WBXA011 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_011,
WHEN WBXA012 IS NOT NULL THEN SAFE_CAST(WBXA012 AS FLOAT64)WHEN WBXA012 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_012,
WHEN WBXA013 IS NOT NULL THEN SAFE_CAST(WBXA013 AS FLOAT64)WHEN WBXA013 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_013,
WHEN WBXA014 IS NOT NULL THEN SAFE_CAST(WBXA014 AS FLOAT64)WHEN WBXA014 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_014,
WHEN WBXA015 IS NOT NULL THEN SAFE_CAST(WBXA015 AS FLOAT64)WHEN WBXA015 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_015,
WHEN WBXA016 IS NOT NULL THEN SAFE_CAST(WBXA016 AS FLOAT64)WHEN WBXA016 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_016,
WHEN WBXA017 IS NOT NULL THEN SAFE_CAST(WBXA017 AS FLOAT64)WHEN WBXA017 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_017,
WHEN WBXA018 IS NOT NULL THEN SAFE_CAST(WBXA018 AS FLOAT64)WHEN WBXA018 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_018,
WHEN WBXA019 IS NOT NULL THEN SAFE_CAST(WBXA019 AS FLOAT64)WHEN WBXA019 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_019,
WHEN WBXA020 IS NOT NULL THEN SAFE_CAST(WBXA020 AS FLOAT64)WHEN WBXA020 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_020,
WHEN WBXA021 IS NOT NULL THEN SAFE_CAST(WBXA021 AS FLOAT64)WHEN WBXA021 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_021,
WHEN WBXA022 IS NOT NULL THEN SAFE_CAST(WBXA022 AS FLOAT64)WHEN WBXA022 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_022,
WHEN WBXA023 IS NOT NULL THEN SAFE_CAST(WBXA023 AS FLOAT64)WHEN WBXA023 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_023,
WHEN WBXA024 IS NOT NULL THEN SAFE_CAST(WBXA024 AS FLOAT64)WHEN WBXA024 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_024,
WHEN WBXA025 IS NOT NULL THEN SAFE_CAST(WBXA025 AS FLOAT64)WHEN WBXA025 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_025,
WHEN WBXA026 IS NOT NULL THEN SAFE_CAST(WBXA026 AS FLOAT64)WHEN WBXA026 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_026,
WHEN WBXA027 IS NOT NULL THEN SAFE_CAST(WBXA027 AS FLOAT64)WHEN WBXA027 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_027,
WHEN WBXA028 IS NOT NULL THEN SAFE_CAST(WBXA028 AS FLOAT64)WHEN WBXA028 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_028,
WHEN WBXA029 IS NOT NULL THEN SAFE_CAST(WBXA029 AS FLOAT64)WHEN WBXA029 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_029,
WHEN WBXA030 IS NOT NULL THEN SAFE_CAST(WBXA030 AS FLOAT64)WHEN WBXA030 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_030,
WHEN WBXA031 IS NOT NULL THEN SAFE_CAST(WBXA031 AS FLOAT64)WHEN WBXA031 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_031,
WHEN WBXA032 IS NOT NULL THEN SAFE_CAST(WBXA032 AS FLOAT64)WHEN WBXA032 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_032,
WHEN WBXA033 IS NOT NULL THEN SAFE_CAST(WBXA033 AS FLOAT64)WHEN WBXA033 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_033,
WHEN WBXA034 IS NOT NULL THEN SAFE_CAST(WBXA034 AS FLOAT64)WHEN WBXA034 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_034,
WHEN WBXA035 IS NOT NULL THEN SAFE_CAST(WBXA035 AS FLOAT64)WHEN WBXA035 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_035,
WHEN WBXA036 IS NOT NULL THEN SAFE_CAST(WBXA036 AS FLOAT64)WHEN WBXA036 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_036,
WHEN WBXA037 IS NOT NULL THEN SAFE_CAST(WBXA037 AS FLOAT64)WHEN WBXA037 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_037,
WHEN WBXA038 IS NOT NULL THEN SAFE_CAST(WBXA038 AS FLOAT64)WHEN WBXA038 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_038,
WHEN WBXA039 IS NOT NULL THEN SAFE_CAST(WBXA039 AS FLOAT64)WHEN WBXA039 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_039,
WHEN WBXA040 IS NOT NULL THEN SAFE_CAST(WBXA040 AS FLOAT64)WHEN WBXA040 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_040,
WHEN WBXA041 IS NOT NULL THEN SAFE_CAST(WBXA041 AS FLOAT64)WHEN WBXA041 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_041,
WHEN WBXA042 IS NOT NULL THEN SAFE_CAST(WBXA042 AS FLOAT64)WHEN WBXA042 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_042,
WHEN WBXA043 IS NOT NULL THEN SAFE_CAST(WBXA043 AS FLOAT64)WHEN WBXA043 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_043,
WHEN WBXA044 IS NOT NULL THEN SAFE_CAST(WBXA044 AS FLOAT64)WHEN WBXA044 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_044,
WHEN WBXA045 IS NOT NULL THEN SAFE_CAST(WBXA045 AS FLOAT64)WHEN WBXA045 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_045,
WHEN WBXA046 IS NOT NULL THEN SAFE_CAST(WBXA046 AS FLOAT64)WHEN WBXA046 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_046,
WHEN WBXA047 IS NOT NULL THEN SAFE_CAST(WBXA047 AS FLOAT64)WHEN WBXA047 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_047,
WHEN WBXA048 IS NOT NULL THEN SAFE_CAST(WBXA048 AS FLOAT64)WHEN WBXA048 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_048,
WHEN WBXA049 IS NOT NULL THEN SAFE_CAST(WBXA049 AS FLOAT64)WHEN WBXA049 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_049,
WHEN WBXA050 IS NOT NULL THEN SAFE_CAST(WBXA050 AS FLOAT64)WHEN WBXA050 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_050,
WHEN WBXA051 IS NOT NULL THEN SAFE_CAST(WBXA051 AS FLOAT64)WHEN WBXA051 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_051,
WHEN WBXA052 IS NOT NULL THEN SAFE_CAST(WBXA052 AS FLOAT64)WHEN WBXA052 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_052,
WHEN WBXA053 IS NOT NULL THEN SAFE_CAST(WBXA053 AS FLOAT64)WHEN WBXA053 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_053,
WHEN WBXA054 IS NOT NULL THEN SAFE_CAST(WBXA054 AS FLOAT64)WHEN WBXA054 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_054,
WHEN WBXA055 IS NOT NULL THEN SAFE_CAST(WBXA055 AS FLOAT64)WHEN WBXA055 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_055,
WHEN WBXA056 IS NOT NULL THEN SAFE_CAST(WBXA056 AS FLOAT64)WHEN WBXA056 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_056,
WHEN WBXA057 IS NOT NULL THEN SAFE_CAST(WBXA057 AS FLOAT64)WHEN WBXA057 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_057,
WHEN WBXA058 IS NOT NULL THEN SAFE_CAST(WBXA058 AS FLOAT64)WHEN WBXA058 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_058,
WHEN WBXA059 IS NOT NULL THEN SAFE_CAST(WBXA059 AS FLOAT64)WHEN WBXA059 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_059,
WHEN WBXA060 IS NOT NULL THEN SAFE_CAST(WBXA060 AS FLOAT64)WHEN WBXA060 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_060,
WHEN WBXA061 IS NOT NULL THEN SAFE_CAST(WBXA061 AS FLOAT64)WHEN WBXA061 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_061,
WHEN WBXA062 IS NOT NULL THEN SAFE_CAST(WBXA062 AS FLOAT64)WHEN WBXA062 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_062,
WHEN WBXA063 IS NOT NULL THEN SAFE_CAST(WBXA063 AS FLOAT64)WHEN WBXA063 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_063,
WHEN WBXA064 IS NOT NULL THEN SAFE_CAST(WBXA064 AS FLOAT64)WHEN WBXA064 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_064,
WHEN WBXA065 IS NOT NULL THEN SAFE_CAST(WBXA065 AS FLOAT64)WHEN WBXA065 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_065,
WHEN WBXA066 IS NOT NULL THEN SAFE_CAST(WBXA066 AS FLOAT64)WHEN WBXA066 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_066,
WHEN WBXA067 IS NOT NULL THEN SAFE_CAST(WBXA067 AS FLOAT64)WHEN WBXA067 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_067,
WHEN WBXA068 IS NOT NULL THEN SAFE_CAST(WBXA068 AS FLOAT64)WHEN WBXA068 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_068,
WHEN WBXA069 IS NOT NULL THEN SAFE_CAST(WBXA069 AS FLOAT64)WHEN WBXA069 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_069,
WHEN WBXA070 IS NOT NULL THEN SAFE_CAST(WBXA070 AS FLOAT64)WHEN WBXA070 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_070,
WHEN WBXA071 IS NOT NULL THEN SAFE_CAST(WBXA071 AS FLOAT64)WHEN WBXA071 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_071,
WHEN WBXA072 IS NOT NULL THEN SAFE_CAST(WBXA072 AS FLOAT64)WHEN WBXA072 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_072,
WHEN WBXA073 IS NOT NULL THEN SAFE_CAST(WBXA073 AS FLOAT64)WHEN WBXA073 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_073,
WHEN WBXA074 IS NOT NULL THEN SAFE_CAST(WBXA074 AS FLOAT64)WHEN WBXA074 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_074,
WHEN WBXA075 IS NOT NULL THEN SAFE_CAST(WBXA075 AS FLOAT64)WHEN WBXA075 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_075,
WHEN WBXA076 IS NOT NULL THEN SAFE_CAST(WBXA076 AS FLOAT64)WHEN WBXA076 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_076,
WHEN WBXA077 IS NOT NULL THEN SAFE_CAST(WBXA077 AS FLOAT64)WHEN WBXA077 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_077,
WHEN WBXA078 IS NOT NULL THEN SAFE_CAST(WBXA078 AS FLOAT64)WHEN WBXA078 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_078,
WHEN WBXA079 IS NOT NULL THEN SAFE_CAST(WBXA079 AS FLOAT64)WHEN WBXA079 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_079,
WHEN WBXA080 IS NOT NULL THEN SAFE_CAST(WBXA080 AS FLOAT64)WHEN WBXA080 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_080,
WHEN WBXA081 IS NOT NULL THEN SAFE_CAST(WBXA081 AS FLOAT64)WHEN WBXA081 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_081,
WHEN WBXA082 IS NOT NULL THEN SAFE_CAST(WBXA082 AS FLOAT64)WHEN WBXA082 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_082,
WHEN WBXA083 IS NOT NULL THEN SAFE_CAST(WBXA083 AS FLOAT64)WHEN WBXA083 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_083,
WHEN WBXA084 IS NOT NULL THEN SAFE_CAST(WBXA084 AS FLOAT64)WHEN WBXA084 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_084,
WHEN WBXA085 IS NOT NULL THEN SAFE_CAST(WBXA085 AS FLOAT64)WHEN WBXA085 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_085,
WHEN WBXA086 IS NOT NULL THEN SAFE_CAST(WBXA086 AS FLOAT64)WHEN WBXA086 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_086,
WHEN WBXA087 IS NOT NULL THEN SAFE_CAST(WBXA087 AS FLOAT64)WHEN WBXA087 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_087,
WHEN WBXA088 IS NOT NULL THEN SAFE_CAST(WBXA088 AS FLOAT64)WHEN WBXA088 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_088,
WHEN WBXA089 IS NOT NULL THEN SAFE_CAST(WBXA089 AS FLOAT64)WHEN WBXA089 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_089,
WHEN WBXA090 IS NOT NULL THEN SAFE_CAST(WBXA090 AS FLOAT64)WHEN WBXA090 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_090,
WHEN WBXA091 IS NOT NULL THEN SAFE_CAST(WBXA091 AS FLOAT64)WHEN WBXA091 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_091,
WHEN WBXA092 IS NOT NULL THEN SAFE_CAST(WBXA092 AS FLOAT64)WHEN WBXA092 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_092,
WHEN WBXA093 IS NOT NULL THEN SAFE_CAST(WBXA093 AS FLOAT64)WHEN WBXA093 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_093,
WHEN WBXA094 IS NOT NULL THEN SAFE_CAST(WBXA094 AS FLOAT64)WHEN WBXA094 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_094,
WHEN WBXA095 IS NOT NULL THEN SAFE_CAST(WBXA095 AS FLOAT64)WHEN WBXA095 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_095,
WHEN WBXA096 IS NOT NULL THEN SAFE_CAST(WBXA096 AS FLOAT64)WHEN WBXA096 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_096,
WHEN WBXA097 IS NOT NULL THEN SAFE_CAST(WBXA097 AS FLOAT64)WHEN WBXA097 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_097,
WHEN WBXA098 IS NOT NULL THEN SAFE_CAST(WBXA098 AS FLOAT64)WHEN WBXA098 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_098,
WHEN WBXA099 IS NOT NULL THEN SAFE_CAST(WBXA099 AS FLOAT64)WHEN WBXA099 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_099,
WHEN WBXA100 IS NOT NULL THEN SAFE_CAST(WBXA100 AS FLOAT64)WHEN WBXA100 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_100,
WHEN WBXA101 IS NOT NULL THEN SAFE_CAST(WBXA101 AS FLOAT64)WHEN WBXA101 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_101,
WHEN WBXA102 IS NOT NULL THEN SAFE_CAST(WBXA102 AS FLOAT64)WHEN WBXA102 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_102,
WHEN WBXA103 IS NOT NULL THEN SAFE_CAST(WBXA103 AS FLOAT64)WHEN WBXA103 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_103,
WHEN WBXA104 IS NOT NULL THEN SAFE_CAST(WBXA104 AS FLOAT64)WHEN WBXA104 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_104,
WHEN WBXA105 IS NOT NULL THEN SAFE_CAST(WBXA105 AS FLOAT64)WHEN WBXA105 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_105,
WHEN WBXA106 IS NOT NULL THEN SAFE_CAST(WBXA106 AS FLOAT64)WHEN WBXA106 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_106,
WHEN WBXA107 IS NOT NULL THEN SAFE_CAST(WBXA107 AS FLOAT64)WHEN WBXA107 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_107,
WHEN WBXP001 IS NOT NULL THEN SAFE_CAST(WBXP001 AS FLOAT64)WHEN WBXP001 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_001,
WHEN WBXP002 IS NOT NULL THEN SAFE_CAST(WBXP002 AS FLOAT64)WHEN WBXP002 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_002,
WHEN WBXP003 IS NOT NULL THEN SAFE_CAST(WBXP003 AS FLOAT64)WHEN WBXP003 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_003,
WHEN WBXP004 IS NOT NULL THEN SAFE_CAST(WBXP004 AS FLOAT64)WHEN WBXP004 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_004,
WHEN WBXP005 IS NOT NULL THEN SAFE_CAST(WBXP005 AS FLOAT64)WHEN WBXP005 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_005,
WHEN WBXP006 IS NOT NULL THEN SAFE_CAST(WBXP006 AS FLOAT64)WHEN WBXP006 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_006,
WHEN WBXP007 IS NOT NULL THEN SAFE_CAST(WBXP007 AS FLOAT64)WHEN WBXP007 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_007,
WHEN WBXP008 IS NOT NULL THEN SAFE_CAST(WBXP008 AS FLOAT64)WHEN WBXP008 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_008,
WHEN WBXP009 IS NOT NULL THEN SAFE_CAST(WBXP009 AS FLOAT64)WHEN WBXP009 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_009,
WHEN WBXP010 IS NOT NULL THEN SAFE_CAST(WBXP010 AS FLOAT64)WHEN WBXP010 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_010,
WHEN WBXP011 IS NOT NULL THEN SAFE_CAST(WBXP011 AS FLOAT64)WHEN WBXP011 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_011,
WHEN WBXP012 IS NOT NULL THEN SAFE_CAST(WBXP012 AS FLOAT64)WHEN WBXP012 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_012,
WHEN WBXP013 IS NOT NULL THEN SAFE_CAST(WBXP013 AS FLOAT64)WHEN WBXP013 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_013,
WHEN WBXP014 IS NOT NULL THEN SAFE_CAST(WBXP014 AS FLOAT64)WHEN WBXP014 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_014,
WHEN WBXP015 IS NOT NULL THEN SAFE_CAST(WBXP015 AS FLOAT64)WHEN WBXP015 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_015,
WHEN WBXP016 IS NOT NULL THEN SAFE_CAST(WBXP016 AS FLOAT64)WHEN WBXP016 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_016,
WHEN WBXP017 IS NOT NULL THEN SAFE_CAST(WBXP017 AS FLOAT64)WHEN WBXP017 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_017,
WHEN WBXP018 IS NOT NULL THEN SAFE_CAST(WBXP018 AS FLOAT64)WHEN WBXP018 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_018,
WHEN WBXP019 IS NOT NULL THEN SAFE_CAST(WBXP019 AS FLOAT64)WHEN WBXP019 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_019,
WHEN WBXP020 IS NOT NULL THEN SAFE_CAST(WBXP020 AS FLOAT64)WHEN WBXP020 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_020,
WHEN WBXP021 IS NOT NULL THEN SAFE_CAST(WBXP021 AS FLOAT64)WHEN WBXP021 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_021,
WHEN WBXP022 IS NOT NULL THEN SAFE_CAST(WBXP022 AS FLOAT64)WHEN WBXP022 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_022,
WHEN WBXP023 IS NOT NULL THEN SAFE_CAST(WBXP023 AS FLOAT64)WHEN WBXP023 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_023,
WHEN WBXP024 IS NOT NULL THEN SAFE_CAST(WBXP024 AS FLOAT64)WHEN WBXP024 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_024,
WHEN WBXP025 IS NOT NULL THEN SAFE_CAST(WBXP025 AS FLOAT64)WHEN WBXP025 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_025,
WHEN WBXP026 IS NOT NULL THEN SAFE_CAST(WBXP026 AS FLOAT64)WHEN WBXP026 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_026,
WHEN WBXP027 IS NOT NULL THEN SAFE_CAST(WBXP027 AS FLOAT64)WHEN WBXP027 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_027,
WHEN WBXP028 IS NOT NULL THEN SAFE_CAST(WBXP028 AS FLOAT64)WHEN WBXP028 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_028,
WHEN WBXP029 IS NOT NULL THEN SAFE_CAST(WBXP029 AS FLOAT64)WHEN WBXP029 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_029,
WHEN WBXP030 IS NOT NULL THEN SAFE_CAST(WBXP030 AS FLOAT64)WHEN WBXP030 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_030,
WHEN WBXP031 IS NOT NULL THEN SAFE_CAST(WBXP031 AS FLOAT64)WHEN WBXP031 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_031,
WHEN WBXP032 IS NOT NULL THEN SAFE_CAST(WBXP032 AS FLOAT64)WHEN WBXP032 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_032,
WHEN WBXP033 IS NOT NULL THEN SAFE_CAST(WBXP033 AS FLOAT64)WHEN WBXP033 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_033,
WHEN WBXP034 IS NOT NULL THEN SAFE_CAST(WBXP034 AS FLOAT64)WHEN WBXP034 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_034,
WHEN WBXP035 IS NOT NULL THEN SAFE_CAST(WBXP035 AS FLOAT64)WHEN WBXP035 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_035,
WHEN WBXP036 IS NOT NULL THEN SAFE_CAST(WBXP036 AS FLOAT64)WHEN WBXP036 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_036,
WHEN WBXP037 IS NOT NULL THEN SAFE_CAST(WBXP037 AS FLOAT64)WHEN WBXP037 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_037,
WHEN WBXP038 IS NOT NULL THEN SAFE_CAST(WBXP038 AS FLOAT64)WHEN WBXP038 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_038,
WHEN WBXP039 IS NOT NULL THEN SAFE_CAST(WBXP039 AS FLOAT64)WHEN WBXP039 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_039,
WHEN WBXP040 IS NOT NULL THEN SAFE_CAST(WBXP040 AS FLOAT64)WHEN WBXP040 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_040,
WHEN WBXP041 IS NOT NULL THEN SAFE_CAST(WBXP041 AS FLOAT64)WHEN WBXP041 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_041,
WHEN WBXP042 IS NOT NULL THEN SAFE_CAST(WBXP042 AS FLOAT64)WHEN WBXP042 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_042,
WHEN WBXP043 IS NOT NULL THEN SAFE_CAST(WBXP043 AS FLOAT64)WHEN WBXP043 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_043,
WHEN WBXP044 IS NOT NULL THEN SAFE_CAST(WBXP044 AS FLOAT64)WHEN WBXP044 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_044,
WHEN WBXP045 IS NOT NULL THEN SAFE_CAST(WBXP045 AS FLOAT64)WHEN WBXP045 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_045,
WHEN WBXP046 IS NOT NULL THEN SAFE_CAST(WBXP046 AS FLOAT64)WHEN WBXP046 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_046,
WHEN WBXP047 IS NOT NULL THEN SAFE_CAST(WBXP047 AS FLOAT64)WHEN WBXP047 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_047,
WHEN WBXP048 IS NOT NULL THEN SAFE_CAST(WBXP048 AS FLOAT64)WHEN WBXP048 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_048,
WHEN WBXP049 IS NOT NULL THEN SAFE_CAST(WBXP049 AS FLOAT64)WHEN WBXP049 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_049,
WHEN WBXP050 IS NOT NULL THEN SAFE_CAST(WBXP050 AS FLOAT64)WHEN WBXP050 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_050,
WHEN WBXP051 IS NOT NULL THEN SAFE_CAST(WBXP051 AS FLOAT64)WHEN WBXP051 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_051,
WHEN WBXP052 IS NOT NULL THEN SAFE_CAST(WBXP052 AS FLOAT64)WHEN WBXP052 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_052,
WHEN WBXP053 IS NOT NULL THEN SAFE_CAST(WBXP053 AS FLOAT64)WHEN WBXP053 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_053,
WHEN WBXP054 IS NOT NULL THEN SAFE_CAST(WBXP054 AS FLOAT64)WHEN WBXP054 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_054,
WHEN WBXP055 IS NOT NULL THEN SAFE_CAST(WBXP055 AS FLOAT64)WHEN WBXP055 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_055,
WHEN WBXP056 IS NOT NULL THEN SAFE_CAST(WBXP056 AS FLOAT64)WHEN WBXP056 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_056,
WHEN WBXP057 IS NOT NULL THEN SAFE_CAST(WBXP057 AS FLOAT64)WHEN WBXP057 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_057,
WHEN WBXP058 IS NOT NULL THEN SAFE_CAST(WBXP058 AS FLOAT64)WHEN WBXP058 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_058,
WHEN WBXP059 IS NOT NULL THEN SAFE_CAST(WBXP059 AS FLOAT64)WHEN WBXP059 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_059,
WHEN WBXP060 IS NOT NULL THEN SAFE_CAST(WBXP060 AS FLOAT64)WHEN WBXP060 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_060,
WHEN WBXP061 IS NOT NULL THEN SAFE_CAST(WBXP061 AS FLOAT64)WHEN WBXP061 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_061,
WHEN WBXP062 IS NOT NULL THEN SAFE_CAST(WBXP062 AS FLOAT64)WHEN WBXP062 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_062,
WHEN WBXP063 IS NOT NULL THEN SAFE_CAST(WBXP063 AS FLOAT64)WHEN WBXP063 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_063,
WHEN WBXP064 IS NOT NULL THEN SAFE_CAST(WBXP064 AS FLOAT64)WHEN WBXP064 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_064,
WHEN WBXP065 IS NOT NULL THEN SAFE_CAST(WBXP065 AS FLOAT64)WHEN WBXP065 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_065,
WHEN WBXP066 IS NOT NULL THEN SAFE_CAST(WBXP066 AS FLOAT64)WHEN WBXP066 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_066,
WHEN WBXP067 IS NOT NULL THEN SAFE_CAST(WBXP067 AS FLOAT64)WHEN WBXP067 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_067,
WHEN WBXP068 IS NOT NULL THEN SAFE_CAST(WBXP068 AS FLOAT64)WHEN WBXP068 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_068,
WHEN WBXP069 IS NOT NULL THEN SAFE_CAST(WBXP069 AS FLOAT64)WHEN WBXP069 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_069,
WHEN WBXP070 IS NOT NULL THEN SAFE_CAST(WBXP070 AS FLOAT64)WHEN WBXP070 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_070,
WHEN WBXP071 IS NOT NULL THEN SAFE_CAST(WBXP071 AS FLOAT64)WHEN WBXP071 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_071,
WHEN WBXP072 IS NOT NULL THEN SAFE_CAST(WBXP072 AS FLOAT64)WHEN WBXP072 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_072,
WHEN WBXP073 IS NOT NULL THEN SAFE_CAST(WBXP073 AS FLOAT64)WHEN WBXP073 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_073,
WHEN WBXP074 IS NOT NULL THEN SAFE_CAST(WBXP074 AS FLOAT64)WHEN WBXP074 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_074,
WHEN WBXP075 IS NOT NULL THEN SAFE_CAST(WBXP075 AS FLOAT64)WHEN WBXP075 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_075,
WHEN WBXP076 IS NOT NULL THEN SAFE_CAST(WBXP076 AS FLOAT64)WHEN WBXP076 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_076,
WHEN WBXP077 IS NOT NULL THEN SAFE_CAST(WBXP077 AS FLOAT64)WHEN WBXP077 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_077,
WHEN WBXP078 IS NOT NULL THEN SAFE_CAST(WBXP078 AS FLOAT64)WHEN WBXP078 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_078,
WHEN WBXP079 IS NOT NULL THEN SAFE_CAST(WBXP079 AS FLOAT64)WHEN WBXP079 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_079,
WHEN WBXP080 IS NOT NULL THEN SAFE_CAST(WBXP080 AS FLOAT64)WHEN WBXP080 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_080,
WHEN WBXP081 IS NOT NULL THEN SAFE_CAST(WBXP081 AS FLOAT64)WHEN WBXP081 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_081,
WHEN WBXP082 IS NOT NULL THEN SAFE_CAST(WBXP082 AS FLOAT64)WHEN WBXP082 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_082,
WHEN WBXP083 IS NOT NULL THEN SAFE_CAST(WBXP083 AS FLOAT64)WHEN WBXP083 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_083,
WHEN WBXP084 IS NOT NULL THEN SAFE_CAST(WBXP084 AS FLOAT64)WHEN WBXP084 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_084,
WHEN WBXP085 IS NOT NULL THEN SAFE_CAST(WBXP085 AS FLOAT64)WHEN WBXP085 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_085,
WHEN WBXP086 IS NOT NULL THEN SAFE_CAST(WBXP086 AS FLOAT64)WHEN WBXP086 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_086,
WHEN WBXP087 IS NOT NULL THEN SAFE_CAST(WBXP087 AS FLOAT64)WHEN WBXP087 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_087,
WHEN WBXP088 IS NOT NULL THEN SAFE_CAST(WBXP088 AS FLOAT64)WHEN WBXP088 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_088,
WHEN WBXP089 IS NOT NULL THEN SAFE_CAST(WBXP089 AS FLOAT64)WHEN WBXP089 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_089,
WHEN WBXP090 IS NOT NULL THEN SAFE_CAST(WBXP090 AS FLOAT64)WHEN WBXP090 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_090,
WHEN WBXP091 IS NOT NULL THEN SAFE_CAST(WBXP091 AS FLOAT64)WHEN WBXP091 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_091,
WHEN WBXP092 IS NOT NULL THEN SAFE_CAST(WBXP092 AS FLOAT64)WHEN WBXP092 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_092,
WHEN WBXP093 IS NOT NULL THEN SAFE_CAST(WBXP093 AS FLOAT64)WHEN WBXP093 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_093,
WHEN WBXP094 IS NOT NULL THEN SAFE_CAST(WBXP094 AS FLOAT64)WHEN WBXP094 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_094,
WHEN WBXP095 IS NOT NULL THEN SAFE_CAST(WBXP095 AS FLOAT64)WHEN WBXP095 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_095,
WHEN WBXP096 IS NOT NULL THEN SAFE_CAST(WBXP096 AS FLOAT64)WHEN WBXP096 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_096,
WHEN WBXP097 IS NOT NULL THEN SAFE_CAST(WBXP097 AS FLOAT64)WHEN WBXP097 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_097,
WHEN WBXP098 IS NOT NULL THEN SAFE_CAST(WBXP098 AS FLOAT64)WHEN WBXP098 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_098,
WHEN WBXP099 IS NOT NULL THEN SAFE_CAST(WBXP099 AS FLOAT64)WHEN WBXP099 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_099,
WHEN WBXP100 IS NOT NULL THEN SAFE_CAST(WBXP100 AS FLOAT64)WHEN WBXP100 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_100,
WHEN WBXP101 IS NOT NULL THEN SAFE_CAST(WBXP101 AS FLOAT64)WHEN WBXP101 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_101,
WHEN WBXP102 IS NOT NULL THEN SAFE_CAST(WBXP102 AS FLOAT64)WHEN WBXP102 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_102,
WHEN WBXP103 IS NOT NULL THEN SAFE_CAST(WBXP103 AS FLOAT64)WHEN WBXP103 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_103,
WHEN WBXP104 IS NOT NULL THEN SAFE_CAST(WBXP104 AS FLOAT64)WHEN WBXP104 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_104,
WHEN WBXP105 IS NOT NULL THEN SAFE_CAST(WBXP105 AS FLOAT64)WHEN WBXP105 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_105,
WHEN WBXP106 IS NOT NULL THEN SAFE_CAST(WBXP106 AS FLOAT64)WHEN WBXP106 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_106,
WHEN WBXP107 IS NOT NULL THEN SAFE_CAST(WBXP107 AS FLOAT64)WHEN WBXP107 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_107,
 FROM {ref('stg_audiometry_wideband_reflectance_examination'})