SELECT
SEQN as respondent_sequence_number,
WHEN WTSAF2YR IS NOT NULL THEN SAFE_CAST(WTSAF2YR AS FLOAT64)WHEN WTSAF2YR IS NULL THEN NULL 
ELSE NULL 
 END as fasting_subsample_2_year_mec_weight,
WHEN LBXTR IS NOT NULL THEN SAFE_CAST(LBXTR AS FLOAT64)WHEN LBXTR IS NULL THEN NULL 
ELSE NULL 
 END as triglyceride_mg_dl,
WHEN LBDTRSI IS NOT NULL THEN SAFE_CAST(LBDTRSI AS FLOAT64)WHEN LBDTRSI IS NULL THEN NULL 
ELSE NULL 
 END as triglyceride_mmol_l,
WHEN LBDLDL IS NOT NULL THEN SAFE_CAST(LBDLDL AS FLOAT64)WHEN LBDLDL IS NULL THEN NULL 
ELSE NULL 
 END as ldl_cholesterol_friedewald_mg_dl,
WHEN LBDLDLSI IS NOT NULL THEN SAFE_CAST(LBDLDLSI AS FLOAT64)WHEN LBDLDLSI IS NULL THEN NULL 
ELSE NULL 
 END as ldl_cholesterol_friedewald_mmol_l,
WHEN LBDLDLM IS NOT NULL THEN SAFE_CAST(LBDLDLM AS FLOAT64)WHEN LBDLDLM IS NULL THEN NULL 
ELSE NULL 
 END as ldl_cholesterol_martin_hopkins_mg_dl,
WHEN LBDLDMSI IS NOT NULL THEN SAFE_CAST(LBDLDMSI AS FLOAT64)WHEN LBDLDMSI IS NULL THEN NULL 
ELSE NULL 
 END as ldl_cholesterol_martin_hopkins_mmol_l,
WHEN LBDLDLN IS NOT NULL THEN SAFE_CAST(LBDLDLN AS FLOAT64)WHEN LBDLDLN IS NULL THEN NULL 
ELSE NULL 
 END as ldl_cholesterol_nih_equation_2_mg_dl,
WHEN LBDLDNSI IS NOT NULL THEN SAFE_CAST(LBDLDNSI AS FLOAT64)WHEN LBDLDNSI IS NULL THEN NULL 
ELSE NULL 
 END as ldl_cholesterol_nih_equation_2_mmol_l,
 FROM {ref('stg_cholesterol_low_density_lipoproteins_ldl_triglycerides_laboratory'})