SELECT
SEQN as respondent_sequence_number,
WHEN WTDRD1 IS NOT NULL THEN SAFE_CAST(WTDRD1 AS FLOAT64)WHEN WTDRD1 IS NULL THEN NULL 
ELSE NULL 
 END as dietary_day_one_sample_weight,
WHEN WTDR2D IS NOT NULL THEN SAFE_CAST(WTDR2D AS FLOAT64)WHEN WTDR2D IS NULL THEN NULL 
ELSE NULL 
 END as dietary_two_day_sample_weight,
CASE
    WHEN DR2DRSTZ = 1 THEN 'Reliable and met the minimum criteria' 
WHEN DR2DRSTZ = 2 THEN 'Not reliable or not met the minimum criteria' 
WHEN DR2DRSTZ = 4 THEN 'Reported consuming breast-milk' 
WHEN DR2DRSTZ = 5 THEN 'Not done' 
WHEN DR2DRSTZ IS NULL THEN NULL 
ELSE NULL 
 END as dietary_recall_status,
WHEN DR2EXMER IS NOT NULL THEN SAFE_CAST(DR2EXMER AS FLOAT64)WHEN DR2EXMER IS NULL THEN NULL 
ELSE NULL 
 END as interviewer_id_code,
CASE
    WHEN DRABF = 1 THEN 'Yes' 
WHEN DRABF = 2 THEN 'No' 
WHEN DRABF IS NULL THEN NULL 
ELSE NULL 
 END as breast_fed_infant_either_day,
CASE
    WHEN DRDINT = 1 THEN 'Day 1 only' 
WHEN DRDINT = 2 THEN 'Day 1 and day 2' 
WHEN DRDINT IS NULL THEN NULL 
ELSE NULL 
 END as number_of_days_of_intake,
WHEN DR2DBIH IS NOT NULL THEN SAFE_CAST(DR2DBIH AS FLOAT64)WHEN DR2DBIH IS NULL THEN NULL 
ELSE NULL 
 END as of_days_b_w_intake_and_hh_interview,
CASE
    WHEN DR2DAY = 1 THEN 'Sunday' 
WHEN DR2DAY = 2 THEN 'Monday' 
WHEN DR2DAY = 3 THEN 'Tuesday' 
WHEN DR2DAY = 4 THEN 'Wednesday' 
WHEN DR2DAY = 5 THEN 'Thursday' 
WHEN DR2DAY = 6 THEN 'Friday' 
WHEN DR2DAY = 7 THEN 'Saturday' 
WHEN DR2DAY IS NULL THEN NULL 
ELSE NULL 
 END as intake_day_of_the_week,
CASE
    WHEN DR2LANG = 1 THEN 'English' 
WHEN DR2LANG = 2 THEN 'Spanish' 
WHEN DR2LANG = 3 THEN 'English and Spanish' 
WHEN DR2LANG = 4 THEN 'Other' 
WHEN DR2LANG = 5 THEN 'Asian Languages' 
WHEN DR2LANG = 6 THEN 'Asian Languages and English' 
WHEN DR2LANG IS NULL THEN NULL 
ELSE NULL 
 END as language_respondent_used_mostly,
CASE
    WHEN DR2MRESP = 1 THEN 'SP' 
WHEN DR2MRESP = 2 THEN 'Mother of SP' 
WHEN DR2MRESP = 3 THEN 'Father of SP' 
WHEN DR2MRESP = 5 THEN 'Spouse of SP' 
WHEN DR2MRESP = 6 THEN 'Child of SP' 
WHEN DR2MRESP = 7 THEN 'Grandparent of SP' 
WHEN DR2MRESP = 8 THEN 'Friend, Partner, Non Relative' 
WHEN DR2MRESP = 9 THEN 'Translator, not a HH member' 
WHEN DR2MRESP = 10 THEN 'Child care provider, Caretaker' 
WHEN DR2MRESP = 11 THEN 'Other Relative' 
WHEN DR2MRESP = 77 THEN 'Refused' 
WHEN DR2MRESP = 99 THEN 'Don't know' 
WHEN DR2MRESP IS NULL THEN NULL 
ELSE NULL 
 END as main_respondent_for_this_interview,
CASE
    WHEN DR2HELP = 1 THEN 'SP' 
WHEN DR2HELP = 4 THEN 'Parent of SP' 
WHEN DR2HELP = 5 THEN 'Spouse of SP' 
WHEN DR2HELP = 6 THEN 'Child of SP' 
WHEN DR2HELP = 7 THEN 'Grandparent of SP' 
WHEN DR2HELP = 8 THEN 'Friend, Partner, Non Relative' 
WHEN DR2HELP = 9 THEN 'Translator, not a HH member' 
WHEN DR2HELP = 10 THEN 'Child care provider, Caretaker' 
WHEN DR2HELP = 11 THEN 'Other Relative' 
WHEN DR2HELP = 12 THEN 'No One' 
WHEN DR2HELP = 77 THEN 'Refused' 
WHEN DR2HELP = 99 THEN 'Don't know' 
WHEN DR2HELP IS NULL THEN NULL 
ELSE NULL 
 END as helped_in_responding_for_this_interview,
WHEN DR2TNUMF IS NOT NULL THEN SAFE_CAST(DR2TNUMF AS FLOAT64)WHEN DR2TNUMF IS NULL THEN NULL 
ELSE NULL 
 END as number_of_foods_beverages_reported,
CASE
    WHEN DR2STY = 1 THEN 'Yes' 
WHEN DR2STY = 2 THEN 'No' 
WHEN DR2STY = 9 THEN 'Don't know' 
WHEN DR2STY IS NULL THEN NULL 
ELSE NULL 
 END as salt_used_at_table_yesterday,
CASE
    WHEN DR2SKY = 1 THEN 'Ordinary, sea, seasoned, or other flavored salt' 
WHEN DR2SKY = 2 THEN 'Lite salt' 
WHEN DR2SKY = 3 THEN 'Salt substitute' 
WHEN DR2SKY = 91 THEN 'Other' 
WHEN DR2SKY = 99 THEN 'Don't know' 
WHEN DR2SKY IS NULL THEN NULL 
ELSE NULL 
 END as type_of_salt_used_yesterday,
WHEN DR2TKCAL IS NOT NULL THEN SAFE_CAST(DR2TKCAL AS FLOAT64)WHEN DR2TKCAL IS NULL THEN NULL 
ELSE NULL 
 END as energy_kcal,
WHEN DR2TPROT IS NOT NULL THEN SAFE_CAST(DR2TPROT AS FLOAT64)WHEN DR2TPROT IS NULL THEN NULL 
ELSE NULL 
 END as protein_gm,
WHEN DR2TCARB IS NOT NULL THEN SAFE_CAST(DR2TCARB AS FLOAT64)WHEN DR2TCARB IS NULL THEN NULL 
ELSE NULL 
 END as carbohydrate_gm,
WHEN DR2TSUGR IS NOT NULL THEN SAFE_CAST(DR2TSUGR AS FLOAT64)WHEN DR2TSUGR IS NULL THEN NULL 
ELSE NULL 
 END as total_sugars_gm,
WHEN DR2TFIBE IS NOT NULL THEN SAFE_CAST(DR2TFIBE AS FLOAT64)WHEN DR2TFIBE IS NULL THEN NULL 
ELSE NULL 
 END as dietary_fiber_gm,
WHEN DR2TTFAT IS NOT NULL THEN SAFE_CAST(DR2TTFAT AS FLOAT64)WHEN DR2TTFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_fat_gm,
WHEN DR2TSFAT IS NOT NULL THEN SAFE_CAST(DR2TSFAT AS FLOAT64)WHEN DR2TSFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_saturated_fatty_acids_gm,
WHEN DR2TMFAT IS NOT NULL THEN SAFE_CAST(DR2TMFAT AS FLOAT64)WHEN DR2TMFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_monounsaturated_fatty_acids_gm,
WHEN DR2TPFAT IS NOT NULL THEN SAFE_CAST(DR2TPFAT AS FLOAT64)WHEN DR2TPFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_polyunsaturated_fatty_acids_gm,
WHEN DR2TCHOL IS NOT NULL THEN SAFE_CAST(DR2TCHOL AS FLOAT64)WHEN DR2TCHOL IS NULL THEN NULL 
ELSE NULL 
 END as cholesterol_mg,
WHEN DR2TATOC IS NOT NULL THEN SAFE_CAST(DR2TATOC AS FLOAT64)WHEN DR2TATOC IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_e_as_alpha_tocopherol_mg,
WHEN DR2TATOA IS NOT NULL THEN SAFE_CAST(DR2TATOA AS FLOAT64)WHEN DR2TATOA IS NULL THEN NULL 
ELSE NULL 
 END as added_alpha_tocopherol_vitamin_e_mg,
WHEN DR2TRET IS NOT NULL THEN SAFE_CAST(DR2TRET AS FLOAT64)WHEN DR2TRET IS NULL THEN NULL 
ELSE NULL 
 END as retinol_mcg,
WHEN DR2TVARA IS NOT NULL THEN SAFE_CAST(DR2TVARA AS FLOAT64)WHEN DR2TVARA IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_a_rae_mcg,
WHEN DR2TACAR IS NOT NULL THEN SAFE_CAST(DR2TACAR AS FLOAT64)WHEN DR2TACAR IS NULL THEN NULL 
ELSE NULL 
 END as alpha_carotene_mcg,
WHEN DR2TBCAR IS NOT NULL THEN SAFE_CAST(DR2TBCAR AS FLOAT64)WHEN DR2TBCAR IS NULL THEN NULL 
ELSE NULL 
 END as beta_carotene_mcg,
WHEN DR2TCRYP IS NOT NULL THEN SAFE_CAST(DR2TCRYP AS FLOAT64)WHEN DR2TCRYP IS NULL THEN NULL 
ELSE NULL 
 END as beta_cryptoxanthin_mcg,
WHEN DR2TLYCO IS NOT NULL THEN SAFE_CAST(DR2TLYCO AS FLOAT64)WHEN DR2TLYCO IS NULL THEN NULL 
ELSE NULL 
 END as lycopene_mcg,
WHEN DR2TLZ IS NOT NULL THEN SAFE_CAST(DR2TLZ AS FLOAT64)WHEN DR2TLZ IS NULL THEN NULL 
ELSE NULL 
 END as lutein_zeaxanthin_mcg,
WHEN DR2TVB1 IS NOT NULL THEN SAFE_CAST(DR2TVB1 AS FLOAT64)WHEN DR2TVB1 IS NULL THEN NULL 
ELSE NULL 
 END as thiamin_vitamin_b1_mg,
WHEN DR2TVB2 IS NOT NULL THEN SAFE_CAST(DR2TVB2 AS FLOAT64)WHEN DR2TVB2 IS NULL THEN NULL 
ELSE NULL 
 END as riboflavin_vitamin_b2_mg,
WHEN DR2TNIAC IS NOT NULL THEN SAFE_CAST(DR2TNIAC AS FLOAT64)WHEN DR2TNIAC IS NULL THEN NULL 
ELSE NULL 
 END as niacin_mg,
WHEN DR2TVB6 IS NOT NULL THEN SAFE_CAST(DR2TVB6 AS FLOAT64)WHEN DR2TVB6 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b6_mg,
WHEN DR2TFOLA IS NOT NULL THEN SAFE_CAST(DR2TFOLA AS FLOAT64)WHEN DR2TFOLA IS NULL THEN NULL 
ELSE NULL 
 END as total_folate_mcg,
WHEN DR2TFA IS NOT NULL THEN SAFE_CAST(DR2TFA AS FLOAT64)WHEN DR2TFA IS NULL THEN NULL 
ELSE NULL 
 END as folic_acid_mcg,
WHEN DR2TFF IS NOT NULL THEN SAFE_CAST(DR2TFF AS FLOAT64)WHEN DR2TFF IS NULL THEN NULL 
ELSE NULL 
 END as food_folate_mcg,
WHEN DR2TFDFE IS NOT NULL THEN SAFE_CAST(DR2TFDFE AS FLOAT64)WHEN DR2TFDFE IS NULL THEN NULL 
ELSE NULL 
 END as folate_dfe_mcg,
WHEN DR2TCHL IS NOT NULL THEN SAFE_CAST(DR2TCHL AS FLOAT64)WHEN DR2TCHL IS NULL THEN NULL 
ELSE NULL 
 END as total_choline_mg,
WHEN DR2TVB12 IS NOT NULL THEN SAFE_CAST(DR2TVB12 AS FLOAT64)WHEN DR2TVB12 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b12_mcg,
WHEN DR2TB12A IS NOT NULL THEN SAFE_CAST(DR2TB12A AS FLOAT64)WHEN DR2TB12A IS NULL THEN NULL 
ELSE NULL 
 END as added_vitamin_b12_mcg,
WHEN DR2TVC IS NOT NULL THEN SAFE_CAST(DR2TVC AS FLOAT64)WHEN DR2TVC IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_c_mg,
WHEN DR2TVD IS NOT NULL THEN SAFE_CAST(DR2TVD AS FLOAT64)WHEN DR2TVD IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_d_d2_d3_mcg,
WHEN DR2TVK IS NOT NULL THEN SAFE_CAST(DR2TVK AS FLOAT64)WHEN DR2TVK IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_k_mcg,
WHEN DR2TCALC IS NOT NULL THEN SAFE_CAST(DR2TCALC AS FLOAT64)WHEN DR2TCALC IS NULL THEN NULL 
ELSE NULL 
 END as calcium_mg,
WHEN DR2TPHOS IS NOT NULL THEN SAFE_CAST(DR2TPHOS AS FLOAT64)WHEN DR2TPHOS IS NULL THEN NULL 
ELSE NULL 
 END as phosphorus_mg,
WHEN DR2TMAGN IS NOT NULL THEN SAFE_CAST(DR2TMAGN AS FLOAT64)WHEN DR2TMAGN IS NULL THEN NULL 
ELSE NULL 
 END as magnesium_mg,
WHEN DR2TIRON IS NOT NULL THEN SAFE_CAST(DR2TIRON AS FLOAT64)WHEN DR2TIRON IS NULL THEN NULL 
ELSE NULL 
 END as iron_mg,
WHEN DR2TZINC IS NOT NULL THEN SAFE_CAST(DR2TZINC AS FLOAT64)WHEN DR2TZINC IS NULL THEN NULL 
ELSE NULL 
 END as zinc_mg,
WHEN DR2TCOPP IS NOT NULL THEN SAFE_CAST(DR2TCOPP AS FLOAT64)WHEN DR2TCOPP IS NULL THEN NULL 
ELSE NULL 
 END as copper_mg,
WHEN DR2TSODI IS NOT NULL THEN SAFE_CAST(DR2TSODI AS FLOAT64)WHEN DR2TSODI IS NULL THEN NULL 
ELSE NULL 
 END as sodium_mg,
WHEN DR2TPOTA IS NOT NULL THEN SAFE_CAST(DR2TPOTA AS FLOAT64)WHEN DR2TPOTA IS NULL THEN NULL 
ELSE NULL 
 END as potassium_mg,
WHEN DR2TSELE IS NOT NULL THEN SAFE_CAST(DR2TSELE AS FLOAT64)WHEN DR2TSELE IS NULL THEN NULL 
ELSE NULL 
 END as selenium_mcg,
WHEN DR2TCAFF IS NOT NULL THEN SAFE_CAST(DR2TCAFF AS FLOAT64)WHEN DR2TCAFF IS NULL THEN NULL 
ELSE NULL 
 END as caffeine_mg,
WHEN DR2TTHEO IS NOT NULL THEN SAFE_CAST(DR2TTHEO AS FLOAT64)WHEN DR2TTHEO IS NULL THEN NULL 
ELSE NULL 
 END as theobromine_mg,
WHEN DR2TALCO IS NOT NULL THEN SAFE_CAST(DR2TALCO AS FLOAT64)WHEN DR2TALCO IS NULL THEN NULL 
ELSE NULL 
 END as alcohol_gm,
WHEN DR2TMOIS IS NOT NULL THEN SAFE_CAST(DR2TMOIS AS FLOAT64)WHEN DR2TMOIS IS NULL THEN NULL 
ELSE NULL 
 END as moisture_gm,
WHEN DR2TS040 IS NOT NULL THEN SAFE_CAST(DR2TS040 AS FLOAT64)WHEN DR2TS040 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_4_0_butanoic_gm,
WHEN DR2TS060 IS NOT NULL THEN SAFE_CAST(DR2TS060 AS FLOAT64)WHEN DR2TS060 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_6_0_hexanoic_gm,
WHEN DR2TS080 IS NOT NULL THEN SAFE_CAST(DR2TS080 AS FLOAT64)WHEN DR2TS080 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_8_0_octanoic_gm,
WHEN DR2TS100 IS NOT NULL THEN SAFE_CAST(DR2TS100 AS FLOAT64)WHEN DR2TS100 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_10_0_decanoic_gm,
WHEN DR2TS120 IS NOT NULL THEN SAFE_CAST(DR2TS120 AS FLOAT64)WHEN DR2TS120 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_12_0_dodecanoic_gm,
WHEN DR2TS140 IS NOT NULL THEN SAFE_CAST(DR2TS140 AS FLOAT64)WHEN DR2TS140 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_14_0_tetradecanoic_gm,
WHEN DR2TS160 IS NOT NULL THEN SAFE_CAST(DR2TS160 AS FLOAT64)WHEN DR2TS160 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_16_0_hexadecanoic_gm,
WHEN DR2TS180 IS NOT NULL THEN SAFE_CAST(DR2TS180 AS FLOAT64)WHEN DR2TS180 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_18_0_octadecanoic_gm,
WHEN DR2TM161 IS NOT NULL THEN SAFE_CAST(DR2TM161 AS FLOAT64)WHEN DR2TM161 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_16_1_hexadecenoic_gm,
WHEN DR2TM181 IS NOT NULL THEN SAFE_CAST(DR2TM181 AS FLOAT64)WHEN DR2TM181 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_18_1_octadecenoic_gm,
WHEN DR2TM201 IS NOT NULL THEN SAFE_CAST(DR2TM201 AS FLOAT64)WHEN DR2TM201 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_20_1_eicosenoic_gm,
WHEN DR2TM221 IS NOT NULL THEN SAFE_CAST(DR2TM221 AS FLOAT64)WHEN DR2TM221 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_22_1_docosenoic_gm,
WHEN DR2TP182 IS NOT NULL THEN SAFE_CAST(DR2TP182 AS FLOAT64)WHEN DR2TP182 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_18_2_octadecadienoic_gm,
WHEN DR2TP183 IS NOT NULL THEN SAFE_CAST(DR2TP183 AS FLOAT64)WHEN DR2TP183 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_18_3_octadecatrienoic_gm,
WHEN DR2TP184 IS NOT NULL THEN SAFE_CAST(DR2TP184 AS FLOAT64)WHEN DR2TP184 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_18_4_octadecatetraenoic_gm,
WHEN DR2TP204 IS NOT NULL THEN SAFE_CAST(DR2TP204 AS FLOAT64)WHEN DR2TP204 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_20_4_eicosatetraenoic_gm,
WHEN DR2TP205 IS NOT NULL THEN SAFE_CAST(DR2TP205 AS FLOAT64)WHEN DR2TP205 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_20_5_eicosapentaenoic_gm,
WHEN DR2TP225 IS NOT NULL THEN SAFE_CAST(DR2TP225 AS FLOAT64)WHEN DR2TP225 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_22_5_docosapentaenoic_gm,
WHEN DR2TP226 IS NOT NULL THEN SAFE_CAST(DR2TP226 AS FLOAT64)WHEN DR2TP226 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_22_6_docosahexaenoic_gm,
CASE
    WHEN DR2_300 = 1 THEN 'Much more than usual' 
WHEN DR2_300 = 2 THEN 'Usual' 
WHEN DR2_300 = 3 THEN 'Much less than usual' 
WHEN DR2_300 = 7 THEN 'Refused' 
WHEN DR2_300 = 9 THEN 'Don't know' 
WHEN DR2_300 IS NULL THEN NULL 
ELSE NULL 
 END as compare_food_consumed_yesterday_to_usual,
WHEN DR2_320Z IS NOT NULL THEN SAFE_CAST(DR2_320Z AS FLOAT64)WHEN DR2_320Z IS NULL THEN NULL 
ELSE NULL 
 END as total_plain_water_drank_yesterday_gm,
WHEN DR2_330Z IS NOT NULL THEN SAFE_CAST(DR2_330Z AS FLOAT64)WHEN DR2_330Z IS NULL THEN NULL 
ELSE NULL 
 END as total_tap_water_drank_yesterday_gm,
WHEN DR2BWATZ IS NOT NULL THEN SAFE_CAST(DR2BWATZ AS FLOAT64)WHEN DR2BWATZ IS NULL THEN NULL 
ELSE NULL 
 END as total_bottled_water_drank_yesterday_gm,
CASE
    WHEN DR2TWSZ = 1 THEN 'Community supply' 
WHEN DR2TWSZ = 4 THEN 'Don't drink tap water' 
WHEN DR2TWSZ = 91 THEN 'Other' 
WHEN DR2TWSZ = 99 THEN 'Don't know' 
WHEN DR2TWSZ IS NULL THEN NULL 
ELSE NULL 
 END as tap_water_source,
 FROM {ref('stg_dietary_interview_total_nutrient_intakes_second_day_dietary'})