SELECT
SEQN as respondent_sequence_number,
WHEN WTDRD1 IS NOT NULL THEN SAFE_CAST(WTDRD1 AS FLOAT64)WHEN WTDRD1 IS NULL THEN NULL 
ELSE NULL 
 END as dietary_day_one_sample_weight,
WHEN WTDR2D IS NOT NULL THEN SAFE_CAST(WTDR2D AS FLOAT64)WHEN WTDR2D IS NULL THEN NULL 
ELSE NULL 
 END as dietary_two_day_sample_weight,
WHEN DR1ILINE IS NOT NULL THEN SAFE_CAST(DR1ILINE AS FLOAT64)WHEN DR1ILINE IS NULL THEN NULL 
ELSE NULL 
 END as food_individual_component_number,
CASE
    WHEN DR1DRSTZ = 1 THEN 'Reliable and met the minimum criteria' 
WHEN DR1DRSTZ = 2 THEN 'Not reliable or not met the minimum criteria' 
WHEN DR1DRSTZ = 4 THEN 'Reported consuming breast-milk' 
WHEN DR1DRSTZ = 5 THEN 'Not done' 
WHEN DR1DRSTZ IS NULL THEN NULL 
ELSE NULL 
 END as dietary_recall_status,
WHEN DR1EXMER IS NOT NULL THEN SAFE_CAST(DR1EXMER AS FLOAT64)WHEN DR1EXMER IS NULL THEN NULL 
ELSE NULL 
 END as interviewer_id_code,
CASE
    WHEN DRABF = 1 THEN 'Yes' 
WHEN DRABF = 2 THEN 'No' 
WHEN DRABF IS NULL THEN NULL 
ELSE NULL 
 END as breast_fed_infant_either_day,
CASE
    WHEN DRDINT = 1 THEN 'Day 1 only' 
WHEN DRDINT = 2 THEN 'Day 1 and day 2' 
WHEN DRDINT IS NULL THEN NULL 
ELSE NULL 
 END as number_of_days_of_intake,
WHEN DR1DBIH IS NOT NULL THEN SAFE_CAST(DR1DBIH AS FLOAT64)WHEN DR1DBIH IS NULL THEN NULL 
ELSE NULL 
 END as of_days_b_w_intake_and_hh_interview,
CASE
    WHEN DR1DAY = 1 THEN 'Sunday' 
WHEN DR1DAY = 2 THEN 'Monday' 
WHEN DR1DAY = 3 THEN 'Tuesday' 
WHEN DR1DAY = 4 THEN 'Wednesday' 
WHEN DR1DAY = 5 THEN 'Thursday' 
WHEN DR1DAY = 6 THEN 'Friday' 
WHEN DR1DAY = 7 THEN 'Saturday' 
WHEN DR1DAY IS NULL THEN NULL 
ELSE NULL 
 END as intake_day_of_the_week,
CASE
    WHEN DR1LANG = 1 THEN 'English' 
WHEN DR1LANG = 2 THEN 'Spanish' 
WHEN DR1LANG = 3 THEN 'English and Spanish' 
WHEN DR1LANG = 4 THEN 'Other' 
WHEN DR1LANG = 5 THEN 'Asian Languages' 
WHEN DR1LANG = 6 THEN 'Asian Languages and English' 
WHEN DR1LANG IS NULL THEN NULL 
ELSE NULL 
 END as language_respondent_used_mostly,
WHEN DR1CCMNM IS NOT NULL THEN SAFE_CAST(DR1CCMNM AS FLOAT64)WHEN DR1CCMNM IS NULL THEN NULL 
ELSE NULL 
 END as combination_food_number,
CASE
    WHEN DR1CCMTX = 0 THEN 'Non-combination food' 
WHEN DR1CCMTX = 1 THEN 'Beverage w/ additions' 
WHEN DR1CCMTX = 2 THEN 'Cereal w/ additions' 
WHEN DR1CCMTX = 3 THEN 'Bread/baked products w/ additions' 
WHEN DR1CCMTX = 4 THEN 'Salad' 
WHEN DR1CCMTX = 5 THEN 'Sandwiches' 
WHEN DR1CCMTX = 6 THEN 'Soup' 
WHEN DR1CCMTX = 7 THEN 'Frozen meals' 
WHEN DR1CCMTX = 8 THEN 'Ice cream/frozen yogurt w/ additions' 
WHEN DR1CCMTX = 9 THEN 'Dried beans and vegetable w/ additions' 
WHEN DR1CCMTX = 10 THEN 'Fruit w/ additions' 
WHEN DR1CCMTX = 11 THEN 'Tortilla products' 
WHEN DR1CCMTX = 12 THEN 'Meat, poultry, fish' 
WHEN DR1CCMTX = 13 THEN 'LunchablesÂ®' 
WHEN DR1CCMTX = 14 THEN 'Chips w/ additions' 
WHEN DR1CCMTX = 90 THEN 'Other mixtures' 
WHEN DR1CCMTX IS NULL THEN NULL 
ELSE NULL 
 END as combination_food_type,
WHEN DR1_020 IS NOT NULL THEN SAFE_CAST(DR1_020 AS FLOAT64)WHEN DR1_020 IS NULL THEN NULL 
ELSE NULL 
 END as time_of_eating_occasion_hh_mm,
CASE
    WHEN DR1_030Z = 1 THEN 'Breakfast' 
WHEN DR1_030Z = 2 THEN 'Lunch' 
WHEN DR1_030Z = 3 THEN 'Dinner' 
WHEN DR1_030Z = 4 THEN 'Supper' 
WHEN DR1_030Z = 5 THEN 'Brunch' 
WHEN DR1_030Z = 6 THEN 'Snack' 
WHEN DR1_030Z = 7 THEN 'Drink' 
WHEN DR1_030Z = 8 THEN 'Infant feeding' 
WHEN DR1_030Z = 9 THEN 'Extended consumption' 
WHEN DR1_030Z = 10 THEN 'Desayano' 
WHEN DR1_030Z = 11 THEN 'Almuerzo' 
WHEN DR1_030Z = 12 THEN 'Comida' 
WHEN DR1_030Z = 13 THEN 'Merienda' 
WHEN DR1_030Z = 14 THEN 'Cena' 
WHEN DR1_030Z = 15 THEN 'Entre comida' 
WHEN DR1_030Z = 16 THEN 'Botana' 
WHEN DR1_030Z = 17 THEN 'Bocadillo' 
WHEN DR1_030Z = 18 THEN 'Tentempie' 
WHEN DR1_030Z = 19 THEN 'Bebida' 
WHEN DR1_030Z = 91 THEN 'Other' 
WHEN DR1_030Z = 99 THEN 'Don't know' 
WHEN DR1_030Z IS NULL THEN NULL 
ELSE NULL 
 END as name_of_eating_occasion,
CASE
    WHEN DR1FS = 1 THEN 'Store - grocery/supermarket' 
WHEN DR1FS = 2 THEN 'Restaurant with waiter/waitress' 
WHEN DR1FS = 3 THEN 'Restaurant fast food/pizza' 
WHEN DR1FS = 4 THEN 'Bar/tavern/lounge' 
WHEN DR1FS = 5 THEN 'Restaurant no additional information' 
WHEN DR1FS = 6 THEN 'Cafeteria NOT in a K-12 school' 
WHEN DR1FS = 7 THEN 'Cafeteria in a K-12 school' 
WHEN DR1FS = 8 THEN 'Child/Adult care center' 
WHEN DR1FS = 9 THEN 'Child/Adult home care' 
WHEN DR1FS = 10 THEN 'Soup kitchen/shelter/food pantry' 
WHEN DR1FS = 11 THEN 'Meals on Wheels' 
WHEN DR1FS = 12 THEN 'Community food program - other' 
WHEN DR1FS = 13 THEN 'Community program no additional information' 
WHEN DR1FS = 14 THEN 'Vending machine' 
WHEN DR1FS = 15 THEN 'Common coffee pot or snack tray' 
WHEN DR1FS = 16 THEN 'From someone else/gift' 
WHEN DR1FS = 17 THEN 'Mail order purchase' 
WHEN DR1FS = 18 THEN 'Residential dining facility' 
WHEN DR1FS = 19 THEN 'Grown or caught by you or someone you know' 
WHEN DR1FS = 20 THEN 'Fish caught by you or someone you know' 
WHEN DR1FS = 24 THEN 'Sport, recreation, or entertainment facility' 
WHEN DR1FS = 25 THEN 'Street vendor, vending truck' 
WHEN DR1FS = 26 THEN 'Fundraiser sales' 
WHEN DR1FS = 27 THEN 'Store - convenience type' 
WHEN DR1FS = 28 THEN 'Store - no additional info' 
WHEN DR1FS = 91 THEN 'Other, specify' 
WHEN DR1FS = 99 THEN 'Don't know' 
WHEN DR1FS IS NULL THEN NULL 
ELSE NULL 
 END as source_of_food,
CASE
    WHEN DR1_040Z = 1 THEN 'Yes' 
WHEN DR1_040Z = 2 THEN 'No' 
WHEN DR1_040Z = 7 THEN 'Refused' 
WHEN DR1_040Z = 9 THEN 'Don't know' 
WHEN DR1_040Z IS NULL THEN NULL 
ELSE NULL 
 END as did_you_eat_this_meal_at_home,
WHEN DR1IFDCD IS NOT NULL THEN SAFE_CAST(DR1IFDCD AS FLOAT64)WHEN DR1IFDCD IS NULL THEN NULL 
ELSE NULL 
 END as usda_food_code,
WHEN DR1IGRMS IS NOT NULL THEN SAFE_CAST(DR1IGRMS AS FLOAT64)WHEN DR1IGRMS IS NULL THEN NULL 
ELSE NULL 
 END as grams,
WHEN DR1IKCAL IS NOT NULL THEN SAFE_CAST(DR1IKCAL AS FLOAT64)WHEN DR1IKCAL IS NULL THEN NULL 
ELSE NULL 
 END as energy_kcal,
WHEN DR1IPROT IS NOT NULL THEN SAFE_CAST(DR1IPROT AS FLOAT64)WHEN DR1IPROT IS NULL THEN NULL 
ELSE NULL 
 END as protein_gm,
WHEN DR1ICARB IS NOT NULL THEN SAFE_CAST(DR1ICARB AS FLOAT64)WHEN DR1ICARB IS NULL THEN NULL 
ELSE NULL 
 END as carbohydrate_gm,
WHEN DR1ISUGR IS NOT NULL THEN SAFE_CAST(DR1ISUGR AS FLOAT64)WHEN DR1ISUGR IS NULL THEN NULL 
ELSE NULL 
 END as total_sugars_gm,
WHEN DR1IFIBE IS NOT NULL THEN SAFE_CAST(DR1IFIBE AS FLOAT64)WHEN DR1IFIBE IS NULL THEN NULL 
ELSE NULL 
 END as dietary_fiber_gm,
WHEN DR1ITFAT IS NOT NULL THEN SAFE_CAST(DR1ITFAT AS FLOAT64)WHEN DR1ITFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_fat_gm,
WHEN DR1ISFAT IS NOT NULL THEN SAFE_CAST(DR1ISFAT AS FLOAT64)WHEN DR1ISFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_saturated_fatty_acids_gm,
WHEN DR1IMFAT IS NOT NULL THEN SAFE_CAST(DR1IMFAT AS FLOAT64)WHEN DR1IMFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_monounsaturated_fatty_acids_gm,
WHEN DR1IPFAT IS NOT NULL THEN SAFE_CAST(DR1IPFAT AS FLOAT64)WHEN DR1IPFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_polyunsaturated_fatty_acids_gm,
WHEN DR1ICHOL IS NOT NULL THEN SAFE_CAST(DR1ICHOL AS FLOAT64)WHEN DR1ICHOL IS NULL THEN NULL 
ELSE NULL 
 END as cholesterol_mg,
WHEN DR1IATOC IS NOT NULL THEN SAFE_CAST(DR1IATOC AS FLOAT64)WHEN DR1IATOC IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_e_as_alpha_tocopherol_mg,
WHEN DR1IATOA IS NOT NULL THEN SAFE_CAST(DR1IATOA AS FLOAT64)WHEN DR1IATOA IS NULL THEN NULL 
ELSE NULL 
 END as added_alpha_tocopherol_vitamin_e_mg,
WHEN DR1IRET IS NOT NULL THEN SAFE_CAST(DR1IRET AS FLOAT64)WHEN DR1IRET IS NULL THEN NULL 
ELSE NULL 
 END as retinol_mcg,
WHEN DR1IVARA IS NOT NULL THEN SAFE_CAST(DR1IVARA AS FLOAT64)WHEN DR1IVARA IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_a_rae_mcg,
WHEN DR1IACAR IS NOT NULL THEN SAFE_CAST(DR1IACAR AS FLOAT64)WHEN DR1IACAR IS NULL THEN NULL 
ELSE NULL 
 END as alpha_carotene_mcg,
WHEN DR1IBCAR IS NOT NULL THEN SAFE_CAST(DR1IBCAR AS FLOAT64)WHEN DR1IBCAR IS NULL THEN NULL 
ELSE NULL 
 END as beta_carotene_mcg,
WHEN DR1ICRYP IS NOT NULL THEN SAFE_CAST(DR1ICRYP AS FLOAT64)WHEN DR1ICRYP IS NULL THEN NULL 
ELSE NULL 
 END as beta_cryptoxanthin_mcg,
WHEN DR1ILYCO IS NOT NULL THEN SAFE_CAST(DR1ILYCO AS FLOAT64)WHEN DR1ILYCO IS NULL THEN NULL 
ELSE NULL 
 END as lycopene_mcg,
WHEN DR1ILZ IS NOT NULL THEN SAFE_CAST(DR1ILZ AS FLOAT64)WHEN DR1ILZ IS NULL THEN NULL 
ELSE NULL 
 END as lutein_zeaxanthin_mcg,
WHEN DR1IVB1 IS NOT NULL THEN SAFE_CAST(DR1IVB1 AS FLOAT64)WHEN DR1IVB1 IS NULL THEN NULL 
ELSE NULL 
 END as thiamin_vitamin_b1_mg,
WHEN DR1IVB2 IS NOT NULL THEN SAFE_CAST(DR1IVB2 AS FLOAT64)WHEN DR1IVB2 IS NULL THEN NULL 
ELSE NULL 
 END as riboflavin_vitamin_b2_mg,
WHEN DR1INIAC IS NOT NULL THEN SAFE_CAST(DR1INIAC AS FLOAT64)WHEN DR1INIAC IS NULL THEN NULL 
ELSE NULL 
 END as niacin_mg,
WHEN DR1IVB6 IS NOT NULL THEN SAFE_CAST(DR1IVB6 AS FLOAT64)WHEN DR1IVB6 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b6_mg,
WHEN DR1IFOLA IS NOT NULL THEN SAFE_CAST(DR1IFOLA AS FLOAT64)WHEN DR1IFOLA IS NULL THEN NULL 
ELSE NULL 
 END as total_folate_mcg,
WHEN DR1IFA IS NOT NULL THEN SAFE_CAST(DR1IFA AS FLOAT64)WHEN DR1IFA IS NULL THEN NULL 
ELSE NULL 
 END as folic_acid_mcg,
WHEN DR1IFF IS NOT NULL THEN SAFE_CAST(DR1IFF AS FLOAT64)WHEN DR1IFF IS NULL THEN NULL 
ELSE NULL 
 END as food_folate_mcg,
WHEN DR1IFDFE IS NOT NULL THEN SAFE_CAST(DR1IFDFE AS FLOAT64)WHEN DR1IFDFE IS NULL THEN NULL 
ELSE NULL 
 END as folate_dfe_mcg,
WHEN DR1ICHL IS NOT NULL THEN SAFE_CAST(DR1ICHL AS FLOAT64)WHEN DR1ICHL IS NULL THEN NULL 
ELSE NULL 
 END as total_choline_mg,
WHEN DR1IVB12 IS NOT NULL THEN SAFE_CAST(DR1IVB12 AS FLOAT64)WHEN DR1IVB12 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b12_mcg,
WHEN DR1IB12A IS NOT NULL THEN SAFE_CAST(DR1IB12A AS FLOAT64)WHEN DR1IB12A IS NULL THEN NULL 
ELSE NULL 
 END as added_vitamin_b12_mcg,
WHEN DR1IVC IS NOT NULL THEN SAFE_CAST(DR1IVC AS FLOAT64)WHEN DR1IVC IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_c_mg,
WHEN DR1IVD IS NOT NULL THEN SAFE_CAST(DR1IVD AS FLOAT64)WHEN DR1IVD IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_d_d2_d3_mcg,
WHEN DR1IVK IS NOT NULL THEN SAFE_CAST(DR1IVK AS FLOAT64)WHEN DR1IVK IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_k_mcg,
WHEN DR1ICALC IS NOT NULL THEN SAFE_CAST(DR1ICALC AS FLOAT64)WHEN DR1ICALC IS NULL THEN NULL 
ELSE NULL 
 END as calcium_mg,
WHEN DR1IPHOS IS NOT NULL THEN SAFE_CAST(DR1IPHOS AS FLOAT64)WHEN DR1IPHOS IS NULL THEN NULL 
ELSE NULL 
 END as phosphorus_mg,
WHEN DR1IMAGN IS NOT NULL THEN SAFE_CAST(DR1IMAGN AS FLOAT64)WHEN DR1IMAGN IS NULL THEN NULL 
ELSE NULL 
 END as magnesium_mg,
WHEN DR1IIRON IS NOT NULL THEN SAFE_CAST(DR1IIRON AS FLOAT64)WHEN DR1IIRON IS NULL THEN NULL 
ELSE NULL 
 END as iron_mg,
WHEN DR1IZINC IS NOT NULL THEN SAFE_CAST(DR1IZINC AS FLOAT64)WHEN DR1IZINC IS NULL THEN NULL 
ELSE NULL 
 END as zinc_mg,
WHEN DR1ICOPP IS NOT NULL THEN SAFE_CAST(DR1ICOPP AS FLOAT64)WHEN DR1ICOPP IS NULL THEN NULL 
ELSE NULL 
 END as copper_mg,
WHEN DR1ISODI IS NOT NULL THEN SAFE_CAST(DR1ISODI AS FLOAT64)WHEN DR1ISODI IS NULL THEN NULL 
ELSE NULL 
 END as sodium_mg,
WHEN DR1IPOTA IS NOT NULL THEN SAFE_CAST(DR1IPOTA AS FLOAT64)WHEN DR1IPOTA IS NULL THEN NULL 
ELSE NULL 
 END as potassium_mg,
WHEN DR1ISELE IS NOT NULL THEN SAFE_CAST(DR1ISELE AS FLOAT64)WHEN DR1ISELE IS NULL THEN NULL 
ELSE NULL 
 END as selenium_mcg,
WHEN DR1ICAFF IS NOT NULL THEN SAFE_CAST(DR1ICAFF AS FLOAT64)WHEN DR1ICAFF IS NULL THEN NULL 
ELSE NULL 
 END as caffeine_mg,
WHEN DR1ITHEO IS NOT NULL THEN SAFE_CAST(DR1ITHEO AS FLOAT64)WHEN DR1ITHEO IS NULL THEN NULL 
ELSE NULL 
 END as theobromine_mg,
WHEN DR1IALCO IS NOT NULL THEN SAFE_CAST(DR1IALCO AS FLOAT64)WHEN DR1IALCO IS NULL THEN NULL 
ELSE NULL 
 END as alcohol_gm,
WHEN DR1IMOIS IS NOT NULL THEN SAFE_CAST(DR1IMOIS AS FLOAT64)WHEN DR1IMOIS IS NULL THEN NULL 
ELSE NULL 
 END as moisture_gm,
WHEN DR1IS040 IS NOT NULL THEN SAFE_CAST(DR1IS040 AS FLOAT64)WHEN DR1IS040 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_4_0_butanoic_gm,
WHEN DR1IS060 IS NOT NULL THEN SAFE_CAST(DR1IS060 AS FLOAT64)WHEN DR1IS060 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_6_0_hexanoic_gm,
WHEN DR1IS080 IS NOT NULL THEN SAFE_CAST(DR1IS080 AS FLOAT64)WHEN DR1IS080 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_8_0_octanoic_gm,
WHEN DR1IS100 IS NOT NULL THEN SAFE_CAST(DR1IS100 AS FLOAT64)WHEN DR1IS100 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_10_0_decanoic_gm,
WHEN DR1IS120 IS NOT NULL THEN SAFE_CAST(DR1IS120 AS FLOAT64)WHEN DR1IS120 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_12_0_dodecanoic_gm,
WHEN DR1IS140 IS NOT NULL THEN SAFE_CAST(DR1IS140 AS FLOAT64)WHEN DR1IS140 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_14_0_tetradecanoic_gm,
WHEN DR1IS160 IS NOT NULL THEN SAFE_CAST(DR1IS160 AS FLOAT64)WHEN DR1IS160 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_16_0_hexadecanoic_gm,
WHEN DR1IS180 IS NOT NULL THEN SAFE_CAST(DR1IS180 AS FLOAT64)WHEN DR1IS180 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_18_0_octadecanoic_gm,
WHEN DR1IM161 IS NOT NULL THEN SAFE_CAST(DR1IM161 AS FLOAT64)WHEN DR1IM161 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_16_1_hexadecenoic_gm,
WHEN DR1IM181 IS NOT NULL THEN SAFE_CAST(DR1IM181 AS FLOAT64)WHEN DR1IM181 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_18_1_octadecenoic_gm,
WHEN DR1IM201 IS NOT NULL THEN SAFE_CAST(DR1IM201 AS FLOAT64)WHEN DR1IM201 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_20_1_eicosenoic_gm,
WHEN DR1IM221 IS NOT NULL THEN SAFE_CAST(DR1IM221 AS FLOAT64)WHEN DR1IM221 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_22_1_docosenoic_gm,
WHEN DR1IP182 IS NOT NULL THEN SAFE_CAST(DR1IP182 AS FLOAT64)WHEN DR1IP182 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_18_2_octadecadienoic_gm,
WHEN DR1IP183 IS NOT NULL THEN SAFE_CAST(DR1IP183 AS FLOAT64)WHEN DR1IP183 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_18_3_octadecatrienoic_gm,
WHEN DR1IP184 IS NOT NULL THEN SAFE_CAST(DR1IP184 AS FLOAT64)WHEN DR1IP184 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_18_4_octadecatetraenoic_gm,
WHEN DR1IP204 IS NOT NULL THEN SAFE_CAST(DR1IP204 AS FLOAT64)WHEN DR1IP204 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_20_4_eicosatetraenoic_gm,
WHEN DR1IP205 IS NOT NULL THEN SAFE_CAST(DR1IP205 AS FLOAT64)WHEN DR1IP205 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_20_5_eicosapentaenoic_gm,
WHEN DR1IP225 IS NOT NULL THEN SAFE_CAST(DR1IP225 AS FLOAT64)WHEN DR1IP225 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_22_5_docosapentaenoic_gm,
WHEN DR1IP226 IS NOT NULL THEN SAFE_CAST(DR1IP226 AS FLOAT64)WHEN DR1IP226 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_22_6_docosahexaenoic_gm,
 FROM {ref('stg_dietary_interview_individual_foods_first_day_dietary'})