SELECT
SEQN as respondent_sequence_number,
WHEN LBXIRN IS NOT NULL THEN SAFE_CAST(LBXIRN AS FLOAT64)WHEN LBXIRN IS NULL THEN NULL 
ELSE NULL 
 END as iron_frozen_serum_ug_dl,
WHEN LBDIRNSI IS NOT NULL THEN SAFE_CAST(LBDIRNSI AS FLOAT64)WHEN LBDIRNSI IS NULL THEN NULL 
ELSE NULL 
 END as iron_frozen_serum_umol_l,
WHEN LBXUIB IS NOT NULL THEN SAFE_CAST(LBXUIB AS FLOAT64)WHEN LBXUIB IS NULL THEN NULL 
ELSE NULL 
 END as uibc_serum_ug_dl,
CASE
    WHEN LBDUIBLC = 0 THEN 'At or above detection limit' 
WHEN LBDUIBLC = 1 THEN 'Below lower detection limit' 
WHEN LBDUIBLC IS NULL THEN NULL 
ELSE NULL 
 END as uibc_serum_comment_code,
WHEN LBDUIBSI IS NOT NULL THEN SAFE_CAST(LBDUIBSI AS FLOAT64)WHEN LBDUIBSI IS NULL THEN NULL 
ELSE NULL 
 END as uibc_serum_umol_l,
WHEN LBDTIB IS NOT NULL THEN SAFE_CAST(LBDTIB AS FLOAT64)WHEN LBDTIB IS NULL THEN NULL 
ELSE NULL 
 END as total_iron_binding_capacity_tibc_ug_dl,
WHEN LBDTIBSI IS NOT NULL THEN SAFE_CAST(LBDTIBSI AS FLOAT64)WHEN LBDTIBSI IS NULL THEN NULL 
ELSE NULL 
 END as tot_iron_binding_capacity_tibc_umol_l,
WHEN LBDPCT IS NOT NULL THEN SAFE_CAST(LBDPCT AS FLOAT64)WHEN LBDPCT IS NULL THEN NULL 
ELSE NULL 
 END as transferrin_saturation,
 FROM {ref('stg_iron_status_serum_laboratory'})