SELECT
SEQN as respondent_sequence_number,
WHEN WTDRD1 IS NOT NULL THEN SAFE_CAST(WTDRD1 AS FLOAT64)WHEN WTDRD1 IS NULL THEN NULL 
ELSE NULL 
 END as dietary_day_one_sample_weight,
WHEN WTDR2D IS NOT NULL THEN SAFE_CAST(WTDR2D AS FLOAT64)WHEN WTDR2D IS NULL THEN NULL 
ELSE NULL 
 END as dietary_two_day_sample_weight,
CASE
    WHEN DR2DRSTZ = 1 THEN 'Reliable and met the minimum criteria' 
WHEN DR2DRSTZ = 2 THEN 'Not reliable or not met the minimum criteria' 
WHEN DR2DRSTZ = 4 THEN 'Reported consuming breast-milk' 
WHEN DR2DRSTZ = 5 THEN 'Not done' 
WHEN DR2DRSTZ IS NULL THEN NULL 
ELSE NULL 
 END as dietary_recall_status,
WHEN DR2EXMER IS NOT NULL THEN SAFE_CAST(DR2EXMER AS FLOAT64)WHEN DR2EXMER IS NULL THEN NULL 
ELSE NULL 
 END as interviewer_id_code,
CASE
    WHEN DRDINT = 1 THEN 'Day 1 only' 
WHEN DRDINT = 2 THEN 'Day 1 and day 2' 
WHEN DRDINT IS NULL THEN NULL 
ELSE NULL 
 END as number_of_days_of_intake,
WHEN DR2DBIH IS NOT NULL THEN SAFE_CAST(DR2DBIH AS FLOAT64)WHEN DR2DBIH IS NULL THEN NULL 
ELSE NULL 
 END as of_days_b_w_intake_and_hh_interview,
CASE
    WHEN DR2DAY = 1 THEN 'Sunday' 
WHEN DR2DAY = 2 THEN 'Monday' 
WHEN DR2DAY = 3 THEN 'Tuesday' 
WHEN DR2DAY = 4 THEN 'Wednesday' 
WHEN DR2DAY = 5 THEN 'Thursday' 
WHEN DR2DAY = 6 THEN 'Friday' 
WHEN DR2DAY = 7 THEN 'Saturday' 
WHEN DR2DAY IS NULL THEN NULL 
ELSE NULL 
 END as intake_day_of_the_week,
CASE
    WHEN DR2LANG = 1 THEN 'English' 
WHEN DR2LANG = 2 THEN 'Spanish' 
WHEN DR2LANG = 3 THEN 'English and Spanish' 
WHEN DR2LANG = 4 THEN 'Other' 
WHEN DR2LANG = 5 THEN 'Asian Languages' 
WHEN DR2LANG = 6 THEN 'Asian Languages and English' 
WHEN DR2LANG IS NULL THEN NULL 
ELSE NULL 
 END as language_respondent_used_mostly,
CASE
    WHEN DS2LOC = 1 THEN 'HouseHold Interview' 
WHEN DS2LOC = 2 THEN 'MEC Interview' 
WHEN DS2LOC = 3 THEN 'Phone Interview' 
WHEN DS2LOC IS NULL THEN NULL 
ELSE NULL 
 END as location_supplement_originally_recorded,
WHEN DSDPID IS NOT NULL THEN SAFE_CAST(DSDPID AS FLOAT64)WHEN DSDPID IS NULL THEN NULL 
ELSE NULL 
 END as nchs_supplement_id,
CASE
    WHEN DSDSUPP = 'Supplement Name' THEN 'Value was recorded' 
WHEN DSDSUPP IS NULL THEN NULL 
ELSE NULL 
 END as supplement_name,
CASE
    WHEN DS2MTCH = 1 THEN 'Exact or near exact match' 
WHEN DS2MTCH = 2 THEN 'Probable match' 
WHEN DS2MTCH = 3 THEN 'Generic match' 
WHEN DS2MTCH = 4 THEN 'Reasonable match' 
WHEN DS2MTCH = 5 THEN 'Default match' 
WHEN DS2MTCH = 6 THEN 'No match' 
WHEN DS2MTCH = 7 THEN 'Refused' 
WHEN DS2MTCH = 9 THEN 'Don't know' 
WHEN DS2MTCH IS NULL THEN NULL 
ELSE NULL 
 END as matching_code,
CASE
    WHEN DS2ANTA = 0 THEN 'Non-antacid supplement' 
WHEN DS2ANTA = 1 THEN 'Antacid containing calcium and/or magnesium' 
WHEN DS2ANTA = 2 THEN 'Antacids reported with antacids' 
WHEN DS2ANTA IS NULL THEN NULL 
ELSE NULL 
 END as antacid_containing_calcium_magnesium,
WHEN DS2ACTSS IS NOT NULL THEN SAFE_CAST(DS2ACTSS AS FLOAT64)WHEN DS2ACTSS IS NULL THEN NULL 
ELSE NULL 
 END as reported_serving_size_label_serving_size,
WHEN DS2IKCAL IS NOT NULL THEN SAFE_CAST(DS2IKCAL AS FLOAT64)WHEN DS2IKCAL IS NULL THEN NULL 
ELSE NULL 
 END as energy_kcal,
WHEN DS2IPROT IS NOT NULL THEN SAFE_CAST(DS2IPROT AS FLOAT64)WHEN DS2IPROT IS NULL THEN NULL 
ELSE NULL 
 END as protein_gm,
WHEN DS2ICARB IS NOT NULL THEN SAFE_CAST(DS2ICARB AS FLOAT64)WHEN DS2ICARB IS NULL THEN NULL 
ELSE NULL 
 END as carbohydrate_gm,
WHEN DS2ISUGR IS NOT NULL THEN SAFE_CAST(DS2ISUGR AS FLOAT64)WHEN DS2ISUGR IS NULL THEN NULL 
ELSE NULL 
 END as total_sugars_gm,
WHEN DS2IFIBE IS NOT NULL THEN SAFE_CAST(DS2IFIBE AS FLOAT64)WHEN DS2IFIBE IS NULL THEN NULL 
ELSE NULL 
 END as dietary_fiber_gm,
WHEN DS2ITFAT IS NOT NULL THEN SAFE_CAST(DS2ITFAT AS FLOAT64)WHEN DS2ITFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_fat_gm,
WHEN DS2ISFAT IS NOT NULL THEN SAFE_CAST(DS2ISFAT AS FLOAT64)WHEN DS2ISFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_saturated_fatty_acids_gm,
WHEN DS2IMFAT IS NOT NULL THEN SAFE_CAST(DS2IMFAT AS FLOAT64)WHEN DS2IMFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_monounsaturated_fatty_acids_gm,
WHEN DS2IPFAT IS NOT NULL THEN SAFE_CAST(DS2IPFAT AS FLOAT64)WHEN DS2IPFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_polyunsaturated_fatty_acids_gm,
WHEN DS2ICHOL IS NOT NULL THEN SAFE_CAST(DS2ICHOL AS FLOAT64)WHEN DS2ICHOL IS NULL THEN NULL 
ELSE NULL 
 END as cholesterol_mg,
WHEN DS2ILYCO IS NOT NULL THEN SAFE_CAST(DS2ILYCO AS FLOAT64)WHEN DS2ILYCO IS NULL THEN NULL 
ELSE NULL 
 END as lycopene_mcg,
WHEN DS2ILZ IS NOT NULL THEN SAFE_CAST(DS2ILZ AS FLOAT64)WHEN DS2ILZ IS NULL THEN NULL 
ELSE NULL 
 END as lutein_zeaxanthin_mcg,
WHEN DS2IVB1 IS NOT NULL THEN SAFE_CAST(DS2IVB1 AS FLOAT64)WHEN DS2IVB1 IS NULL THEN NULL 
ELSE NULL 
 END as thiamin_vitamin_b1_mg,
WHEN DS2IVB2 IS NOT NULL THEN SAFE_CAST(DS2IVB2 AS FLOAT64)WHEN DS2IVB2 IS NULL THEN NULL 
ELSE NULL 
 END as riboflavin_vitamin_b2_mg,
WHEN DS2INIAC IS NOT NULL THEN SAFE_CAST(DS2INIAC AS FLOAT64)WHEN DS2INIAC IS NULL THEN NULL 
ELSE NULL 
 END as niacin_mg,
WHEN DS2IVB6 IS NOT NULL THEN SAFE_CAST(DS2IVB6 AS FLOAT64)WHEN DS2IVB6 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b6_mg,
WHEN DS2IFA IS NOT NULL THEN SAFE_CAST(DS2IFA AS FLOAT64)WHEN DS2IFA IS NULL THEN NULL 
ELSE NULL 
 END as folic_acid_mcg,
WHEN DS2IFDFE IS NOT NULL THEN SAFE_CAST(DS2IFDFE AS FLOAT64)WHEN DS2IFDFE IS NULL THEN NULL 
ELSE NULL 
 END as folate_dfe_mcg,
WHEN DS2ICHL IS NOT NULL THEN SAFE_CAST(DS2ICHL AS FLOAT64)WHEN DS2ICHL IS NULL THEN NULL 
ELSE NULL 
 END as total_choline_mg,
WHEN DS2IVB12 IS NOT NULL THEN SAFE_CAST(DS2IVB12 AS FLOAT64)WHEN DS2IVB12 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b12_mcg,
WHEN DS2IVC IS NOT NULL THEN SAFE_CAST(DS2IVC AS FLOAT64)WHEN DS2IVC IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_c_mg,
WHEN DS2IVK IS NOT NULL THEN SAFE_CAST(DS2IVK AS FLOAT64)WHEN DS2IVK IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_k_mcg,
WHEN DS2IVD IS NOT NULL THEN SAFE_CAST(DS2IVD AS FLOAT64)WHEN DS2IVD IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_d_d2_d3_mcg,
WHEN DS2ICALC IS NOT NULL THEN SAFE_CAST(DS2ICALC AS FLOAT64)WHEN DS2ICALC IS NULL THEN NULL 
ELSE NULL 
 END as calcium_mg,
WHEN DS2IPHOS IS NOT NULL THEN SAFE_CAST(DS2IPHOS AS FLOAT64)WHEN DS2IPHOS IS NULL THEN NULL 
ELSE NULL 
 END as phosphorus_mg,
WHEN DS2IMAGN IS NOT NULL THEN SAFE_CAST(DS2IMAGN AS FLOAT64)WHEN DS2IMAGN IS NULL THEN NULL 
ELSE NULL 
 END as magnesium_mg,
WHEN DS2IIRON IS NOT NULL THEN SAFE_CAST(DS2IIRON AS FLOAT64)WHEN DS2IIRON IS NULL THEN NULL 
ELSE NULL 
 END as iron_mg,
WHEN DS2IZINC IS NOT NULL THEN SAFE_CAST(DS2IZINC AS FLOAT64)WHEN DS2IZINC IS NULL THEN NULL 
ELSE NULL 
 END as zinc_mg,
WHEN DS2ICOPP IS NOT NULL THEN SAFE_CAST(DS2ICOPP AS FLOAT64)WHEN DS2ICOPP IS NULL THEN NULL 
ELSE NULL 
 END as copper_mg,
WHEN DS2ISODI IS NOT NULL THEN SAFE_CAST(DS2ISODI AS FLOAT64)WHEN DS2ISODI IS NULL THEN NULL 
ELSE NULL 
 END as sodium_mg,
WHEN DS2IPOTA IS NOT NULL THEN SAFE_CAST(DS2IPOTA AS FLOAT64)WHEN DS2IPOTA IS NULL THEN NULL 
ELSE NULL 
 END as potassium_mg,
WHEN DS2ISELE IS NOT NULL THEN SAFE_CAST(DS2ISELE AS FLOAT64)WHEN DS2ISELE IS NULL THEN NULL 
ELSE NULL 
 END as selenium_mcg,
WHEN DS2ICAFF IS NOT NULL THEN SAFE_CAST(DS2ICAFF AS FLOAT64)WHEN DS2ICAFF IS NULL THEN NULL 
ELSE NULL 
 END as caffeine_mg,
WHEN DS2IIODI IS NOT NULL THEN SAFE_CAST(DS2IIODI AS FLOAT64)WHEN DS2IIODI IS NULL THEN NULL 
ELSE NULL 
 END as iodine_mcg,
 FROM {ref('stg_nhanes_file_metadata'})