SELECT
SEQN as respondent_sequence_number,
WHEN LBXSATSI IS NOT NULL THEN SAFE_CAST(LBXSATSI AS FLOAT64)WHEN LBXSATSI IS NULL THEN NULL 
ELSE NULL 
 END as alanine_aminotransferase_alt_u_l,
CASE
    WHEN LBDSATLC = 0 THEN 'At or above detection limit' 
WHEN LBDSATLC = 1 THEN 'Below lower detection limit' 
WHEN LBDSATLC IS NULL THEN NULL 
ELSE NULL 
 END as alt_comment_code,
WHEN LBXSAL IS NOT NULL THEN SAFE_CAST(LBXSAL AS FLOAT64)WHEN LBXSAL IS NULL THEN NULL 
ELSE NULL 
 END as albumin_refrigerated_serum_g_dl,
WHEN LBDSALSI IS NOT NULL THEN SAFE_CAST(LBDSALSI AS FLOAT64)WHEN LBDSALSI IS NULL THEN NULL 
ELSE NULL 
 END as albumin_refrigerated_serum_g_l,
WHEN LBXSAPSI IS NOT NULL THEN SAFE_CAST(LBXSAPSI AS FLOAT64)WHEN LBXSAPSI IS NULL THEN NULL 
ELSE NULL 
 END as alkaline_phosphatase_alp_iu_l,
WHEN LBXSASSI IS NOT NULL THEN SAFE_CAST(LBXSASSI AS FLOAT64)WHEN LBXSASSI IS NULL THEN NULL 
ELSE NULL 
 END as aspartate_aminotransferase_ast_u_l,
WHEN LBXSC3SI IS NOT NULL THEN SAFE_CAST(LBXSC3SI AS FLOAT64)WHEN LBXSC3SI IS NULL THEN NULL 
ELSE NULL 
 END as bicarbonate_mmol_l,
WHEN LBXSBU IS NOT NULL THEN SAFE_CAST(LBXSBU AS FLOAT64)WHEN LBXSBU IS NULL THEN NULL 
ELSE NULL 
 END as blood_urea_nitrogen_mg_dl,
WHEN LBDSBUSI IS NOT NULL THEN SAFE_CAST(LBDSBUSI AS FLOAT64)WHEN LBDSBUSI IS NULL THEN NULL 
ELSE NULL 
 END as blood_urea_nitrogen_mmol_l,
WHEN LBXSCLSI IS NOT NULL THEN SAFE_CAST(LBXSCLSI AS FLOAT64)WHEN LBXSCLSI IS NULL THEN NULL 
ELSE NULL 
 END as chloride_mmol_l,
WHEN LBXSCK IS NOT NULL THEN SAFE_CAST(LBXSCK AS FLOAT64)WHEN LBXSCK IS NULL THEN NULL 
ELSE NULL 
 END as creatine_phosphokinase_cpk_iu_l,
WHEN LBXSCR IS NOT NULL THEN SAFE_CAST(LBXSCR AS FLOAT64)WHEN LBXSCR IS NULL THEN NULL 
ELSE NULL 
 END as creatinine_refrigerated_serum_mg_dl,
WHEN LBDSCRSI IS NOT NULL THEN SAFE_CAST(LBDSCRSI AS FLOAT64)WHEN LBDSCRSI IS NULL THEN NULL 
ELSE NULL 
 END as creatinine_refrigerated_serum_umol_l,
WHEN LBXSGB IS NOT NULL THEN SAFE_CAST(LBXSGB AS FLOAT64)WHEN LBXSGB IS NULL THEN NULL 
ELSE NULL 
 END as globulin_g_dl,
WHEN LBDSGBSI IS NOT NULL THEN SAFE_CAST(LBDSGBSI AS FLOAT64)WHEN LBDSGBSI IS NULL THEN NULL 
ELSE NULL 
 END as globulin_g_l,
WHEN LBXSGL IS NOT NULL THEN SAFE_CAST(LBXSGL AS FLOAT64)WHEN LBXSGL IS NULL THEN NULL 
ELSE NULL 
 END as glucose_refrigerated_serum_mg_dl,
WHEN LBDSGLSI IS NOT NULL THEN SAFE_CAST(LBDSGLSI AS FLOAT64)WHEN LBDSGLSI IS NULL THEN NULL 
ELSE NULL 
 END as glucose_refrigerated_serum_mmol_l,
WHEN LBXSGTSI IS NOT NULL THEN SAFE_CAST(LBXSGTSI AS FLOAT64)WHEN LBXSGTSI IS NULL THEN NULL 
ELSE NULL 
 END as gamma_glutamyl_transferase_ggt_iu_l,
CASE
    WHEN LBDSGTLC = 0 THEN 'At or above detection limit' 
WHEN LBDSGTLC = 1 THEN 'Below lower detection limit' 
WHEN LBDSGTLC IS NULL THEN NULL 
ELSE NULL 
 END as ggt_comment_code,
WHEN LBXSIR IS NOT NULL THEN SAFE_CAST(LBXSIR AS FLOAT64)WHEN LBXSIR IS NULL THEN NULL 
ELSE NULL 
 END as iron_refrigerated_serum_ug_dl,
WHEN LBDSIRSI IS NOT NULL THEN SAFE_CAST(LBDSIRSI AS FLOAT64)WHEN LBDSIRSI IS NULL THEN NULL 
ELSE NULL 
 END as iron_refrigerated_serum_umol_l,
WHEN LBXSLDSI IS NOT NULL THEN SAFE_CAST(LBXSLDSI AS FLOAT64)WHEN LBXSLDSI IS NULL THEN NULL 
ELSE NULL 
 END as lactate_dehydrogenase_ldh_iu_l,
WHEN LBXSOSSI IS NOT NULL THEN SAFE_CAST(LBXSOSSI AS FLOAT64)WHEN LBXSOSSI IS NULL THEN NULL 
ELSE NULL 
 END as osmolality_mmol_kg,
WHEN LBXSPH IS NOT NULL THEN SAFE_CAST(LBXSPH AS FLOAT64)WHEN LBXSPH IS NULL THEN NULL 
ELSE NULL 
 END as phosphorus_mg_dl,
WHEN LBDSPHSI IS NOT NULL THEN SAFE_CAST(LBDSPHSI AS FLOAT64)WHEN LBDSPHSI IS NULL THEN NULL 
ELSE NULL 
 END as phosphorus_mmol_l,
WHEN LBXSKSI IS NOT NULL THEN SAFE_CAST(LBXSKSI AS FLOAT64)WHEN LBXSKSI IS NULL THEN NULL 
ELSE NULL 
 END as potassium_mmol_l,
WHEN LBXSNASI IS NOT NULL THEN SAFE_CAST(LBXSNASI AS FLOAT64)WHEN LBXSNASI IS NULL THEN NULL 
ELSE NULL 
 END as sodium_mmol_l,
WHEN LBXSTB IS NOT NULL THEN SAFE_CAST(LBXSTB AS FLOAT64)WHEN LBXSTB IS NULL THEN NULL 
ELSE NULL 
 END as total_bilirubin_mg_dl,
WHEN LBDSTBSI IS NOT NULL THEN SAFE_CAST(LBDSTBSI AS FLOAT64)WHEN LBDSTBSI IS NULL THEN NULL 
ELSE NULL 
 END as total_bilirubin_umol_l,
CASE
    WHEN LBDSTBLC = 0 THEN 'At or above detection limit' 
WHEN LBDSTBLC = 1 THEN 'Below lower detection limit' 
WHEN LBDSTBLC IS NULL THEN NULL 
ELSE NULL 
 END as total_bilirubin_comment_code,
WHEN LBXSCA IS NOT NULL THEN SAFE_CAST(LBXSCA AS FLOAT64)WHEN LBXSCA IS NULL THEN NULL 
ELSE NULL 
 END as total_calcium_mg_dl,
WHEN LBDSCASI IS NOT NULL THEN SAFE_CAST(LBDSCASI AS FLOAT64)WHEN LBDSCASI IS NULL THEN NULL 
ELSE NULL 
 END as total_calcium_mmol_l,
WHEN LBXSCH IS NOT NULL THEN SAFE_CAST(LBXSCH AS FLOAT64)WHEN LBXSCH IS NULL THEN NULL 
ELSE NULL 
 END as cholesterol_refrigerated_serum_mg_dl,
WHEN LBDSCHSI IS NOT NULL THEN SAFE_CAST(LBDSCHSI AS FLOAT64)WHEN LBDSCHSI IS NULL THEN NULL 
ELSE NULL 
 END as cholesterol_refrigerated_serum_mmol_l,
WHEN LBXSTP IS NOT NULL THEN SAFE_CAST(LBXSTP AS FLOAT64)WHEN LBXSTP IS NULL THEN NULL 
ELSE NULL 
 END as total_protein_g_dl,
WHEN LBDSTPSI IS NOT NULL THEN SAFE_CAST(LBDSTPSI AS FLOAT64)WHEN LBDSTPSI IS NULL THEN NULL 
ELSE NULL 
 END as total_protein_g_l,
WHEN LBXSTR IS NOT NULL THEN SAFE_CAST(LBXSTR AS FLOAT64)WHEN LBXSTR IS NULL THEN NULL 
ELSE NULL 
 END as triglycerides_refrig_serum_mg_dl,
WHEN LBDSTRSI IS NOT NULL THEN SAFE_CAST(LBDSTRSI AS FLOAT64)WHEN LBDSTRSI IS NULL THEN NULL 
ELSE NULL 
 END as triglycerides_refrig_serum_mmol_l,
WHEN LBXSUA IS NOT NULL THEN SAFE_CAST(LBXSUA AS FLOAT64)WHEN LBXSUA IS NULL THEN NULL 
ELSE NULL 
 END as uric_acid_mg_dl,
WHEN LBDSUASI IS NOT NULL THEN SAFE_CAST(LBDSUASI AS FLOAT64)WHEN LBDSUASI IS NULL THEN NULL 
ELSE NULL 
 END as uric_acid_umol_l,
 FROM {ref('stg_standard_biochemistry_profile_laboratory'})