SELECT
SEQN as respondent_sequence_number, 

CASE
        WHEN WBXFEAR = 1 THEN 'Right Ear' 
WHEN WBXFEAR = 2 THEN 'Left Ear' 
WHEN WBXFEAR IS NULL THEN NULL 
ELSE NULL 
 END as ear_tested, 

CASE
        WHEN WBXF001 IS NOT NULL THEN WBXF001 
WHEN WBXF001 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_001, 

CASE
        WHEN WBXF002 IS NOT NULL THEN WBXF002 
WHEN WBXF002 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_002, 

CASE
        WHEN WBXF003 IS NOT NULL THEN WBXF003 
WHEN WBXF003 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_003, 

CASE
        WHEN WBXF004 IS NOT NULL THEN WBXF004 
WHEN WBXF004 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_004, 

CASE
        WHEN WBXF005 IS NOT NULL THEN WBXF005 
WHEN WBXF005 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_005, 

CASE
        WHEN WBXF006 IS NOT NULL THEN WBXF006 
WHEN WBXF006 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_006, 

CASE
        WHEN WBXF007 IS NOT NULL THEN WBXF007 
WHEN WBXF007 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_007, 

CASE
        WHEN WBXF008 IS NOT NULL THEN WBXF008 
WHEN WBXF008 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_008, 

CASE
        WHEN WBXF009 IS NOT NULL THEN WBXF009 
WHEN WBXF009 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_009, 

CASE
        WHEN WBXF010 IS NOT NULL THEN WBXF010 
WHEN WBXF010 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_010, 

CASE
        WHEN WBXF011 IS NOT NULL THEN WBXF011 
WHEN WBXF011 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_011, 

CASE
        WHEN WBXF012 IS NOT NULL THEN WBXF012 
WHEN WBXF012 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_012, 

CASE
        WHEN WBXF013 IS NOT NULL THEN WBXF013 
WHEN WBXF013 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_013, 

CASE
        WHEN WBXF014 IS NOT NULL THEN WBXF014 
WHEN WBXF014 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_014, 

CASE
        WHEN WBXF015 IS NOT NULL THEN WBXF015 
WHEN WBXF015 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_015, 

CASE
        WHEN WBXF016 IS NOT NULL THEN WBXF016 
WHEN WBXF016 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_016, 

CASE
        WHEN WBXF017 IS NOT NULL THEN WBXF017 
WHEN WBXF017 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_017, 

CASE
        WHEN WBXF018 IS NOT NULL THEN WBXF018 
WHEN WBXF018 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_018, 

CASE
        WHEN WBXF019 IS NOT NULL THEN WBXF019 
WHEN WBXF019 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_019, 

CASE
        WHEN WBXF020 IS NOT NULL THEN WBXF020 
WHEN WBXF020 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_020, 

CASE
        WHEN WBXF021 IS NOT NULL THEN WBXF021 
WHEN WBXF021 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_021, 

CASE
        WHEN WBXF022 IS NOT NULL THEN WBXF022 
WHEN WBXF022 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_022, 

CASE
        WHEN WBXF023 IS NOT NULL THEN WBXF023 
WHEN WBXF023 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_023, 

CASE
        WHEN WBXF024 IS NOT NULL THEN WBXF024 
WHEN WBXF024 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_024, 

CASE
        WHEN WBXF025 IS NOT NULL THEN WBXF025 
WHEN WBXF025 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_025, 

CASE
        WHEN WBXF026 IS NOT NULL THEN WBXF026 
WHEN WBXF026 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_026, 

CASE
        WHEN WBXF027 IS NOT NULL THEN WBXF027 
WHEN WBXF027 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_027, 

CASE
        WHEN WBXF028 IS NOT NULL THEN WBXF028 
WHEN WBXF028 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_028, 

CASE
        WHEN WBXF029 IS NOT NULL THEN WBXF029 
WHEN WBXF029 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_029, 

CASE
        WHEN WBXF030 IS NOT NULL THEN WBXF030 
WHEN WBXF030 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_030, 

CASE
        WHEN WBXF031 IS NOT NULL THEN WBXF031 
WHEN WBXF031 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_031, 

CASE
        WHEN WBXF032 IS NOT NULL THEN WBXF032 
WHEN WBXF032 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_032, 

CASE
        WHEN WBXF033 IS NOT NULL THEN WBXF033 
WHEN WBXF033 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_033, 

CASE
        WHEN WBXF034 IS NOT NULL THEN WBXF034 
WHEN WBXF034 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_034, 

CASE
        WHEN WBXF035 IS NOT NULL THEN WBXF035 
WHEN WBXF035 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_035, 

CASE
        WHEN WBXF036 IS NOT NULL THEN WBXF036 
WHEN WBXF036 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_036, 

CASE
        WHEN WBXF037 IS NOT NULL THEN WBXF037 
WHEN WBXF037 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_037, 

CASE
        WHEN WBXF038 IS NOT NULL THEN WBXF038 
WHEN WBXF038 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_038, 

CASE
        WHEN WBXF039 IS NOT NULL THEN WBXF039 
WHEN WBXF039 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_039, 

CASE
        WHEN WBXF040 IS NOT NULL THEN WBXF040 
WHEN WBXF040 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_040, 

CASE
        WHEN WBXF041 IS NOT NULL THEN WBXF041 
WHEN WBXF041 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_041, 

CASE
        WHEN WBXF042 IS NOT NULL THEN WBXF042 
WHEN WBXF042 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_042, 

CASE
        WHEN WBXF043 IS NOT NULL THEN WBXF043 
WHEN WBXF043 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_043, 

CASE
        WHEN WBXF044 IS NOT NULL THEN WBXF044 
WHEN WBXF044 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_044, 

CASE
        WHEN WBXF045 IS NOT NULL THEN WBXF045 
WHEN WBXF045 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_045, 

CASE
        WHEN WBXF046 IS NOT NULL THEN WBXF046 
WHEN WBXF046 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_046, 

CASE
        WHEN WBXF047 IS NOT NULL THEN WBXF047 
WHEN WBXF047 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_047, 

CASE
        WHEN WBXF048 IS NOT NULL THEN WBXF048 
WHEN WBXF048 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_048, 

CASE
        WHEN WBXF049 IS NOT NULL THEN WBXF049 
WHEN WBXF049 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_049, 

CASE
        WHEN WBXF050 IS NOT NULL THEN WBXF050 
WHEN WBXF050 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_050, 

CASE
        WHEN WBXF051 IS NOT NULL THEN WBXF051 
WHEN WBXF051 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_051, 

CASE
        WHEN WBXF052 IS NOT NULL THEN WBXF052 
WHEN WBXF052 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_052, 

CASE
        WHEN WBXF053 IS NOT NULL THEN WBXF053 
WHEN WBXF053 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_053, 

CASE
        WHEN WBXF054 IS NOT NULL THEN WBXF054 
WHEN WBXF054 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_054, 

CASE
        WHEN WBXF055 IS NOT NULL THEN WBXF055 
WHEN WBXF055 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_055, 

CASE
        WHEN WBXF056 IS NOT NULL THEN WBXF056 
WHEN WBXF056 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_056, 

CASE
        WHEN WBXF057 IS NOT NULL THEN WBXF057 
WHEN WBXF057 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_057, 

CASE
        WHEN WBXF058 IS NOT NULL THEN WBXF058 
WHEN WBXF058 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_058, 

CASE
        WHEN WBXF059 IS NOT NULL THEN WBXF059 
WHEN WBXF059 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_059, 

CASE
        WHEN WBXF060 IS NOT NULL THEN WBXF060 
WHEN WBXF060 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_060, 

CASE
        WHEN WBXF061 IS NOT NULL THEN WBXF061 
WHEN WBXF061 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_061, 

CASE
        WHEN WBXF062 IS NOT NULL THEN WBXF062 
WHEN WBXF062 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_062, 

CASE
        WHEN WBXF063 IS NOT NULL THEN WBXF063 
WHEN WBXF063 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_063, 

CASE
        WHEN WBXF064 IS NOT NULL THEN WBXF064 
WHEN WBXF064 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_064, 

CASE
        WHEN WBXF065 IS NOT NULL THEN WBXF065 
WHEN WBXF065 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_065, 

CASE
        WHEN WBXF066 IS NOT NULL THEN WBXF066 
WHEN WBXF066 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_066, 

CASE
        WHEN WBXF067 IS NOT NULL THEN WBXF067 
WHEN WBXF067 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_067, 

CASE
        WHEN WBXF068 IS NOT NULL THEN WBXF068 
WHEN WBXF068 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_068, 

CASE
        WHEN WBXF069 IS NOT NULL THEN WBXF069 
WHEN WBXF069 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_069, 

CASE
        WHEN WBXF070 IS NOT NULL THEN WBXF070 
WHEN WBXF070 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_070, 

CASE
        WHEN WBXF071 IS NOT NULL THEN WBXF071 
WHEN WBXF071 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_071, 

CASE
        WHEN WBXF072 IS NOT NULL THEN WBXF072 
WHEN WBXF072 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_072, 

CASE
        WHEN WBXF073 IS NOT NULL THEN WBXF073 
WHEN WBXF073 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_073, 

CASE
        WHEN WBXF074 IS NOT NULL THEN WBXF074 
WHEN WBXF074 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_074, 

CASE
        WHEN WBXF075 IS NOT NULL THEN WBXF075 
WHEN WBXF075 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_075, 

CASE
        WHEN WBXF076 IS NOT NULL THEN WBXF076 
WHEN WBXF076 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_076, 

CASE
        WHEN WBXF077 IS NOT NULL THEN WBXF077 
WHEN WBXF077 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_077, 

CASE
        WHEN WBXF078 IS NOT NULL THEN WBXF078 
WHEN WBXF078 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_078, 

CASE
        WHEN WBXF079 IS NOT NULL THEN WBXF079 
WHEN WBXF079 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_079, 

CASE
        WHEN WBXF080 IS NOT NULL THEN WBXF080 
WHEN WBXF080 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_080, 

CASE
        WHEN WBXF081 IS NOT NULL THEN WBXF081 
WHEN WBXF081 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_081, 

CASE
        WHEN WBXF082 IS NOT NULL THEN WBXF082 
WHEN WBXF082 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_082, 

CASE
        WHEN WBXF083 IS NOT NULL THEN WBXF083 
WHEN WBXF083 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_083, 

CASE
        WHEN WBXF084 IS NOT NULL THEN WBXF084 
WHEN WBXF084 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_084, 

CASE
        WHEN WBXF085 IS NOT NULL THEN WBXF085 
WHEN WBXF085 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_085, 

CASE
        WHEN WBXF086 IS NOT NULL THEN WBXF086 
WHEN WBXF086 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_086, 

CASE
        WHEN WBXF087 IS NOT NULL THEN WBXF087 
WHEN WBXF087 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_087, 

CASE
        WHEN WBXF088 IS NOT NULL THEN WBXF088 
WHEN WBXF088 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_088, 

CASE
        WHEN WBXF089 IS NOT NULL THEN WBXF089 
WHEN WBXF089 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_089, 

CASE
        WHEN WBXF090 IS NOT NULL THEN WBXF090 
WHEN WBXF090 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_090, 

CASE
        WHEN WBXF091 IS NOT NULL THEN WBXF091 
WHEN WBXF091 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_091, 

CASE
        WHEN WBXF092 IS NOT NULL THEN WBXF092 
WHEN WBXF092 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_092, 

CASE
        WHEN WBXF093 IS NOT NULL THEN WBXF093 
WHEN WBXF093 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_093, 

CASE
        WHEN WBXF094 IS NOT NULL THEN WBXF094 
WHEN WBXF094 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_094, 

CASE
        WHEN WBXF095 IS NOT NULL THEN WBXF095 
WHEN WBXF095 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_095, 

CASE
        WHEN WBXF096 IS NOT NULL THEN WBXF096 
WHEN WBXF096 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_096, 

CASE
        WHEN WBXF097 IS NOT NULL THEN WBXF097 
WHEN WBXF097 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_097, 

CASE
        WHEN WBXF098 IS NOT NULL THEN WBXF098 
WHEN WBXF098 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_098, 

CASE
        WHEN WBXF099 IS NOT NULL THEN WBXF099 
WHEN WBXF099 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_099, 

CASE
        WHEN WBXF100 IS NOT NULL THEN WBXF100 
WHEN WBXF100 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_100, 

CASE
        WHEN WBXF101 IS NOT NULL THEN WBXF101 
WHEN WBXF101 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_101, 

CASE
        WHEN WBXF102 IS NOT NULL THEN WBXF102 
WHEN WBXF102 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_102, 

CASE
        WHEN WBXF103 IS NOT NULL THEN WBXF103 
WHEN WBXF103 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_103, 

CASE
        WHEN WBXF104 IS NOT NULL THEN WBXF104 
WHEN WBXF104 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_104, 

CASE
        WHEN WBXF105 IS NOT NULL THEN WBXF105 
WHEN WBXF105 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_105, 

CASE
        WHEN WBXF106 IS NOT NULL THEN WBXF106 
WHEN WBXF106 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_106, 

CASE
        WHEN WBXF107 IS NOT NULL THEN WBXF107 
WHEN WBXF107 IS NULL THEN NULL 
ELSE NULL 
 END as frequency_array_data_point_107, 

CASE
        WHEN WBXA001 IS NOT NULL THEN WBXA001 
WHEN WBXA001 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_001, 

CASE
        WHEN WBXA002 IS NOT NULL THEN WBXA002 
WHEN WBXA002 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_002, 

CASE
        WHEN WBXA003 IS NOT NULL THEN WBXA003 
WHEN WBXA003 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_003, 

CASE
        WHEN WBXA004 IS NOT NULL THEN WBXA004 
WHEN WBXA004 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_004, 

CASE
        WHEN WBXA005 IS NOT NULL THEN WBXA005 
WHEN WBXA005 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_005, 

CASE
        WHEN WBXA006 IS NOT NULL THEN WBXA006 
WHEN WBXA006 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_006, 

CASE
        WHEN WBXA007 IS NOT NULL THEN WBXA007 
WHEN WBXA007 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_007, 

CASE
        WHEN WBXA008 IS NOT NULL THEN WBXA008 
WHEN WBXA008 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_008, 

CASE
        WHEN WBXA009 IS NOT NULL THEN WBXA009 
WHEN WBXA009 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_009, 

CASE
        WHEN WBXA010 IS NOT NULL THEN WBXA010 
WHEN WBXA010 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_010, 

CASE
        WHEN WBXA011 IS NOT NULL THEN WBXA011 
WHEN WBXA011 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_011, 

CASE
        WHEN WBXA012 IS NOT NULL THEN WBXA012 
WHEN WBXA012 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_012, 

CASE
        WHEN WBXA013 IS NOT NULL THEN WBXA013 
WHEN WBXA013 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_013, 

CASE
        WHEN WBXA014 IS NOT NULL THEN WBXA014 
WHEN WBXA014 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_014, 

CASE
        WHEN WBXA015 IS NOT NULL THEN WBXA015 
WHEN WBXA015 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_015, 

CASE
        WHEN WBXA016 IS NOT NULL THEN WBXA016 
WHEN WBXA016 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_016, 

CASE
        WHEN WBXA017 IS NOT NULL THEN WBXA017 
WHEN WBXA017 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_017, 

CASE
        WHEN WBXA018 IS NOT NULL THEN WBXA018 
WHEN WBXA018 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_018, 

CASE
        WHEN WBXA019 IS NOT NULL THEN WBXA019 
WHEN WBXA019 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_019, 

CASE
        WHEN WBXA020 IS NOT NULL THEN WBXA020 
WHEN WBXA020 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_020, 

CASE
        WHEN WBXA021 IS NOT NULL THEN WBXA021 
WHEN WBXA021 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_021, 

CASE
        WHEN WBXA022 IS NOT NULL THEN WBXA022 
WHEN WBXA022 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_022, 

CASE
        WHEN WBXA023 IS NOT NULL THEN WBXA023 
WHEN WBXA023 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_023, 

CASE
        WHEN WBXA024 IS NOT NULL THEN WBXA024 
WHEN WBXA024 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_024, 

CASE
        WHEN WBXA025 IS NOT NULL THEN WBXA025 
WHEN WBXA025 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_025, 

CASE
        WHEN WBXA026 IS NOT NULL THEN WBXA026 
WHEN WBXA026 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_026, 

CASE
        WHEN WBXA027 IS NOT NULL THEN WBXA027 
WHEN WBXA027 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_027, 

CASE
        WHEN WBXA028 IS NOT NULL THEN WBXA028 
WHEN WBXA028 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_028, 

CASE
        WHEN WBXA029 IS NOT NULL THEN WBXA029 
WHEN WBXA029 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_029, 

CASE
        WHEN WBXA030 IS NOT NULL THEN WBXA030 
WHEN WBXA030 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_030, 

CASE
        WHEN WBXA031 IS NOT NULL THEN WBXA031 
WHEN WBXA031 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_031, 

CASE
        WHEN WBXA032 IS NOT NULL THEN WBXA032 
WHEN WBXA032 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_032, 

CASE
        WHEN WBXA033 IS NOT NULL THEN WBXA033 
WHEN WBXA033 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_033, 

CASE
        WHEN WBXA034 IS NOT NULL THEN WBXA034 
WHEN WBXA034 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_034, 

CASE
        WHEN WBXA035 IS NOT NULL THEN WBXA035 
WHEN WBXA035 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_035, 

CASE
        WHEN WBXA036 IS NOT NULL THEN WBXA036 
WHEN WBXA036 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_036, 

CASE
        WHEN WBXA037 IS NOT NULL THEN WBXA037 
WHEN WBXA037 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_037, 

CASE
        WHEN WBXA038 IS NOT NULL THEN WBXA038 
WHEN WBXA038 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_038, 

CASE
        WHEN WBXA039 IS NOT NULL THEN WBXA039 
WHEN WBXA039 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_039, 

CASE
        WHEN WBXA040 IS NOT NULL THEN WBXA040 
WHEN WBXA040 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_040, 

CASE
        WHEN WBXA041 IS NOT NULL THEN WBXA041 
WHEN WBXA041 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_041, 

CASE
        WHEN WBXA042 IS NOT NULL THEN WBXA042 
WHEN WBXA042 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_042, 

CASE
        WHEN WBXA043 IS NOT NULL THEN WBXA043 
WHEN WBXA043 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_043, 

CASE
        WHEN WBXA044 IS NOT NULL THEN WBXA044 
WHEN WBXA044 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_044, 

CASE
        WHEN WBXA045 IS NOT NULL THEN WBXA045 
WHEN WBXA045 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_045, 

CASE
        WHEN WBXA046 IS NOT NULL THEN WBXA046 
WHEN WBXA046 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_046, 

CASE
        WHEN WBXA047 IS NOT NULL THEN WBXA047 
WHEN WBXA047 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_047, 

CASE
        WHEN WBXA048 IS NOT NULL THEN WBXA048 
WHEN WBXA048 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_048, 

CASE
        WHEN WBXA049 IS NOT NULL THEN WBXA049 
WHEN WBXA049 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_049, 

CASE
        WHEN WBXA050 IS NOT NULL THEN WBXA050 
WHEN WBXA050 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_050, 

CASE
        WHEN WBXA051 IS NOT NULL THEN WBXA051 
WHEN WBXA051 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_051, 

CASE
        WHEN WBXA052 IS NOT NULL THEN WBXA052 
WHEN WBXA052 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_052, 

CASE
        WHEN WBXA053 IS NOT NULL THEN WBXA053 
WHEN WBXA053 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_053, 

CASE
        WHEN WBXA054 IS NOT NULL THEN WBXA054 
WHEN WBXA054 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_054, 

CASE
        WHEN WBXA055 IS NOT NULL THEN WBXA055 
WHEN WBXA055 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_055, 

CASE
        WHEN WBXA056 IS NOT NULL THEN WBXA056 
WHEN WBXA056 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_056, 

CASE
        WHEN WBXA057 IS NOT NULL THEN WBXA057 
WHEN WBXA057 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_057, 

CASE
        WHEN WBXA058 IS NOT NULL THEN WBXA058 
WHEN WBXA058 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_058, 

CASE
        WHEN WBXA059 IS NOT NULL THEN WBXA059 
WHEN WBXA059 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_059, 

CASE
        WHEN WBXA060 IS NOT NULL THEN WBXA060 
WHEN WBXA060 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_060, 

CASE
        WHEN WBXA061 IS NOT NULL THEN WBXA061 
WHEN WBXA061 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_061, 

CASE
        WHEN WBXA062 IS NOT NULL THEN WBXA062 
WHEN WBXA062 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_062, 

CASE
        WHEN WBXA063 IS NOT NULL THEN WBXA063 
WHEN WBXA063 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_063, 

CASE
        WHEN WBXA064 IS NOT NULL THEN WBXA064 
WHEN WBXA064 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_064, 

CASE
        WHEN WBXA065 IS NOT NULL THEN WBXA065 
WHEN WBXA065 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_065, 

CASE
        WHEN WBXA066 IS NOT NULL THEN WBXA066 
WHEN WBXA066 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_066, 

CASE
        WHEN WBXA067 IS NOT NULL THEN WBXA067 
WHEN WBXA067 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_067, 

CASE
        WHEN WBXA068 IS NOT NULL THEN WBXA068 
WHEN WBXA068 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_068, 

CASE
        WHEN WBXA069 IS NOT NULL THEN WBXA069 
WHEN WBXA069 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_069, 

CASE
        WHEN WBXA070 IS NOT NULL THEN WBXA070 
WHEN WBXA070 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_070, 

CASE
        WHEN WBXA071 IS NOT NULL THEN WBXA071 
WHEN WBXA071 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_071, 

CASE
        WHEN WBXA072 IS NOT NULL THEN WBXA072 
WHEN WBXA072 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_072, 

CASE
        WHEN WBXA073 IS NOT NULL THEN WBXA073 
WHEN WBXA073 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_073, 

CASE
        WHEN WBXA074 IS NOT NULL THEN WBXA074 
WHEN WBXA074 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_074, 

CASE
        WHEN WBXA075 IS NOT NULL THEN WBXA075 
WHEN WBXA075 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_075, 

CASE
        WHEN WBXA076 IS NOT NULL THEN WBXA076 
WHEN WBXA076 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_076, 

CASE
        WHEN WBXA077 IS NOT NULL THEN WBXA077 
WHEN WBXA077 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_077, 

CASE
        WHEN WBXA078 IS NOT NULL THEN WBXA078 
WHEN WBXA078 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_078, 

CASE
        WHEN WBXA079 IS NOT NULL THEN WBXA079 
WHEN WBXA079 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_079, 

CASE
        WHEN WBXA080 IS NOT NULL THEN WBXA080 
WHEN WBXA080 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_080, 

CASE
        WHEN WBXA081 IS NOT NULL THEN WBXA081 
WHEN WBXA081 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_081, 

CASE
        WHEN WBXA082 IS NOT NULL THEN WBXA082 
WHEN WBXA082 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_082, 

CASE
        WHEN WBXA083 IS NOT NULL THEN WBXA083 
WHEN WBXA083 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_083, 

CASE
        WHEN WBXA084 IS NOT NULL THEN WBXA084 
WHEN WBXA084 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_084, 

CASE
        WHEN WBXA085 IS NOT NULL THEN WBXA085 
WHEN WBXA085 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_085, 

CASE
        WHEN WBXA086 IS NOT NULL THEN WBXA086 
WHEN WBXA086 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_086, 

CASE
        WHEN WBXA087 IS NOT NULL THEN WBXA087 
WHEN WBXA087 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_087, 

CASE
        WHEN WBXA088 IS NOT NULL THEN WBXA088 
WHEN WBXA088 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_088, 

CASE
        WHEN WBXA089 IS NOT NULL THEN WBXA089 
WHEN WBXA089 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_089, 

CASE
        WHEN WBXA090 IS NOT NULL THEN WBXA090 
WHEN WBXA090 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_090, 

CASE
        WHEN WBXA091 IS NOT NULL THEN WBXA091 
WHEN WBXA091 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_091, 

CASE
        WHEN WBXA092 IS NOT NULL THEN WBXA092 
WHEN WBXA092 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_092, 

CASE
        WHEN WBXA093 IS NOT NULL THEN WBXA093 
WHEN WBXA093 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_093, 

CASE
        WHEN WBXA094 IS NOT NULL THEN WBXA094 
WHEN WBXA094 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_094, 

CASE
        WHEN WBXA095 IS NOT NULL THEN WBXA095 
WHEN WBXA095 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_095, 

CASE
        WHEN WBXA096 IS NOT NULL THEN WBXA096 
WHEN WBXA096 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_096, 

CASE
        WHEN WBXA097 IS NOT NULL THEN WBXA097 
WHEN WBXA097 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_097, 

CASE
        WHEN WBXA098 IS NOT NULL THEN WBXA098 
WHEN WBXA098 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_098, 

CASE
        WHEN WBXA099 IS NOT NULL THEN WBXA099 
WHEN WBXA099 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_099, 

CASE
        WHEN WBXA100 IS NOT NULL THEN WBXA100 
WHEN WBXA100 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_100, 

CASE
        WHEN WBXA101 IS NOT NULL THEN WBXA101 
WHEN WBXA101 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_101, 

CASE
        WHEN WBXA102 IS NOT NULL THEN WBXA102 
WHEN WBXA102 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_102, 

CASE
        WHEN WBXA103 IS NOT NULL THEN WBXA103 
WHEN WBXA103 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_103, 

CASE
        WHEN WBXA104 IS NOT NULL THEN WBXA104 
WHEN WBXA104 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_104, 

CASE
        WHEN WBXA105 IS NOT NULL THEN WBXA105 
WHEN WBXA105 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_105, 

CASE
        WHEN WBXA106 IS NOT NULL THEN WBXA106 
WHEN WBXA106 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_106, 

CASE
        WHEN WBXA107 IS NOT NULL THEN WBXA107 
WHEN WBXA107 IS NULL THEN NULL 
ELSE NULL 
 END as absorbance_array_data_point_107, 

CASE
        WHEN WBXP001 IS NOT NULL THEN WBXP001 
WHEN WBXP001 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_001, 

CASE
        WHEN WBXP002 IS NOT NULL THEN WBXP002 
WHEN WBXP002 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_002, 

CASE
        WHEN WBXP003 IS NOT NULL THEN WBXP003 
WHEN WBXP003 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_003, 

CASE
        WHEN WBXP004 IS NOT NULL THEN WBXP004 
WHEN WBXP004 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_004, 

CASE
        WHEN WBXP005 IS NOT NULL THEN WBXP005 
WHEN WBXP005 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_005, 

CASE
        WHEN WBXP006 IS NOT NULL THEN WBXP006 
WHEN WBXP006 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_006, 

CASE
        WHEN WBXP007 IS NOT NULL THEN WBXP007 
WHEN WBXP007 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_007, 

CASE
        WHEN WBXP008 IS NOT NULL THEN WBXP008 
WHEN WBXP008 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_008, 

CASE
        WHEN WBXP009 IS NOT NULL THEN WBXP009 
WHEN WBXP009 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_009, 

CASE
        WHEN WBXP010 IS NOT NULL THEN WBXP010 
WHEN WBXP010 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_010, 

CASE
        WHEN WBXP011 IS NOT NULL THEN WBXP011 
WHEN WBXP011 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_011, 

CASE
        WHEN WBXP012 IS NOT NULL THEN WBXP012 
WHEN WBXP012 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_012, 

CASE
        WHEN WBXP013 IS NOT NULL THEN WBXP013 
WHEN WBXP013 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_013, 

CASE
        WHEN WBXP014 IS NOT NULL THEN WBXP014 
WHEN WBXP014 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_014, 

CASE
        WHEN WBXP015 IS NOT NULL THEN WBXP015 
WHEN WBXP015 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_015, 

CASE
        WHEN WBXP016 IS NOT NULL THEN WBXP016 
WHEN WBXP016 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_016, 

CASE
        WHEN WBXP017 IS NOT NULL THEN WBXP017 
WHEN WBXP017 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_017, 

CASE
        WHEN WBXP018 IS NOT NULL THEN WBXP018 
WHEN WBXP018 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_018, 

CASE
        WHEN WBXP019 IS NOT NULL THEN WBXP019 
WHEN WBXP019 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_019, 

CASE
        WHEN WBXP020 IS NOT NULL THEN WBXP020 
WHEN WBXP020 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_020, 

CASE
        WHEN WBXP021 IS NOT NULL THEN WBXP021 
WHEN WBXP021 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_021, 

CASE
        WHEN WBXP022 IS NOT NULL THEN WBXP022 
WHEN WBXP022 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_022, 

CASE
        WHEN WBXP023 IS NOT NULL THEN WBXP023 
WHEN WBXP023 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_023, 

CASE
        WHEN WBXP024 IS NOT NULL THEN WBXP024 
WHEN WBXP024 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_024, 

CASE
        WHEN WBXP025 IS NOT NULL THEN WBXP025 
WHEN WBXP025 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_025, 

CASE
        WHEN WBXP026 IS NOT NULL THEN WBXP026 
WHEN WBXP026 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_026, 

CASE
        WHEN WBXP027 IS NOT NULL THEN WBXP027 
WHEN WBXP027 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_027, 

CASE
        WHEN WBXP028 IS NOT NULL THEN WBXP028 
WHEN WBXP028 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_028, 

CASE
        WHEN WBXP029 IS NOT NULL THEN WBXP029 
WHEN WBXP029 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_029, 

CASE
        WHEN WBXP030 IS NOT NULL THEN WBXP030 
WHEN WBXP030 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_030, 

CASE
        WHEN WBXP031 IS NOT NULL THEN WBXP031 
WHEN WBXP031 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_031, 

CASE
        WHEN WBXP032 IS NOT NULL THEN WBXP032 
WHEN WBXP032 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_032, 

CASE
        WHEN WBXP033 IS NOT NULL THEN WBXP033 
WHEN WBXP033 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_033, 

CASE
        WHEN WBXP034 IS NOT NULL THEN WBXP034 
WHEN WBXP034 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_034, 

CASE
        WHEN WBXP035 IS NOT NULL THEN WBXP035 
WHEN WBXP035 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_035, 

CASE
        WHEN WBXP036 IS NOT NULL THEN WBXP036 
WHEN WBXP036 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_036, 

CASE
        WHEN WBXP037 IS NOT NULL THEN WBXP037 
WHEN WBXP037 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_037, 

CASE
        WHEN WBXP038 IS NOT NULL THEN WBXP038 
WHEN WBXP038 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_038, 

CASE
        WHEN WBXP039 IS NOT NULL THEN WBXP039 
WHEN WBXP039 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_039, 

CASE
        WHEN WBXP040 IS NOT NULL THEN WBXP040 
WHEN WBXP040 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_040, 

CASE
        WHEN WBXP041 IS NOT NULL THEN WBXP041 
WHEN WBXP041 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_041, 

CASE
        WHEN WBXP042 IS NOT NULL THEN WBXP042 
WHEN WBXP042 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_042, 

CASE
        WHEN WBXP043 IS NOT NULL THEN WBXP043 
WHEN WBXP043 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_043, 

CASE
        WHEN WBXP044 IS NOT NULL THEN WBXP044 
WHEN WBXP044 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_044, 

CASE
        WHEN WBXP045 IS NOT NULL THEN WBXP045 
WHEN WBXP045 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_045, 

CASE
        WHEN WBXP046 IS NOT NULL THEN WBXP046 
WHEN WBXP046 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_046, 

CASE
        WHEN WBXP047 IS NOT NULL THEN WBXP047 
WHEN WBXP047 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_047, 

CASE
        WHEN WBXP048 IS NOT NULL THEN WBXP048 
WHEN WBXP048 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_048, 

CASE
        WHEN WBXP049 IS NOT NULL THEN WBXP049 
WHEN WBXP049 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_049, 

CASE
        WHEN WBXP050 IS NOT NULL THEN WBXP050 
WHEN WBXP050 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_050, 

CASE
        WHEN WBXP051 IS NOT NULL THEN WBXP051 
WHEN WBXP051 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_051, 

CASE
        WHEN WBXP052 IS NOT NULL THEN WBXP052 
WHEN WBXP052 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_052, 

CASE
        WHEN WBXP053 IS NOT NULL THEN WBXP053 
WHEN WBXP053 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_053, 

CASE
        WHEN WBXP054 IS NOT NULL THEN WBXP054 
WHEN WBXP054 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_054, 

CASE
        WHEN WBXP055 IS NOT NULL THEN WBXP055 
WHEN WBXP055 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_055, 

CASE
        WHEN WBXP056 IS NOT NULL THEN WBXP056 
WHEN WBXP056 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_056, 

CASE
        WHEN WBXP057 IS NOT NULL THEN WBXP057 
WHEN WBXP057 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_057, 

CASE
        WHEN WBXP058 IS NOT NULL THEN WBXP058 
WHEN WBXP058 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_058, 

CASE
        WHEN WBXP059 IS NOT NULL THEN WBXP059 
WHEN WBXP059 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_059, 

CASE
        WHEN WBXP060 IS NOT NULL THEN WBXP060 
WHEN WBXP060 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_060, 

CASE
        WHEN WBXP061 IS NOT NULL THEN WBXP061 
WHEN WBXP061 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_061, 

CASE
        WHEN WBXP062 IS NOT NULL THEN WBXP062 
WHEN WBXP062 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_062, 

CASE
        WHEN WBXP063 IS NOT NULL THEN WBXP063 
WHEN WBXP063 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_063, 

CASE
        WHEN WBXP064 IS NOT NULL THEN WBXP064 
WHEN WBXP064 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_064, 

CASE
        WHEN WBXP065 IS NOT NULL THEN WBXP065 
WHEN WBXP065 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_065, 

CASE
        WHEN WBXP066 IS NOT NULL THEN WBXP066 
WHEN WBXP066 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_066, 

CASE
        WHEN WBXP067 IS NOT NULL THEN WBXP067 
WHEN WBXP067 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_067, 

CASE
        WHEN WBXP068 IS NOT NULL THEN WBXP068 
WHEN WBXP068 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_068, 

CASE
        WHEN WBXP069 IS NOT NULL THEN WBXP069 
WHEN WBXP069 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_069, 

CASE
        WHEN WBXP070 IS NOT NULL THEN WBXP070 
WHEN WBXP070 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_070, 

CASE
        WHEN WBXP071 IS NOT NULL THEN WBXP071 
WHEN WBXP071 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_071, 

CASE
        WHEN WBXP072 IS NOT NULL THEN WBXP072 
WHEN WBXP072 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_072, 

CASE
        WHEN WBXP073 IS NOT NULL THEN WBXP073 
WHEN WBXP073 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_073, 

CASE
        WHEN WBXP074 IS NOT NULL THEN WBXP074 
WHEN WBXP074 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_074, 

CASE
        WHEN WBXP075 IS NOT NULL THEN WBXP075 
WHEN WBXP075 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_075, 

CASE
        WHEN WBXP076 IS NOT NULL THEN WBXP076 
WHEN WBXP076 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_076, 

CASE
        WHEN WBXP077 IS NOT NULL THEN WBXP077 
WHEN WBXP077 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_077, 

CASE
        WHEN WBXP078 IS NOT NULL THEN WBXP078 
WHEN WBXP078 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_078, 

CASE
        WHEN WBXP079 IS NOT NULL THEN WBXP079 
WHEN WBXP079 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_079, 

CASE
        WHEN WBXP080 IS NOT NULL THEN WBXP080 
WHEN WBXP080 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_080, 

CASE
        WHEN WBXP081 IS NOT NULL THEN WBXP081 
WHEN WBXP081 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_081, 

CASE
        WHEN WBXP082 IS NOT NULL THEN WBXP082 
WHEN WBXP082 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_082, 

CASE
        WHEN WBXP083 IS NOT NULL THEN WBXP083 
WHEN WBXP083 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_083, 

CASE
        WHEN WBXP084 IS NOT NULL THEN WBXP084 
WHEN WBXP084 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_084, 

CASE
        WHEN WBXP085 IS NOT NULL THEN WBXP085 
WHEN WBXP085 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_085, 

CASE
        WHEN WBXP086 IS NOT NULL THEN WBXP086 
WHEN WBXP086 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_086, 

CASE
        WHEN WBXP087 IS NOT NULL THEN WBXP087 
WHEN WBXP087 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_087, 

CASE
        WHEN WBXP088 IS NOT NULL THEN WBXP088 
WHEN WBXP088 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_088, 

CASE
        WHEN WBXP089 IS NOT NULL THEN WBXP089 
WHEN WBXP089 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_089, 

CASE
        WHEN WBXP090 IS NOT NULL THEN WBXP090 
WHEN WBXP090 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_090, 

CASE
        WHEN WBXP091 IS NOT NULL THEN WBXP091 
WHEN WBXP091 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_091, 

CASE
        WHEN WBXP092 IS NOT NULL THEN WBXP092 
WHEN WBXP092 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_092, 

CASE
        WHEN WBXP093 IS NOT NULL THEN WBXP093 
WHEN WBXP093 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_093, 

CASE
        WHEN WBXP094 IS NOT NULL THEN WBXP094 
WHEN WBXP094 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_094, 

CASE
        WHEN WBXP095 IS NOT NULL THEN WBXP095 
WHEN WBXP095 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_095, 

CASE
        WHEN WBXP096 IS NOT NULL THEN WBXP096 
WHEN WBXP096 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_096, 

CASE
        WHEN WBXP097 IS NOT NULL THEN WBXP097 
WHEN WBXP097 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_097, 

CASE
        WHEN WBXP098 IS NOT NULL THEN WBXP098 
WHEN WBXP098 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_098, 

CASE
        WHEN WBXP099 IS NOT NULL THEN WBXP099 
WHEN WBXP099 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_099, 

CASE
        WHEN WBXP100 IS NOT NULL THEN WBXP100 
WHEN WBXP100 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_100, 

CASE
        WHEN WBXP101 IS NOT NULL THEN WBXP101 
WHEN WBXP101 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_101, 

CASE
        WHEN WBXP102 IS NOT NULL THEN WBXP102 
WHEN WBXP102 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_102, 

CASE
        WHEN WBXP103 IS NOT NULL THEN WBXP103 
WHEN WBXP103 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_103, 

CASE
        WHEN WBXP104 IS NOT NULL THEN WBXP104 
WHEN WBXP104 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_104, 

CASE
        WHEN WBXP105 IS NOT NULL THEN WBXP105 
WHEN WBXP105 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_105, 

CASE
        WHEN WBXP106 IS NOT NULL THEN WBXP106 
WHEN WBXP106 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_106, 

CASE
        WHEN WBXP107 IS NOT NULL THEN WBXP107 
WHEN WBXP107 IS NULL THEN NULL 
ELSE NULL 
 END as phase_array_data_point_107, 

 FROM {{ ref('stg_audiometry_wideband_reflectance_examination') }}