SELECT
SEQN as respondent_sequence_number, 

CASE
        WHEN LBXWBCSI IS NOT NULL THEN LBXWBCSI 
WHEN LBXWBCSI IS NOT NULL THEN LBXWBCSI 
WHEN LBXWBCSI IS NULL THEN NULL 
ELSE NULL 
 END as white_blood_cell_count_1000_cells_ul, 

CASE
        WHEN LBXLYPCT IS NOT NULL THEN LBXLYPCT 
WHEN LBXLYPCT IS NULL THEN NULL 
ELSE NULL 
 END as lymphocyte_percent, 

CASE
        WHEN LBXMOPCT IS NOT NULL THEN LBXMOPCT 
WHEN LBXMOPCT IS NULL THEN NULL 
ELSE NULL 
 END as monocyte_percent, 

CASE
        WHEN LBXNEPCT IS NOT NULL THEN LBXNEPCT 
WHEN LBXNEPCT IS NULL THEN NULL 
ELSE NULL 
 END as segmented_neutrophils_percent, 

CASE
        WHEN LBXEOPCT IS NOT NULL THEN LBXEOPCT 
WHEN LBXEOPCT IS NULL THEN NULL 
ELSE NULL 
 END as eosinophils_percent, 

CASE
        WHEN LBXBAPCT IS NOT NULL THEN LBXBAPCT 
WHEN LBXBAPCT IS NULL THEN NULL 
ELSE NULL 
 END as basophils_percent, 

CASE
        WHEN LBDLYMNO IS NOT NULL THEN LBDLYMNO 
WHEN LBDLYMNO IS NULL THEN NULL 
ELSE NULL 
 END as lymphocyte_number_1000_cells_ul, 

CASE
        WHEN LBDMONO IS NOT NULL THEN LBDMONO 
WHEN LBDMONO IS NULL THEN NULL 
ELSE NULL 
 END as monocyte_number_1000_cells_ul, 

CASE
        WHEN LBDNENO IS NOT NULL THEN LBDNENO 
WHEN LBDNENO IS NULL THEN NULL 
ELSE NULL 
 END as segmented_neutrophils_num_1000_cell_ul, 

CASE
        WHEN LBDEONO IS NOT NULL THEN LBDEONO 
WHEN LBDEONO IS NULL THEN NULL 
ELSE NULL 
 END as eosinophils_number_1000_cells_ul, 

CASE
        WHEN LBDBANO IS NOT NULL THEN LBDBANO 
WHEN LBDBANO IS NULL THEN NULL 
ELSE NULL 
 END as basophils_number_1000_cells_ul, 

CASE
        WHEN LBXRBCSI IS NOT NULL THEN LBXRBCSI 
WHEN LBXRBCSI IS NULL THEN NULL 
ELSE NULL 
 END as red_blood_cell_count_million_cells_ul, 

CASE
        WHEN LBXHGB IS NOT NULL THEN LBXHGB 
WHEN LBXHGB IS NULL THEN NULL 
ELSE NULL 
 END as hemoglobin_g_dl, 

CASE
        WHEN LBXHCT IS NOT NULL THEN LBXHCT 
WHEN LBXHCT IS NULL THEN NULL 
ELSE NULL 
 END as hematocrit, 

CASE
        WHEN LBXMCVSI IS NOT NULL THEN LBXMCVSI 
WHEN LBXMCVSI IS NULL THEN NULL 
ELSE NULL 
 END as mean_cell_volume_fl, 

CASE
        WHEN LBXMCHSI IS NOT NULL THEN LBXMCHSI 
WHEN LBXMCHSI IS NULL THEN NULL 
ELSE NULL 
 END as mean_cell_hemoglobin_pg, 

CASE
        WHEN LBXMC IS NOT NULL THEN LBXMC 
WHEN LBXMC IS NULL THEN NULL 
ELSE NULL 
 END as mean_cell_hgb_conc_g_dl, 

CASE
        WHEN LBXRDW IS NOT NULL THEN LBXRDW 
WHEN LBXRDW IS NULL THEN NULL 
ELSE NULL 
 END as red_cell_distribution_width, 

CASE
        WHEN LBXPLTSI IS NOT NULL THEN LBXPLTSI 
WHEN LBXPLTSI IS NULL THEN NULL 
ELSE NULL 
 END as platelet_count_1000_cells_ul, 

CASE
        WHEN LBXMPSI IS NOT NULL THEN LBXMPSI 
WHEN LBXMPSI IS NULL THEN NULL 
ELSE NULL 
 END as mean_platelet_volume_fl, 

CASE
        WHEN LBXNRBC IS NOT NULL THEN LBXNRBC 
WHEN LBXNRBC IS NULL THEN NULL 
ELSE NULL 
 END as nucleated_red_blood_cells, 

 FROM {{ ref('stg_complete_blood_count_with_5_part_differential_laboratory') }}