SELECT
SEQN as respondent_sequence_number, 

CASE
        WHEN WTDRD1 IS NOT NULL THEN WTDRD1 
WHEN WTDRD1 IS NOT NULL THEN WTDRD1 
WHEN WTDRD1 IS NULL THEN NULL 
ELSE NULL 
 END as dietary_day_one_sample_weight, 

CASE
        WHEN WTDR2D IS NOT NULL THEN WTDR2D 
WHEN WTDR2D IS NOT NULL THEN WTDR2D 
WHEN WTDR2D IS NULL THEN NULL 
ELSE NULL 
 END as dietary_two_day_sample_weight, 

CASE
        WHEN DR2DRSTZ = 1 THEN 'Reliable and met the minimum criteria' 
WHEN DR2DRSTZ = 2 THEN 'Not reliable or not met the minimum criteria' 
WHEN DR2DRSTZ = 4 THEN 'Reported consuming breast-milk' 
WHEN DR2DRSTZ = 5 THEN 'Not done' 
WHEN DR2DRSTZ IS NULL THEN NULL 
ELSE NULL 
 END as dietary_recall_status, 

CASE
        WHEN DR2EXMER IS NOT NULL THEN DR2EXMER 
WHEN DR2EXMER IS NULL THEN NULL 
ELSE NULL 
 END as interviewer_id_code, 

CASE
        WHEN DRDINT = 1 THEN 'Day 1 only' 
WHEN DRDINT = 2 THEN 'Day 1 and day 2' 
WHEN DRDINT IS NULL THEN NULL 
ELSE NULL 
 END as number_of_days_of_intake, 

CASE
        WHEN DR2DBIH IS NOT NULL THEN DR2DBIH 
WHEN DR2DBIH IS NULL THEN NULL 
ELSE NULL 
 END as of_days_b_w_intake_and_hh_interview, 

CASE
        WHEN DR2DAY = 1 THEN 'Sunday' 
WHEN DR2DAY = 2 THEN 'Monday' 
WHEN DR2DAY = 3 THEN 'Tuesday' 
WHEN DR2DAY = 4 THEN 'Wednesday' 
WHEN DR2DAY = 5 THEN 'Thursday' 
WHEN DR2DAY = 6 THEN 'Friday' 
WHEN DR2DAY = 7 THEN 'Saturday' 
WHEN DR2DAY IS NULL THEN NULL 
ELSE NULL 
 END as intake_day_of_the_week, 

CASE
        WHEN DR2LANG = 1 THEN 'English' 
WHEN DR2LANG = 2 THEN 'Spanish' 
WHEN DR2LANG = 3 THEN 'English and Spanish' 
WHEN DR2LANG = 4 THEN 'Other' 
WHEN DR2LANG = 5 THEN 'Asian Languages' 
WHEN DR2LANG = 6 THEN 'Asian Languages and English' 
WHEN DR2LANG IS NULL THEN NULL 
ELSE NULL 
 END as language_respondent_used_mostly, 

CASE
        WHEN DS2LOC = 1 THEN 'HouseHold Interview' 
WHEN DS2LOC = 2 THEN 'MEC Interview' 
WHEN DS2LOC = 3 THEN 'Phone Interview' 
WHEN DS2LOC IS NULL THEN NULL 
ELSE NULL 
 END as location_supplement_originally_recorded, 

CASE
        WHEN DSDPID IS NOT NULL THEN SAFE_CAST(DSDPID AS FLOAT64) 
WHEN DSDPID IS NULL THEN NULL 
ELSE NULL 
 END as nchs_supplement_id, 

CASE
        WHEN DSDSUPP = 'Supplement Name' THEN 'Value was recorded' 
WHEN DSDSUPP IS NULL THEN NULL 
ELSE NULL 
 END as supplement_name, 

CASE
        WHEN DS2MTCH = 1 THEN 'Exact or near exact match' 
WHEN DS2MTCH = 2 THEN 'Probable match' 
WHEN DS2MTCH = 3 THEN 'Generic match' 
WHEN DS2MTCH = 4 THEN 'Reasonable match' 
WHEN DS2MTCH = 5 THEN 'Default match' 
WHEN DS2MTCH = 6 THEN 'No match' 
WHEN DS2MTCH = 7 THEN 'Refused' 
WHEN DS2MTCH = 9 THEN 'Dont know' 
WHEN DS2MTCH IS NULL THEN NULL 
ELSE NULL 
 END as matching_code, 

CASE
        WHEN DS2ANTA = 0 THEN 'Non-antacid supplement' 
WHEN DS2ANTA = 1 THEN 'Antacid containing calcium and/or magnesium' 
WHEN DS2ANTA = 2 THEN 'Antacids reported with antacids' 
WHEN DS2ANTA IS NULL THEN NULL 
ELSE NULL 
 END as antacid_containing_calcium_magnesium, 

CASE
        WHEN DS2ACTSS IS NOT NULL THEN DS2ACTSS 
WHEN DS2ACTSS IS NOT NULL THEN DS2ACTSS 
WHEN DS2ACTSS IS NULL THEN NULL 
ELSE NULL 
 END as reported_serving_size_label_serving_size, 

CASE
        WHEN DS2IKCAL IS NOT NULL THEN DS2IKCAL 
WHEN DS2IKCAL IS NULL THEN NULL 
ELSE NULL 
 END as energy_kcal, 

CASE
        WHEN DS2IPROT IS NOT NULL THEN DS2IPROT 
WHEN DS2IPROT IS NULL THEN NULL 
ELSE NULL 
 END as protein_gm, 

CASE
        WHEN DS2ICARB IS NOT NULL THEN DS2ICARB 
WHEN DS2ICARB IS NULL THEN NULL 
ELSE NULL 
 END as carbohydrate_gm, 

CASE
        WHEN DS2ISUGR IS NOT NULL THEN DS2ISUGR 
WHEN DS2ISUGR IS NULL THEN NULL 
ELSE NULL 
 END as total_sugars_gm, 

CASE
        WHEN DS2IFIBE IS NOT NULL THEN DS2IFIBE 
WHEN DS2IFIBE IS NULL THEN NULL 
ELSE NULL 
 END as dietary_fiber_gm, 

CASE
        WHEN DS2ITFAT IS NOT NULL THEN DS2ITFAT 
WHEN DS2ITFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_fat_gm, 

CASE
        WHEN DS2ISFAT IS NOT NULL THEN DS2ISFAT 
WHEN DS2ISFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_saturated_fatty_acids_gm, 

CASE
        WHEN DS2IMFAT IS NOT NULL THEN DS2IMFAT 
WHEN DS2IMFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_monounsaturated_fatty_acids_gm, 

CASE
        WHEN DS2IPFAT IS NOT NULL THEN DS2IPFAT 
WHEN DS2IPFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_polyunsaturated_fatty_acids_gm, 

CASE
        WHEN DS2ICHOL IS NOT NULL THEN DS2ICHOL 
WHEN DS2ICHOL IS NULL THEN NULL 
ELSE NULL 
 END as cholesterol_mg, 

CASE
        WHEN DS2ILYCO IS NOT NULL THEN DS2ILYCO 
WHEN DS2ILYCO IS NULL THEN NULL 
ELSE NULL 
 END as lycopene_mcg, 

CASE
        WHEN DS2ILZ IS NOT NULL THEN DS2ILZ 
WHEN DS2ILZ IS NULL THEN NULL 
ELSE NULL 
 END as lutein_zeaxanthin_mcg, 

CASE
        WHEN DS2IVB1 IS NOT NULL THEN DS2IVB1 
WHEN DS2IVB1 IS NULL THEN NULL 
ELSE NULL 
 END as thiamin_vitamin_b1_mg, 

CASE
        WHEN DS2IVB2 IS NOT NULL THEN DS2IVB2 
WHEN DS2IVB2 IS NULL THEN NULL 
ELSE NULL 
 END as riboflavin_vitamin_b2_mg, 

CASE
        WHEN DS2INIAC IS NOT NULL THEN DS2INIAC 
WHEN DS2INIAC IS NULL THEN NULL 
ELSE NULL 
 END as niacin_mg, 

CASE
        WHEN DS2IVB6 IS NOT NULL THEN DS2IVB6 
WHEN DS2IVB6 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b6_mg, 

CASE
        WHEN DS2IFA IS NOT NULL THEN DS2IFA 
WHEN DS2IFA IS NULL THEN NULL 
ELSE NULL 
 END as folic_acid_mcg, 

CASE
        WHEN DS2IFDFE IS NOT NULL THEN DS2IFDFE 
WHEN DS2IFDFE IS NULL THEN NULL 
ELSE NULL 
 END as folate_dfe_mcg, 

CASE
        WHEN DS2ICHL IS NOT NULL THEN DS2ICHL 
WHEN DS2ICHL IS NULL THEN NULL 
ELSE NULL 
 END as total_choline_mg, 

CASE
        WHEN DS2IVB12 IS NOT NULL THEN DS2IVB12 
WHEN DS2IVB12 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b12_mcg, 

CASE
        WHEN DS2IVC IS NOT NULL THEN DS2IVC 
WHEN DS2IVC IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_c_mg, 

CASE
        WHEN DS2IVK IS NOT NULL THEN DS2IVK 
WHEN DS2IVK IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_k_mcg, 

CASE
        WHEN DS2IVD IS NOT NULL THEN DS2IVD 
WHEN DS2IVD IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_d_d2_d3_mcg, 

CASE
        WHEN DS2ICALC IS NOT NULL THEN DS2ICALC 
WHEN DS2ICALC IS NULL THEN NULL 
ELSE NULL 
 END as calcium_mg, 

CASE
        WHEN DS2IPHOS IS NOT NULL THEN DS2IPHOS 
WHEN DS2IPHOS IS NULL THEN NULL 
ELSE NULL 
 END as phosphorus_mg, 

CASE
        WHEN DS2IMAGN IS NOT NULL THEN DS2IMAGN 
WHEN DS2IMAGN IS NULL THEN NULL 
ELSE NULL 
 END as magnesium_mg, 

CASE
        WHEN DS2IIRON IS NOT NULL THEN DS2IIRON 
WHEN DS2IIRON IS NULL THEN NULL 
ELSE NULL 
 END as iron_mg, 

CASE
        WHEN DS2IZINC IS NOT NULL THEN DS2IZINC 
WHEN DS2IZINC IS NULL THEN NULL 
ELSE NULL 
 END as zinc_mg, 

CASE
        WHEN DS2ICOPP IS NOT NULL THEN DS2ICOPP 
WHEN DS2ICOPP IS NULL THEN NULL 
ELSE NULL 
 END as copper_mg, 

CASE
        WHEN DS2ISODI IS NOT NULL THEN DS2ISODI 
WHEN DS2ISODI IS NULL THEN NULL 
ELSE NULL 
 END as sodium_mg, 

CASE
        WHEN DS2IPOTA IS NOT NULL THEN DS2IPOTA 
WHEN DS2IPOTA IS NULL THEN NULL 
ELSE NULL 
 END as potassium_mg, 

CASE
        WHEN DS2ISELE IS NOT NULL THEN DS2ISELE 
WHEN DS2ISELE IS NULL THEN NULL 
ELSE NULL 
 END as selenium_mcg, 

CASE
        WHEN DS2ICAFF IS NOT NULL THEN DS2ICAFF 
WHEN DS2ICAFF IS NULL THEN NULL 
ELSE NULL 
 END as caffeine_mg, 

CASE
        WHEN DS2IIODI IS NOT NULL THEN SAFE_CAST(DS2IIODI AS FLOAT64) 
WHEN DS2IIODI IS NULL THEN NULL 
ELSE NULL 
 END as iodine_mcg, 

 FROM {{ ref('stg_dietary_supplement_use_24_hour_individual_dietary_supplements_second_day_dietary') }}