SELECT
SEQN as respondent_sequence_number,
WHEN WTDRD1 IS NOT NULL THEN WTDRD1WHEN WTDRD1 IS NULL THEN NULL 
ELSE NULL 
 END as dietary_day_one_sample_weight,
WHEN WTDR2D IS NOT NULL THEN WTDR2DWHEN WTDR2D IS NULL THEN NULL 
ELSE NULL 
 END as dietary_two_day_sample_weight,
CASE
        WHEN DR1DRSTZ = 1 THEN 'Reliable and met the minimum criteria' 
WHEN DR1DRSTZ = 2 THEN 'Not reliable or not met the minimum criteria' 
WHEN DR1DRSTZ = 4 THEN 'Reported consuming breast-milk' 
WHEN DR1DRSTZ = 5 THEN 'Not done' 
WHEN DR1DRSTZ IS NULL THEN NULL 
ELSE NULL 
 END as dietary_recall_status,
WHEN DR1EXMER IS NOT NULL THEN DR1EXMERWHEN DR1EXMER IS NULL THEN NULL 
ELSE NULL 
 END as interviewer_id_code,
CASE
        WHEN DRDINT = 1 THEN 'Day 1 only' 
WHEN DRDINT = 2 THEN 'Day 1 and day 2' 
WHEN DRDINT IS NULL THEN NULL 
ELSE NULL 
 END as number_of_days_of_intake,
WHEN DR1DBIH IS NOT NULL THEN DR1DBIHWHEN DR1DBIH IS NULL THEN NULL 
ELSE NULL 
 END as of_days_b_w_intake_and_hh_interview,
CASE
        WHEN DR1DAY = 1 THEN 'Sunday' 
WHEN DR1DAY = 2 THEN 'Monday' 
WHEN DR1DAY = 3 THEN 'Tuesday' 
WHEN DR1DAY = 4 THEN 'Wednesday' 
WHEN DR1DAY = 5 THEN 'Thursday' 
WHEN DR1DAY = 6 THEN 'Friday' 
WHEN DR1DAY = 7 THEN 'Saturday' 
WHEN DR1DAY IS NULL THEN NULL 
ELSE NULL 
 END as intake_day_of_the_week,
CASE
        WHEN DR1LANG = 1 THEN 'English' 
WHEN DR1LANG = 2 THEN 'Spanish' 
WHEN DR1LANG = 3 THEN 'English and Spanish' 
WHEN DR1LANG = 4 THEN 'Other' 
WHEN DR1LANG = 5 THEN 'Asian Languages' 
WHEN DR1LANG = 6 THEN 'Asian Languages and English' 
WHEN DR1LANG IS NULL THEN NULL 
ELSE NULL 
 END as language_respondent_used_mostly,
CASE
        WHEN DR1MRESP = '1' THEN 'SP' 
WHEN DR1MRESP = '2' THEN 'Mother of SP' 
WHEN DR1MRESP = '3' THEN 'Father of SP' 
WHEN DR1MRESP = '5' THEN 'Spouse of SP' 
WHEN DR1MRESP = '6' THEN 'Child of SP' 
WHEN DR1MRESP = '7' THEN 'Grandparent of SP' 
WHEN DR1MRESP = '8' THEN 'Friend, Partner, Non Relative' 
WHEN DR1MRESP = '9' THEN 'Translator, not a HH member' 
WHEN DR1MRESP = '10' THEN 'Child care provider, Caretaker' 
WHEN DR1MRESP = '11' THEN 'Other Relative' 
WHEN DR1MRESP = '77' THEN 'Refused' 
WHEN DR1MRESP = '99' THEN 'Don\'t know' 
WHEN DR1MRESP IS NULL THEN NULL 
ELSE NULL 
 END as main_respondent_for_this_interview,
CASE
        WHEN DR1HELP = '1' THEN 'SP' 
WHEN DR1HELP = '4' THEN 'Parent of SP' 
WHEN DR1HELP = '5' THEN 'Spouse of SP' 
WHEN DR1HELP = '6' THEN 'Child of SP' 
WHEN DR1HELP = '7' THEN 'Grandparent of SP' 
WHEN DR1HELP = '8' THEN 'Friend, Partner, Non Relative' 
WHEN DR1HELP = '9' THEN 'Translator, not a HH member' 
WHEN DR1HELP = '10' THEN 'Child care provider, Caretaker' 
WHEN DR1HELP = '11' THEN 'Other Relative' 
WHEN DR1HELP = '12' THEN 'No One' 
WHEN DR1HELP = '77' THEN 'Refused' 
WHEN DR1HELP = '99' THEN 'Don\'t know' 
WHEN DR1HELP IS NULL THEN NULL 
ELSE NULL 
 END as helped_in_responding_for_this_interview,
WHEN DS1DSCNT IS NOT NULL THEN DS1DSCNTWHEN DS1DSCNT IS NULL THEN NULL 
ELSE NULL 
 END as total_of_dietary_supplements_taken,
CASE
        WHEN DS1DS = 1 THEN 'Yes' 
WHEN DS1DS = 2 THEN 'No' 
WHEN DS1DS = 7 THEN 'Refused' 
WHEN DS1DS = 9 THEN 'Don\'t know' 
WHEN DS1DS IS NULL THEN NULL 
ELSE NULL 
 END as any_dietary_supplements_taken,
WHEN DS1ANCNT IS NOT NULL THEN DS1ANCNTWHEN DS1ANCNT IS NULL THEN NULL 
ELSE NULL 
 END as total_of_antacids_taken,
CASE
        WHEN DS1AN = 1 THEN 'Yes' 
WHEN DS1AN = 2 THEN 'No' 
WHEN DS1AN = 7 THEN 'Refused' 
WHEN DS1AN = 9 THEN 'Don\'t know' 
WHEN DS1AN IS NULL THEN NULL 
ELSE NULL 
 END as any_antacids_taken,
WHEN DS1TKCAL IS NOT NULL THEN DS1TKCALWHEN DS1TKCAL IS NULL THEN NULL 
ELSE NULL 
 END as energy_kcal,
WHEN DS1TPROT IS NOT NULL THEN DS1TPROTWHEN DS1TPROT IS NULL THEN NULL 
ELSE NULL 
 END as protein_gm,
WHEN DS1TCARB IS NOT NULL THEN DS1TCARBWHEN DS1TCARB IS NULL THEN NULL 
ELSE NULL 
 END as carbohydrate_gm,
WHEN DS1TSUGR IS NOT NULL THEN DS1TSUGRWHEN DS1TSUGR IS NULL THEN NULL 
ELSE NULL 
 END as total_sugars_gm,
WHEN DS1TFIBE IS NOT NULL THEN DS1TFIBEWHEN DS1TFIBE IS NULL THEN NULL 
ELSE NULL 
 END as dietary_fiber_gm,
WHEN DS1TTFAT IS NOT NULL THEN DS1TTFATWHEN DS1TTFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_fat_gm,
WHEN DS1TSFAT IS NOT NULL THEN DS1TSFATWHEN DS1TSFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_saturated_fatty_acids_gm,
WHEN DS1TMFAT IS NOT NULL THEN DS1TMFATWHEN DS1TMFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_monounsaturated_fatty_acids_gm,
WHEN DS1TPFAT IS NOT NULL THEN DS1TPFATWHEN DS1TPFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_polyunsaturated_fatty_acids_gm,
WHEN DS1TCHOL IS NOT NULL THEN DS1TCHOLWHEN DS1TCHOL IS NULL THEN NULL 
ELSE NULL 
 END as cholesterol_mg,
WHEN DS1TLYCO IS NOT NULL THEN DS1TLYCOWHEN DS1TLYCO IS NULL THEN NULL 
ELSE NULL 
 END as lycopene_mcg,
WHEN DS1TLZ IS NOT NULL THEN DS1TLZWHEN DS1TLZ IS NULL THEN NULL 
ELSE NULL 
 END as lutein_zeaxanthin_mcg,
WHEN DS1TVB1 IS NOT NULL THEN DS1TVB1WHEN DS1TVB1 IS NULL THEN NULL 
ELSE NULL 
 END as thiamin_vitamin_b1_mg,
WHEN DS1TVB2 IS NOT NULL THEN DS1TVB2WHEN DS1TVB2 IS NULL THEN NULL 
ELSE NULL 
 END as riboflavin_vitamin_b2_mg,
WHEN DS1TNIAC IS NOT NULL THEN DS1TNIACWHEN DS1TNIAC IS NULL THEN NULL 
ELSE NULL 
 END as niacin_mg,
WHEN DS1TVB6 IS NOT NULL THEN DS1TVB6WHEN DS1TVB6 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b6_mg,
WHEN DS1TVB12 IS NOT NULL THEN DS1TVB12WHEN DS1TVB12 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b12_mcg,
WHEN DS1TFA IS NOT NULL THEN DS1TFAWHEN DS1TFA IS NULL THEN NULL 
ELSE NULL 
 END as folic_acid_mcg,
WHEN DS1TFDFE IS NOT NULL THEN DS1TFDFEWHEN DS1TFDFE IS NULL THEN NULL 
ELSE NULL 
 END as folate_dfe_mcg,
WHEN DS1TCHL IS NOT NULL THEN DS1TCHLWHEN DS1TCHL IS NULL THEN NULL 
ELSE NULL 
 END as total_choline_mg,
WHEN DS1TVC IS NOT NULL THEN DS1TVCWHEN DS1TVC IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_c_mg,
WHEN DS1TVK IS NOT NULL THEN DS1TVKWHEN DS1TVK IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_k_mcg,
WHEN DS1TVD IS NOT NULL THEN DS1TVDWHEN DS1TVD IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_d_d2_d3_mcg,
WHEN DS1TCALC IS NOT NULL THEN DS1TCALCWHEN DS1TCALC IS NULL THEN NULL 
ELSE NULL 
 END as calcium_mg,
WHEN DS1TPHOS IS NOT NULL THEN DS1TPHOSWHEN DS1TPHOS IS NULL THEN NULL 
ELSE NULL 
 END as phosphorus_mg,
WHEN DS1TMAGN IS NOT NULL THEN DS1TMAGNWHEN DS1TMAGN IS NULL THEN NULL 
ELSE NULL 
 END as magnesium_mg,
WHEN DS1TIRON IS NOT NULL THEN DS1TIRONWHEN DS1TIRON IS NULL THEN NULL 
ELSE NULL 
 END as iron_mg,
WHEN DS1TZINC IS NOT NULL THEN DS1TZINCWHEN DS1TZINC IS NULL THEN NULL 
ELSE NULL 
 END as zinc_mg,
WHEN DS1TCOPP IS NOT NULL THEN DS1TCOPPWHEN DS1TCOPP IS NULL THEN NULL 
ELSE NULL 
 END as copper_mg,
WHEN DS1TSODI IS NOT NULL THEN DS1TSODIWHEN DS1TSODI IS NULL THEN NULL 
ELSE NULL 
 END as sodium_mg,
WHEN DS1TPOTA IS NOT NULL THEN DS1TPOTAWHEN DS1TPOTA IS NULL THEN NULL 
ELSE NULL 
 END as potassium_mg,
WHEN DS1TSELE IS NOT NULL THEN DS1TSELEWHEN DS1TSELE IS NULL THEN NULL 
ELSE NULL 
 END as selenium_mcg,
WHEN DS1TCAFF IS NOT NULL THEN DS1TCAFFWHEN DS1TCAFF IS NULL THEN NULL 
ELSE NULL 
 END as caffeine_mg,
WHEN DS1TIODI IS NOT NULL THEN SAFE_CAST(DS1TIODI AS FLOAT64)WHEN DS1TIODI IS NULL THEN NULL 
ELSE NULL 
 END as iodine_mcg,
 FROM {{ ref('stg_dietary_supplement_use_24_hour_total_dietary_supplements_first_day_dietary') }}