SELECT
SEQN as respondent_sequence_number, 

CASE
        WHEN WTDRD1 IS NOT NULL THEN WTDRD1 
WHEN WTDRD1 IS NOT NULL THEN WTDRD1 
WHEN WTDRD1 IS NULL THEN NULL 
ELSE NULL 
 END as dietary_day_one_sample_weight, 

CASE
        WHEN WTDR2D IS NOT NULL THEN WTDR2D 
WHEN WTDR2D IS NOT NULL THEN WTDR2D 
WHEN WTDR2D IS NULL THEN NULL 
ELSE NULL 
 END as dietary_two_day_sample_weight, 

CASE
        WHEN DR1ILINE IS NOT NULL THEN DR1ILINE 
WHEN DR1ILINE IS NULL THEN NULL 
ELSE NULL 
 END as food_individual_component_number, 

CASE
        WHEN DR1DRSTZ = 1 THEN 'Reliable and met the minimum criteria' 
WHEN DR1DRSTZ = 2 THEN 'Not reliable or not met the minimum criteria' 
WHEN DR1DRSTZ = 4 THEN 'Reported consuming breast-milk' 
WHEN DR1DRSTZ = 5 THEN 'Not done' 
WHEN DR1DRSTZ IS NULL THEN NULL 
ELSE NULL 
 END as dietary_recall_status, 

CASE
        WHEN DR1EXMER IS NOT NULL THEN DR1EXMER 
WHEN DR1EXMER IS NULL THEN NULL 
ELSE NULL 
 END as interviewer_id_code, 

CASE
        WHEN DRABF = 1 THEN 'Yes' 
WHEN DRABF = 2 THEN 'No' 
WHEN DRABF IS NULL THEN NULL 
ELSE NULL 
 END as breast_fed_infant_either_day, 

CASE
        WHEN DRDINT = 1 THEN 'Day 1 only' 
WHEN DRDINT = 2 THEN 'Day 1 and day 2' 
WHEN DRDINT IS NULL THEN NULL 
ELSE NULL 
 END as number_of_days_of_intake, 

CASE
        WHEN DR1DBIH IS NOT NULL THEN SAFE_CAST(DR1DBIH AS FLOAT64) 
WHEN DR1DBIH IS NULL THEN NULL 
ELSE NULL 
 END as of_days_b_w_intake_and_hh_interview, 

CASE
        WHEN DR1DAY = 1 THEN 'Sunday' 
WHEN DR1DAY = 2 THEN 'Monday' 
WHEN DR1DAY = 3 THEN 'Tuesday' 
WHEN DR1DAY = 4 THEN 'Wednesday' 
WHEN DR1DAY = 5 THEN 'Thursday' 
WHEN DR1DAY = 6 THEN 'Friday' 
WHEN DR1DAY = 7 THEN 'Saturday' 
WHEN DR1DAY IS NULL THEN NULL 
ELSE NULL 
 END as intake_day_of_the_week, 

CASE
        WHEN DR1LANG = 1 THEN 'English' 
WHEN DR1LANG = 2 THEN 'Spanish' 
WHEN DR1LANG = 3 THEN 'English and Spanish' 
WHEN DR1LANG = 4 THEN 'Other' 
WHEN DR1LANG = 5 THEN 'Asian Languages' 
WHEN DR1LANG = 6 THEN 'Asian Languages and English' 
WHEN DR1LANG IS NULL THEN NULL 
ELSE NULL 
 END as language_respondent_used_mostly, 

CASE
        WHEN DR1CCMNM IS NOT NULL THEN DR1CCMNM 
WHEN DR1CCMNM IS NULL THEN NULL 
ELSE NULL 
 END as combination_food_number, 

CASE
        WHEN DR1CCMTX = 0 THEN 'Non-combination food' 
WHEN DR1CCMTX = 1 THEN 'Beverage w/ additions' 
WHEN DR1CCMTX = 2 THEN 'Cereal w/ additions' 
WHEN DR1CCMTX = 3 THEN 'Bread/baked products w/ additions' 
WHEN DR1CCMTX = 4 THEN 'Salad' 
WHEN DR1CCMTX = 5 THEN 'Sandwiches' 
WHEN DR1CCMTX = 6 THEN 'Soup' 
WHEN DR1CCMTX = 7 THEN 'Frozen meals' 
WHEN DR1CCMTX = 8 THEN 'Ice cream/frozen yogurt w/ additions' 
WHEN DR1CCMTX = 9 THEN 'Dried beans and vegetable w/ additions' 
WHEN DR1CCMTX = 10 THEN 'Fruit w/ additions' 
WHEN DR1CCMTX = 11 THEN 'Tortilla products' 
WHEN DR1CCMTX = 12 THEN 'Meat, poultry, fish' 
WHEN DR1CCMTX = 13 THEN 'LunchablesÂ®' 
WHEN DR1CCMTX = 14 THEN 'Chips w/ additions' 
WHEN DR1CCMTX = 90 THEN 'Other mixtures' 
WHEN DR1CCMTX IS NULL THEN NULL 
ELSE NULL 
 END as combination_food_type, 

CASE
        WHEN DR1_020 IS NOT NULL THEN DR1_020 
WHEN DR1_020 IS NULL THEN NULL 
ELSE NULL 
 END as time_of_eating_occasion_hh_mm, 

CASE
        WHEN DR1_030Z = 1 THEN 'Breakfast' 
WHEN DR1_030Z = 2 THEN 'Lunch' 
WHEN DR1_030Z = 3 THEN 'Dinner' 
WHEN DR1_030Z = 4 THEN 'Supper' 
WHEN DR1_030Z = 5 THEN 'Brunch' 
WHEN DR1_030Z = 6 THEN 'Snack' 
WHEN DR1_030Z = 7 THEN 'Drink' 
WHEN DR1_030Z = 8 THEN 'Infant feeding' 
WHEN DR1_030Z = 9 THEN 'Extended consumption' 
WHEN DR1_030Z = 10 THEN 'Desayano' 
WHEN DR1_030Z = 11 THEN 'Almuerzo' 
WHEN DR1_030Z = 12 THEN 'Comida' 
WHEN DR1_030Z = 13 THEN 'Merienda' 
WHEN DR1_030Z = 14 THEN 'Cena' 
WHEN DR1_030Z = 15 THEN 'Entre comida' 
WHEN DR1_030Z = 16 THEN 'Botana' 
WHEN DR1_030Z = 17 THEN 'Bocadillo' 
WHEN DR1_030Z = 18 THEN 'Tentempie' 
WHEN DR1_030Z = 19 THEN 'Bebida' 
WHEN DR1_030Z = 91 THEN 'Other' 
WHEN DR1_030Z = 99 THEN 'Dont know' 
WHEN DR1_030Z IS NULL THEN NULL 
ELSE NULL 
 END as name_of_eating_occasion, 

CASE
        WHEN DR1FS = 1 THEN 'Store - grocery/supermarket' 
WHEN DR1FS = 2 THEN 'Restaurant with waiter/waitress' 
WHEN DR1FS = 3 THEN 'Restaurant fast food/pizza' 
WHEN DR1FS = 4 THEN 'Bar/tavern/lounge' 
WHEN DR1FS = 5 THEN 'Restaurant no additional information' 
WHEN DR1FS = 6 THEN 'Cafeteria NOT in a K-12 school' 
WHEN DR1FS = 7 THEN 'Cafeteria in a K-12 school' 
WHEN DR1FS = 8 THEN 'Child/Adult care center' 
WHEN DR1FS = 9 THEN 'Child/Adult home care' 
WHEN DR1FS = 10 THEN 'Soup kitchen/shelter/food pantry' 
WHEN DR1FS = 11 THEN 'Meals on Wheels' 
WHEN DR1FS = 12 THEN 'Community food program - other' 
WHEN DR1FS = 13 THEN 'Community program no additional information' 
WHEN DR1FS = 14 THEN 'Vending machine' 
WHEN DR1FS = 15 THEN 'Common coffee pot or snack tray' 
WHEN DR1FS = 16 THEN 'From someone else/gift' 
WHEN DR1FS = 17 THEN 'Mail order purchase' 
WHEN DR1FS = 18 THEN 'Residential dining facility' 
WHEN DR1FS = 19 THEN 'Grown or caught by you or someone you know' 
WHEN DR1FS = 20 THEN 'Fish caught by you or someone you know' 
WHEN DR1FS = 24 THEN 'Sport, recreation, or entertainment facility' 
WHEN DR1FS = 25 THEN 'Street vendor, vending truck' 
WHEN DR1FS = 26 THEN 'Fundraiser sales' 
WHEN DR1FS = 27 THEN 'Store - convenience type' 
WHEN DR1FS = 28 THEN 'Store - no additional info' 
WHEN DR1FS = 91 THEN 'Other, specify' 
WHEN DR1FS = 99 THEN 'Dont know' 
WHEN DR1FS IS NULL THEN NULL 
ELSE NULL 
 END as source_of_food, 

CASE
        WHEN DR1_040Z = 1 THEN 'Yes' 
WHEN DR1_040Z = 2 THEN 'No' 
WHEN DR1_040Z = 7 THEN 'Refused' 
WHEN DR1_040Z = 9 THEN 'Dont know' 
WHEN DR1_040Z IS NULL THEN NULL 
ELSE NULL 
 END as did_you_eat_this_meal_at_home, 

CASE
        WHEN DR1IFDCD IS NOT NULL THEN DR1IFDCD 
WHEN DR1IFDCD IS NULL THEN NULL 
ELSE NULL 
 END as usda_food_code, 

CASE
        WHEN DR1IGRMS IS NOT NULL THEN DR1IGRMS 
WHEN DR1IGRMS IS NULL THEN NULL 
ELSE NULL 
 END as grams, 

CASE
        WHEN DR1IKCAL IS NOT NULL THEN DR1IKCAL 
WHEN DR1IKCAL IS NULL THEN NULL 
ELSE NULL 
 END as energy_kcal, 

CASE
        WHEN DR1IPROT IS NOT NULL THEN DR1IPROT 
WHEN DR1IPROT IS NULL THEN NULL 
ELSE NULL 
 END as protein_gm, 

CASE
        WHEN DR1ICARB IS NOT NULL THEN DR1ICARB 
WHEN DR1ICARB IS NULL THEN NULL 
ELSE NULL 
 END as carbohydrate_gm, 

CASE
        WHEN DR1ISUGR IS NOT NULL THEN DR1ISUGR 
WHEN DR1ISUGR IS NULL THEN NULL 
ELSE NULL 
 END as total_sugars_gm, 

CASE
        WHEN DR1IFIBE IS NOT NULL THEN DR1IFIBE 
WHEN DR1IFIBE IS NULL THEN NULL 
ELSE NULL 
 END as dietary_fiber_gm, 

CASE
        WHEN DR1ITFAT IS NOT NULL THEN DR1ITFAT 
WHEN DR1ITFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_fat_gm, 

CASE
        WHEN DR1ISFAT IS NOT NULL THEN DR1ISFAT 
WHEN DR1ISFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_saturated_fatty_acids_gm, 

CASE
        WHEN DR1IMFAT IS NOT NULL THEN DR1IMFAT 
WHEN DR1IMFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_monounsaturated_fatty_acids_gm, 

CASE
        WHEN DR1IPFAT IS NOT NULL THEN DR1IPFAT 
WHEN DR1IPFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_polyunsaturated_fatty_acids_gm, 

CASE
        WHEN DR1ICHOL IS NOT NULL THEN DR1ICHOL 
WHEN DR1ICHOL IS NULL THEN NULL 
ELSE NULL 
 END as cholesterol_mg, 

CASE
        WHEN DR1IATOC IS NOT NULL THEN DR1IATOC 
WHEN DR1IATOC IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_e_as_alpha_tocopherol_mg, 

CASE
        WHEN DR1IATOA IS NOT NULL THEN DR1IATOA 
WHEN DR1IATOA IS NULL THEN NULL 
ELSE NULL 
 END as added_alpha_tocopherol_vitamin_e_mg, 

CASE
        WHEN DR1IRET IS NOT NULL THEN DR1IRET 
WHEN DR1IRET IS NULL THEN NULL 
ELSE NULL 
 END as retinol_mcg, 

CASE
        WHEN DR1IVARA IS NOT NULL THEN DR1IVARA 
WHEN DR1IVARA IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_a_rae_mcg, 

CASE
        WHEN DR1IACAR IS NOT NULL THEN DR1IACAR 
WHEN DR1IACAR IS NULL THEN NULL 
ELSE NULL 
 END as alpha_carotene_mcg, 

CASE
        WHEN DR1IBCAR IS NOT NULL THEN DR1IBCAR 
WHEN DR1IBCAR IS NULL THEN NULL 
ELSE NULL 
 END as beta_carotene_mcg, 

CASE
        WHEN DR1ICRYP IS NOT NULL THEN DR1ICRYP 
WHEN DR1ICRYP IS NULL THEN NULL 
ELSE NULL 
 END as beta_cryptoxanthin_mcg, 

CASE
        WHEN DR1ILYCO IS NOT NULL THEN DR1ILYCO 
WHEN DR1ILYCO IS NULL THEN NULL 
ELSE NULL 
 END as lycopene_mcg, 

CASE
        WHEN DR1ILZ IS NOT NULL THEN DR1ILZ 
WHEN DR1ILZ IS NULL THEN NULL 
ELSE NULL 
 END as lutein_zeaxanthin_mcg, 

CASE
        WHEN DR1IVB1 IS NOT NULL THEN DR1IVB1 
WHEN DR1IVB1 IS NULL THEN NULL 
ELSE NULL 
 END as thiamin_vitamin_b1_mg, 

CASE
        WHEN DR1IVB2 IS NOT NULL THEN DR1IVB2 
WHEN DR1IVB2 IS NULL THEN NULL 
ELSE NULL 
 END as riboflavin_vitamin_b2_mg, 

CASE
        WHEN DR1INIAC IS NOT NULL THEN DR1INIAC 
WHEN DR1INIAC IS NULL THEN NULL 
ELSE NULL 
 END as niacin_mg, 

CASE
        WHEN DR1IVB6 IS NOT NULL THEN DR1IVB6 
WHEN DR1IVB6 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b6_mg, 

CASE
        WHEN DR1IFOLA IS NOT NULL THEN DR1IFOLA 
WHEN DR1IFOLA IS NULL THEN NULL 
ELSE NULL 
 END as total_folate_mcg, 

CASE
        WHEN DR1IFA IS NOT NULL THEN DR1IFA 
WHEN DR1IFA IS NULL THEN NULL 
ELSE NULL 
 END as folic_acid_mcg, 

CASE
        WHEN DR1IFF IS NOT NULL THEN DR1IFF 
WHEN DR1IFF IS NULL THEN NULL 
ELSE NULL 
 END as food_folate_mcg, 

CASE
        WHEN DR1IFDFE IS NOT NULL THEN DR1IFDFE 
WHEN DR1IFDFE IS NULL THEN NULL 
ELSE NULL 
 END as folate_dfe_mcg, 

CASE
        WHEN DR1ICHL IS NOT NULL THEN SAFE_CAST(DR1ICHL AS FLOAT64) 
WHEN DR1ICHL IS NULL THEN NULL 
ELSE NULL 
 END as total_choline_mg, 

CASE
        WHEN DR1IVB12 IS NOT NULL THEN DR1IVB12 
WHEN DR1IVB12 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b12_mcg, 

CASE
        WHEN DR1IB12A IS NOT NULL THEN DR1IB12A 
WHEN DR1IB12A IS NULL THEN NULL 
ELSE NULL 
 END as added_vitamin_b12_mcg, 

CASE
        WHEN DR1IVC IS NOT NULL THEN DR1IVC 
WHEN DR1IVC IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_c_mg, 

CASE
        WHEN DR1IVD IS NOT NULL THEN SAFE_CAST(DR1IVD AS FLOAT64) 
WHEN DR1IVD IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_d_d2_d3_mcg, 

CASE
        WHEN DR1IVK IS NOT NULL THEN DR1IVK 
WHEN DR1IVK IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_k_mcg, 

CASE
        WHEN DR1ICALC IS NOT NULL THEN DR1ICALC 
WHEN DR1ICALC IS NULL THEN NULL 
ELSE NULL 
 END as calcium_mg, 

CASE
        WHEN DR1IPHOS IS NOT NULL THEN DR1IPHOS 
WHEN DR1IPHOS IS NULL THEN NULL 
ELSE NULL 
 END as phosphorus_mg, 

CASE
        WHEN DR1IMAGN IS NOT NULL THEN DR1IMAGN 
WHEN DR1IMAGN IS NULL THEN NULL 
ELSE NULL 
 END as magnesium_mg, 

CASE
        WHEN DR1IIRON IS NOT NULL THEN DR1IIRON 
WHEN DR1IIRON IS NULL THEN NULL 
ELSE NULL 
 END as iron_mg, 

CASE
        WHEN DR1IZINC IS NOT NULL THEN DR1IZINC 
WHEN DR1IZINC IS NULL THEN NULL 
ELSE NULL 
 END as zinc_mg, 

CASE
        WHEN DR1ICOPP IS NOT NULL THEN DR1ICOPP 
WHEN DR1ICOPP IS NULL THEN NULL 
ELSE NULL 
 END as copper_mg, 

CASE
        WHEN DR1ISODI IS NOT NULL THEN DR1ISODI 
WHEN DR1ISODI IS NULL THEN NULL 
ELSE NULL 
 END as sodium_mg, 

CASE
        WHEN DR1IPOTA IS NOT NULL THEN DR1IPOTA 
WHEN DR1IPOTA IS NULL THEN NULL 
ELSE NULL 
 END as potassium_mg, 

CASE
        WHEN DR1ISELE IS NOT NULL THEN DR1ISELE 
WHEN DR1ISELE IS NULL THEN NULL 
ELSE NULL 
 END as selenium_mcg, 

CASE
        WHEN DR1ICAFF IS NOT NULL THEN DR1ICAFF 
WHEN DR1ICAFF IS NULL THEN NULL 
ELSE NULL 
 END as caffeine_mg, 

CASE
        WHEN DR1ITHEO IS NOT NULL THEN DR1ITHEO 
WHEN DR1ITHEO IS NULL THEN NULL 
ELSE NULL 
 END as theobromine_mg, 

CASE
        WHEN DR1IALCO IS NOT NULL THEN DR1IALCO 
WHEN DR1IALCO IS NULL THEN NULL 
ELSE NULL 
 END as alcohol_gm, 

CASE
        WHEN DR1IMOIS IS NOT NULL THEN DR1IMOIS 
WHEN DR1IMOIS IS NULL THEN NULL 
ELSE NULL 
 END as moisture_gm, 

CASE
        WHEN DR1IS040 IS NOT NULL THEN DR1IS040 
WHEN DR1IS040 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_4_0_butanoic_gm, 

CASE
        WHEN DR1IS060 IS NOT NULL THEN DR1IS060 
WHEN DR1IS060 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_6_0_hexanoic_gm, 

CASE
        WHEN DR1IS080 IS NOT NULL THEN DR1IS080 
WHEN DR1IS080 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_8_0_octanoic_gm, 

CASE
        WHEN DR1IS100 IS NOT NULL THEN DR1IS100 
WHEN DR1IS100 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_10_0_decanoic_gm, 

CASE
        WHEN DR1IS120 IS NOT NULL THEN DR1IS120 
WHEN DR1IS120 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_12_0_dodecanoic_gm, 

CASE
        WHEN DR1IS140 IS NOT NULL THEN DR1IS140 
WHEN DR1IS140 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_14_0_tetradecanoic_gm, 

CASE
        WHEN DR1IS160 IS NOT NULL THEN DR1IS160 
WHEN DR1IS160 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_16_0_hexadecanoic_gm, 

CASE
        WHEN DR1IS180 IS NOT NULL THEN DR1IS180 
WHEN DR1IS180 IS NULL THEN NULL 
ELSE NULL 
 END as sfa_18_0_octadecanoic_gm, 

CASE
        WHEN DR1IM161 IS NOT NULL THEN DR1IM161 
WHEN DR1IM161 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_16_1_hexadecenoic_gm, 

CASE
        WHEN DR1IM181 IS NOT NULL THEN DR1IM181 
WHEN DR1IM181 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_18_1_octadecenoic_gm, 

CASE
        WHEN DR1IM201 IS NOT NULL THEN DR1IM201 
WHEN DR1IM201 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_20_1_eicosenoic_gm, 

CASE
        WHEN DR1IM221 IS NOT NULL THEN DR1IM221 
WHEN DR1IM221 IS NULL THEN NULL 
ELSE NULL 
 END as mfa_22_1_docosenoic_gm, 

CASE
        WHEN DR1IP182 IS NOT NULL THEN DR1IP182 
WHEN DR1IP182 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_18_2_octadecadienoic_gm, 

CASE
        WHEN DR1IP183 IS NOT NULL THEN DR1IP183 
WHEN DR1IP183 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_18_3_octadecatrienoic_gm, 

CASE
        WHEN DR1IP184 IS NOT NULL THEN DR1IP184 
WHEN DR1IP184 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_18_4_octadecatetraenoic_gm, 

CASE
        WHEN DR1IP204 IS NOT NULL THEN DR1IP204 
WHEN DR1IP204 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_20_4_eicosatetraenoic_gm, 

CASE
        WHEN DR1IP205 IS NOT NULL THEN DR1IP205 
WHEN DR1IP205 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_20_5_eicosapentaenoic_gm, 

CASE
        WHEN DR1IP225 IS NOT NULL THEN DR1IP225 
WHEN DR1IP225 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_22_5_docosapentaenoic_gm, 

CASE
        WHEN DR1IP226 IS NOT NULL THEN DR1IP226 
WHEN DR1IP226 IS NULL THEN NULL 
ELSE NULL 
 END as pfa_22_6_docosahexaenoic_gm, 

 FROM {{ ref('stg_dietary_interview_individual_foods_first_day_dietary') }}