SELECT
SEQN as respondent_sequence_number, 

CASE
        WHEN WTDRD1 IS NOT NULL THEN WTDRD1 
WHEN WTDRD1 IS NOT NULL THEN WTDRD1 
WHEN WTDRD1 IS NULL THEN NULL 
ELSE NULL 
 END as dietary_day_one_sample_weight, 

CASE
        WHEN WTDR2D IS NOT NULL THEN WTDR2D 
WHEN WTDR2D IS NOT NULL THEN WTDR2D 
WHEN WTDR2D IS NULL THEN NULL 
ELSE NULL 
 END as dietary_two_day_sample_weight, 

CASE
        WHEN DR1DRSTZ = 1 THEN 'Reliable and met the minimum criteria' 
WHEN DR1DRSTZ = 2 THEN 'Not reliable or not met the minimum criteria' 
WHEN DR1DRSTZ = 4 THEN 'Reported consuming breast-milk' 
WHEN DR1DRSTZ = 5 THEN 'Not done' 
WHEN DR1DRSTZ IS NULL THEN NULL 
ELSE NULL 
 END as dietary_recall_status, 

CASE
        WHEN DR1EXMER IS NOT NULL THEN DR1EXMER 
WHEN DR1EXMER IS NULL THEN NULL 
ELSE NULL 
 END as interviewer_id_code, 

CASE
        WHEN DRDINT = 1 THEN 'Day 1 only' 
WHEN DRDINT = 2 THEN 'Day 1 and day 2' 
WHEN DRDINT IS NULL THEN NULL 
ELSE NULL 
 END as number_of_days_of_intake, 

CASE
        WHEN DR1DBIH IS NOT NULL THEN DR1DBIH 
WHEN DR1DBIH IS NULL THEN NULL 
ELSE NULL 
 END as of_days_b_w_intake_and_hh_interview, 

CASE
        WHEN DR1DAY = 1 THEN 'Sunday' 
WHEN DR1DAY = 2 THEN 'Monday' 
WHEN DR1DAY = 3 THEN 'Tuesday' 
WHEN DR1DAY = 4 THEN 'Wednesday' 
WHEN DR1DAY = 5 THEN 'Thursday' 
WHEN DR1DAY = 6 THEN 'Friday' 
WHEN DR1DAY = 7 THEN 'Saturday' 
WHEN DR1DAY IS NULL THEN NULL 
ELSE NULL 
 END as intake_day_of_the_week, 

CASE
        WHEN DR1LANG = 1 THEN 'English' 
WHEN DR1LANG = 2 THEN 'Spanish' 
WHEN DR1LANG = 3 THEN 'English and Spanish' 
WHEN DR1LANG = 4 THEN 'Other' 
WHEN DR1LANG = 5 THEN 'Asian Languages' 
WHEN DR1LANG = 6 THEN 'Asian Languages and English' 
WHEN DR1LANG IS NULL THEN NULL 
ELSE NULL 
 END as language_respondent_used_mostly, 

CASE
        WHEN DS1LOC = 1 THEN 'HouseHold Interview' 
WHEN DS1LOC = 2 THEN 'MEC Interview' 
WHEN DS1LOC = 3 THEN 'Phone Interview' 
WHEN DS1LOC IS NULL THEN NULL 
ELSE NULL 
 END as location_supplement_originally_recorded, 

CASE
        WHEN DSDPID IS NOT NULL THEN SAFE_CAST(DSDPID AS FLOAT64) 
WHEN DSDPID IS NULL THEN NULL 
ELSE NULL 
 END as nchs_supplement_id, 

CASE
        WHEN DSDSUPP = 'Supplement Name' THEN 'Value was recorded' 
WHEN DSDSUPP IS NULL THEN NULL 
ELSE NULL 
 END as supplement_name, 

CASE
        WHEN DS1MTCH = 1 THEN 'Exact or near exact match' 
WHEN DS1MTCH = 2 THEN 'Probable match' 
WHEN DS1MTCH = 3 THEN 'Generic match' 
WHEN DS1MTCH = 4 THEN 'Reasonable match' 
WHEN DS1MTCH = 5 THEN 'Default match' 
WHEN DS1MTCH = 6 THEN 'No match' 
WHEN DS1MTCH = 7 THEN 'Refused' 
WHEN DS1MTCH = 9 THEN 'Dont know' 
WHEN DS1MTCH IS NULL THEN NULL 
ELSE NULL 
 END as matching_code, 

CASE
        WHEN DS1ANTA = 0 THEN 'Non-antacid supplement' 
WHEN DS1ANTA = 1 THEN 'Antacid containing calcium and/or magnesium' 
WHEN DS1ANTA = 2 THEN 'Antacids reported with antacids' 
WHEN DS1ANTA IS NULL THEN NULL 
ELSE NULL 
 END as antacid_containing_calcium_magnesium, 

CASE
        WHEN DS1ACTSS IS NOT NULL THEN DS1ACTSS 
WHEN DS1ACTSS IS NOT NULL THEN DS1ACTSS 
WHEN DS1ACTSS IS NULL THEN NULL 
ELSE NULL 
 END as reported_serving_size_label_serving_size, 

CASE
        WHEN DS1IKCAL IS NOT NULL THEN DS1IKCAL 
WHEN DS1IKCAL IS NULL THEN NULL 
ELSE NULL 
 END as energy_kcal, 

CASE
        WHEN DS1IPROT IS NOT NULL THEN DS1IPROT 
WHEN DS1IPROT IS NULL THEN NULL 
ELSE NULL 
 END as protein_gm, 

CASE
        WHEN DS1ICARB IS NOT NULL THEN DS1ICARB 
WHEN DS1ICARB IS NULL THEN NULL 
ELSE NULL 
 END as carbohydrate_gm, 

CASE
        WHEN DS1ISUGR IS NOT NULL THEN DS1ISUGR 
WHEN DS1ISUGR IS NULL THEN NULL 
ELSE NULL 
 END as total_sugars_gm, 

CASE
        WHEN DS1IFIBE IS NOT NULL THEN DS1IFIBE 
WHEN DS1IFIBE IS NULL THEN NULL 
ELSE NULL 
 END as dietary_fiber_gm, 

CASE
        WHEN DS1ITFAT IS NOT NULL THEN DS1ITFAT 
WHEN DS1ITFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_fat_gm, 

CASE
        WHEN DS1ISFAT IS NOT NULL THEN DS1ISFAT 
WHEN DS1ISFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_saturated_fatty_acids_gm, 

CASE
        WHEN DS1IMFAT IS NOT NULL THEN DS1IMFAT 
WHEN DS1IMFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_monounsaturated_fatty_acids_gm, 

CASE
        WHEN DS1IPFAT IS NOT NULL THEN DS1IPFAT 
WHEN DS1IPFAT IS NULL THEN NULL 
ELSE NULL 
 END as total_polyunsaturated_fatty_acids_gm, 

CASE
        WHEN DS1ICHOL IS NOT NULL THEN DS1ICHOL 
WHEN DS1ICHOL IS NULL THEN NULL 
ELSE NULL 
 END as cholesterol_mg, 

CASE
        WHEN DS1ILYCO IS NOT NULL THEN DS1ILYCO 
WHEN DS1ILYCO IS NULL THEN NULL 
ELSE NULL 
 END as lycopene_mcg, 

CASE
        WHEN DS1ILZ IS NOT NULL THEN DS1ILZ 
WHEN DS1ILZ IS NULL THEN NULL 
ELSE NULL 
 END as lutein_zeaxanthin_mcg, 

CASE
        WHEN DS1IVB1 IS NOT NULL THEN DS1IVB1 
WHEN DS1IVB1 IS NULL THEN NULL 
ELSE NULL 
 END as thiamin_vitamin_b1_mg, 

CASE
        WHEN DS1IVB2 IS NOT NULL THEN DS1IVB2 
WHEN DS1IVB2 IS NULL THEN NULL 
ELSE NULL 
 END as riboflavin_vitamin_b2_mg, 

CASE
        WHEN DS1INIAC IS NOT NULL THEN DS1INIAC 
WHEN DS1INIAC IS NULL THEN NULL 
ELSE NULL 
 END as niacin_mg, 

CASE
        WHEN DS1IVB6 IS NOT NULL THEN DS1IVB6 
WHEN DS1IVB6 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b6_mg, 

CASE
        WHEN DS1IFA IS NOT NULL THEN DS1IFA 
WHEN DS1IFA IS NULL THEN NULL 
ELSE NULL 
 END as folic_acid_mcg, 

CASE
        WHEN DS1IFDFE IS NOT NULL THEN DS1IFDFE 
WHEN DS1IFDFE IS NULL THEN NULL 
ELSE NULL 
 END as folate_dfe_mcg, 

CASE
        WHEN DS1ICHL IS NOT NULL THEN DS1ICHL 
WHEN DS1ICHL IS NULL THEN NULL 
ELSE NULL 
 END as total_choline_mg, 

CASE
        WHEN DS1IVB12 IS NOT NULL THEN DS1IVB12 
WHEN DS1IVB12 IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_b12_mcg, 

CASE
        WHEN DS1IVC IS NOT NULL THEN DS1IVC 
WHEN DS1IVC IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_c_mg, 

CASE
        WHEN DS1IVK IS NOT NULL THEN DS1IVK 
WHEN DS1IVK IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_k_mcg, 

CASE
        WHEN DS1IVD IS NOT NULL THEN DS1IVD 
WHEN DS1IVD IS NULL THEN NULL 
ELSE NULL 
 END as vitamin_d_d2_d3_mcg, 

CASE
        WHEN DS1ICALC IS NOT NULL THEN DS1ICALC 
WHEN DS1ICALC IS NULL THEN NULL 
ELSE NULL 
 END as calcium_mg, 

CASE
        WHEN DS1IPHOS IS NOT NULL THEN DS1IPHOS 
WHEN DS1IPHOS IS NULL THEN NULL 
ELSE NULL 
 END as phosphorus_mg, 

CASE
        WHEN DS1IMAGN IS NOT NULL THEN DS1IMAGN 
WHEN DS1IMAGN IS NULL THEN NULL 
ELSE NULL 
 END as magnesium_mg, 

CASE
        WHEN DS1IIRON IS NOT NULL THEN DS1IIRON 
WHEN DS1IIRON IS NULL THEN NULL 
ELSE NULL 
 END as iron_mg, 

CASE
        WHEN DS1IZINC IS NOT NULL THEN DS1IZINC 
WHEN DS1IZINC IS NULL THEN NULL 
ELSE NULL 
 END as zinc_mg, 

CASE
        WHEN DS1ICOPP IS NOT NULL THEN DS1ICOPP 
WHEN DS1ICOPP IS NULL THEN NULL 
ELSE NULL 
 END as copper_mg, 

CASE
        WHEN DS1ISODI IS NOT NULL THEN DS1ISODI 
WHEN DS1ISODI IS NULL THEN NULL 
ELSE NULL 
 END as sodium_mg, 

CASE
        WHEN DS1IPOTA IS NOT NULL THEN DS1IPOTA 
WHEN DS1IPOTA IS NULL THEN NULL 
ELSE NULL 
 END as potassium_mg, 

CASE
        WHEN DS1ISELE IS NOT NULL THEN DS1ISELE 
WHEN DS1ISELE IS NULL THEN NULL 
ELSE NULL 
 END as selenium_mcg, 

CASE
        WHEN DS1ICAFF IS NOT NULL THEN DS1ICAFF 
WHEN DS1ICAFF IS NULL THEN NULL 
ELSE NULL 
 END as caffeine_mg, 

CASE
        WHEN DS1IIODI IS NOT NULL THEN SAFE_CAST(DS1IIODI AS FLOAT64) 
WHEN DS1IIODI IS NULL THEN NULL 
ELSE NULL 
 END as iodine_mcg, 

 FROM {{ ref('stg_dietary_supplement_use_24_hour_individual_dietary_supplements_first_day_dietary') }}