SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RXD300 IS NULL THEN NULL 
ELSE SAFE_CAST(RXD300 AS STRING) 
 END as drugs_over_counter_taken_regularly, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Aspirin - also buffered aspirin products such as Anacin, Bayer, Bufferin, Midol, Ascripton, Ecotrin, Pabrin and Alka Seltzer' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Tylenol - also other acetaminophen products, including sinus products such as Anacin-3, Dristan AF, and Comtrex' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Ibuprofen - also Advil, Nuprin, Motrin IB (including cold and sinus products containing ibuprofen)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'Excedrin' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Vanquish' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Feldene' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(16 AS FLOAT64),0) AS INT64) THEN 'Voltarin' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(17 AS FLOAT64),0) AS INT64) THEN 'Clinoril' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(18 AS FLOAT64),0) AS INT64) THEN 'Indocin' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(19 AS FLOAT64),0) AS INT64) THEN 'Naprosyn - also Aleve' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(20 AS FLOAT64),0) AS INT64) THEN 'Tolectin' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RXD310 IS NULL THEN NULL 
ELSE SAFE_CAST(RXD310 AS STRING) 
 END as product_taken, 

CASE
WHEN RXD320 IS NULL THEN NULL 
ELSE SAFE_CAST(RXD320 AS FLOAT64) 
 END as years_taking_product_every_day, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD330 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD330 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD330 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD330 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RXD330 IS NULL THEN NULL 
ELSE SAFE_CAST(RXD330 AS STRING) 
 END as currently_taking_product_every_day, 

CASE
WHEN RXD331Q IS NULL THEN NULL 
ELSE SAFE_CAST(RXD331Q AS FLOAT64) 
 END as of_pills_doses_taken_day, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD331U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Pills' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD331U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Doses' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD331U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXD331U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RXD331U IS NULL THEN NULL 
ELSE SAFE_CAST(RXD331U AS STRING) 
 END as unit_of_measure_pills_doses, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ355 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Container seen' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ355 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Container not seen' -- categorize string values 
WHEN RXQ355 IS NULL THEN NULL 
ELSE SAFE_CAST(RXQ355 AS STRING) 
 END as container_seen_by_interviewer, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360G AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Enter strength' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360G AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Information not on bottle/container' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360G AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Multiple ingredient product' -- categorize string values 
WHEN RXQ360G IS NULL THEN NULL 
ELSE SAFE_CAST(RXQ360G AS STRING) 
 END as strength_of_product, 

CASE
WHEN SAFE_CAST(RXQ360Q AS FLOAT64) > 811.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RXQ360Q IS NULL THEN NULL 
ELSE SAFE_CAST(RXQ360Q AS FLOAT64) 
 END as quantity_of_strength, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360U AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Microgram (mcg)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360U AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Milligram (mg)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360U AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Gram (g)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360U AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'Microgram/Milliliter' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360U AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'Milligram/Milliliter' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360U AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN 'Gram/Milliliter' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360U AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Other' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360U AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RXQ360U AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN RXQ360U IS NULL THEN NULL 
ELSE SAFE_CAST(RXQ360U AS STRING) 
 END as unit_of_strength_on_bottle, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RXQ300 IS NULL THEN NULL 
ELSE SAFE_CAST(RXQ300 AS STRING) 
 END as drugs_over_counter_taken_regularly_RXQ300, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Aspirin - also buffered aspirin products such as Anacin, Bayer, Bufferin, Midol, Ascripton, Ecotrin, Pabrin and Alka Seltzer' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Tylenol - also other acetaminophen products, including sinus products such as Anacin-3, Dristan AF, and Comtrex' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Ibuprofen - also, Advil, Nuprin, Motrin IB (including cold and sinus products containing ibuprofen)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'Excedrin' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Vanquish' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Feldene' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(16 AS FLOAT64),0) AS INT64) THEN 'Voltarin' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(17 AS FLOAT64),0) AS INT64) THEN 'Clinoril' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(18 AS FLOAT64),0) AS INT64) THEN 'Indocin' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(19 AS FLOAT64),0) AS INT64) THEN 'Naprosyn - also Aleve' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(20 AS FLOAT64),0) AS INT64) THEN 'Tolectin' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RXQ310 IS NULL THEN NULL 
ELSE SAFE_CAST(RXQ310 AS STRING) 
 END as product_taken_RXQ310, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ330 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ330 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ330 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RXQ330 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RXQ330 IS NULL THEN NULL 
ELSE SAFE_CAST(RXQ330 AS STRING) 
 END as currently_taking_product_every_day_RXQ330, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_analgesic_pain_relievers_questionnaire') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/RXQANA_C.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/RXQANA_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/RXQ_ANA.htm
*/
