SELECT
        SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
            WHEN DSDCOUNT IS NULL THEN NULL 
ELSE SAFE_CAST(DSDCOUNT AS FLOAT64) 
 END as total_of_dietary_supplements_taken, 

CASE
            WHEN DSDANCNT IS NULL THEN NULL 
ELSE SAFE_CAST(DSDANCNT AS FLOAT64) 
 END as total_of_antacids_taken, 

CASE
            WHEN SAFE_CAST(DSD010 AS FLOAT64) = SAFE_CAST(1 AS FLOAT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(DSD010 AS FLOAT64) = SAFE_CAST(2 AS FLOAT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(DSD010 AS FLOAT64) = SAFE_CAST(7 AS FLOAT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(DSD010 AS FLOAT64) = SAFE_CAST(9 AS FLOAT64) THEN 'Dont know' -- categorize numeric values
WHEN DSD010 IS NULL THEN NULL 
ELSE SAFE_CAST(DSD010 AS STRING) 
 END as any_dietary_supplements_taken, 

CASE
            WHEN SAFE_CAST(DSD010AN AS FLOAT64) = SAFE_CAST(1 AS FLOAT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(DSD010AN AS FLOAT64) = SAFE_CAST(2 AS FLOAT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(DSD010AN AS FLOAT64) = SAFE_CAST(7 AS FLOAT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(DSD010AN AS FLOAT64) = SAFE_CAST(9 AS FLOAT64) THEN 'Dont know' -- categorize numeric values
WHEN DSD010AN IS NULL THEN NULL 
ELSE SAFE_CAST(DSD010AN AS STRING) 
 END as any_antacids_taken, 

CASE
            WHEN DSQTKCAL IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTKCAL AS STRING) 
 END as energy_kcal, 

CASE
            WHEN DSQTPROT IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTPROT AS STRING) 
 END as protein_gm, 

CASE
            WHEN DSQTCARB IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTCARB AS STRING) 
 END as carbohydrate_gm, 

CASE
            WHEN DSQTSUGR IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTSUGR AS STRING) 
 END as total_sugars_gm, 

CASE
            WHEN DSQTFIBE IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTFIBE AS STRING) 
 END as dietary_fiber_gm, 

CASE
            WHEN DSQTTFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTTFAT AS STRING) 
 END as total_fat_gm, 

CASE
            WHEN DSQTSFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTSFAT AS STRING) 
 END as total_saturated_fatty_acids_gm, 

CASE
            WHEN DSQTMFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTMFAT AS STRING) 
 END as total_monounsaturated_fatty_acids_gm, 

CASE
            WHEN DSQTPFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTPFAT AS STRING) 
 END as total_polyunsaturated_fatty_acids_gm, 

CASE
            WHEN DSQTCHOL IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTCHOL AS STRING) 
 END as cholesterol_mg, 

CASE
            WHEN DSQTLYCO IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTLYCO AS STRING) 
 END as lycopene_mcg, 

CASE
            WHEN DSQTLZ IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTLZ AS STRING) 
 END as lutein_zeaxanthin_mcg, 

CASE
            WHEN DSQTVB1 IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTVB1 AS STRING) 
 END as thiamin_vitamin_b1_mg, 

CASE
            WHEN DSQTVB2 IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTVB2 AS STRING) 
 END as riboflavin_vitamin_b2_mg, 

CASE
            WHEN DSQTNIAC IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTNIAC AS STRING) 
 END as niacin_mg, 

CASE
            WHEN DSQTVB6 IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTVB6 AS STRING) 
 END as vitamin_b6_mg, 

CASE
            WHEN DSQTFA IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTFA AS STRING) 
 END as folic_acid_mcg, 

CASE
            WHEN DSQTFDFE IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTFDFE AS STRING) 
 END as folate_dfe_mcg, 

CASE
            WHEN DSQTCHL IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTCHL AS STRING) 
 END as total_choline_mg, 

CASE
            WHEN DSQTVB12 IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTVB12 AS STRING) 
 END as vitamin_b12_mcg, 

CASE
            WHEN DSQTVC IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTVC AS STRING) 
 END as vitamin_c_mg, 

CASE
            WHEN DSQTVK IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTVK AS STRING) 
 END as vitamin_k_mcg, 

CASE
            WHEN DSQTVD IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTVD AS STRING) 
 END as vitamin_d_d2_d3_mcg, 

CASE
            WHEN DSQTCALC IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTCALC AS STRING) 
 END as calcium_mg, 

CASE
            WHEN DSQTPHOS IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTPHOS AS STRING) 
 END as phosphorus_mg, 

CASE
            WHEN DSQTMAGN IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTMAGN AS STRING) 
 END as magnesium_mg, 

CASE
            WHEN DSQTIRON IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTIRON AS STRING) 
 END as iron_mg, 

CASE
            WHEN DSQTZINC IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTZINC AS STRING) 
 END as zinc_mg, 

CASE
            WHEN DSQTCOPP IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTCOPP AS STRING) 
 END as copper_mg, 

CASE
            WHEN DSQTSODI IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTSODI AS STRING) 
 END as sodium_mg, 

CASE
            WHEN DSQTPOTA IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTPOTA AS STRING) 
 END as potassium_mg, 

CASE
            WHEN DSQTSELE IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTSELE AS STRING) 
 END as selenium_mcg, 

CASE
            WHEN DSQTCAFF IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTCAFF AS STRING) 
 END as caffeine_mg, 

CASE
            WHEN DSQTIODI IS NOT NULL THEN SAFE_CAST(DSQTIODI AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DSQTIODI IS NULL THEN NULL 
ELSE SAFE_CAST(DSQTIODI AS FLOAT64) 
 END as iodine_mcg, 

 FROM {{ ref('stg_dietary_supplement_use_30_day_total_dietary_supplements_dietary') }}

        -- Docs utilized to generate this SQL can be found at https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DSQTOT_J.htm
        