SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
    WHEN REPLACE(DSDSUPP,'.0','') = 'Supplement name' THEN 'Value was recorded' -- categorize string values 
WHEN REPLACE(DSDSUPP,'.0','') = '7777' THEN 'Refused' -- categorize string values 
WHEN REPLACE(DSDSUPP,'.0','') = '9999' THEN 'Dont know' -- categorize string values 
WHEN DSDSUPP IS NULL THEN NULL 
ELSE SAFE_CAST(DSDSUPP AS STRING) 
 END as supplement_name, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN DSD070 IS NULL THEN NULL 
ELSE SAFE_CAST(DSD070 AS STRING) 
 END as was_container_seen, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DSDMTCH AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Exact or near exact match' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSDMTCH AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Probable match' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSDMTCH AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Generic match' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSDMTCH AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Reasonable match' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSDMTCH AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Default match' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSDMTCH AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'No match' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSDMTCH AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSDMTCH AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN DSDMTCH IS NULL THEN NULL 
ELSE SAFE_CAST(DSDMTCH AS STRING) 
 END as matching_code, 

CASE
    WHEN DSD090 IS NULL THEN NULL 
ELSE SAFE_CAST(DSD090 AS FLOAT64) 
 END as how_long_supplement_taken_days, 

CASE
    WHEN DSD103 IS NULL THEN NULL 
ELSE SAFE_CAST(DSD103 AS FLOAT64) 
 END as days_supplement_taken_past_30_days, 

CASE
    WHEN DSD122Q IS NULL THEN NULL 
ELSE SAFE_CAST(DSD122Q AS FLOAT64) 
 END as quantity_of_supplement_taken_daily, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Tablets, capsules, pills, caplets, softgels, gelcaps, vegicaps' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Droppers' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Drops' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Injections/Shots' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Lozenges' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Milliliters' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Powder/Granules' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Tablespoons' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Teaspoons' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'Wafers' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Cans' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(16 AS FLOAT64),0) AS INT64) THEN 'Grams' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(17 AS FLOAT64),0) AS INT64) THEN 'Dots' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(18 AS FLOAT64),0) AS INT64) THEN 'Cups' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(19 AS FLOAT64),0) AS INT64) THEN 'Spray/Squirts' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(20 AS FLOAT64),0) AS INT64) THEN 'Chews' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(21 AS FLOAT64),0) AS INT64) THEN 'Scoop' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(22 AS FLOAT64),0) AS INT64) THEN 'CC' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(23 AS FLOAT64),0) AS INT64) THEN 'Capful' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(24 AS FLOAT64),0) AS INT64) THEN 'MG' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(25 AS FLOAT64),0) AS INT64) THEN 'Units' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(26 AS FLOAT64),0) AS INT64) THEN 'Gulp' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(27 AS FLOAT64),0) AS INT64) THEN 'Ounces' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(28 AS FLOAT64),0) AS INT64) THEN 'Packages/Packets' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(29 AS FLOAT64),0) AS INT64) THEN 'Vial' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(30 AS FLOAT64),0) AS INT64) THEN 'Gumball' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(31 AS FLOAT64),0) AS INT64) THEN 'Strips' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD122U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN DSD122U IS NULL THEN NULL 
ELSE SAFE_CAST(DSD122U AS STRING) 
 END as dosage_form, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DSDANTA AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Non-antacid supplement' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSDANTA AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Antacid reported with dietary supplements(DSQ)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSDANTA AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Antacid reported with medications(RXQ)' -- categorize numeric values
WHEN DSDANTA IS NULL THEN NULL 
ELSE SAFE_CAST(DSDANTA AS STRING) 
 END as antacid_reported_as_a_dietary_supplement, 

CASE
    WHEN DSD100Q IS NULL THEN NULL 
ELSE SAFE_CAST(DSD100Q AS FLOAT64) 
 END as how_often_taken_last_month_quantity, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD100U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Day' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD100U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Week' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD100U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD100U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD100U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN DSD100U IS NULL THEN NULL 
ELSE SAFE_CAST(DSD100U AS STRING) 
 END as how_often_taken_in_last_month_unit, 

CASE
    WHEN DSD120Q IS NULL THEN NULL 
ELSE SAFE_CAST(DSD120Q AS FLOAT64) 
 END as quantity_of_supplement_taken, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Tablets, capsules, pills, caplets, softgels, gelcaps' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Droppers' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Drops' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Fluid Ounces' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Injections/shots' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Lozenges' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Milliliters' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Packages' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Packets' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Powder/granules' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Tablespoons' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Teaspoons' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'Wafers' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Weight ounces' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Can' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(16 AS FLOAT64),0) AS INT64) THEN 'Grams' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(17 AS FLOAT64),0) AS INT64) THEN 'Dots' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(18 AS FLOAT64),0) AS INT64) THEN 'Cups' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(19 AS FLOAT64),0) AS INT64) THEN 'Spray/squirts' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(20 AS FLOAT64),0) AS INT64) THEN 'Chews/chewables' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(21 AS FLOAT64),0) AS INT64) THEN 'Scoop' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(22 AS FLOAT64),0) AS INT64) THEN 'CC' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(23 AS FLOAT64),0) AS INT64) THEN 'Capful' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(24 AS FLOAT64),0) AS INT64) THEN 'Mg' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(25 AS FLOAT64),0) AS INT64) THEN 'Units' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(26 AS FLOAT64),0) AS INT64) THEN 'Gulp' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DSD120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN DSD120U IS NULL THEN NULL 
ELSE SAFE_CAST(DSD120U AS STRING) 
 END as dosage_form_DSD120U, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_dietary_supplement_use_30_day_file_2_participant_s_use_of_supplements_dietary') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/DSQ2_D.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/DSQ2_C.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/DSQ2_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/DSQFILE2.htm
*/
