SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
WHEN WTDRD1 IS NULL THEN NULL 
ELSE SAFE_CAST(WTDRD1 AS FLOAT64) 
 END as dietary_day_one_2_year_sample_weight, 

CASE
WHEN WTDR4YR IS NULL THEN NULL 
ELSE SAFE_CAST(WTDR4YR AS FLOAT64) 
 END as dietary_day_one_4_year_sample_weight, 

CASE
WHEN DRXILINE IS NULL THEN NULL 
ELSE SAFE_CAST(DRXILINE AS FLOAT64) 
 END as food_individual_component_number, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDDRSTZ AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Reliable and met the minimum criteria' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDDRSTZ AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Not reliable or not met the minimum criteria' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDDRSTZ AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'Reported consuming breast-milk' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDDRSTZ AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'Not done' -- categorize string values 
WHEN DRDDRSTZ IS NULL THEN NULL 
ELSE SAFE_CAST(DRDDRSTZ AS STRING) 
 END as dietary_recall_status, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDAY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Sunday' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDAY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Monday' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDAY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Tuesday' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDAY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Wednesday' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDAY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Thursday' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDAY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Friday' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDAY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Saturday' -- categorize numeric values
WHEN DRDDAY IS NULL THEN NULL 
ELSE SAFE_CAST(DRDDAY AS STRING) 
 END as intake_day_of_week, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRALANG AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'English' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRALANG AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Spanish' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRALANG AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'English and Spanish' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRALANG AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DRALANG IS NULL THEN NULL 
ELSE SAFE_CAST(DRALANG AS STRING) 
 END as language_sp_proxy_used_mostly, 

CASE
WHEN DRXCCMNM IS NULL THEN NULL 
ELSE SAFE_CAST(DRXCCMNM AS FLOAT64) 
 END as combination_food_number, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '0' THEN 'Non-combination food' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Beverage w/ adds' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Cereal w/ adds' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Bread/baked products w/ adds' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'Salad' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'Sandwiches' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN 'Soup' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Frozen meals' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '8' THEN 'Ice cream/frozen yogurt w/ additions' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dried beans and vegetable w/ adds' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '10' THEN 'Fruit w/ adds' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '11' THEN 'Tortilla Products' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '12' THEN 'Meat, poultry, fish' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '13' THEN 'Lunchables' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTZ AS FLOAT64),0) AS INT64) AS STRING) = '90' THEN 'Other mixtures' -- categorize string values 
WHEN DRDCCMTZ IS NULL THEN NULL 
ELSE SAFE_CAST(DRDCCMTZ AS STRING) 
 END as combination_food_type, 

CASE
WHEN DRD020 IS NULL THEN NULL 
ELSE SAFE_CAST(DRD020 AS FLOAT64) 
 END as time_of_eating_occasion_hh_mm, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Breakfast' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Lunch' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Dinner/supper' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'Brunch' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN 'Snack/beverage' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '8' THEN 'Infant feeding' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Extended consumption' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '10' THEN 'Desayano (Spanish)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '11' THEN 'Almuerzo (Spanish)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '12' THEN 'Comida (Spanish)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '13' THEN 'Merienda (Spanish)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '14' THEN 'Cena (Spanish)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '15' THEN 'Entre comida/bebida/tentempie (Spanish)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '16' THEN 'Botana (Spanish)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '17' THEN 'Bocadillo (Spanish)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '91' THEN 'Other' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD030Z AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN DRD030Z IS NULL THEN NULL 
ELSE SAFE_CAST(DRD030Z AS STRING) 
 END as name_of_eating_occasion, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD040Z AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(DRD040Z AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN DRD040Z IS NULL THEN NULL 
ELSE SAFE_CAST(DRD040Z AS STRING) 
 END as was_this_food_eaten_at_home, 

CASE
WHEN DRDIFDCD IS NULL THEN NULL 
ELSE SAFE_CAST(DRDIFDCD AS FLOAT64) 
 END as usda_food_code, 

CASE
WHEN DRXIGRMS IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIGRMS AS FLOAT64) 
 END as grams, 

CASE
WHEN DRXIKCAL IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIKCAL AS FLOAT64) 
 END as energy_kcal, 

CASE
WHEN DRXIPROT IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIPROT AS FLOAT64) 
 END as protein_gm, 

CASE
WHEN DRXICARB IS NULL THEN NULL 
ELSE SAFE_CAST(DRXICARB AS FLOAT64) 
 END as carbohydrate_gm, 

CASE
WHEN DRXISUGR IS NOT NULL THEN SAFE_CAST(DRXISUGR AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXISUGR IS NULL THEN NULL 
ELSE SAFE_CAST(DRXISUGR AS FLOAT64) 
 END as total_sugars_gm, 

CASE
WHEN DRXIFIBE IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIFIBE AS FLOAT64) 
 END as dietary_fiber_gm, 

CASE
WHEN DRXITFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DRXITFAT AS FLOAT64) 
 END as total_fat_gm, 

CASE
WHEN DRXISFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DRXISFAT AS FLOAT64) 
 END as total_saturated_fatty_acids_gm, 

CASE
WHEN DRXIMFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIMFAT AS FLOAT64) 
 END as total_monounsaturated_fatty_acids_gm, 

CASE
WHEN DRXIPFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIPFAT AS FLOAT64) 
 END as total_polyunsaturated_fatty_acids_gm, 

CASE
WHEN DRXICHOL IS NULL THEN NULL 
ELSE SAFE_CAST(DRXICHOL AS FLOAT64) 
 END as cholesterol_mg, 

CASE
WHEN DRXIATOC IS NOT NULL THEN SAFE_CAST(DRXIATOC AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXIATOC IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIATOC AS FLOAT64) 
 END as vitamin_e_as_alpha_tocopherol_mg, 

CASE
WHEN DRXIRET IS NOT NULL THEN SAFE_CAST(DRXIRET AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXIRET IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIRET AS FLOAT64) 
 END as retinol_mcg, 

CASE
WHEN DRXIVARA IS NOT NULL THEN SAFE_CAST(DRXIVARA AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXIVARA IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIVARA AS FLOAT64) 
 END as vitamin_a_rae_mcg, 

CASE
WHEN DRXIACAR IS NOT NULL THEN SAFE_CAST(DRXIACAR AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXIACAR IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIACAR AS FLOAT64) 
 END as alpha_carotene_mcg, 

CASE
WHEN DRXIBCAR IS NOT NULL THEN SAFE_CAST(DRXIBCAR AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXIBCAR IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIBCAR AS FLOAT64) 
 END as beta_carotene_mcg, 

CASE
WHEN DRXICRYP IS NOT NULL THEN SAFE_CAST(DRXICRYP AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXICRYP IS NULL THEN NULL 
ELSE SAFE_CAST(DRXICRYP AS FLOAT64) 
 END as beta_cryptoxanthin_mcg, 

CASE
WHEN DRXILYCO IS NOT NULL THEN SAFE_CAST(DRXILYCO AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXILYCO IS NULL THEN NULL 
ELSE SAFE_CAST(DRXILYCO AS FLOAT64) 
 END as lycopene_mcg, 

CASE
WHEN DRXILZ IS NOT NULL THEN SAFE_CAST(DRXILZ AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXILZ IS NULL THEN NULL 
ELSE SAFE_CAST(DRXILZ AS FLOAT64) 
 END as lutein_zeaxanthin_mcg, 

CASE
WHEN DRXIVB1 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIVB1 AS FLOAT64) 
 END as thiamin_vitamin_b1_mg, 

CASE
WHEN DRXIVB2 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIVB2 AS FLOAT64) 
 END as riboflavin_vitamin_b2_mg, 

CASE
WHEN DRXINIAC IS NULL THEN NULL 
ELSE SAFE_CAST(DRXINIAC AS FLOAT64) 
 END as niacin_mg, 

CASE
WHEN DRXIVB6 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIVB6 AS FLOAT64) 
 END as vitamin_b6_mg, 

CASE
WHEN DRXIFOLA IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIFOLA AS FLOAT64) 
 END as total_folate_mcg, 

CASE
WHEN DRXIFA IS NOT NULL THEN SAFE_CAST(DRXIFA AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXIFA IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIFA AS FLOAT64) 
 END as folic_acid_mcg, 

CASE
WHEN DRXIFF IS NOT NULL THEN SAFE_CAST(DRXIFF AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXIFF IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIFF AS FLOAT64) 
 END as food_folate_mcg, 

CASE
WHEN DRXIFDFE IS NOT NULL THEN SAFE_CAST(DRXIFDFE AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXIFDFE IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIFDFE AS FLOAT64) 
 END as folate_dfe_mcg, 

CASE
WHEN DRXIVB12 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIVB12 AS FLOAT64) 
 END as vitamin_b12_mcg, 

CASE
WHEN DRXIVC IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIVC AS FLOAT64) 
 END as vitamin_c_mg, 

CASE
WHEN DRXIVK IS NOT NULL THEN SAFE_CAST(DRXIVK AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXIVK IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIVK AS FLOAT64) 
 END as vitamin_k_mcg, 

CASE
WHEN DRXICALC IS NULL THEN NULL 
ELSE SAFE_CAST(DRXICALC AS FLOAT64) 
 END as calcium_mg, 

CASE
WHEN DRXIPHOS IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIPHOS AS FLOAT64) 
 END as phosphorus_mg, 

CASE
WHEN DRXIMAGN IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIMAGN AS FLOAT64) 
 END as magnesium_mg, 

CASE
WHEN DRXIIRON IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIIRON AS FLOAT64) 
 END as iron_mg, 

CASE
WHEN DRXIZINC IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIZINC AS FLOAT64) 
 END as zinc_mg, 

CASE
WHEN DRXICOPP IS NULL THEN NULL 
ELSE SAFE_CAST(DRXICOPP AS FLOAT64) 
 END as copper_mg, 

CASE
WHEN DRDISODI IS NULL THEN NULL 
ELSE SAFE_CAST(DRDISODI AS FLOAT64) 
 END as sodium_mg, 

CASE
WHEN DRXIPOTA IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIPOTA AS FLOAT64) 
 END as potassium_mg, 

CASE
WHEN DRXISELE IS NULL THEN NULL 
ELSE SAFE_CAST(DRXISELE AS FLOAT64) 
 END as selenium_mcg, 

CASE
WHEN DRXICAFF IS NULL THEN NULL 
ELSE SAFE_CAST(DRXICAFF AS FLOAT64) 
 END as caffeine_mg, 

CASE
WHEN DRXITHEO IS NULL THEN NULL 
ELSE SAFE_CAST(DRXITHEO AS FLOAT64) 
 END as theobromine_mg, 

CASE
WHEN DRXIALCO IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIALCO AS FLOAT64) 
 END as alcohol_gm, 

CASE
WHEN DRXIMOIS IS NOT NULL THEN SAFE_CAST(DRXIMOIS AS FLOAT64) -- correct wrong data types for numerical data 
WHEN DRXIMOIS IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIMOIS AS FLOAT64) 
 END as moisture_gm, 

CASE
WHEN DRXIS040 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIS040 AS FLOAT64) 
 END as sfa_4_0_butanoic_gm, 

CASE
WHEN DRXIS060 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIS060 AS FLOAT64) 
 END as sfa_6_0_hexanoic_gm, 

CASE
WHEN DRXIS080 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIS080 AS FLOAT64) 
 END as sfa_8_0_octanoic_gm, 

CASE
WHEN DRXIS100 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIS100 AS FLOAT64) 
 END as sfa_10_0_decanoic_gm, 

CASE
WHEN DRXIS120 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIS120 AS FLOAT64) 
 END as sfa_12_0_dodecanoic_gm, 

CASE
WHEN DRXIS140 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIS140 AS FLOAT64) 
 END as sfa_14_0_tetradecanoic_gm, 

CASE
WHEN DRXIS160 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIS160 AS FLOAT64) 
 END as sfa_16_0_hexadecanoic_gm, 

CASE
WHEN DRXIS180 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIS180 AS FLOAT64) 
 END as sfa_18_0_octadecanoic_gm, 

CASE
WHEN DRXIM161 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIM161 AS FLOAT64) 
 END as mfa_16_1_hexadecenoic_gm, 

CASE
WHEN DRXIM181 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIM181 AS FLOAT64) 
 END as mfa_18_1_octadecenoic_gm, 

CASE
WHEN DRXIM201 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIM201 AS FLOAT64) 
 END as mfa_20_1_eicosenoic_gm, 

CASE
WHEN DRXIM221 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIM221 AS FLOAT64) 
 END as mfa_22_1_docosenoic_gm, 

CASE
WHEN DRXIP182 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIP182 AS FLOAT64) 
 END as pfa_18_2_octadecadienoic_gm, 

CASE
WHEN DRXIP183 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIP183 AS FLOAT64) 
 END as pfa_18_3_octadecatrienoic_gm, 

CASE
WHEN DRXIP184 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIP184 AS FLOAT64) 
 END as pfa_18_4_octadecatetraenoic_gm, 

CASE
WHEN DRXIP204 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIP204 AS FLOAT64) 
 END as pfa_20_4_eicosatetraenoic_gm, 

CASE
WHEN DRXIP205 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIP205 AS FLOAT64) 
 END as pfa_20_5_eicosapentaenoic_gm, 

CASE
WHEN DRXIP225 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIP225 AS FLOAT64) 
 END as pfa_22_5_docosapentaenoic_gm, 

CASE
WHEN DRXIP226 IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIP226 AS FLOAT64) 
 END as pfa_22_6_docosahexaenoic_gm, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDRSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Reliable and meet minimum criteria' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDRSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Reliable but not meet minimum criteria' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDRSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not reliable' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDRSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Breast-fed infant or child' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDDRSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Not done' -- categorize numeric values
WHEN DRDDRSTS IS NULL THEN NULL 
ELSE SAFE_CAST(DRDDRSTS AS STRING) 
 END as dietary_recall_status_DRDDRSTS, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDINTMD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'In-person' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDINTMD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Telephone' -- categorize numeric values
WHEN DRDINTMD IS NULL THEN NULL 
ELSE SAFE_CAST(DRDINTMD AS STRING) 
 END as mode_of_interview, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Non-combination food' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Baby food combo' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Dried beans w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Beverage combo' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Bread/baked products w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Cereal mix/cereal w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Chips w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Crackers w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Desserts w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Eggs w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Fish w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Frozen meal' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Fruit combo' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'Grains w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Meat w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Mixed dish' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(17 AS FLOAT64),0) AS INT64) THEN 'Poultry w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(18 AS FLOAT64),0) AS INT64) THEN 'Salads (greens based)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(19 AS FLOAT64),0) AS INT64) THEN 'Salads (non-greens based)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(20 AS FLOAT64),0) AS INT64) THEN 'Sandwiches' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(21 AS FLOAT64),0) AS INT64) THEN 'Soup combo' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(22 AS FLOAT64),0) AS INT64) THEN 'Tortilla w/adds' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(23 AS FLOAT64),0) AS INT64) THEN 'Vegetable combo' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCCMTY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(90 AS FLOAT64),0) AS INT64) THEN 'Other foods eaten together' -- categorize numeric values
WHEN DRDCCMTY IS NULL THEN NULL 
ELSE SAFE_CAST(DRDCCMTY AS STRING) 
 END as combination_food_type_DRDCCMTY, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Breakfast' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Brunch' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Lunch' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Snack/beverage' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Dinner/supper' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Infant feeding' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Extended consumption' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Desayuno (Spanish)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Almuerzo (Spanish)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Comida (Spanish)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Merienda (Spanish)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'Cena (Spanish)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Entre comida/bebida (Spanish)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Bocadillo (Spanish)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(16 AS FLOAT64),0) AS INT64) THEN 'Botana (Spanish)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN DRD030 IS NULL THEN NULL 
ELSE SAFE_CAST(DRD030 AS STRING) 
 END as coded_meal_name, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Boat' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Self serve buffet' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Cafeteria' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Car' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Community feeding program' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Deli' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Fast food' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Friends house' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Home' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Plane' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Restaurant' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'School' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Someone elses house' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Store' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(16 AS FLOAT64),0) AS INT64) THEN 'Take out' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(17 AS FLOAT64),0) AS INT64) THEN 'Work' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(18 AS FLOAT64),0) AS INT64) THEN 'Day camp' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(19 AS FLOAT64),0) AS INT64) THEN 'Day care' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(90 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DRD040 IS NULL THEN NULL 
ELSE SAFE_CAST(DRD040 AS STRING) 
 END as meal_place, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCFF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Single component food' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDCFF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Combo food' -- categorize numeric values
WHEN DRDCFF IS NULL THEN NULL 
ELSE SAFE_CAST(DRDCFF AS STRING) 
 END as combination_food_flag, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDMRUF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Non-modified recipe' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDMRUF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Modified recipe' -- categorize numeric values
WHEN DRDMRUF IS NULL THEN NULL 
ELSE SAFE_CAST(DRDMRUF AS STRING) 
 END as flag_for_modified_recipe_use, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDISODF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'No sodium adjustment done' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DRDISODF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Sodium value adjusted for salt use in food preparation' -- categorize numeric values
WHEN DRDISODF IS NULL THEN NULL 
ELSE SAFE_CAST(DRDISODF AS STRING) 
 END as salt_adjustment_flag_of_individual_food, 

CASE
WHEN DRXIVAIU IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIVAIU AS FLOAT64) 
 END as vitamin_a_iu, 

CASE
WHEN DRXIVARE IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIVARE AS FLOAT64) 
 END as vitamin_a_re, 

CASE
WHEN DRXICARO IS NULL THEN NULL 
ELSE SAFE_CAST(DRXICARO AS FLOAT64) 
 END as carotene_re, 

CASE
WHEN DRXIVE IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIVE AS FLOAT64) 
 END as vitamin_e_ate_mg, 

CASE
WHEN DRXIWATE IS NULL THEN NULL 
ELSE SAFE_CAST(DRXIWATE AS FLOAT64) 
 END as moisture_gm_DRXIWATE, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_dietary_interview_individual_foods_dietary') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/DRXIFF_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/DRXIFF.htm
*/
