SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Whole body scan completed' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Whole body scan completed, but invalid' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Whole body not scanned, pregnancy' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Whole body not scanned, weight > 450 lbs' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Whole body not scanned, height > 65' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Whole body not scanned, other reason' -- categorize numeric values
WHEN DXAEXSTS IS NULL THEN NULL 
ELSE SAFE_CAST(DXAEXSTS AS STRING) 
 END as exam_status, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAHEBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAHEBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAHEBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAHEBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAHEBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXAHEBV IS NULL THEN NULL 
ELSE SAFE_CAST(DXAHEBV AS STRING) 
 END as head_bone_invalidity_code, 

CASE
    WHEN DXXHEA IS NULL THEN NULL 
ELSE SAFE_CAST(DXXHEA AS FLOAT64) 
 END as head_area_cm_2, 

CASE
    WHEN DXXHEBMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXXHEBMC AS FLOAT64) 
 END as head_bone_mineral_content_g, 

CASE
    WHEN DXXHEBMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXXHEBMD AS FLOAT64) 
 END as head_bone_mineral_density_g_cm_2, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAHETV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAHETV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAHETV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAHETV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXAHETV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXAHETV IS NULL THEN NULL 
ELSE SAFE_CAST(DXAHETV AS STRING) 
 END as head_tissue_invalidity_code, 

CASE
    WHEN DXXHEFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DXXHEFAT AS FLOAT64) 
 END as head_fat_g, 

CASE
    WHEN DXDHELE IS NULL THEN NULL 
ELSE SAFE_CAST(DXDHELE AS FLOAT64) 
 END as head_lean_excl_bmc_g, 

CASE
    WHEN DXXHELI IS NULL THEN NULL 
ELSE SAFE_CAST(DXXHELI AS FLOAT64) 
 END as head_lean_incl_bmc_g, 

CASE
    WHEN DXDHETOT IS NULL THEN NULL 
ELSE SAFE_CAST(DXDHETOT AS FLOAT64) 
 END as head_total_g, 

CASE
    WHEN DXDHEPF IS NULL THEN NULL 
ELSE SAFE_CAST(DXDHEPF AS FLOAT64) 
 END as head_percent_fat, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Arm/leg overlap' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXALABV IS NULL THEN NULL 
ELSE SAFE_CAST(DXALABV AS STRING) 
 END as left_arm_bone_invalidity_code, 

CASE
    WHEN DXXLAA IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLAA AS FLOAT64) 
 END as left_arm_area_cm_2, 

CASE
    WHEN DXXLABMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLABMC AS FLOAT64) 
 END as left_arm_bmc_g, 

CASE
    WHEN DXXLABMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLABMD AS FLOAT64) 
 END as left_arm_bmd_g_cm_2, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Arm/leg overlap' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXALATV IS NULL THEN NULL 
ELSE SAFE_CAST(DXALATV AS STRING) 
 END as left_arm_tissue_invalidity_code, 

CASE
    WHEN DXXLAFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLAFAT AS FLOAT64) 
 END as left_arm_fat_g, 

CASE
    WHEN DXDLALE IS NULL THEN NULL 
ELSE SAFE_CAST(DXDLALE AS FLOAT64) 
 END as left_arm_lean_excl_bmc_g, 

CASE
    WHEN DXXLALI IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLALI AS FLOAT64) 
 END as left_arm_lean_incl_bmc_g, 

CASE
    WHEN DXDLATOT IS NULL THEN NULL 
ELSE SAFE_CAST(DXDLATOT AS FLOAT64) 
 END as left_arm_total_g, 

CASE
    WHEN DXDLAPF IS NULL THEN NULL 
ELSE SAFE_CAST(DXDLAPF AS FLOAT64) 
 END as left_arm_percent_fat, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Arm/leg overlap' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXALLBV IS NULL THEN NULL 
ELSE SAFE_CAST(DXALLBV AS STRING) 
 END as left_leg_bone_invalidity_code, 

CASE
    WHEN DXXLLA IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLLA AS FLOAT64) 
 END as left_leg_area_cm_2, 

CASE
    WHEN DXXLLBMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLLBMC AS FLOAT64) 
 END as left_leg_bmc_g, 

CASE
    WHEN DXXLLBMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLLBMD AS FLOAT64) 
 END as left_leg_bmd_g_cm_2, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Arm/leg overlap' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXALLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXALLTV IS NULL THEN NULL 
ELSE SAFE_CAST(DXALLTV AS STRING) 
 END as left_leg_tissue_invalidity_code, 

CASE
    WHEN DXXLLFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLLFAT AS FLOAT64) 
 END as left_leg_fat_g, 

CASE
    WHEN DXDLLLE IS NULL THEN NULL 
ELSE SAFE_CAST(DXDLLLE AS FLOAT64) 
 END as left_leg_lean_excl_bmc_g, 

CASE
    WHEN DXXLLLI IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLLLI AS FLOAT64) 
 END as left_leg_lean_incl_bmc_g, 

CASE
    WHEN DXDLLTOT IS NULL THEN NULL 
ELSE SAFE_CAST(DXDLLTOT AS FLOAT64) 
 END as left_leg_total_g, 

CASE
    WHEN DXDLLPF IS NULL THEN NULL 
ELSE SAFE_CAST(DXDLLPF AS FLOAT64) 
 END as left_leg_percent_fat, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Arm/leg overlap' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARABV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXARABV IS NULL THEN NULL 
ELSE SAFE_CAST(DXARABV AS STRING) 
 END as right_arm_bone_invalidity_code, 

CASE
    WHEN DXXRAA IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRAA AS FLOAT64) 
 END as right_arm_area_cm_2, 

CASE
    WHEN DXXRABMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRABMC AS FLOAT64) 
 END as right_arm_bmc_g, 

CASE
    WHEN DXXRABMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRABMD AS FLOAT64) 
 END as right_arm_bmd_g_cm_2, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Arm/leg overlap' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARATV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXARATV IS NULL THEN NULL 
ELSE SAFE_CAST(DXARATV AS STRING) 
 END as right_arm_tissue_invalidity_code, 

CASE
    WHEN DXXRAFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRAFAT AS FLOAT64) 
 END as right_arm_fat_g, 

CASE
    WHEN DXDRALE IS NULL THEN NULL 
ELSE SAFE_CAST(DXDRALE AS FLOAT64) 
 END as right_arm_lean_excl_bmc_g, 

CASE
    WHEN DXXRALI IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRALI AS FLOAT64) 
 END as right_arm_lean_incl_bmc_g, 

CASE
    WHEN DXDRATOT IS NULL THEN NULL 
ELSE SAFE_CAST(DXDRATOT AS FLOAT64) 
 END as right_arm_total_g, 

CASE
    WHEN DXDRAPF IS NULL THEN NULL 
ELSE SAFE_CAST(DXDRAPF AS FLOAT64) 
 END as right_arm_percent_fat, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Arm/leg overlap' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXARLBV IS NULL THEN NULL 
ELSE SAFE_CAST(DXARLBV AS STRING) 
 END as right_leg_bone_invalidity_code, 

CASE
    WHEN DXXRLA IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRLA AS FLOAT64) 
 END as right_leg_area_cm_2, 

CASE
    WHEN DXXRLBMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRLBMC AS FLOAT64) 
 END as right_leg_bmc_g, 

CASE
    WHEN DXXRLBMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRLBMD AS FLOAT64) 
 END as right_leg_bmd_g_cm_2, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Arm/leg overlap' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXARLTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXARLTV IS NULL THEN NULL 
ELSE SAFE_CAST(DXARLTV AS STRING) 
 END as right_leg_tissue_invalidity_code, 

CASE
    WHEN DXXRLFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRLFAT AS FLOAT64) 
 END as right_leg_fat_g, 

CASE
    WHEN DXDRLLE IS NULL THEN NULL 
ELSE SAFE_CAST(DXDRLLE AS FLOAT64) 
 END as right_leg_lean_excl_bmc_g, 

CASE
    WHEN DXXRLLI IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRLLI AS FLOAT64) 
 END as right_leg_lean_incl_bmc_g, 

CASE
    WHEN DXDRLTOT IS NULL THEN NULL 
ELSE SAFE_CAST(DXDRLTOT AS FLOAT64) 
 END as right_leg_total_g, 

CASE
    WHEN DXDRLPF IS NULL THEN NULL 
ELSE SAFE_CAST(DXDRLPF AS FLOAT64) 
 END as right_leg_percent_fat, 

CASE
    WHEN DXXLRA IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLRA AS FLOAT64) 
 END as left_ribs_area_cm_2, 

CASE
    WHEN DXXLRBMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLRBMC AS FLOAT64) 
 END as left_ribs_bmc_g, 

CASE
    WHEN DXXLRBMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLRBMD AS FLOAT64) 
 END as left_ribs_bmd_g_cm_2, 

CASE
    WHEN DXXRRA IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRRA AS FLOAT64) 
 END as right_ribs_area_cm_2, 

CASE
    WHEN DXXRRBMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRRBMC AS FLOAT64) 
 END as right_ribs_bmc_g, 

CASE
    WHEN DXXRRBMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXXRRBMD AS FLOAT64) 
 END as right_ribs_bmd_g_cm_2, 

CASE
    WHEN DXXTSA IS NULL THEN NULL 
ELSE SAFE_CAST(DXXTSA AS FLOAT64) 
 END as thoracic_spine_area_cm_2, 

CASE
    WHEN DXXTSBMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXXTSBMC AS FLOAT64) 
 END as thoracic_spine_bmc_g, 

CASE
    WHEN DXXTSBMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXXTSBMD AS FLOAT64) 
 END as thoracic_spine_bmd_g_cm_2, 

CASE
    WHEN DXXLSA IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLSA AS FLOAT64) 
 END as lumbar_spine_area_cm_2, 

CASE
    WHEN DXXLSBMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLSBMC AS FLOAT64) 
 END as lumbar_spine_bmc_g, 

CASE
    WHEN DXXLSBMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXXLSBMD AS FLOAT64) 
 END as lumbar_spine_bmd_g_cm_2, 

CASE
    WHEN DXXPEA IS NULL THEN NULL 
ELSE SAFE_CAST(DXXPEA AS FLOAT64) 
 END as pelvis_area_cm_2, 

CASE
    WHEN DXXPEBMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXXPEBMC AS FLOAT64) 
 END as pelvis_bmc_g, 

CASE
    WHEN DXXPEBMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXXPEBMD AS FLOAT64) 
 END as pelvis_bmd_g_cm_2, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Excessive x-ray noise due to morbid obesity' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Arm/leg overlap' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRBV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXATRBV IS NULL THEN NULL 
ELSE SAFE_CAST(DXATRBV AS STRING) 
 END as trunk_bone_invalidity_code, 

CASE
    WHEN DXDTRA IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTRA AS FLOAT64) 
 END as trunk_bone_area_cm_2, 

CASE
    WHEN DXDTRBMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTRBMC AS FLOAT64) 
 END as trunk_bmc_g, 

CASE
    WHEN DXDTRBMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTRBMD AS FLOAT64) 
 END as trunk_bone_bmd_g_cm_2, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Valid data' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Removable or non-removable objects' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Excessive x-ray noise due to morbid obesity' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Arm/leg overlap' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Body parts out of scan region' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Positioning problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(DXATRTV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN DXATRTV IS NULL THEN NULL 
ELSE SAFE_CAST(DXATRTV AS STRING) 
 END as trunk_tissue_invalidity_code, 

CASE
    WHEN DXXTRFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DXXTRFAT AS FLOAT64) 
 END as trunk_fat_g, 

CASE
    WHEN DXDTRLE IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTRLE AS FLOAT64) 
 END as trunk_lean_excl_bmc_g, 

CASE
    WHEN DXXTRLI IS NULL THEN NULL 
ELSE SAFE_CAST(DXXTRLI AS FLOAT64) 
 END as trunk_lean_incl_bmc_g, 

CASE
    WHEN DXDTRTOT IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTRTOT AS FLOAT64) 
 END as trunk_total_g, 

CASE
    WHEN DXDTRPF IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTRPF AS FLOAT64) 
 END as trunk_percent_fat, 

CASE
    WHEN DXDSTA IS NULL THEN NULL 
ELSE SAFE_CAST(DXDSTA AS FLOAT64) 
 END as subtotal_area_cm_2, 

CASE
    WHEN DXDSTBMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXDSTBMC AS FLOAT64) 
 END as subtotal_bmc_g, 

CASE
    WHEN DXDSTBMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXDSTBMD AS FLOAT64) 
 END as subtotal_bmd_g_cm_2, 

CASE
    WHEN DXDSTFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DXDSTFAT AS FLOAT64) 
 END as subtotal_fat_g, 

CASE
    WHEN DXDSTLE IS NULL THEN NULL 
ELSE SAFE_CAST(DXDSTLE AS FLOAT64) 
 END as subtotal_lean_excl_bmc_g, 

CASE
    WHEN DXDSTLI IS NULL THEN NULL 
ELSE SAFE_CAST(DXDSTLI AS FLOAT64) 
 END as subtotal_lean_incl_bmc_g, 

CASE
    WHEN DXDSTTOT IS NULL THEN NULL 
ELSE SAFE_CAST(DXDSTTOT AS FLOAT64) 
 END as subtotal_total_excl_head_g, 

CASE
    WHEN DXDSTPF IS NULL THEN NULL 
ELSE SAFE_CAST(DXDSTPF AS FLOAT64) 
 END as subtotal_percent_fat, 

CASE
    WHEN DXDTOA IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTOA AS FLOAT64) 
 END as total_area_cm_2, 

CASE
    WHEN DXDTOBMC IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTOBMC AS FLOAT64) 
 END as total_bone_mineral_content_g, 

CASE
    WHEN DXDTOBMD IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTOBMD AS FLOAT64) 
 END as total_bone_mineral_density_g_cm_2, 

CASE
    WHEN DXDTOFAT IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTOFAT AS FLOAT64) 
 END as total_fat_g, 

CASE
    WHEN DXDTOLE IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTOLE AS FLOAT64) 
 END as total_lean_excl_bmc_g, 

CASE
    WHEN DXDTOLI IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTOLI AS FLOAT64) 
 END as total_lean_incl_bmc_g, 

CASE
    WHEN DXDTOTOT IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTOTOT AS FLOAT64) 
 END as total_lean_fat_g, 

CASE
    WHEN DXDTOPF IS NULL THEN NULL 
ELSE SAFE_CAST(DXDTOPF AS FLOAT64) 
 END as total_percent_fat, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_dual_energy_x_ray_absorptiometry_whole_body_examination') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DXX_J.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/DXX_I.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/DXX_H.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/DXX_G.htm
https://wwwn.cdc.gov/Nchs/Nhanes/Dxa/Dxa.aspx
*/
