SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032A AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Often true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032A AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Sometimes true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032A AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Never true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032A AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032A AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD032A IS NULL THEN NULL 
ELSE SAFE_CAST(FSD032A AS STRING) 
 END as hh_worried_run_out_of_food, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032B AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Often true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032B AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Sometimes true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032B AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Never true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032B AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032B AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD032B IS NULL THEN NULL 
ELSE SAFE_CAST(FSD032B AS STRING) 
 END as hh_food_didn_t_last, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032C AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Often true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032C AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Sometimes true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032C AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Never true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032C AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032C AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD032C IS NULL THEN NULL 
ELSE SAFE_CAST(FSD032C AS STRING) 
 END as hh_couldn_t_afford_balanced_meals, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD041 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD041 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD041 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD041 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD041 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD041 AS STRING) 
 END as hh_adults_cut_size_or_skip_meals, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD052 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Almost every month,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD052 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Some months but not every month, or' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD052 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Only 1 or 2 months?' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD052 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD052 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD052 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD052 AS STRING) 
 END as hh_how_often_adults_cut_size_skip_meals, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD061 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD061 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD061 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD061 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD061 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD061 AS STRING) 
 END as hh_eat_less_than_should, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD071 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD071 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD071 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD071 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD071 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD071 AS STRING) 
 END as hh_hungry_but_didn_t_eat, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD081 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD081 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD081 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD081 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD081 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD081 AS STRING) 
 END as hh_lost_weight_no_money_for_food, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD092 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD092 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD092 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD092 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD092 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD092 AS STRING) 
 END as hh_adults_not_eat_whole_day, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD102 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Almost every month,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD102 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Some months but not every month, or' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD102 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Only 1 or 2 months?' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD102 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD102 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD102 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD102 AS STRING) 
 END as hh_how_often_adults_not_eat_for_day, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032D AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Often true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032D AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Sometimes true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032D AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Never true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032D AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032D AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD032D IS NULL THEN NULL 
ELSE SAFE_CAST(FSD032D AS STRING) 
 END as hh_relied_on_low_cost_food_for_child, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032E AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Often true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032E AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Sometimes true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032E AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Never true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032E AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032E AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD032E IS NULL THEN NULL 
ELSE SAFE_CAST(FSD032E AS STRING) 
 END as hh_couldn_t_feed_child_balanced_meal, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032F AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Often true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032F AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Sometimes true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032F AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Never true' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032F AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD032F AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD032F IS NULL THEN NULL 
ELSE SAFE_CAST(FSD032F AS STRING) 
 END as hh_child_not_eating_enough, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD111 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD111 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD111 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD111 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD111 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD111 AS STRING) 
 END as hh_cut_size_of_child_meals, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD122 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD122 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD122 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD122 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD122 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD122 AS STRING) 
 END as hh_child_skip_meals, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD132 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Almost every month,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD132 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Some months but not every month, or' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD132 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Only 1 or 2 months?' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD132 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD132 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD132 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD132 AS STRING) 
 END as hh_how_often_child_skip_meals, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD141 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD141 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD141 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD141 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD141 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD141 AS STRING) 
 END as hh_child_hungry_in_last_12_months, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD146 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD146 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD146 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD146 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD146 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD146 AS STRING) 
 END as hh_child_not_eat_whole_day, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDHH AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'HH full food security: 0' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDHH AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'HH marginal food security: 1-2' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDHH AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'HH low food security: 3-5 (HH w/o child) / 3-7 (HH w/ child)' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDHH AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'HH very low food security: 6-10 (HH w/o child) / 8-18 (HH w/ child)' -- categorize string values 
WHEN FSDHH IS NULL THEN NULL 
ELSE SAFE_CAST(FSDHH AS STRING) 
 END as household_food_security_category, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDAD AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'AD full food security: 0' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDAD AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'AD marginal food security: 1-2' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDAD AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'AD low food security: 3-5' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDAD AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'AD very low food security: 6-10' -- categorize string values 
WHEN FSDAD IS NULL THEN NULL 
ELSE SAFE_CAST(FSDAD AS STRING) 
 END as adult_food_security_category, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDCH AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'CH full or marginal food security: 0' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDCH AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'CH marginal food security: 1' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDCH AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'CH low food security: 2-4' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSDCH AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'CH very low food security: 5-8' -- categorize string values 
WHEN FSDCH IS NULL THEN NULL 
ELSE SAFE_CAST(FSDCH AS STRING) 
 END as child_food_security_category, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD151 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD151 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD151 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD151 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD151 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD151 AS STRING) 
 END as hh_emergency_food_received, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ165 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ165 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ165 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ165 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSQ165 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ165 AS STRING) 
 END as hh_fs_benefit_ever_received, 

CASE
    WHEN SAFE_CAST(FSD165N AS FLOAT64) > 17.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSD165N IS NULL THEN NULL 
ELSE SAFE_CAST(FSD165N AS FLOAT64) 
 END as hh_fs_benefit_of_people_ever_received, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ012 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ012 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ012 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ012 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSQ012 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ012 AS STRING) 
 END as hh_fs_benefit_receive_in_last_12_months, 

CASE
    WHEN SAFE_CAST(FSD012N AS FLOAT64) > 17.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSD012N IS NULL THEN NULL 
ELSE SAFE_CAST(FSD012N AS FLOAT64) 
 END as hh_fs_benefit_of_people_received_12m, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD230 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD230 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD230 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD230 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD230 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD230 AS STRING) 
 END as hh_fs_benefit_currently_receive, 

CASE
    WHEN SAFE_CAST(FSD230N AS FLOAT64) > 17.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSD230N IS NULL THEN NULL 
ELSE SAFE_CAST(FSD230N AS FLOAT64) 
 END as hh_fs_benefit_people_currently_receive, 

CASE
    WHEN SAFE_CAST(FSD795 AS FLOAT64) > 23.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSD795 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD795 AS FLOAT64) 
 END as hh_fs_benefit_of_months_received, 

CASE
    WHEN SAFE_CAST(FSD225 AS FLOAT64) > 311.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSD225 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD225 AS FLOAT64) 
 END as hh_fs_benefit_time_since_last_received, 

CASE
    WHEN SAFE_CAST(FSD235 AS FLOAT64) > 975.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSD235 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD235 AS FLOAT64) 
 END as hh_fs_benefit_amount_received_last_time, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD855 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD855 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD855 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD855 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD855 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD855 AS STRING) 
 END as hh_fs_benefit_anticipate_will_receive, 

CASE
    WHEN SAFE_CAST(FSD860 AS FLOAT64) > 46.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSD860 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD860 AS FLOAT64) 
 END as hh_fs_benefit_time_will_receive, 

CASE
    WHEN SAFE_CAST(FSQ865 AS FLOAT64) > 711.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSQ865 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ865 AS FLOAT64) 
 END as hh_fs_benefit_amount_will_receive, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ162 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ162 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ162 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ162 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSQ162 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ162 AS STRING) 
 END as hh_wic_benefit_receive_in_last_12_month, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ760 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ760 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ760 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ760 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSQ760 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ760 AS STRING) 
 END as hh_wic_benefit_received_in_last_30_days, 

CASE
    WHEN SAFE_CAST(FSD760N AS FLOAT64) > 17.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSD760N IS NULL THEN NULL 
ELSE SAFE_CAST(FSD760N AS FLOAT64) 
 END as hh_wic_benefit_no_people_received, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ653 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ653 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ653 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ653 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSQ653 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ653 AS STRING) 
 END as ch_wic_benefit_ever_received, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660ZC AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660ZC AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660ZC AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660ZC AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD660ZC IS NULL THEN NULL 
ELSE SAFE_CAST(FSD660ZC AS STRING) 
 END as ch_wic_benefit_currently_receive, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD675 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD675 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD675 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD675 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD675 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD675 AS STRING) 
 END as ch_wic_benefit_received_in_infancy, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD680 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD680 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD680 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD680 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD680 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD680 AS STRING) 
 END as ch_wic_benefit_received_b_w_1_4_yrs_old, 

CASE
    WHEN SAFE_CAST(FSD670ZC AS FLOAT64) > 71.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSD670ZC IS NULL THEN NULL 
ELSE SAFE_CAST(FSD670ZC AS FLOAT64) 
 END as ch_wic_benefit_of_months_received, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ690 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ690 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ690 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ690 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSQ690 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ690 AS STRING) 
 END as ch_wic_benefit_mom_received_while_preg, 

CASE
    WHEN SAFE_CAST(FSQ695 AS FLOAT64) > 20.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSQ695 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ695 AS FLOAT64) 
 END as ch_wic_benefit_starting_month_of_preg, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD652ZW AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD652ZW AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD652ZW AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD652ZW AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD652ZW IS NULL THEN NULL 
ELSE SAFE_CAST(FSD652ZW AS STRING) 
 END as wm_wic_benefit_receive_in_latest_preg, 

CASE
    WHEN SAFE_CAST(FSD672ZW AS FLOAT64) > 20.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSD672ZW IS NULL THEN NULL 
ELSE SAFE_CAST(FSD672ZW AS FLOAT64) 
 END as wm_wic_benefit_starting_month_of_preg, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD652CW AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD652CW AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD652CW AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Currently pregnant' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD652CW AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD652CW AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD652CW IS NULL THEN NULL 
ELSE SAFE_CAST(FSD652CW AS STRING) 
 END as wm_wic_benefit_receive_post_partum, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660ZW AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660ZW AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660ZW AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660ZW AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD660ZW IS NULL THEN NULL 
ELSE SAFE_CAST(FSD660ZW AS STRING) 
 END as wm_wic_benefit_currently_receive, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD162 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD162 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD162 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD162 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD162 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD162 AS STRING) 
 END as hh_wic_benefit_receive_in_last_12_month_FSD162, 

CASE
    WHEN SAFE_CAST(FSQ235 AS FLOAT64) > 1408.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSQ235 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ235 AS FLOAT64) 
 END as hh_fs_benefit_amount_received_last_time_FSQ235, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650ZC AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650ZC AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650ZC AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650ZC AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD650ZC IS NULL THEN NULL 
ELSE SAFE_CAST(FSD650ZC AS STRING) 
 END as ch_wic_benefit_receive_in_last_12_month, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650ZW AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650ZW AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650ZW AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650ZW AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD650ZW IS NULL THEN NULL 
ELSE SAFE_CAST(FSD650ZW AS STRING) 
 END as wm_wic_benefit_receive_in_last_12_month, 

CASE
    WHEN SAFE_CAST(FSD670ZW AS FLOAT64) > 59.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSD670ZW IS NULL THEN NULL 
ELSE SAFE_CAST(FSD670ZW AS FLOAT64) 
 END as wm_wic_benefit_of_months_received, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ171 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ171 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ171 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ171 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSQ171 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ171 AS STRING) 
 END as hh_fs_benefit_receive_in_last_12_months_FSQ171, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD401 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Often' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD401 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Sometimes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD401 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Never' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD401 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD401 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD401 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD401 AS STRING) 
 END as meal_size_cut, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD421 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Often' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD421 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Sometimes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD421 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Never' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD421 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD421 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD421 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD421 AS STRING) 
 END as ate_less_than_should, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD431 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Often' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD431 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Sometimes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD431 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Never' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD431 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD431 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD431 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD431 AS STRING) 
 END as hungry, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD411 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Often' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD411 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Sometimes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD411 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Never' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD411 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD411 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD411 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD411 AS STRING) 
 END as skipped_meals, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD440 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD440 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD440 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD440 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD440 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD440 AS STRING) 
 END as lost_weight, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD451 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Ever' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD451 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Never' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD451 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD451 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD451 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD451 AS STRING) 
 END as not_eat_whole_day, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSQ440 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ440 AS STRING) 
 END as lost_weight_FSQ440, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ170 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ170 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ170 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ170 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSQ170 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ170 AS STRING) 
 END as fd_stmp_hh_authorized_last_12_mos, 

CASE
    WHEN FSD170N IS NULL THEN NULL 
ELSE SAFE_CAST(FSD170N AS FLOAT64) 
 END as fd_stmp_hh_no_people_authorized, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSD180 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD180 AS STRING) 
 END as fd_stmp_sp_authorized_in_last_12_mos, 

CASE
    WHEN FSD190 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD190 AS FLOAT64) 
 END as fd_stmp_sp_mos_authorized_in_last_12_mos, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSD200 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD200 AS STRING) 
 END as fd_stmp_sp_currentlyauthorized, 

CASE
    WHEN SAFE_CAST(FSQ210 AS FLOAT64) > 1011.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSQ210 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ210 AS FLOAT64) 
 END as fd_stmp_hh_amount_last_month, 

CASE
    WHEN SAFE_CAST(FSQ220 AS FLOAT64) > 1011.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSQ220 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ220 AS FLOAT64) 
 END as fd_stmp_hh_amount_last_time, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD650 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD650 AS STRING) 
 END as wic_sp_got_past_12_mos, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD660 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD660 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD660 AS STRING) 
 END as wic_sp_currently_get, 

CASE
    WHEN FSD670 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD670 AS FLOAT64) 
 END as wic_sp_no_mos_received, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ400 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ400 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ400 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ400 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSQ400 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ400 AS STRING) 
 END as adult_cut_size_or_skipped_meals, 

CASE
    WHEN FSQ410 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ410 AS FLOAT64) 
 END as adult_days_cut_size_or_skipped_meals, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSQ420 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ420 AS STRING) 
 END as adult_ate_less_than_should, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ430 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ430 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ430 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ430 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSQ430 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ430 AS STRING) 
 END as adult_hungry_didn_t_eat, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ450 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ450 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ450 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ450 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSQ450 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ450 AS STRING) 
 END as adult_not_eat_whole_day, 

CASE
    WHEN SAFE_CAST(FSQ460 AS FLOAT64) > 21.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSQ460 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ460 AS FLOAT64) 
 END as adult_days_without_eating, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ470 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ470 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ470 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ470 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSQ470 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ470 AS STRING) 
 END as child_ate_less_than_should, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSQ480 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ480 AS STRING) 
 END as child_cut_size_of_meals, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ490 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ490 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ490 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ490 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSQ490 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ490 AS STRING) 
 END as child_hungry_in_last_30_days, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ500 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ500 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ500 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ500 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSQ500 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ500 AS STRING) 
 END as child_skipped_meal, 

CASE
    WHEN SAFE_CAST(FSQ510 AS FLOAT64) > 21.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN FSQ510 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ510 AS FLOAT64) 
 END as child_days_skipped_meal, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ520 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ520 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ520 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSQ520 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSQ520 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ520 AS STRING) 
 END as child_not_eat_whole_day, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650C AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650C AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650C AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650C AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD650C IS NULL THEN NULL 
ELSE SAFE_CAST(FSD650C AS STRING) 
 END as child_wic_in_past_12_months, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD660C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD660C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD660C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD660C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSD660C IS NULL THEN NULL 
ELSE SAFE_CAST(FSD660C AS STRING) 
 END as child_current_wic, 

CASE
    WHEN FSD670C IS NOT NULL THEN SAFE_CAST(FSD670C AS FLOAT64) -- correct wrong data types for numerical data 
WHEN FSD670C IS NULL THEN NULL 
ELSE SAFE_CAST(FSD670C AS FLOAT64) 
 END as child_no_months_wic, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650M AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650M AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650M AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(FSD650M AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN FSD650M IS NULL THEN NULL 
ELSE SAFE_CAST(FSD650M AS STRING) 
 END as mom_wic_in_past_12_months, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD660M AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD660M AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD660M AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD660M AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSD660M IS NULL THEN NULL 
ELSE SAFE_CAST(FSD660M AS STRING) 
 END as mom_current_wic, 

CASE
    WHEN FSD670M IS NOT NULL THEN SAFE_CAST(FSD670M AS FLOAT64) -- correct wrong data types for numerical data 
WHEN FSD670M IS NULL THEN NULL 
ELSE SAFE_CAST(FSD670M AS FLOAT64) 
 END as mom_no_months_wic, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD160 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD160 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD160 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD160 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSD160 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD160 AS STRING) 
 END as household_wic_received, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD450 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD450 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD450 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD450 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSD450 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD450 AS STRING) 
 END as adult_not_eat_whole_day_FSD450, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSD520 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD520 AS STRING) 
 END as child_not_eat_whole_day_FSD520, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD655 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD655 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD655 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD655 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSD655 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD655 AS STRING) 
 END as child_received_wic_in_past_12_months, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD665 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '0-6 months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD665 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '7-12 months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD665 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '13-18 months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD665 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '19-24 months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD665 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '25-36 months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD665 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN '37-60 months' -- categorize numeric values
WHEN FSD665 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD665 AS STRING) 
 END as how_long_child_receiving_wic, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ650 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ650 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ650 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSQ650 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSQ650 IS NULL THEN NULL 
ELSE SAFE_CAST(FSQ650 AS STRING) 
 END as mom_received_wic_in_past_12_months, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(HHFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'HH fully food secure' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HHFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'HH marginally food secure' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HHFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'HH food insecure without hunger' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HHFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'HH food insecure with hunger' -- categorize numeric values
WHEN HHFDSEC IS NULL THEN NULL 
ELSE SAFE_CAST(HHFDSEC AS STRING) 
 END as household_food_security_category_HHFDSEC, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(ADFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'AD fully food secure: 0' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ADFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'AD marginally food secure: 1-2' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ADFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'AD food insecure without hunger: 3-5' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ADFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'AD food insecure with hunger: 6-10' -- categorize numeric values
WHEN ADFDSEC IS NULL THEN NULL 
ELSE SAFE_CAST(ADFDSEC AS STRING) 
 END as adult_food_security_category_ADFDSEC, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CHFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'CH food quality & quantity unaffected: 0' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CHFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'CH marginally food secure: 1' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CHFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'CH reduced food quality or quantity: 2-4' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CHFDSEC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'CH food insecure with hunger: 5-8' -- categorize numeric values
WHEN CHFDSEC IS NULL THEN NULL 
ELSE SAFE_CAST(CHFDSEC AS STRING) 
 END as child_food_security_category_CHFDSEC, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Enough and the kinds of food wanted' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Enough but not always the kinds of food wanted' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Sometimes/Often not enough to eat' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(FSD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN FSD010 IS NULL THEN NULL 
ELSE SAFE_CAST(FSD010 AS STRING) 
 END as food_adequacy_indicator, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_food_security_questionnaire') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/FSQ_J.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_FSQ.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/FSQ_I.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/FSQ_H.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/FSQ_G.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2009-2010/FSQ_F.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2007-2008/FSQ_E.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/FSQ_D.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/FSQ_C.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/FSQ_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/FSQ.htm
*/
