SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ011 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ011 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ011 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ011 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN HIQ011 IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ011 AS STRING) 
 END as covered_by_health_insurance, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031A AS FLOAT64),0) AS INT64) AS STRING) = '14' THEN 'Covered by private insurance' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031A AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031A AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN HIQ031A IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ031A AS STRING) 
 END as covered_by_private_insurance, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031B AS FLOAT64),0) AS INT64) AS STRING) = '15' THEN 'Covered by Medicare' -- categorize string values 
WHEN HIQ031B IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ031B AS STRING) 
 END as covered_by_medicare, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031C AS FLOAT64),0) AS INT64) AS STRING) = '16' THEN 'Covered by Medi-Gap' -- categorize string values 
WHEN HIQ031C IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ031C AS STRING) 
 END as covered_by_medi_gap, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031D AS FLOAT64),0) AS INT64) AS STRING) = '17' THEN 'Covered by Medicaid' -- categorize string values 
WHEN HIQ031D IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ031D AS STRING) 
 END as covered_by_medicaid, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031E AS FLOAT64),0) AS INT64) AS STRING) = '18' THEN 'Covered by CHIP' -- categorize string values 
WHEN HIQ031E IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ031E AS STRING) 
 END as covered_by_chip, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031F AS FLOAT64),0) AS INT64) AS STRING) = '19' THEN 'Covered by military health care' -- categorize string values 
WHEN HIQ031F IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ031F AS STRING) 
 END as covered_by_military_health_care, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031H AS FLOAT64),0) AS INT64) AS STRING) = '21' THEN 'Covered by state-sponsored health plan' -- categorize string values 
WHEN HIQ031H IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ031H AS STRING) 
 END as covered_by_state_sponsored_health_plan, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031I AS FLOAT64),0) AS INT64) AS STRING) = '22' THEN 'Covered by other government insurance' -- categorize string values 
WHEN HIQ031I IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ031I AS STRING) 
 END as covered_by_other_government_insurance, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031J AS FLOAT64),0) AS INT64) AS STRING) = '23' THEN 'Covered by single service plan' -- categorize string values 
WHEN HIQ031J IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ031J AS STRING) 
 END as covered_by_single_service_plan, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031AA AS FLOAT64),0) AS INT64) AS STRING) = '40' THEN 'No coverage of any type' -- categorize string values 
WHEN HIQ031AA IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ031AA AS STRING) 
 END as no_coverage_of_any_type, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ260 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ260 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ260 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ260 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN HIQ260 IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ260 AS STRING) 
 END as have_medicare, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ105 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ105 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN HIQ105 IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ105 AS STRING) 
 END as insurance_card_available_or_not, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ270 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ270 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ270 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ270 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN HIQ270 IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ270 AS STRING) 
 END as do_plans_cover_prescriptions, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(HIQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HIQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HIQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HIQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HIQ210 IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ210 AS STRING) 
 END as time_when_no_insurance_in_past_year, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ032A AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Covered by private insurance' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ032A AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ032A AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN HIQ032A IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ032A AS STRING) 
 END as covered_by_private_insurance_HIQ032A, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ032B AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Covered by Medicare' -- categorize string values 
WHEN HIQ032B IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ032B AS STRING) 
 END as covered_by_medicare_HIQ032B, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ032C AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Covered by Medi-Gap' -- categorize string values 
WHEN HIQ032C IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ032C AS STRING) 
 END as covered_by_medi_gap_HIQ032C, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ032D AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'Covered by Medicaid' -- categorize string values 
WHEN HIQ032D IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ032D AS STRING) 
 END as covered_by_medicaid_HIQ032D, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ032E AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'Covered by CHIP' -- categorize string values 
WHEN HIQ032E IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ032E AS STRING) 
 END as covered_by_chip_HIQ032E, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ032H AS FLOAT64),0) AS INT64) AS STRING) = '8' THEN 'Covered by state-sponsored health plan' -- categorize string values 
WHEN HIQ032H IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ032H AS STRING) 
 END as covered_by_state_sponsored_health_plan_HIQ032H, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ032I AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Covered by other government insurance' -- categorize string values 
WHEN HIQ032I IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ032I AS STRING) 
 END as covered_by_other_government_insurance_HIQ032I, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ032J AS FLOAT64),0) AS INT64) AS STRING) = '10' THEN 'No coverage of any type' -- categorize string values 
WHEN HIQ032J IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ032J AS STRING) 
 END as not_covered_by_any_insurance, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HIQ031G AS FLOAT64),0) AS INT64) AS STRING) = '20' THEN 'Covered by Indian Health Service' -- categorize string values 
WHEN HIQ031G IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ031G AS STRING) 
 END as covered_by_indian_health_service, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(HID010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HID010 IS NULL THEN NULL 
ELSE SAFE_CAST(HID010 AS STRING) 
 END as covered_by_health_insurance_HID010, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HID030A IS NULL THEN NULL 
ELSE SAFE_CAST(HID030A AS STRING) 
 END as covered_by_private_insurance_HID030A, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HID030B IS NULL THEN NULL 
ELSE SAFE_CAST(HID030B AS STRING) 
 END as covered_by_medicare_HID030B, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HID030C IS NULL THEN NULL 
ELSE SAFE_CAST(HID030C AS STRING) 
 END as covered_by_medicaid_chip, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Covered by other government insurance' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Not covered by other government insurance' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HID030D IS NULL THEN NULL 
ELSE SAFE_CAST(HID030D AS STRING) 
 END as covered_by_other_government_insurance_HID030D, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID030E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HID030E IS NULL THEN NULL 
ELSE SAFE_CAST(HID030E AS STRING) 
 END as covered_by_single_service_plan_HID030E, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(HID040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HID040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HID040 IS NULL THEN NULL 
ELSE SAFE_CAST(HID040 AS STRING) 
 END as dental_coverage_included, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(HIQ220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '6 months or less' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HIQ220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'More than 6 months, but not more than 1 year ago' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HIQ220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'More than 1 year, but not more than 3 years ago' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HIQ220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'More than 3 years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HIQ220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Never' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HIQ220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HIQ220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HIQ220 IS NULL THEN NULL 
ELSE SAFE_CAST(HIQ220 AS STRING) 
 END as how_long_since_last_insured, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_health_insurance_questionnaire') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/HIQ_J.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_HIQ.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/HIQ_I.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/HIQ_H.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/HIQ_G.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2009-2010/HIQ_F.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2007-2008/HIQ_E.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/HIQ_D.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/HIQ_C.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/HIQ_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/HIQ.htm
*/
