SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '1' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '2' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '3' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '4' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '5' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN '6' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN '7' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN '8' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN '9' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN '10' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN '11' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN '12' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN '13 or more' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(777 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(999 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD050 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD050 AS STRING) 
 END as number_of_rooms_in_home, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ065 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Owned or being bought' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ065 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Rented' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ065 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Other arrangement' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ065 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ065 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOQ065 IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ065 AS STRING) 
 END as home_owned_bought_rented_other, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ040 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN '1990 to present' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ040 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '1978 to 1989' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ040 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN '1960 to 1977' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ040 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN '1950 to 1959' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ040 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN '1940 to 1949' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ040 AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN 'Before 1940' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ040 AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ040 AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN HOQ040 IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ040 AS STRING) 
 END as when_was_home_built, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Less than one year' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '1-2 years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '3-5 years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '6-10 years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'More than 10 years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD060 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD060 AS STRING) 
 END as how_many_years_family_lived_in_home, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Private/public water company' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Private/public well' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Something else' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOQ070 IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ070 AS STRING) 
 END as source_of_tap_water, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOQ080 IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ080 AS STRING) 
 END as water_treatment_devices_used_or_not, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ011 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Mobile home or trailer' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ011 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'One family house detached from any other house' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ011 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'One family house attached to one or more houses' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ011 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'Apartment' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ011 AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN 'Dormitory' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ011 AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ011 AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN HOQ011 IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ011 AS STRING) 
 END as type_of_home, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '1 or 2' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '3 or 4' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '5 to 9' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '10 to 19' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN '20 to 49' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN '50 or more' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD030 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD030 AS STRING) 
 END as how_many_apartments_in_building, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ230 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ230 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ230 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ230 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN HOQ230 IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ230 AS STRING) 
 END as has_home_had_a_mildew_or_musty_smell, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ240 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ240 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ240 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ240 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN HOQ240 IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ240 AS STRING) 
 END as have_you_seen_cockroaches_in_your_home, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ250 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ250 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ250 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ250 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN HOQ250 IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ250 AS STRING) 
 END as do_animals_live_or_spend_time_in_home, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ260A AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Dog' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ260A AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ260A AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN HOQ260A IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ260A AS STRING) 
 END as dog_in_house_now, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ260B AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Cat' -- categorize string values 
WHEN HOQ260B IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ260B AS STRING) 
 END as cat_in_house_now, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ260C AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Small furry animal' -- categorize string values 
WHEN HOQ260C IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ260C AS STRING) 
 END as small_furry_animal_in_house_now, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ270 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ270 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ270 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ270 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN HOQ270 IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ270 AS STRING) 
 END as did_animals_live_or_spend_time_in_home, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ280A AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Dog' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ280A AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ280A AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN HOQ280A IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ280A AS STRING) 
 END as dog_in_house_last_12_months, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ280B AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Cat' -- categorize string values 
WHEN HOQ280B IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ280B AS STRING) 
 END as cat_in_house_last_12_months, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOQ280C AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Small furry animal' -- categorize string values 
WHEN HOQ280C IS NULL THEN NULL 
ELSE SAFE_CAST(HOQ280C AS STRING) 
 END as small_furry_animal_in_house_last_12_mon, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOD011 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Mobile home or trailer' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOD011 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'One family house detached from any other house' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOD011 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'One family house attached to one or more houses' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOD011 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'Apartment' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOD011 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'Something else' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOD011 AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN 'Dormitory' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOD011 AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(HOD011 AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN HOD011 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD011 AS STRING) 
 END as type_of_home_HOD011, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '1990 to present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '1978 to 1989' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '1960 to 1977' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '1950 to 1959' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '1940 to 1949' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Before 1940' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD040 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD040 AS STRING) 
 END as when_was_home_built_HOD040, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD140 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD140 AS STRING) 
 END as home_painted_in_last_12_months, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD150 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD150 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD150 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD150 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD150 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD150 AS STRING) 
 END as old_paint_scraped_when_home_painted, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD160 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD160 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD160 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD160 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD160 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD160 AS STRING) 
 END as paint_peeling_flaking_chipping_inside, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD170 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD170 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD170 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD170 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD170 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD170 AS STRING) 
 END as inside_peeling_area_plus_22x26, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'One room' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Two or more rooms' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD180 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD180 AS STRING) 
 END as number_of_rooms_22x26_peeling, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD190 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD190 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD190 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD190 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD190 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD190 AS STRING) 
 END as outside_paint_peeling_flaking_chipping, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD210 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD210 AS STRING) 
 END as outside_peeling_larger_than_door, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD220 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD220 AS STRING) 
 END as window_cabinet_or_wall_renovation, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'A mobile home or trailer,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'A one family house detached from any other house,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'A one family house attached to one or more houses,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'An apartment,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Something else,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Dormitory?' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(HOD010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN HOD010 IS NULL THEN NULL 
ELSE SAFE_CAST(HOD010 AS STRING) 
 END as type_of_home_HOD010, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_housing_characteristics_questionnaire') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/HOQ_J.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/HOQ_I.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/HOQ_H.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/HOQ_G.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2009-2010/HOQ_F.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2007-2008/HOQ_E.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/HOQ_D.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/HOQ_C.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/HOQ_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/HOQ.htm
*/
