SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
    WHEN LBXH2RL IS NULL THEN NULL 
ELSE SAFE_CAST(LBXH2RL AS FLOAT64) 
 END as hybrid_capture_high_risk_rlu_result, 

CASE
    WHEN LBXH3RL IS NULL THEN NULL 
ELSE SAFE_CAST(LBXH3RL AS FLOAT64) 
 END as hybrid_capture_low_risk_rlu_result, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDHPCR AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDHPCR AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDHPCR AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDHPCR IS NULL THEN NULL 
ELSE SAFE_CAST(LBDHPCR AS STRING) 
 END as hpv_summary_variable, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH06 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH06 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH06 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH06 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH06 AS STRING) 
 END as hpv_type_06, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH11 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH11 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH11 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH11 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH11 AS STRING) 
 END as hpv_type_11, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH16 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH16 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH16 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH16 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH16 AS STRING) 
 END as hpv_type_16, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH18 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH18 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH18 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH18 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH18 AS STRING) 
 END as hpv_type_18, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH26 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH26 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH26 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH26 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH26 AS STRING) 
 END as hpv_type_26, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH31 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH31 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH31 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH31 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH31 AS STRING) 
 END as hpv_type_31, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH33 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH33 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH33 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH33 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH33 AS STRING) 
 END as hpv_type_33, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH35 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH35 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH35 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH35 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH35 AS STRING) 
 END as hpv_type_35, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH39 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH39 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH39 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH39 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH39 AS STRING) 
 END as hpv_type_39, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH40 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH40 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH40 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH40 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH40 AS STRING) 
 END as hpv_type_40, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH42 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH42 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH42 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH42 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH42 AS STRING) 
 END as hpv_type_42, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH45 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH45 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH45 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH45 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH45 AS STRING) 
 END as hpv_type_45, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH51 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH51 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH51 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH51 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH51 AS STRING) 
 END as hpv_type_51, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH52 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH52 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH52 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH52 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH52 AS STRING) 
 END as hpv_type_52, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH53 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH53 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH53 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH53 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH53 AS STRING) 
 END as hpv_type_53, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH54 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH54 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH54 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH54 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH54 AS STRING) 
 END as hpv_type_54, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH55 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH55 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH55 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH55 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH55 AS STRING) 
 END as hpv_type_55, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH56 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH56 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH56 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH56 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH56 AS STRING) 
 END as hpv_type_56, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH58 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH58 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH58 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH58 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH58 AS STRING) 
 END as hpv_type_58, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH59 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH59 AS STRING) 
 END as hpv_type_59, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH61 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH61 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH61 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH61 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH61 AS STRING) 
 END as hpv_type_61, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH62 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH62 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH62 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH62 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH62 AS STRING) 
 END as hpv_type_62, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH64 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH64 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH64 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH64 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH64 AS STRING) 
 END as hpv_type_64, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH66 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH66 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH66 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH66 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH66 AS STRING) 
 END as hpv_type_66, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH67 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH67 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH67 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH67 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH67 AS STRING) 
 END as hpv_type_67, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH68 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH68 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH68 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH68 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH68 AS STRING) 
 END as hpv_type_68, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH69 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH69 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH69 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH69 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH69 AS STRING) 
 END as hpv_type_69, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH70 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH70 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH70 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH70 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH70 AS STRING) 
 END as hpv_type_70, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH71 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH71 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH71 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH71 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH71 AS STRING) 
 END as hpv_type_71, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH72 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH72 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH72 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH72 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH72 AS STRING) 
 END as hpv_type_72, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH73 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH73 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH73 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH73 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH73 AS STRING) 
 END as hpv_type_73, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH81 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH81 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH81 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH81 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH81 AS STRING) 
 END as hpv_type_81, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH82 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH82 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH82 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH82 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH82 AS STRING) 
 END as hpv_type_82, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH83 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH83 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH83 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH83 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH83 AS STRING) 
 END as hpv_type_83, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH84 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH84 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH84 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH84 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH84 AS STRING) 
 END as hpv_type_84, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH89 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH89 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDH89 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDH89 IS NULL THEN NULL 
ELSE SAFE_CAST(LBDH89 AS STRING) 
 END as hpv_type_89, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDHPI AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDHPI AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDHPI AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Inadequate' -- categorize numeric values
WHEN LBDHPI IS NULL THEN NULL 
ELSE SAFE_CAST(LBDHPI AS STRING) 
 END as hpv_type_is39, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXNST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'HPV 22' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXNST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'HPV 32' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXNST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'HPV 38' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXNST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'HPV 44' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXNST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'HPV 74' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXNST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'HPV 85' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXNST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'HPV 87' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXNST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'HPV 91' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXNST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'HPV DL285' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXNST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'HPV IA06' -- categorize numeric values
WHEN LBXNST IS NULL THEN NULL 
ELSE SAFE_CAST(LBXNST AS STRING) 
 END as other_hpv_strip_types, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_human_papillomavirus_hpv_dna_vaginal_swab_digene_hybrid_capture_prototype_line_blot_assay_laboratory') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/L37SWA_C.htm
*/
