SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXGH AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXGH AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXGH AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXGH IS NULL THEN NULL 
ELSE SAFE_CAST(ORXGH AS STRING) 
 END as hpv_high_globulin_band_result, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXGL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXGL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXGL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXGL IS NULL THEN NULL 
ELSE SAFE_CAST(ORXGL AS STRING) 
 END as hpv_low_globulin_band_result, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH06 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH06 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH06 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH06 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH06 AS STRING) 
 END as hpv_type_6, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH11 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH11 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH11 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH11 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH11 AS STRING) 
 END as hpv_type_11, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH16 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH16 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH16 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH16 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH16 AS STRING) 
 END as hpv_type_16, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH18 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH18 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH18 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH18 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH18 AS STRING) 
 END as hpv_type_18, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH26 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH26 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH26 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH26 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH26 AS STRING) 
 END as hpv_type_26, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH31 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH31 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH31 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH31 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH31 AS STRING) 
 END as hpv_type_31, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH33 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH33 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH33 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH33 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH33 AS STRING) 
 END as hpv_type_33, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH35 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH35 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH35 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH35 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH35 AS STRING) 
 END as hpv_type_35, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH39 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH39 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH39 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH39 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH39 AS STRING) 
 END as hpv_type_39, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH40 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH40 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH40 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH40 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH40 AS STRING) 
 END as hpv_type_40, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH42 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH42 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH42 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH42 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH42 AS STRING) 
 END as hpv_type_42, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH45 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH45 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH45 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH45 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH45 AS STRING) 
 END as hpv_type_45, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH51 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH51 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH51 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH51 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH51 AS STRING) 
 END as hpv_type_51, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH52 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH52 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH52 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH52 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH52 AS STRING) 
 END as hpv_type_52, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH53 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH53 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH53 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH53 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH53 AS STRING) 
 END as hpv_type_53, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH54 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH54 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH54 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH54 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH54 AS STRING) 
 END as hpv_type_54, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH55 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH55 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH55 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH55 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH55 AS STRING) 
 END as hpv_type_55, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH56 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH56 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH56 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH56 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH56 AS STRING) 
 END as hpv_type_56, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH58 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH58 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH58 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH58 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH58 AS STRING) 
 END as hpv_type_58, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH59 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH59 AS STRING) 
 END as hpv_type_59, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH61 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH61 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH61 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH61 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH61 AS STRING) 
 END as hpv_type_61, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH62 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH62 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH62 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH62 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH62 AS STRING) 
 END as hpv_type_62, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH64 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH64 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH64 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH64 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH64 AS STRING) 
 END as hpv_type_64, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH66 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH66 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH66 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH66 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH66 AS STRING) 
 END as hpv_type_66, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH67 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH67 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH67 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH67 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH67 AS STRING) 
 END as hpv_type_67, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH68 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH68 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH68 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH68 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH68 AS STRING) 
 END as hpv_type_68, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH69 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH69 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH69 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH69 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH69 AS STRING) 
 END as hpv_type_69, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH70 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH70 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH70 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH70 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH70 AS STRING) 
 END as hpv_type_70, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH71 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH71 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH71 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH71 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH71 AS STRING) 
 END as hpv_type_71, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH72 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH72 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH72 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH72 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH72 AS STRING) 
 END as hpv_type_72, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH73 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH73 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH73 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH73 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH73 AS STRING) 
 END as hpv_type_73, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH81 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH81 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH81 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH81 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH81 AS STRING) 
 END as hpv_type_81, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH82 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH82 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH82 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH82 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH82 AS STRING) 
 END as hpv_type_82, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH83 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH83 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH83 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH83 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH83 AS STRING) 
 END as hpv_type_83, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH84 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH84 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXH84 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXH84 IS NULL THEN NULL 
ELSE SAFE_CAST(ORXH84 AS STRING) 
 END as hpv_type_84, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXHPC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXHPC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXHPC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXHPC IS NULL THEN NULL 
ELSE SAFE_CAST(ORXHPC AS STRING) 
 END as hpv_cp_6108, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXHPI AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXHPI AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXHPI AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXHPI IS NULL THEN NULL 
ELSE SAFE_CAST(ORXHPI AS STRING) 
 END as hpv_type_is39, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXHPV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXHPV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Negative' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(ORXHPV AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not evaluated' -- categorize numeric values
WHEN ORXHPV IS NULL THEN NULL 
ELSE SAFE_CAST(ORXHPV AS STRING) 
 END as oral_hpv_result, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_human_papillomavirus_hpv_oral_rinse_laboratory') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/ORHPV_I.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/ORHPV_H.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/ORHPV_G.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2009-2010/ORHPV_F.htm
*/
