SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'None' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Safety exclusion' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'SP refusal' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'No time' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Physical limitation' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Communication problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Equipment failure' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'SP ill/emergency' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Interrupted' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(22 AS FLOAT64),0) AS INT64) THEN 'Pain or discomfort' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(23 AS FLOAT64),0) AS INT64) THEN 'Poor cuff fit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(56 AS FLOAT64),0) AS INT64) THEN 'Came late/left early' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(58 AS FLOAT64),0) AS INT64) THEN 'Unable to obtain all bps' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(72 AS FLOAT64),0) AS INT64) THEN 'Error (technician/software/supply)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(84 AS FLOAT64),0) AS INT64) THEN 'SP with child' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(101 AS FLOAT64),0) AS INT64) THEN 'Bandage, stocking, or other obstruction' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(104 AS FLOAT64),0) AS INT64) THEN 'Swollen legs/ankle edema' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDSCCT2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(999 AS FLOAT64),0) AS INT64) THEN 'Other, specify' -- categorize numeric values
WHEN LEDSCCT2 IS NULL THEN NULL 
ELSE SAFE_CAST(LEDSCCT2 AS STRING) 
 END as abpi_section_comment, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAARM AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Right' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAARM AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Left' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAARM AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Could not obtain' -- categorize numeric values
WHEN LEAARM IS NULL THEN NULL 
ELSE SAFE_CAST(LEAARM AS STRING) 
 END as arm_tested, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAARMC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Lesion, bandage' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAARMC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Rash' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAARMC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Amputation' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAARMC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN LEAARMC IS NULL THEN NULL 
ELSE SAFE_CAST(LEAARMC AS STRING) 
 END as arm_comment, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDARMCF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '9 cm' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDARMCF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '12 cm' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDARMCF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '15 cm' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDARMCF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '18 cm' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDARMCF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Could not obtain' -- categorize numeric values
WHEN LEDARMCF IS NULL THEN NULL 
ELSE SAFE_CAST(LEDARMCF AS STRING) 
 END as brachial_cuff_size_used, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN LEQ020 IS NULL THEN NULL 
ELSE SAFE_CAST(LEQ020 AS STRING) 
 END as large_adult_used_poor_thigh_cuff_fit, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAANKL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Right' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAANKL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Left' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAANKL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Both' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAANKL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Could not obtain' -- categorize numeric values
WHEN LEAANKL IS NULL THEN NULL 
ELSE SAFE_CAST(LEAANKL AS STRING) 
 END as ankle_s_tested, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAANKLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Edema, lesions, bandages' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAANKLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Rash' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAANKLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Amputation' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEAANKLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN LEAANKLC IS NULL THEN NULL 
ELSE SAFE_CAST(LEAANKLC AS STRING) 
 END as ankle_comment, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDANKCF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '9 cm' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDANKCF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '12 cm' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDANKCF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '15 cm' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDANKCF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '18 cm' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEDANKCF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Could not obtain' -- categorize numeric values
WHEN LEDANKCF IS NULL THEN NULL 
ELSE SAFE_CAST(LEDANKCF AS STRING) 
 END as ankle_cuff_size_used, 

CASE
    WHEN LEXBRP1 IS NULL THEN NULL 
ELSE SAFE_CAST(LEXBRP1 AS FLOAT64) 
 END as brachial_sbp_1_mm_hg, 

CASE
    WHEN LEXBRP2 IS NULL THEN NULL 
ELSE SAFE_CAST(LEXBRP2 AS FLOAT64) 
 END as brachial_sbp_2_mm_hg, 

CASE
    WHEN LEXBRPM IS NULL THEN NULL 
ELSE SAFE_CAST(LEXBRPM AS FLOAT64) 
 END as mean_brachial_sbp_mm_hg, 

CASE
    WHEN LEXLPTS1 IS NULL THEN NULL 
ELSE SAFE_CAST(LEXLPTS1 AS FLOAT64) 
 END as left_posterior_tibial_sbp_1_mm_hg, 

CASE
    WHEN LEXLPTS2 IS NULL THEN NULL 
ELSE SAFE_CAST(LEXLPTS2 AS FLOAT64) 
 END as left_posterior_tibial_sbp_2_mm_hg, 

CASE
    WHEN LEXLPTSM IS NULL THEN NULL 
ELSE SAFE_CAST(LEXLPTSM AS FLOAT64) 
 END as left_mean_posterior_tibial_sbp_mm_hg, 

CASE
    WHEN LEXLABPI IS NULL THEN NULL 
ELSE SAFE_CAST(LEXLABPI AS FLOAT64) 
 END as left_abpi, 

CASE
    WHEN LEXRPTS1 IS NULL THEN NULL 
ELSE SAFE_CAST(LEXRPTS1 AS FLOAT64) 
 END as right_posterior_tibial_sbp_1_mm_hg, 

CASE
    WHEN LEXRPTS2 IS NULL THEN NULL 
ELSE SAFE_CAST(LEXRPTS2 AS FLOAT64) 
 END as right_posterior_tibial_sbp_2_mm_hg, 

CASE
    WHEN LEXRPTSM IS NULL THEN NULL 
ELSE SAFE_CAST(LEXRPTSM AS FLOAT64) 
 END as right_mean_posterior_tibial_sbp_mm_hg, 

CASE
    WHEN LEXRABPI IS NULL THEN NULL 
ELSE SAFE_CAST(LEXRABPI AS FLOAT64) 
 END as right_abpi, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEALPTPD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEALPTPD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEALPTPD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Could not obtain' -- categorize numeric values
WHEN LEALPTPD IS NULL THEN NULL 
ELSE SAFE_CAST(LEALPTPD AS STRING) 
 END as left_pt_pulse_detected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEARPTPD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEARPTPD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEARPTPD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Could not obtain' -- categorize numeric values
WHEN LEARPTPD IS NULL THEN NULL 
ELSE SAFE_CAST(LEARPTPD AS STRING) 
 END as right_pt_pulse_detected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEALAPNC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEALAPNC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEALAPNC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Could not obtain' -- categorize numeric values
WHEN LEALAPNC IS NULL THEN NULL 
ELSE SAFE_CAST(LEALAPNC AS STRING) 
 END as left_ankle_sbp_255_mm_hg, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(LEARAPNC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEARAPNC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LEARAPNC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Could not obtain' -- categorize numeric values
WHEN LEARAPNC IS NULL THEN NULL 
ELSE SAFE_CAST(LEARAPNC AS STRING) 
 END as right_ankle_sbp_255_mm_hg, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_lower_extremity_disease_ankle_brachial_blood_pressure_index_examination') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/LEXAB_C.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/LEXAB_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/LEXABPI.htm
*/
