SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
    WHEN WTSCI2YR IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI2YR AS FLOAT64) 
 END as cidi_subsample_2_year_mec_weight, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIAORDER AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Panic, GAD, Depression' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIAORDER AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Depression, Panic, GAD' -- categorize numeric values
WHEN CIAORDER IS NULL THEN NULL 
ELSE SAFE_CAST(CIAORDER AS STRING) 
 END as order_in_which_cidi_modules_are_asked, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP01 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP01 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP01 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refuse' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP01 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP01 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP01 AS STRING) 
 END as entire_life_ever_fear_or_panic_attack, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP02 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP02 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP02 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refuse' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP02 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP02 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP02 AS STRING) 
 END as ever_attack_for_no_reason_out_of_blue, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP03 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP03 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP03 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refuse' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP03 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP03 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP03 AS STRING) 
 END as panic_attack_past_12_months, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP04 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP04 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP04 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refuse' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP04 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP04 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP04 AS STRING) 
 END as past_12_mos_avoided_situations_bc_fear, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP05 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Past Month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP05 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Past 6 Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP05 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Over 6 Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP05 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP05 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP05 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP05 AS STRING) 
 END as how_recently_avoided_situations_bc_fear, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP06 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP06 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP06 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP06 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP06 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP06 AS STRING) 
 END as past_12_mos_month_fear_another, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP07 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Past Month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP07 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Past 6 Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP07 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Over 6 Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP07 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP07 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP07 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP07 AS STRING) 
 END as how_recently_have_concern, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP08 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP08 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP08 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP08 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP08 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP08 AS STRING) 
 END as past_12_mos_attacks_lead_to_terrible, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP09 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Past Month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP09 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Past 6 Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP09 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Over 6 Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP09 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP09 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP09 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP09 AS STRING) 
 END as how_recently_have_concern_CIQP09, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP11 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP11 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP11 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP11 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP11 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP11 AS STRING) 
 END as ever_attacks_life_threatening, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP12 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP12 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP12 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP12 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP12 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP12 AS STRING) 
 END as ever_attacks_not_life_threatening, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13A IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13A AS STRING) 
 END as did_your_heart_pound_or_race, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13B IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13B AS STRING) 
 END as did_you_sweat, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13C IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13C AS STRING) 
 END as did_you_tremble_or_shake, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13D IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13D AS STRING) 
 END as did_you_have_dry_mouth, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13E IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13E AS STRING) 
 END as were_you_short_of_breath, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13F IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13F AS STRING) 
 END as feel_like_you_were_choking, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13G IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13G AS STRING) 
 END as pain_or_discomfort_in_chest, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13H AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13H AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13H AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13H AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13H IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13H AS STRING) 
 END as nausea_or_discomfort_in_stomach, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13I AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13I AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13I AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13I AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13I IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13I AS STRING) 
 END as were_you_dizzy_or_feeling_faint, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13J AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13J AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13J AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13J AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13J IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13J AS STRING) 
 END as did_you_feel_unreal, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13K AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13K AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13K AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13K AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13K IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13K AS STRING) 
 END as feel_things_around_you_unreal, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13L AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13L AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13L AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13L AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13L IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13L AS STRING) 
 END as afraid_you_might_lose_control, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13M AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13M AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13M AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13M AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13M IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13M AS STRING) 
 END as afraid_you_might_pass_out, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13N AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13N AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13N AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13N AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13N IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13N AS STRING) 
 END as afraid_you_might_die, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13O AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13O AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13O AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13O AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13O IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13O AS STRING) 
 END as have_hot_flashes_or_chills, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13P AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13P AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13P AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP13P AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP13P IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP13P AS STRING) 
 END as have_numbness_or_tingling, 

CASE
    WHEN CIQP14 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP14 AS FLOAT64) 
 END as no_attacks_w_symptoms_in_lifetime, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP15 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP15 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Sometimes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP15 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP15 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP15 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP15 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP15 AS STRING) 
 END as problems_began_suddenly_got_worse, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP16 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Past Month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP16 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Past 6 Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP16 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Over 6 Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP16 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP16 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP16 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP16 AS STRING) 
 END as when_did_attack_occur, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP17 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP17 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP17 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP17 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP17 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP17 AS STRING) 
 END as remember_age_when_attack_occurred, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP18 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7777 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP18 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9999 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP18 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP18 AS STRING) 
 END as exact_age_when_attack_occurred, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP19 AS FLOAT64),0) AS INT64) AS STRING) = '7777' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP19 AS FLOAT64),0) AS INT64) AS STRING) = '9999' THEN 'Dont know' -- categorize string values 
WHEN CIQP19 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP19 AS STRING) 
 END as approx_age_when_attack_occurred, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP20 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Out of the blue' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP20 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'A situation where R had an unreasonably' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP20 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'A situation of real danger' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP20 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7777 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP20 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9999 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP20 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP20 AS STRING) 
 END as which_of_three_situations_occurred, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21A AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Fear: Giving a speech' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21A AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21A AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN CIQP21A IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21A AS STRING) 
 END as fear_giving_a_speech, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21B AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Fear: Party or social event' -- categorize string values 
WHEN CIQP21B IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21B AS STRING) 
 END as fear_party_or_social_event, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21C AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Fear: Being in a crowd' -- categorize string values 
WHEN CIQP21C IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21C AS STRING) 
 END as fear_being_in_a_crowd, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21D AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'Fear: Meeting new people' -- categorize string values 
WHEN CIQP21D IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21D AS STRING) 
 END as fear_meeting_new_people, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21E AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'Fear: Being outside, away' -- categorize string values 
WHEN CIQP21E IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21E AS STRING) 
 END as fear_being_outside_away, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21F AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN 'Fear: Traveling bus, train, car' -- categorize string values 
WHEN CIQP21F IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21F AS STRING) 
 END as fear_traveling_bus_train_car, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21G AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Fear: Crowd, standing in line' -- categorize string values 
WHEN CIQP21G IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21G AS STRING) 
 END as fear_crowd_standing_in_line, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21H AS FLOAT64),0) AS INT64) AS STRING) = '8' THEN 'Fear: Being in a public place' -- categorize string values 
WHEN CIQP21H IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21H AS STRING) 
 END as fear_being_in_a_public_place, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21I AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Fear: Animals' -- categorize string values 
WHEN CIQP21I IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21I AS STRING) 
 END as fear_animals, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21J AS FLOAT64),0) AS INT64) AS STRING) = '10' THEN 'Fear: Heights' -- categorize string values 
WHEN CIQP21J IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21J AS STRING) 
 END as fear_heights, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21K AS FLOAT64),0) AS INT64) AS STRING) = '11' THEN 'Fear: Storms, thunder, lightening' -- categorize string values 
WHEN CIQP21K IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21K AS STRING) 
 END as fear_storms_thunder_lightening, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21L AS FLOAT64),0) AS INT64) AS STRING) = '12' THEN 'Fear: Flying' -- categorize string values 
WHEN CIQP21L IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21L AS STRING) 
 END as fear_flying, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21M AS FLOAT64),0) AS INT64) AS STRING) = '13' THEN 'Fear: Closed spaces' -- categorize string values 
WHEN CIQP21M IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21M AS STRING) 
 END as fear_closed_spaces, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21N AS FLOAT64),0) AS INT64) AS STRING) = '14' THEN 'Fear: Seeing blood' -- categorize string values 
WHEN CIQP21N IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21N AS STRING) 
 END as fear_seeing_blood, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21O AS FLOAT64),0) AS INT64) AS STRING) = '15' THEN 'Fear: Getting an injection' -- categorize string values 
WHEN CIQP21O IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21O AS STRING) 
 END as fear_getting_an_injection, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21P AS FLOAT64),0) AS INT64) AS STRING) = '16' THEN 'Fear: Going to the dentist' -- categorize string values 
WHEN CIQP21P IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21P AS STRING) 
 END as fear_going_to_the_dentist, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21Q AS FLOAT64),0) AS INT64) AS STRING) = '17' THEN 'Fear: Going to a hospital' -- categorize string values 
WHEN CIQP21Q IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21Q AS STRING) 
 END as fear_going_to_a_hospital, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP21R AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(18 AS FLOAT64),0) AS INT64) THEN 'Fear: Other 1' -- categorize numeric values
WHEN CIQP21R IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21R AS STRING) 
 END as fear_other_1, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21S AS FLOAT64),0) AS INT64) AS STRING) = '19' THEN 'Fear: Other 2' -- categorize string values 
WHEN CIQP21S IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21S AS STRING) 
 END as fear_other_2, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP21T AS FLOAT64),0) AS INT64) AS STRING) = '20' THEN 'Fear: Other 3' -- categorize string values 
WHEN CIQP21T IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP21T AS STRING) 
 END as fear_other_3, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP23 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP23 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP23 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP23 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP23 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP23 AS STRING) 
 END as exact_age_when_attack_occurred_CIQP23, 

CASE
    WHEN CIQP24 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP24 AS FLOAT64) 
 END as years_of_age_attack_occurred, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP25 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Past Month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP25 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Past 6 Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP25 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'More than 6 months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP25 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP25 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP25 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP25 AS STRING) 
 END as when_did_attack_occur_CIQP25, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP26 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Past 12 months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP26 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'More than 12 months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP26 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP26 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP26 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP26 AS STRING) 
 END as attack_in_past_12_months_or_more, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP27 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Past month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP27 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Past 6 months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP27 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'More than 6 months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP27 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP27 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP27 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP27 AS STRING) 
 END as when_did_attack_occur_CIQP27, 

CASE
    WHEN CIQP28 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP28 AS FLOAT64) 
 END as approx_age_when_attack_occurred_CIQP28, 

CASE
    WHEN CIQP29 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP29 AS FLOAT64) 
 END as earliest_age_attack_occurred, 

CASE
    WHEN CIQP31 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP31 AS FLOAT64) 
 END as age_last_time_had_attack, 

CASE
    WHEN CIQP32 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP32 AS FLOAT64) 
 END as no_attacks_lifetime_out_of_the_blue, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP33 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP33 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP33 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP33 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP33 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP33 AS STRING) 
 END as out_of_the_blue_attack_past_12_months, 

CASE
    WHEN CIQP34 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP34 AS FLOAT64) 
 END as no_attacks_past_12_months, 

CASE
    WHEN CIQP36 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP36 AS FLOAT64) 
 END as no_attacks_lifetime_strong_fear, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP37 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP37 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP37 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP37 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP37 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP37 AS STRING) 
 END as attack_in_past_12_months, 

CASE
    WHEN CIQP38 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP38 AS FLOAT64) 
 END as no_attacks_past_12_months_CIQP38, 

CASE
    WHEN CIQP40 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP40 AS FLOAT64) 
 END as no_attacks_lifetime_real_danger, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP41 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP41 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP41 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP41 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP41 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP41 AS STRING) 
 END as attack_in_past_12_months_CIQP41, 

CASE
    WHEN CIQP42 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP42 AS FLOAT64) 
 END as no_attacks_past_12_months_CIQP42, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: giving speech' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP44A IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44A AS STRING) 
 END as strong_fear_giving_a_speech, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Party or social event' -- categorize numeric values
WHEN CIQP44B IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44B AS STRING) 
 END as strong_fear_party_or_social_event, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Being in a crowd' -- categorize numeric values
WHEN CIQP44C IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44C AS STRING) 
 END as strong_fear_being_in_a_crowd, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Meeting new people' -- categorize numeric values
WHEN CIQP44D IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44D AS STRING) 
 END as strong_fear_meeting_new_people, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Being outside, away' -- categorize numeric values
WHEN CIQP44E IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44E AS STRING) 
 END as strong_fear_being_outside_away, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Traveling bus, train, car' -- categorize numeric values
WHEN CIQP44F IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44F AS STRING) 
 END as strong_fear_traveling_bus_train_car, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Crowd, standing in line' -- categorize numeric values
WHEN CIQP44G IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44G AS STRING) 
 END as strong_fear_crowd_standing_in_line, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44H AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Being in a public place' -- categorize numeric values
WHEN CIQP44H IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44H AS STRING) 
 END as strong_fear_being_in_a_public_place, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44I AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Animals' -- categorize numeric values
WHEN CIQP44I IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44I AS STRING) 
 END as strong_fear_animals, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44J AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Heights' -- categorize numeric values
WHEN CIQP44J IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44J AS STRING) 
 END as strong_fear_heights, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44K AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Storms, thunder, lightning' -- categorize numeric values
WHEN CIQP44K IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44K AS STRING) 
 END as strong_fear_storms_thunder_lightning, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44L AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Flying' -- categorize numeric values
WHEN CIQP44L IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44L AS STRING) 
 END as strong_fear_flying, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44M AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Closed spaces' -- categorize numeric values
WHEN CIQP44M IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44M AS STRING) 
 END as strong_fear_closed_spaces, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44N AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Seeing blood' -- categorize numeric values
WHEN CIQP44N IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44N AS STRING) 
 END as strong_fear_seeing_blood, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44O AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Getting an injection' -- categorize numeric values
WHEN CIQP44O IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44O AS STRING) 
 END as strong_fear_getting_an_injection, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44P AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(16 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Going to the dentist' -- categorize numeric values
WHEN CIQP44P IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44P AS STRING) 
 END as strong_fear_going_to_the_dentist, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44Q AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(17 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Going to a hospital' -- categorize numeric values
WHEN CIQP44Q IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44Q AS STRING) 
 END as strong_fear_going_to_a_hospital, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44R AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(18 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Other 1' -- categorize numeric values
WHEN CIQP44R IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44R AS STRING) 
 END as strong_fear_other_1, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP44S AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(19 AS FLOAT64),0) AS INT64) THEN 'Strong Fear: Other 2' -- categorize numeric values
WHEN CIQP44S IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44S AS STRING) 
 END as strong_fear_other_2, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQP44T AS FLOAT64),0) AS INT64) AS STRING) = '20' THEN 'Strong Fear: Other 3' -- categorize string values 
WHEN CIQP44T IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP44T AS STRING) 
 END as strong_fear_other_3, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP49 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Past Month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP49 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Past 6 Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP49 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Over 6 Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP49 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP49 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP49 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP49 AS STRING) 
 END as recency_of_fear_or_out_of_the_blue, 

CASE
    WHEN CIQP50 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP50 AS FLOAT64) 
 END as past_12_months_no_weeks_attack, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP51 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'All in a row' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP51 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '2 or more periods' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP51 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP51 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP51 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP51 AS STRING) 
 END as single_period_or_two_periods, 

CASE
    WHEN CIQP52 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP52 AS FLOAT64) 
 END as longest_no_weeks_in_row_attack, 

CASE
    WHEN CIQP54 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP54 AS FLOAT64) 
 END as largest_no_attacks_any_one_week, 

CASE
    WHEN CIQP55 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP55 AS FLOAT64) 
 END as largest_no_attack_any_four_weeks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP57 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP57 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP57 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP57 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP57 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP57 AS STRING) 
 END as four_week_in_row_and_four_attacks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP58 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP58 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN CIQP58 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP58 AS STRING) 
 END as did_you_tell_doctor_about_attack, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPA AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPA AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPA AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPA AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQPPA IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPA AS STRING) 
 END as did_you_tell_other_prof_about_attack, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPB AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPB AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPB AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPB AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQPPB IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPB AS STRING) 
 END as did_you_take_medication_for_attack, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQPPC IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPC AS STRING) 
 END as did_attacks_interfere_with_life, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQPPD IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPD AS STRING) 
 END as were_attacks_result_of_phys_illness, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPE AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPE AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPE AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPE AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQPPE IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPE AS STRING) 
 END as were_attacks_result_of_mda, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQPPF AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQPPF AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQPPF AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQPPF AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN CIQPPF IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPF AS STRING) 
 END as were_attacks_always_result_mda, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPHA AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Doctor said nerves causing attacks' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPHA AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPHA AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQPPHA IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPHA AS STRING) 
 END as doctor_said_nerves_causing_attacks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPHB AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Doctor said stress causing attacks' -- categorize numeric values
WHEN CIQPPHB IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPHB AS STRING) 
 END as doctor_said_stress_causing_attacks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPHC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Doctor said anxiety causing attacks' -- categorize numeric values
WHEN CIQPPHC IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPHC AS STRING) 
 END as doctor_said_anxiety_causing_attacks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPHD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Doctor said depression causing attacks' -- categorize numeric values
WHEN CIQPPHD IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPHD AS STRING) 
 END as doctor_said_depression_causing_attacks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPHE AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Doc said mental illness causing attacks' -- categorize numeric values
WHEN CIQPPHE IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPHE AS STRING) 
 END as doc_said_mental_illness_causing_attacks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPHF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Doctor said medication causing attacks' -- categorize numeric values
WHEN CIQPPHF IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPHF AS STRING) 
 END as doctor_said_medication_causing_attacks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPHG AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Doctor said drugs causing attacks' -- categorize numeric values
WHEN CIQPPHG IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPHG AS STRING) 
 END as doctor_said_drugs_causing_attacks, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQPPHH AS FLOAT64),0) AS INT64) AS STRING) = '8' THEN 'Doctor said alcohol causing attacks' -- categorize string values 
WHEN CIQPPHH IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPHH AS STRING) 
 END as doctor_said_alcohol_causing_attacks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPHI AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Doctor said phys illness causing attacks' -- categorize numeric values
WHEN CIQPPHI IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPHI AS STRING) 
 END as doctor_said_phys_illness_causing_attacks, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(CIQPPHJ AS FLOAT64),0) AS INT64) AS STRING) = '10' THEN 'Doctor said phys injury causing attacks' -- categorize string values 
WHEN CIQPPHJ IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPHJ AS STRING) 
 END as doctor_said_phys_injury_causing_attacks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPHK AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Doctor gave no definite diagnosis for attacks' -- categorize numeric values
WHEN CIQPPHK IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPHK AS STRING) 
 END as doctor_gave_no_definite_diag_for_attacks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPJ AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPJ AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPJ AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPJ AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQPPJ IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPJ AS STRING) 
 END as were_attacks_always_result_mda_CIQPPJ, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPK AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPK AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPK AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPK AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQPPK IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPK AS STRING) 
 END as were_attacks_result_of_phys_illness_CIQPPK, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPQ AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Nothing abnormal' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPQ AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No examination' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPQ AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Something abnormal' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPQ AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPQ AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQPPQ IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPQ AS STRING) 
 END as anything_abnormal_when_exam, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQPPN IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPN AS STRING) 
 END as were_attacks_always_result_phys_ill, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPO AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPO AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPO AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQPPO AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQPPO IS NULL THEN NULL 
ELSE SAFE_CAST(CIQPPO AS STRING) 
 END as were_attacks_always_result_mda_CIQPPO, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIDPPRB AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'No Problem' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIDPPRB AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Not clinically significant' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIDPPRB AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Medication, Drugs, or Alcohol' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIDPPRB AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Physical cause' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIDPPRB AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Psychiatric Symptom' -- categorize numeric values
WHEN CIDPPRB IS NULL THEN NULL 
ELSE SAFE_CAST(CIDPPRB AS STRING) 
 END as general_cause_of_problem, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'A lot' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Some' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'A little' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Not at all' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP59 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP59 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP59 AS STRING) 
 END as attacks_interfere_with_daily_life, 

CASE
    WHEN CIQP60 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP60 AS FLOAT64) 
 END as no_days_totally_unable_work, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP61 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP61 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP61 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP61 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP61 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP61 AS STRING) 
 END as did_totally_occur_past_4_weeks, 

CASE
    WHEN CIQP62 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP62 AS FLOAT64) 
 END as no_days_totally_past_4_weeks, 

CASE
    WHEN CIQP63 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP63 AS FLOAT64) 
 END as no_days_cutback_amount_quality, 

CASE
    WHEN CIQP64 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP64 AS FLOAT64) 
 END as describe_quantity_quality_cutback, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP65 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP65 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP65 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP65 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP65 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP65 AS STRING) 
 END as did_cutback_occur_past_4_weeks, 

CASE
    WHEN CIQP66 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP66 AS FLOAT64) 
 END as no_days_cutback_past_4_weeks, 

CASE
    WHEN CIQP67 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP67 AS FLOAT64) 
 END as no_days_extreme_effort_to_work, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP68 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP68 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP68 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP68 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP68 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP68 AS STRING) 
 END as did_extreme_occur_past_4_weeks, 

CASE
    WHEN CIQP69 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP69 AS FLOAT64) 
 END as no_days_extreme_past_4_weeks, 

CASE
    WHEN CIQP70 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP70 AS FLOAT64) 
 END as no_days_interfere_personal_life, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP71 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP71 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP71 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIQP71 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN CIQP71 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP71 AS STRING) 
 END as did_interfere_occur_past_4_weeks, 

CASE
    WHEN CIQP72 IS NULL THEN NULL 
ELSE SAFE_CAST(CIQP72 AS FLOAT64) 
 END as no_days_interfere_past_4_weeks, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(CIDPSCOR AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Positive Diagnosis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(CIDPSCOR AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Negative Diagnosis' -- categorize numeric values
WHEN CIDPSCOR IS NULL THEN NULL 
ELSE SAFE_CAST(CIDPSCOR AS STRING) 
 END as panic_score, 

CASE
    WHEN WTSCI4YR IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI4YR AS FLOAT64) 
 END as cidi_subsample_4_year_mec_weight, 

CASE
    WHEN WTSCI01 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI01 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_1, 

CASE
    WHEN WTSCI02 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI02 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_2, 

CASE
    WHEN WTSCI03 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI03 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_3, 

CASE
    WHEN WTSCI04 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI04 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_4, 

CASE
    WHEN WTSCI05 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI05 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_5, 

CASE
    WHEN WTSCI06 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI06 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_6, 

CASE
    WHEN WTSCI07 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI07 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_7, 

CASE
    WHEN WTSCI08 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI08 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_8, 

CASE
    WHEN WTSCI09 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI09 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_9, 

CASE
    WHEN WTSCI10 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI10 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_10, 

CASE
    WHEN WTSCI11 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI11 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_11, 

CASE
    WHEN WTSCI12 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI12 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_12, 

CASE
    WHEN WTSCI13 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI13 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_13, 

CASE
    WHEN WTSCI14 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI14 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_14, 

CASE
    WHEN WTSCI15 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI15 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_15, 

CASE
    WHEN WTSCI16 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI16 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_16, 

CASE
    WHEN WTSCI17 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI17 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_17, 

CASE
    WHEN WTSCI18 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI18 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_18, 

CASE
    WHEN WTSCI19 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI19 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_19, 

CASE
    WHEN WTSCI20 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI20 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_20, 

CASE
    WHEN WTSCI21 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI21 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_21, 

CASE
    WHEN WTSCI22 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI22 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_22, 

CASE
    WHEN WTSCI23 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI23 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_23, 

CASE
    WHEN WTSCI24 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI24 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_24, 

CASE
    WHEN WTSCI25 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI25 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_25, 

CASE
    WHEN WTSCI26 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI26 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_26, 

CASE
    WHEN WTSCI27 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI27 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_27, 

CASE
    WHEN WTSCI28 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI28 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_28, 

CASE
    WHEN WTSCI29 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI29 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_29, 

CASE
    WHEN WTSCI30 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI30 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_30, 

CASE
    WHEN WTSCI31 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI31 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_31, 

CASE
    WHEN WTSCI32 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI32 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_32, 

CASE
    WHEN WTSCI33 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI33 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_33, 

CASE
    WHEN WTSCI34 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI34 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_34, 

CASE
    WHEN WTSCI35 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI35 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_35, 

CASE
    WHEN WTSCI36 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI36 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_36, 

CASE
    WHEN WTSCI37 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI37 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_37, 

CASE
    WHEN WTSCI38 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI38 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_38, 

CASE
    WHEN WTSCI39 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI39 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_39, 

CASE
    WHEN WTSCI40 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI40 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_40, 

CASE
    WHEN WTSCI41 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI41 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_41, 

CASE
    WHEN WTSCI42 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI42 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_42, 

CASE
    WHEN WTSCI43 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI43 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_43, 

CASE
    WHEN WTSCI44 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI44 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_44, 

CASE
    WHEN WTSCI45 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI45 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_45, 

CASE
    WHEN WTSCI46 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI46 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_46, 

CASE
    WHEN WTSCI47 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI47 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_47, 

CASE
    WHEN WTSCI48 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI48 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_48, 

CASE
    WHEN WTSCI49 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI49 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_49, 

CASE
    WHEN WTSCI50 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI50 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_50, 

CASE
    WHEN WTSCI51 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI51 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_51, 

CASE
    WHEN WTSCI52 IS NULL THEN NULL 
ELSE SAFE_CAST(WTSCI52 AS FLOAT64) 
 END as cidi_mec_weight_jack_knife_rep_52, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_mental_health_panic_disorder_questionnaire') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/CIQPAN_C.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/CIQPAN_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/CIQPANIC.htm
*/
