SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ010 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MPQ010 IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ010 AS STRING) 
 END as joint_pain_aching_stiffness_in_past_year, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MPQ020 IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ020 AS STRING) 
 END as symptoms_present_for_most_of_month, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MPQ030 IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ030 AS STRING) 
 END as symptoms_begin_only_because_of_injury, 

CASE
    WHEN MPD040 IS NULL THEN NULL 
ELSE SAFE_CAST(MPD040 AS FLOAT64) 
 END as weeks_have_joint_pain_symptoms, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Shoulder - right' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MPD050A IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050A AS STRING) 
 END as right_shoulder_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Shoulder - left' -- categorize numeric values
WHEN MPD050B IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050B AS STRING) 
 END as left_shoulder_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Elbow - right' -- categorize numeric values
WHEN MPD050C IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050C AS STRING) 
 END as right_elbow_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'Elbow - left' -- categorize numeric values
WHEN MPD050D IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050D AS STRING) 
 END as left_elbow_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Hip - right' -- categorize numeric values
WHEN MPD050E IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050E AS STRING) 
 END as right_hip_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Hip - left' -- categorize numeric values
WHEN MPD050F IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050F AS STRING) 
 END as left_hip_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(16 AS FLOAT64),0) AS INT64) THEN 'Wrist - right' -- categorize numeric values
WHEN MPD050G IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050G AS STRING) 
 END as right_wrist_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050H AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(17 AS FLOAT64),0) AS INT64) THEN 'Wrist - left' -- categorize numeric values
WHEN MPD050H IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050H AS STRING) 
 END as left_wrist_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050I AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(18 AS FLOAT64),0) AS INT64) THEN 'Knee - right' -- categorize numeric values
WHEN MPD050I IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050I AS STRING) 
 END as right_knee_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050J AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(19 AS FLOAT64),0) AS INT64) THEN 'Knee - left' -- categorize numeric values
WHEN MPD050J IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050J AS STRING) 
 END as left_knee_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050K AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(20 AS FLOAT64),0) AS INT64) THEN 'Ankle - right' -- categorize numeric values
WHEN MPD050K IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050K AS STRING) 
 END as right_ankle_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050L AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(21 AS FLOAT64),0) AS INT64) THEN 'Ankle - left' -- categorize numeric values
WHEN MPD050L IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050L AS STRING) 
 END as left_ankle_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050M AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(22 AS FLOAT64),0) AS INT64) THEN 'Toes - right' -- categorize numeric values
WHEN MPD050M IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050M AS STRING) 
 END as right_toes_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050N AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(23 AS FLOAT64),0) AS INT64) THEN 'Toes - left' -- categorize numeric values
WHEN MPD050N IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050N AS STRING) 
 END as left_toes_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050O AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(24 AS FLOAT64),0) AS INT64) THEN 'Fingers/thumb - right' -- categorize numeric values
WHEN MPD050O IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050O AS STRING) 
 END as right_fingers_thumb_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050P AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(25 AS FLOAT64),0) AS INT64) THEN 'Fingers/thumb - left' -- categorize numeric values
WHEN MPD050P IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050P AS STRING) 
 END as left_fingers_thumb_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MPQ060 IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ060 AS STRING) 
 END as neck_pain_over_last_three_months, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MPQ070 IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ070 AS STRING) 
 END as low_back_pain, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MPQ080 IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ080 AS STRING) 
 END as pain_down_either_leg_below_knee, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MPQ090 IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ090 AS STRING) 
 END as severe_headaches_or_migraines, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MPQ100 IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ100 AS STRING) 
 END as pain_problem_lasting_more_than_24_hrs, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Less than a month,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'At least 1 month but less than 3 months,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'At least 3 months but less than 1 year, or' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Greater than 1 year?' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MPQ110 IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ110 AS STRING) 
 END as how_long_experience_this_pain, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Head' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MPQ120A IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120A AS STRING) 
 END as head_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Face/dental' -- categorize numeric values
WHEN MPQ120B IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120B AS STRING) 
 END as face_dental_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Shoulder girdle - right' -- categorize numeric values
WHEN MPQ120C IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120C AS STRING) 
 END as right_shoulder_girdle_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'Shoulder girdle - left' -- categorize numeric values
WHEN MPQ120D IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120D AS STRING) 
 END as left_shoulder_girdle_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Upper arm - right' -- categorize numeric values
WHEN MPQ120E IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120E AS STRING) 
 END as right_upper_arm_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Upper arm - left' -- categorize numeric values
WHEN MPQ120F IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120F AS STRING) 
 END as left_upper_arm_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(16 AS FLOAT64),0) AS INT64) THEN 'Mid-arm - right' -- categorize numeric values
WHEN MPQ120G IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120G AS STRING) 
 END as right_mid_arm_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120H AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(17 AS FLOAT64),0) AS INT64) THEN 'Mid-arm - left' -- categorize numeric values
WHEN MPQ120H IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120H AS STRING) 
 END as left_mid_arm_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120I AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(18 AS FLOAT64),0) AS INT64) THEN 'Lower arm - right' -- categorize numeric values
WHEN MPQ120I IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120I AS STRING) 
 END as right_lower_arm_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120J AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(19 AS FLOAT64),0) AS INT64) THEN 'Lower arm - left' -- categorize numeric values
WHEN MPQ120J IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120J AS STRING) 
 END as left_lower_arm_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120K AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(20 AS FLOAT64),0) AS INT64) THEN 'Upper back - right' -- categorize numeric values
WHEN MPQ120K IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120K AS STRING) 
 END as right_upper_back_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120L AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(21 AS FLOAT64),0) AS INT64) THEN 'Upper back - left' -- categorize numeric values
WHEN MPQ120L IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120L AS STRING) 
 END as left_upper_back_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120M AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(22 AS FLOAT64),0) AS INT64) THEN 'Lower back - right' -- categorize numeric values
WHEN MPQ120M IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120M AS STRING) 
 END as right_lower_back_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120N AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(23 AS FLOAT64),0) AS INT64) THEN 'Lower back - left' -- categorize numeric values
WHEN MPQ120N IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120N AS STRING) 
 END as left_lower_back_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120O AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(24 AS FLOAT64),0) AS INT64) THEN 'Buttocks - right' -- categorize numeric values
WHEN MPQ120O IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120O AS STRING) 
 END as right_buttock_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120P AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(25 AS FLOAT64),0) AS INT64) THEN 'Buttocks - left' -- categorize numeric values
WHEN MPQ120P IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120P AS STRING) 
 END as left_buttock_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120Q AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(26 AS FLOAT64),0) AS INT64) THEN 'Upper leg - right' -- categorize numeric values
WHEN MPQ120Q IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120Q AS STRING) 
 END as right_upper_leg_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120R AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(27 AS FLOAT64),0) AS INT64) THEN 'Upper leg - left' -- categorize numeric values
WHEN MPQ120R IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120R AS STRING) 
 END as left_upper_leg_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120S AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(28 AS FLOAT64),0) AS INT64) THEN 'Mid-leg - right' -- categorize numeric values
WHEN MPQ120S IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120S AS STRING) 
 END as right_mid_leg_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120T AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(29 AS FLOAT64),0) AS INT64) THEN 'Mid-leg - left' -- categorize numeric values
WHEN MPQ120T IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120T AS STRING) 
 END as left_mid_leg_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(30 AS FLOAT64),0) AS INT64) THEN 'Lower leg - right' -- categorize numeric values
WHEN MPQ120U IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120U AS STRING) 
 END as right_lower_leg_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120V AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(31 AS FLOAT64),0) AS INT64) THEN 'Lower leg - left' -- categorize numeric values
WHEN MPQ120V IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120V AS STRING) 
 END as left_lower_leg_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120W AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(32 AS FLOAT64),0) AS INT64) THEN 'Neck' -- categorize numeric values
WHEN MPQ120W IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120W AS STRING) 
 END as neck_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120X AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(33 AS FLOAT64),0) AS INT64) THEN 'Sternum' -- categorize numeric values
WHEN MPQ120X IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120X AS STRING) 
 END as sternum_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120Y AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(34 AS FLOAT64),0) AS INT64) THEN 'Chest - right' -- categorize numeric values
WHEN MPQ120Y IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120Y AS STRING) 
 END as right_chest_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120Z AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(35 AS FLOAT64),0) AS INT64) THEN 'Chest - left' -- categorize numeric values
WHEN MPQ120Z IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120Z AS STRING) 
 END as left_chest_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120AA AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(36 AS FLOAT64),0) AS INT64) THEN 'Abdomen' -- categorize numeric values
WHEN MPQ120AA IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120AA AS STRING) 
 END as abdomen_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120AB AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(37 AS FLOAT64),0) AS INT64) THEN 'Spine' -- categorize numeric values
WHEN MPQ120AB IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120AB AS STRING) 
 END as spine_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120AC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(38 AS FLOAT64),0) AS INT64) THEN 'Hand - right' -- categorize numeric values
WHEN MPQ120AC IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120AC AS STRING) 
 END as right_hand_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120AD AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(39 AS FLOAT64),0) AS INT64) THEN 'Hand - left' -- categorize numeric values
WHEN MPQ120AD IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120AD AS STRING) 
 END as left_hand_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120AE AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(40 AS FLOAT64),0) AS INT64) THEN 'Foot - right' -- categorize numeric values
WHEN MPQ120AE IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120AE AS STRING) 
 END as right_foot_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPQ120AF AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(41 AS FLOAT64),0) AS INT64) THEN 'Foot - left' -- categorize numeric values
WHEN MPQ120AF IS NULL THEN NULL 
ELSE SAFE_CAST(MPQ120AF AS STRING) 
 END as left_foot_affected, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(MPD050Q AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(26 AS FLOAT64),0) AS INT64) THEN 'Other(specify)' -- categorize numeric values
WHEN MPD050Q IS NULL THEN NULL 
ELSE SAFE_CAST(MPD050Q AS STRING) 
 END as other_joints_affected, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_miscellaneous_pain_questionnaire') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/MPQ_C.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/MPQ_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/MPQ.htm
*/
