SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGDEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Completed test on both hands' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGDEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Completed test on only one hand' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGDEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Did not perform test' -- categorize numeric values
WHEN MGDEXSTS IS NULL THEN NULL 
ELSE SAFE_CAST(MGDEXSTS AS STRING) 
 END as grip_test_status, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MGD050 IS NULL THEN NULL 
ELSE SAFE_CAST(MGD050 AS STRING) 
 END as ever_had_surgery_on_hands_or_wrists, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Right hand/wrist' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Left hand/wrist' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Both hands/wrists' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD060 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MGD060 IS NULL THEN NULL 
ELSE SAFE_CAST(MGD060 AS STRING) 
 END as which_hand_or_wrist_had_surgery, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MGQ070 IS NULL THEN NULL 
ELSE SAFE_CAST(MGQ070 AS STRING) 
 END as recent_pain_aching_stiffness_right_hand, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ080 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MGQ080 IS NULL THEN NULL 
ELSE SAFE_CAST(MGQ080 AS STRING) 
 END as cause_of_recent_pain_in_right_hand, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MGQ090 IS NULL THEN NULL 
ELSE SAFE_CAST(MGQ090 AS STRING) 
 END as pain_in_right_hand_gotten_worse_recently, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MGQ100 IS NULL THEN NULL 
ELSE SAFE_CAST(MGQ100 AS STRING) 
 END as recent_pain_aching_stiffness_left_hand, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MGQ110 IS NULL THEN NULL 
ELSE SAFE_CAST(MGQ110 AS STRING) 
 END as cause_of_recent_pain_in_left_hand, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ120 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ120 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ120 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ120 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MGQ120 IS NULL THEN NULL 
ELSE SAFE_CAST(MGQ120 AS STRING) 
 END as pain_in_left_hand_gotten_worse_recently, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD130 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Right-handed' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD130 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Left-handed' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD130 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Use both hands equally' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD130 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGD130 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN MGD130 IS NULL THEN NULL 
ELSE SAFE_CAST(MGD130 AS STRING) 
 END as dominant_hand, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ90DG AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ90DG AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No - Not right hand' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ90DG AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'No - Not left hand' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGQ90DG AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'No - Not either hand' -- categorize numeric values
WHEN MGQ90DG IS NULL THEN NULL 
ELSE SAFE_CAST(MGQ90DG AS STRING) 
 END as exa_90_degree_angle_with_index_finger, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGDSEAT AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Standing' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGDSEAT AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Seated' -- categorize numeric values
WHEN MGDSEAT IS NULL THEN NULL 
ELSE SAFE_CAST(MGDSEAT AS STRING) 
 END as testing_position, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGAPHAND AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Right' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGAPHAND AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Left' -- categorize numeric values
WHEN MGAPHAND IS NULL THEN NULL 
ELSE SAFE_CAST(MGAPHAND AS STRING) 
 END as hand_assigned_for_practice_trial, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGATHAND AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Right' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGATHAND AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Left' -- categorize numeric values
WHEN MGATHAND IS NULL THEN NULL 
ELSE SAFE_CAST(MGATHAND AS STRING) 
 END as begin_the_test_with_this_hand, 

CASE
WHEN MGXH1T1 IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH1T1 AS FLOAT64) 
 END as grip_strength_kg_hand_1_test_1, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH1T1E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Maximal' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH1T1E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Questionable' -- categorize numeric values
WHEN MGXH1T1E IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH1T1E AS STRING) 
 END as grip_strength_hand_1_test_1_effort, 

CASE
WHEN MGXH2T1 IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH2T1 AS FLOAT64) 
 END as grip_strength_kg_hand_2_test_1, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH2T1E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Maximal' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH2T1E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Questionable' -- categorize numeric values
WHEN MGXH2T1E IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH2T1E AS STRING) 
 END as grip_strength_hand_2_test_1_effort, 

CASE
WHEN MGXH1T2 IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH1T2 AS FLOAT64) 
 END as grip_strength_kg_hand_1_test_2, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH1T2E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Maximal' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH1T2E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Questionable' -- categorize numeric values
WHEN MGXH1T2E IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH1T2E AS STRING) 
 END as grip_strength_hand_1_test_2_effort, 

CASE
WHEN MGXH2T2 IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH2T2 AS FLOAT64) 
 END as grip_strength_kg_hand_2_test_2, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH2T2E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Maximal' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH2T2E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Questionable' -- categorize numeric values
WHEN MGXH2T2E IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH2T2E AS STRING) 
 END as grip_strength_hand_2_test_2_effort, 

CASE
WHEN MGXH1T3 IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH1T3 AS FLOAT64) 
 END as grip_strength_kg_hand_1_test_3, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH1T3E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Maximal' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH1T3E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Questionable' -- categorize numeric values
WHEN MGXH1T3E IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH1T3E AS STRING) 
 END as grip_strength_hand_1_test_3_effort, 

CASE
WHEN MGXH2T3 IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH2T3 AS FLOAT64) 
 END as grip_strength_kg_hand_2_test_3, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH2T3E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Maximal' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(MGXH2T3E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Questionable' -- categorize numeric values
WHEN MGXH2T3E IS NULL THEN NULL 
ELSE SAFE_CAST(MGXH2T3E AS STRING) 
 END as grip_strength_hand_2_test_3_effort, 

CASE
WHEN MGDCGSZ IS NULL THEN NULL 
ELSE SAFE_CAST(MGDCGSZ AS FLOAT64) 
 END as combined_grip_strength_kg, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_muscle_strength_grip_test_examination') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/MGX_H.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/MGX_G.htm
*/
