SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(OHDEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Complete' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHDEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Partial' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHDEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not done' -- categorize numeric values
WHEN OHDEXSTS IS NULL THEN NULL 
ELSE SAFE_CAST(OHDEXSTS AS STRING) 
 END as overall_oral_health_exam_status, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(OHDPDSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Complete' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHDPDSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Partial' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHDPDSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not Done' -- categorize numeric values
WHEN OHDPDSTS IS NULL THEN NULL 
ELSE SAFE_CAST(OHDPDSTS AS STRING) 
 END as periodontal_status_code, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(OHDEXCLU AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHDEXCLU AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN OHDEXCLU IS NULL THEN NULL 
ELSE SAFE_CAST(OHDEXCLU AS STRING) 
 END as medical_exclusion_from_periodontal_exam, 

CASE
    WHEN OHX02CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02CJD AS FLOAT64) 
 END as loa_max_r_2m_df_fgm_cej_mm, 

CASE
    WHEN OHX02CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02CJM AS FLOAT64) 
 END as loa_max_r_2m_mdf_fgm_cej_mm, 

CASE
    WHEN OHX02CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02CJS AS FLOAT64) 
 END as loa_max_r_2m_mf_fgm_cej_mm, 

CASE
    WHEN OHX02CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02CJP AS FLOAT64) 
 END as loa_max_r_2m_dl_fgm_cej_mm, 

CASE
    WHEN OHX02CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02CJL AS FLOAT64) 
 END as loa_max_r_2m_mdl_fgm_cej_mm, 

CASE
    WHEN OHX02CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02CJA AS FLOAT64) 
 END as loa_max_r_2m_ml_fgm_cej_mm, 

CASE
    WHEN OHX02PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02PCD AS FLOAT64) 
 END as loa_max_r_2m_df_fgm_sulcus_mm, 

CASE
    WHEN OHX02PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02PCM AS FLOAT64) 
 END as loa_max_r_2m_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX02PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02PCS AS FLOAT64) 
 END as loa_max_r_2m_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX02PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02PCP AS FLOAT64) 
 END as loa_max_r_2m_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX02PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02PCL AS FLOAT64) 
 END as loa_max_r_2m_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX02PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02PCA AS FLOAT64) 
 END as loa_max_r_2m_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX02LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02LAD AS FLOAT64) 
 END as loa_max_r_2m_df_calculated_al_mm, 

CASE
    WHEN OHX02LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02LAM AS FLOAT64) 
 END as loa_max_r_2m_mdf_calculated_al_mm, 

CASE
    WHEN OHX02LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02LAS AS FLOAT64) 
 END as loa_max_r_2m_mf_calculated_al_mm, 

CASE
    WHEN OHX02LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02LAP AS FLOAT64) 
 END as loa_max_r_2m_dl_calculated_al_mm, 

CASE
    WHEN OHX02LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02LAL AS FLOAT64) 
 END as loa_max_r_2m_mdl_calculated_al_mm, 

CASE
    WHEN OHX02LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02LAA AS FLOAT64) 
 END as loa_max_r_2m_ml_calculated_al_mm, 

CASE
    WHEN OHX03CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03CJD AS FLOAT64) 
 END as loa_max_r_1m_df_fgm_cej_mm, 

CASE
    WHEN OHX03CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03CJM AS FLOAT64) 
 END as loa_max_r_1m_mdf_fgm_cej_mm, 

CASE
    WHEN OHX03CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03CJS AS FLOAT64) 
 END as loa_max_r_1m_mf_fgm_cej_mm, 

CASE
    WHEN OHX03CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03CJP AS FLOAT64) 
 END as loa_max_r_1m_dl_fgm_cej_mm, 

CASE
    WHEN OHX03CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03CJL AS FLOAT64) 
 END as loa_max_r_1m_mdl_fgm_cej_mm, 

CASE
    WHEN OHX03CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03CJA AS FLOAT64) 
 END as loa_max_r_1m_ml_fgm_cej_mm, 

CASE
    WHEN OHX03PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03PCD AS FLOAT64) 
 END as loa_max_r_1m_df_fgm_sulcus_mm, 

CASE
    WHEN OHX03PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03PCM AS FLOAT64) 
 END as loa_max_r_1m_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX03PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03PCS AS FLOAT64) 
 END as loa_max_r_1m_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX03PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03PCP AS FLOAT64) 
 END as loa_max_r_1m_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX03PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03PCL AS FLOAT64) 
 END as loa_max_r_1m_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX03PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03PCA AS FLOAT64) 
 END as loa_max_r_1m_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX03LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03LAD AS FLOAT64) 
 END as loa_max_r_1m_df_calculated_al_mm, 

CASE
    WHEN OHX03LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03LAM AS FLOAT64) 
 END as loa_max_r_1m_mdf_calculated_al_mm, 

CASE
    WHEN OHX03LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03LAS AS FLOAT64) 
 END as loa_max_r_1m_mf_calculated_al_mm, 

CASE
    WHEN OHX03LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03LAP AS FLOAT64) 
 END as loa_max_r_1m_dl_calculated_al_mm, 

CASE
    WHEN OHX03LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03LAL AS FLOAT64) 
 END as loa_max_r_1m_mdl_calculated_al_mm, 

CASE
    WHEN OHX03LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03LAA AS FLOAT64) 
 END as loa_max_r_1m_ml_calculated_al_mm, 

CASE
    WHEN OHX04CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04CJD AS FLOAT64) 
 END as loa_max_r_2b_df_fgm_cej_mm, 

CASE
    WHEN OHX04CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04CJM AS FLOAT64) 
 END as loa_max_r_2b_mdf_fgm_cej_mm, 

CASE
    WHEN OHX04CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04CJS AS FLOAT64) 
 END as loa_max_r_2b_mf_fgm_cej_mm, 

CASE
    WHEN OHX04CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04CJP AS FLOAT64) 
 END as loa_max_r_2b_dl_fgm_cej_mm, 

CASE
    WHEN OHX04CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04CJL AS FLOAT64) 
 END as loa_max_r_2b_mdl_fgm_cej_mm, 

CASE
    WHEN OHX04CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04CJA AS FLOAT64) 
 END as loa_max_r_2b_ml_fgm_cej_mm, 

CASE
    WHEN OHX04PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04PCD AS FLOAT64) 
 END as loa_max_r_2b_df_fgm_sulcus_mm, 

CASE
    WHEN OHX04PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04PCM AS FLOAT64) 
 END as loa_max_r_2b_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX04PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04PCS AS FLOAT64) 
 END as loa_max_r_2b_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX04PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04PCP AS FLOAT64) 
 END as loa_max_r_2b_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX04PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04PCL AS FLOAT64) 
 END as loa_max_r_2b_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX04PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04PCA AS FLOAT64) 
 END as loa_max_r_2b_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX04LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04LAD AS FLOAT64) 
 END as loa_max_r_2b_df_calculated_al_mm, 

CASE
    WHEN OHX04LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04LAM AS FLOAT64) 
 END as loa_max_r_2b_mdf_calculated_al_mm, 

CASE
    WHEN OHX04LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04LAS AS FLOAT64) 
 END as loa_max_r_2b_mf_calculated_al_mm, 

CASE
    WHEN OHX04LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04LAP AS FLOAT64) 
 END as loa_max_r_2b_dl_calculated_al_mm, 

CASE
    WHEN OHX04LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04LAL AS FLOAT64) 
 END as loa_max_r_2b_mdl_calculated_al_mm, 

CASE
    WHEN OHX04LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04LAA AS FLOAT64) 
 END as loa_max_r_2b_ml_calculated_al_mm, 

CASE
    WHEN OHX05CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05CJD AS FLOAT64) 
 END as loa_max_r_1b_df_fgm_cej_mm, 

CASE
    WHEN OHX05CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05CJM AS FLOAT64) 
 END as loa_max_r_1b_mdf_fgm_cej_mm, 

CASE
    WHEN OHX05CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05CJS AS FLOAT64) 
 END as loa_max_r_1b_mf_fgm_cej_mm, 

CASE
    WHEN OHX05CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05CJP AS FLOAT64) 
 END as loa_max_r_1b_dl_fgm_cej_mm, 

CASE
    WHEN OHX05CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05CJL AS FLOAT64) 
 END as loa_max_r_1b_mdl_fgm_cej_mm, 

CASE
    WHEN OHX05CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05CJA AS FLOAT64) 
 END as loa_max_r_1b_ml_fgm_cej_mm, 

CASE
    WHEN OHX05PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05PCD AS FLOAT64) 
 END as loa_max_r_1b_df_fgm_sulcus_mm, 

CASE
    WHEN OHX05PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05PCM AS FLOAT64) 
 END as loa_max_r_1b_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX05PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05PCS AS FLOAT64) 
 END as loa_max_r_1b_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX05PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05PCP AS FLOAT64) 
 END as loa_max_r_1b_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX05PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05PCL AS FLOAT64) 
 END as loa_max_r_1b_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX05PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05PCA AS FLOAT64) 
 END as loa_max_r_1b_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX05LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05LAD AS FLOAT64) 
 END as loa_max_r_1b_df_calculated_al_mm, 

CASE
    WHEN OHX05LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05LAM AS FLOAT64) 
 END as loa_max_r_1b_mdf_calculated_al_mm, 

CASE
    WHEN OHX05LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05LAS AS FLOAT64) 
 END as loa_max_r_1b_mf_calculated_al_mm, 

CASE
    WHEN OHX05LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05LAP AS FLOAT64) 
 END as loa_max_r_1b_dl_calculated_al_mm, 

CASE
    WHEN OHX05LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05LAL AS FLOAT64) 
 END as loa_max_r_1b_mdl_calculated_al_mm, 

CASE
    WHEN OHX05LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05LAA AS FLOAT64) 
 END as loa_max_r_1b_ml_calculated_al_mm, 

CASE
    WHEN OHX06CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06CJD AS FLOAT64) 
 END as loa_max_r_c_df_fgm_cej_mm, 

CASE
    WHEN OHX06CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06CJM AS FLOAT64) 
 END as loa_max_r_c_mdf_fgm_cej_mm, 

CASE
    WHEN OHX06CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06CJS AS FLOAT64) 
 END as loa_max_r_c_mf_fgm_cej_mm, 

CASE
    WHEN OHX06CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06CJP AS FLOAT64) 
 END as loa_max_r_c_dl_fgm_cej_mm, 

CASE
    WHEN OHX06CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06CJL AS FLOAT64) 
 END as loa_max_r_c_mdl_fgm_cej_mm, 

CASE
    WHEN OHX06CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06CJA AS FLOAT64) 
 END as loa_max_r_c_ml_fgm_cej_mm, 

CASE
    WHEN OHX06PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06PCD AS FLOAT64) 
 END as loa_max_r_c_df_fgm_sulcus_mm, 

CASE
    WHEN OHX06PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06PCM AS FLOAT64) 
 END as loa_max_r_c_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX06PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06PCS AS FLOAT64) 
 END as loa_max_r_c_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX06PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06PCP AS FLOAT64) 
 END as loa_max_r_c_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX06PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06PCL AS FLOAT64) 
 END as loa_max_r_c_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX06PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06PCA AS FLOAT64) 
 END as loa_max_r_c_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX06LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06LAD AS FLOAT64) 
 END as loa_max_r_c_df_calculated_al_mm, 

CASE
    WHEN OHX06LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06LAM AS FLOAT64) 
 END as loa_max_r_c_mdf_calculated_al_mm, 

CASE
    WHEN OHX06LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06LAS AS FLOAT64) 
 END as loa_max_r_c_mf_calculated_al_mm, 

CASE
    WHEN OHX06LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06LAP AS FLOAT64) 
 END as loa_max_r_c_dl_calculated_al_mm, 

CASE
    WHEN OHX06LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06LAL AS FLOAT64) 
 END as loa_max_r_c_mdl_calculated_al_mm, 

CASE
    WHEN OHX06LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06LAA AS FLOAT64) 
 END as loa_max_r_c_ml_calculated_al_mm, 

CASE
    WHEN OHX07CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07CJD AS FLOAT64) 
 END as loa_max_r_li_df_fgm_cej_mm, 

CASE
    WHEN OHX07CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07CJM AS FLOAT64) 
 END as loa_max_r_li_mdf_fgm_cej_mm, 

CASE
    WHEN OHX07CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07CJS AS FLOAT64) 
 END as loa_max_r_li_mf_fgm_cej_mm, 

CASE
    WHEN OHX07CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07CJP AS FLOAT64) 
 END as loa_max_r_li_dl_fgm_cej_mm, 

CASE
    WHEN OHX07CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07CJL AS FLOAT64) 
 END as loa_max_r_li_mdl_fgm_cej_mm, 

CASE
    WHEN OHX07CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07CJA AS FLOAT64) 
 END as loa_max_r_li_ml_fgm_cej_mm, 

CASE
    WHEN OHX07PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07PCD AS FLOAT64) 
 END as loa_max_r_li_df_fgm_sulcus_mm, 

CASE
    WHEN OHX07PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07PCM AS FLOAT64) 
 END as loa_max_r_li_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX07PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07PCS AS FLOAT64) 
 END as loa_max_r_li_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX07PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07PCP AS FLOAT64) 
 END as loa_max_r_li_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX07PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07PCL AS FLOAT64) 
 END as loa_max_r_li_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX07PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07PCA AS FLOAT64) 
 END as loa_max_r_li_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX07LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07LAD AS FLOAT64) 
 END as loa_max_r_li_df_calculated_al_mm, 

CASE
    WHEN OHX07LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07LAM AS FLOAT64) 
 END as loa_max_r_li_mdf_calculated_al_mm, 

CASE
    WHEN OHX07LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07LAS AS FLOAT64) 
 END as loa_max_r_li_mf_calculated_al_mm, 

CASE
    WHEN OHX07LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07LAP AS FLOAT64) 
 END as loa_max_r_li_dl_calculated_al_mm, 

CASE
    WHEN OHX07LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07LAL AS FLOAT64) 
 END as loa_max_r_li_mdl_calculated_al_mm, 

CASE
    WHEN OHX07LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07LAA AS FLOAT64) 
 END as loa_max_r_li_ml_calculated_al_mm, 

CASE
    WHEN OHX08CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08CJD AS FLOAT64) 
 END as loa_max_r_ci_df_fgm_cej_mm, 

CASE
    WHEN OHX08CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08CJM AS FLOAT64) 
 END as loa_max_r_ci_mdf_fgm_cej_mm, 

CASE
    WHEN OHX08CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08CJS AS FLOAT64) 
 END as loa_max_r_ci_mf_fgm_cej_mm, 

CASE
    WHEN OHX08CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08CJP AS FLOAT64) 
 END as loa_max_r_ci_dl_fgm_cej_mm, 

CASE
    WHEN OHX08CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08CJL AS FLOAT64) 
 END as loa_max_r_ci_mdl_fgm_cej_mm, 

CASE
    WHEN OHX08CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08CJA AS FLOAT64) 
 END as loa_max_r_ci_ml_fgm_cej_mm, 

CASE
    WHEN OHX08PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08PCD AS FLOAT64) 
 END as loa_max_r_ci_df_fgm_sulcus_mm, 

CASE
    WHEN OHX08PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08PCM AS FLOAT64) 
 END as loa_max_r_ci_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX08PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08PCS AS FLOAT64) 
 END as loa_max_r_ci_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX08PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08PCP AS FLOAT64) 
 END as loa_max_r_ci_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX08PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08PCL AS FLOAT64) 
 END as loa_max_r_ci_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX08PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08PCA AS FLOAT64) 
 END as loa_max_r_ci_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX08LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08LAD AS FLOAT64) 
 END as loa_max_r_ci_df_calculated_al_mm, 

CASE
    WHEN OHX08LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08LAM AS FLOAT64) 
 END as loa_max_r_ci_mdf_calculated_al_mm, 

CASE
    WHEN OHX08LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08LAS AS FLOAT64) 
 END as loa_max_r_ci_mf_calculated_al_mm, 

CASE
    WHEN OHX08LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08LAP AS FLOAT64) 
 END as loa_max_r_ci_dl_calculated_al_mm, 

CASE
    WHEN OHX08LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08LAL AS FLOAT64) 
 END as loa_max_r_ci_mdl_calculated_al_mm, 

CASE
    WHEN OHX08LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08LAA AS FLOAT64) 
 END as loa_max_r_ci_ml_calculated_al_mm, 

CASE
    WHEN OHX09CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09CJD AS FLOAT64) 
 END as loa_max_l_ci_df_fgm_cej_mm, 

CASE
    WHEN OHX09CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09CJM AS FLOAT64) 
 END as loa_max_l_ci_mdf_fgm_cej_mm, 

CASE
    WHEN OHX09CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09CJS AS FLOAT64) 
 END as loa_max_l_ci_mf_fgm_cej_mm, 

CASE
    WHEN OHX09CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09CJP AS FLOAT64) 
 END as loa_max_l_ci_dl_fgm_cej_mm, 

CASE
    WHEN OHX09CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09CJL AS FLOAT64) 
 END as loa_max_l_ci_mdl_fgm_cej_mm, 

CASE
    WHEN OHX09CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09CJA AS FLOAT64) 
 END as loa_max_l_ci_ml_fgm_cej_mm, 

CASE
    WHEN OHX09PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09PCD AS FLOAT64) 
 END as loa_max_l_ci_df_fgm_sulcus_mm, 

CASE
    WHEN OHX09PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09PCM AS FLOAT64) 
 END as loa_max_l_ci_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX09PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09PCS AS FLOAT64) 
 END as loa_max_l_ci_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX09PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09PCP AS FLOAT64) 
 END as loa_max_l_ci_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX09PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09PCL AS FLOAT64) 
 END as loa_max_l_ci_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX09PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09PCA AS FLOAT64) 
 END as loa_max_l_ci_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX09LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09LAD AS FLOAT64) 
 END as loa_max_l_ci_df_calculated_al_mm, 

CASE
    WHEN OHX09LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09LAM AS FLOAT64) 
 END as loa_max_l_ci_mdf_calculated_al_mm, 

CASE
    WHEN OHX09LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09LAS AS FLOAT64) 
 END as loa_max_l_ci_mf_calculated_al_mm, 

CASE
    WHEN OHX09LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09LAP AS FLOAT64) 
 END as loa_max_l_ci_dl_calculated_al_mm, 

CASE
    WHEN OHX09LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09LAL AS FLOAT64) 
 END as loa_max_l_ci_mdl_calculated_al_mm, 

CASE
    WHEN OHX09LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09LAA AS FLOAT64) 
 END as loa_max_l_ci_ml_calculated_al_mm, 

CASE
    WHEN OHX10CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10CJD AS FLOAT64) 
 END as loa_max_l_li_df_fgm_cej_mm, 

CASE
    WHEN OHX10CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10CJM AS FLOAT64) 
 END as loa_max_l_li_mdf_fgm_cej_mm, 

CASE
    WHEN OHX10CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10CJS AS FLOAT64) 
 END as loa_max_l_li_mf_fgm_cej_mm, 

CASE
    WHEN OHX10CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10CJP AS FLOAT64) 
 END as loa_max_l_li_dl_fgm_cej_mm, 

CASE
    WHEN OHX10CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10CJL AS FLOAT64) 
 END as loa_max_l_li_mdl_fgm_cej_mm, 

CASE
    WHEN OHX10CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10CJA AS FLOAT64) 
 END as loa_max_l_li_ml_fgm_cej_mm, 

CASE
    WHEN OHX10PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10PCD AS FLOAT64) 
 END as loa_max_l_li_df_fgm_sulcus_mm, 

CASE
    WHEN OHX10PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10PCM AS FLOAT64) 
 END as loa_max_l_li_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX10PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10PCS AS FLOAT64) 
 END as loa_max_l_li_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX10PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10PCP AS FLOAT64) 
 END as loa_max_l_li_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX10PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10PCL AS FLOAT64) 
 END as loa_max_l_li_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX10PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10PCA AS FLOAT64) 
 END as loa_max_l_li_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX10LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10LAD AS FLOAT64) 
 END as loa_max_l_li_df_calculated_al_mm, 

CASE
    WHEN OHX10LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10LAM AS FLOAT64) 
 END as loa_max_l_li_mdf_calculated_al_mm, 

CASE
    WHEN OHX10LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10LAS AS FLOAT64) 
 END as loa_max_l_li_mf_calculated_al_mm, 

CASE
    WHEN OHX10LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10LAP AS FLOAT64) 
 END as loa_max_l_li_dl_calculated_al_mm, 

CASE
    WHEN OHX10LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10LAL AS FLOAT64) 
 END as loa_max_l_li_mdl_calculated_al_mm, 

CASE
    WHEN OHX10LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10LAA AS FLOAT64) 
 END as loa_max_l_li_ml_calculated_al_mm, 

CASE
    WHEN OHX11CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11CJD AS FLOAT64) 
 END as loa_max_l_c_df_fgm_cej_mm, 

CASE
    WHEN OHX11CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11CJM AS FLOAT64) 
 END as loa_max_l_c_mdf_fgm_cej_mm, 

CASE
    WHEN OHX11CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11CJS AS FLOAT64) 
 END as loa_max_l_c_mf_fgm_cej_mm, 

CASE
    WHEN OHX11CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11CJP AS FLOAT64) 
 END as loa_max_l_c_dl_fgm_cej_mm, 

CASE
    WHEN OHX11CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11CJL AS FLOAT64) 
 END as loa_max_l_c_mdl_fgm_cej_mm, 

CASE
    WHEN OHX11CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11CJA AS FLOAT64) 
 END as loa_max_l_c_ml_fgm_cej_mm, 

CASE
    WHEN OHX11PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11PCD AS FLOAT64) 
 END as loa_max_l_c_df_fgm_sulcus_mm, 

CASE
    WHEN OHX11PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11PCM AS FLOAT64) 
 END as loa_max_l_c_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX11PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11PCS AS FLOAT64) 
 END as loa_max_l_c_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX11PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11PCP AS FLOAT64) 
 END as loa_max_l_c_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX11PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11PCL AS FLOAT64) 
 END as loa_max_l_c_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX11PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11PCA AS FLOAT64) 
 END as loa_max_l_c_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX11LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11LAD AS FLOAT64) 
 END as loa_max_l_c_df_calculated_al_mm, 

CASE
    WHEN OHX11LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11LAM AS FLOAT64) 
 END as loa_max_l_c_mdf_calculated_al_mm, 

CASE
    WHEN OHX11LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11LAS AS FLOAT64) 
 END as loa_max_l_c_mf_calculated_al_mm, 

CASE
    WHEN OHX11LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11LAP AS FLOAT64) 
 END as loa_max_l_c_dl_calculated_al_mm, 

CASE
    WHEN OHX11LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11LAL AS FLOAT64) 
 END as loa_max_l_c_mdl_calculated_al_mm, 

CASE
    WHEN OHX11LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11LAA AS FLOAT64) 
 END as loa_max_l_c_ml_calculated_al_mm, 

CASE
    WHEN OHX12CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12CJD AS FLOAT64) 
 END as loa_max_l_1b_df_fgm_cej_mm, 

CASE
    WHEN OHX12CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12CJM AS FLOAT64) 
 END as loa_max_l_1b_mdf_fgm_cej_mm, 

CASE
    WHEN OHX12CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12CJS AS FLOAT64) 
 END as loa_max_l_1b_mf_fgm_cej_mm, 

CASE
    WHEN OHX12CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12CJP AS FLOAT64) 
 END as loa_max_l_1b_dl_fgm_cej_mm, 

CASE
    WHEN OHX12CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12CJL AS FLOAT64) 
 END as loa_max_l_1b_mdl_fgm_cej_mm, 

CASE
    WHEN OHX12CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12CJA AS FLOAT64) 
 END as loa_max_l_1b_ml_fgm_cej_mm, 

CASE
    WHEN OHX12PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12PCD AS FLOAT64) 
 END as loa_max_l_1b_df_fgm_sulcus_mm, 

CASE
    WHEN OHX12PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12PCM AS FLOAT64) 
 END as loa_max_l_1b_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX12PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12PCS AS FLOAT64) 
 END as loa_max_l_1b_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX12PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12PCP AS FLOAT64) 
 END as loa_max_l_1b_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX12PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12PCL AS FLOAT64) 
 END as loa_max_l_1b_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX12PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12PCA AS FLOAT64) 
 END as loa_max_l_1b_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX12LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12LAD AS FLOAT64) 
 END as loa_max_l_1b_df_calculated_al_mm, 

CASE
    WHEN OHX12LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12LAM AS FLOAT64) 
 END as loa_max_l_1b_mdf_calculated_al_mm, 

CASE
    WHEN OHX12LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12LAS AS FLOAT64) 
 END as loa_max_l_1b_mf_calculated_al_mm, 

CASE
    WHEN OHX12LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12LAP AS FLOAT64) 
 END as loa_max_l_1b_dl_calculated_al_mm, 

CASE
    WHEN OHX12LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12LAL AS FLOAT64) 
 END as loa_max_l_1b_mdl_calculated_al_mm, 

CASE
    WHEN OHX12LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12LAA AS FLOAT64) 
 END as loa_max_l_1b_ml_calculated_al_mm, 

CASE
    WHEN OHX13CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13CJD AS FLOAT64) 
 END as loa_max_l_2b_df_fgm_cej_mm, 

CASE
    WHEN OHX13CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13CJM AS FLOAT64) 
 END as loa_max_l_2b_mdf_fgm_cej_mm, 

CASE
    WHEN OHX13CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13CJS AS FLOAT64) 
 END as loa_max_l_2b_mf_fgm_cej_mm, 

CASE
    WHEN OHX13CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13CJP AS FLOAT64) 
 END as loa_max_l_2b_dl_fgm_cej_mm, 

CASE
    WHEN OHX13CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13CJL AS FLOAT64) 
 END as loa_max_l_2b_mdl_fgm_cej_mm, 

CASE
    WHEN OHX13CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13CJA AS FLOAT64) 
 END as loa_max_l_2b_ml_fgm_cej_mm, 

CASE
    WHEN OHX13PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13PCD AS FLOAT64) 
 END as loa_max_l_2b_df_fgm_sulcus_mm, 

CASE
    WHEN OHX13PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13PCM AS FLOAT64) 
 END as loa_max_l_2b_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX13PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13PCS AS FLOAT64) 
 END as loa_max_l_2b_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX13PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13PCP AS FLOAT64) 
 END as loa_max_l_2b_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX13PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13PCL AS FLOAT64) 
 END as loa_max_l_2b_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX13PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13PCA AS FLOAT64) 
 END as loa_max_l_2b_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX13LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13LAD AS FLOAT64) 
 END as loa_max_l_2b_df_calculated_al_mm, 

CASE
    WHEN OHX13LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13LAM AS FLOAT64) 
 END as loa_max_l_2b_mdf_calculated_al_mm, 

CASE
    WHEN OHX13LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13LAS AS FLOAT64) 
 END as loa_max_l_2b_mf_calculated_al_mm, 

CASE
    WHEN OHX13LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13LAP AS FLOAT64) 
 END as loa_max_l_2b_dl_calculated_al_mm, 

CASE
    WHEN OHX13LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13LAL AS FLOAT64) 
 END as loa_max_l_2b_mdl_calculated_al_mm, 

CASE
    WHEN OHX13LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13LAA AS FLOAT64) 
 END as loa_max_l_2b_ml_calculated_al_mm, 

CASE
    WHEN OHX14CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14CJD AS FLOAT64) 
 END as loa_max_l_1m_df_fgm_cej_mm, 

CASE
    WHEN OHX14CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14CJM AS FLOAT64) 
 END as loa_max_l_1m_mdf_fgm_cej_mm, 

CASE
    WHEN OHX14CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14CJS AS FLOAT64) 
 END as loa_max_l_1m_mf_fgm_cej_mm, 

CASE
    WHEN OHX14CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14CJP AS FLOAT64) 
 END as loa_max_l_1m_dl_fgm_cej_mm, 

CASE
    WHEN OHX14CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14CJL AS FLOAT64) 
 END as loa_max_l_1m_mdl_fgm_cej_mm, 

CASE
    WHEN OHX14CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14CJA AS FLOAT64) 
 END as loa_max_l_1m_ml_fgm_cej_mm, 

CASE
    WHEN OHX14PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14PCD AS FLOAT64) 
 END as loa_max_l_1m_df_fgm_sulcus_mm, 

CASE
    WHEN OHX14PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14PCM AS FLOAT64) 
 END as loa_max_l_1m_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX14PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14PCS AS FLOAT64) 
 END as loa_max_l_1m_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX14PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14PCP AS FLOAT64) 
 END as loa_max_l_1m_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX14PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14PCL AS FLOAT64) 
 END as loa_max_l_1m_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX14PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14PCA AS FLOAT64) 
 END as loa_max_l_1m_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX14LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14LAD AS FLOAT64) 
 END as loa_max_l_1m_df_calculated_al_mm, 

CASE
    WHEN OHX14LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14LAM AS FLOAT64) 
 END as loa_max_l_1m_mdf_calculated_al_mm, 

CASE
    WHEN OHX14LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14LAS AS FLOAT64) 
 END as loa_max_l_1m_mf_calculated_al_mm, 

CASE
    WHEN OHX14LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14LAP AS FLOAT64) 
 END as loa_max_l_1m_dl_calculated_al_mm, 

CASE
    WHEN OHX14LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14LAL AS FLOAT64) 
 END as loa_max_l_1m_mdl_calculated_al_mm, 

CASE
    WHEN OHX14LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14LAA AS FLOAT64) 
 END as loa_max_l_1m_ml_calculated_al_mm, 

CASE
    WHEN OHX15CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15CJD AS FLOAT64) 
 END as loa_max_l_2m_df_fgm_cej_mm, 

CASE
    WHEN OHX15CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15CJM AS FLOAT64) 
 END as loa_max_l_2m_mdf_fgm_cej_mm, 

CASE
    WHEN OHX15CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15CJS AS FLOAT64) 
 END as loa_max_l_2m_mf_fgm_cej_mm, 

CASE
    WHEN OHX15CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15CJP AS FLOAT64) 
 END as loa_max_l_2m_dl_fgm_cej_mm, 

CASE
    WHEN OHX15CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15CJL AS FLOAT64) 
 END as loa_max_l_2m_mdl_fgm_cej_mm, 

CASE
    WHEN OHX15CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15CJA AS FLOAT64) 
 END as loa_max_l_2m_ml_fgm_cej_mm, 

CASE
    WHEN OHX15PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15PCD AS FLOAT64) 
 END as loa_max_l_2m_df_fgm_sulcus_mm, 

CASE
    WHEN OHX15PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15PCM AS FLOAT64) 
 END as loa_max_l_2m_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX15PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15PCS AS FLOAT64) 
 END as loa_max_l_2m_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX15PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15PCP AS FLOAT64) 
 END as loa_max_l_2m_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX15PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15PCL AS FLOAT64) 
 END as loa_max_l_2m_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX15PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15PCA AS FLOAT64) 
 END as loa_max_l_2m_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX15LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15LAD AS FLOAT64) 
 END as loa_max_l_2m_df_calculated_al_mm, 

CASE
    WHEN OHX15LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15LAM AS FLOAT64) 
 END as loa_max_l_2m_mdf_calculated_al_mm, 

CASE
    WHEN OHX15LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15LAS AS FLOAT64) 
 END as loa_max_l_2m_mf_calculated_al_mm, 

CASE
    WHEN OHX15LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15LAP AS FLOAT64) 
 END as loa_max_l_2m_dl_calculated_al_mm, 

CASE
    WHEN OHX15LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15LAL AS FLOAT64) 
 END as loa_max_l_2m_mdl_calculated_al_mm, 

CASE
    WHEN OHX15LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15LAA AS FLOAT64) 
 END as loa_max_l_2m_ml_calculated_al_mm, 

CASE
    WHEN OHX18CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18CJD AS FLOAT64) 
 END as loa_mnd_l_2m_df_fgm_cej_mm, 

CASE
    WHEN OHX18CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18CJM AS FLOAT64) 
 END as loa_mnd_l_2m_mdf_fgm_cej_mm, 

CASE
    WHEN OHX18CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18CJS AS FLOAT64) 
 END as loa_mnd_l_2m_mf_fgm_cej_mm, 

CASE
    WHEN OHX18CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18CJP AS FLOAT64) 
 END as loa_mnd_l_2m_dl_fgm_cej_mm, 

CASE
    WHEN OHX18CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18CJL AS FLOAT64) 
 END as loa_mnd_l_2m_mdl_fgm_cej_mm, 

CASE
    WHEN OHX18CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18CJA AS FLOAT64) 
 END as loa_mnd_l_2m_ml_fgm_cej_mm, 

CASE
    WHEN OHX18PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18PCD AS FLOAT64) 
 END as loa_mnd_l_2m_df_fgm_sulcus_mm, 

CASE
    WHEN OHX18PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18PCM AS FLOAT64) 
 END as loa_mnd_l_2m_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX18PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18PCS AS FLOAT64) 
 END as loa_mnd_l_2m_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX18PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18PCP AS FLOAT64) 
 END as loa_mnd_l_2m_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX18PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18PCL AS FLOAT64) 
 END as loa_mnd_l_2m_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX18PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18PCA AS FLOAT64) 
 END as loa_mnd_l_2m_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX18LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18LAD AS FLOAT64) 
 END as loa_mnd_l_2m_df_calculated_al_mm, 

CASE
    WHEN OHX18LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18LAM AS FLOAT64) 
 END as loa_mnd_l_2m_mdf_calculated_al_mm, 

CASE
    WHEN OHX18LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18LAS AS FLOAT64) 
 END as loa_mnd_l_2m_mf_calculated_al_mm, 

CASE
    WHEN OHX18LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18LAP AS FLOAT64) 
 END as loa_mnd_l_2m_dl_calculated_al_mm, 

CASE
    WHEN OHX18LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18LAL AS FLOAT64) 
 END as loa_mnd_l_2m_mdl_calculated_al_mm, 

CASE
    WHEN OHX18LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18LAA AS FLOAT64) 
 END as loa_mnd_l_2m_ml_calculated_al_mm, 

CASE
    WHEN OHX19CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19CJD AS FLOAT64) 
 END as loa_mnd_l_1m_df_fgm_cej_mm, 

CASE
    WHEN OHX19CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19CJM AS FLOAT64) 
 END as loa_mnd_l_1m_mdf_fgm_cej_mm, 

CASE
    WHEN OHX19CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19CJS AS FLOAT64) 
 END as loa_mnd_l_1m_mf_fgm_cej_mm, 

CASE
    WHEN OHX19CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19CJP AS FLOAT64) 
 END as loa_max_l_1m_dl_fgm_cej_mm_OHX19CJP, 

CASE
    WHEN OHX19CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19CJL AS FLOAT64) 
 END as loa_mnd_l_1m_mdl_fgm_cej_mm, 

CASE
    WHEN OHX19CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19CJA AS FLOAT64) 
 END as loa_mnd_l_1m_ml_fgm_cej_mm, 

CASE
    WHEN OHX19PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19PCD AS FLOAT64) 
 END as loa_mnd_l_1m_df_fgm_sulcus_mm, 

CASE
    WHEN OHX19PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19PCM AS FLOAT64) 
 END as loa_mnd_l_1m_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX19PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19PCS AS FLOAT64) 
 END as loa_mnd_l_1m_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX19PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19PCP AS FLOAT64) 
 END as loa_mnd_l_1m_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX19PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19PCL AS FLOAT64) 
 END as loa_mnd_l_1m_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX19PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19PCA AS FLOAT64) 
 END as loa_mnd_l_1m_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX19LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19LAD AS FLOAT64) 
 END as loa_mnd_l_1m_df_calculated_al_mm, 

CASE
    WHEN OHX19LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19LAM AS FLOAT64) 
 END as loa_mnd_l_1m_mdf_calculated_al_mm, 

CASE
    WHEN OHX19LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19LAS AS FLOAT64) 
 END as loa_mnd_l_1m_mf_calculated_al_mm, 

CASE
    WHEN OHX19LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19LAP AS FLOAT64) 
 END as loa_mnd_l_1m_dl_calculated_al_mm, 

CASE
    WHEN OHX19LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19LAL AS FLOAT64) 
 END as loa_mnd_l_1m_mdl_calculated_al_mm, 

CASE
    WHEN OHX19LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19LAA AS FLOAT64) 
 END as loa_mnd_l_1m_ml_calculated_al_mm, 

CASE
    WHEN OHX20CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20CJD AS FLOAT64) 
 END as loa_mnd_l_2b_df_fgm_cej_mm, 

CASE
    WHEN OHX20CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20CJM AS FLOAT64) 
 END as loa_mnd_l_2b_mdf_fgm_cej_mm, 

CASE
    WHEN OHX20CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20CJS AS FLOAT64) 
 END as loa_mnd_l_2b_mf_fgm_cej_mm, 

CASE
    WHEN OHX20CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20CJP AS FLOAT64) 
 END as loa_mnd_l_2b_dl_fgm_cej_mm, 

CASE
    WHEN OHX20CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20CJL AS FLOAT64) 
 END as loa_mnd_l_2b_mdl_fgm_cej_mm, 

CASE
    WHEN OHX20CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20CJA AS FLOAT64) 
 END as loa_mnd_l_2b_ml_fgm_cej_mm, 

CASE
    WHEN OHX20PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20PCD AS FLOAT64) 
 END as loa_mnd_l_2b_df_fgm_sulcus_mm, 

CASE
    WHEN OHX20PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20PCM AS FLOAT64) 
 END as loa_mnd_l_2b_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX20PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20PCS AS FLOAT64) 
 END as loa_mnd_l_2b_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX20PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20PCP AS FLOAT64) 
 END as loa_mnd_l_2b_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX20PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20PCL AS FLOAT64) 
 END as loa_mnd_l_2b_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX20PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20PCA AS FLOAT64) 
 END as loa_mnd_l_2b_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX20LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20LAD AS FLOAT64) 
 END as loa_mnd_l_2b_df_calculated_al_mm, 

CASE
    WHEN OHX20LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20LAM AS FLOAT64) 
 END as loa_mnd_l_2b_mdf_calculated_al_mm, 

CASE
    WHEN OHX20LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20LAS AS FLOAT64) 
 END as loa_mnd_l_2b_mf_calculated_al_mm, 

CASE
    WHEN OHX20LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20LAP AS FLOAT64) 
 END as loa_mnd_l_2b_dl_calculated_al_mm, 

CASE
    WHEN OHX20LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20LAL AS FLOAT64) 
 END as loa_mnd_l_2b_mdl_calculated_al_mm, 

CASE
    WHEN OHX20LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20LAA AS FLOAT64) 
 END as loa_mnd_l_2b_ml_calculated_al_mm, 

CASE
    WHEN OHX21CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21CJD AS FLOAT64) 
 END as loa_mnd_l_1b_df_fgm_cej_mm, 

CASE
    WHEN OHX21CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21CJM AS FLOAT64) 
 END as loa_mnd_l_1b_mdf_fgm_cej_mm, 

CASE
    WHEN OHX21CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21CJS AS FLOAT64) 
 END as loa_mnd_l_1b_mf_fgm_cej_mm, 

CASE
    WHEN OHX21CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21CJP AS FLOAT64) 
 END as loa_mnd_l_1b_dl_fgm_cej_mm, 

CASE
    WHEN OHX21CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21CJL AS FLOAT64) 
 END as loa_mnd_l_1b_mdl_fgm_cej_mm, 

CASE
    WHEN OHX21CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21CJA AS FLOAT64) 
 END as loa_mnd_l_1b_ml_fgm_cej_mm, 

CASE
    WHEN OHX21PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21PCD AS FLOAT64) 
 END as loa_mnd_l_1b_df_fgm_sulcus_mm, 

CASE
    WHEN OHX21PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21PCM AS FLOAT64) 
 END as loa_mnd_l_1b_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX21PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21PCS AS FLOAT64) 
 END as loa_mnd_l_1b_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX21PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21PCP AS FLOAT64) 
 END as loa_mnd_l_1b_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX21PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21PCL AS FLOAT64) 
 END as loa_mnd_l_1b_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX21PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21PCA AS FLOAT64) 
 END as loa_mnd_l_1b_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX21LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21LAD AS FLOAT64) 
 END as loa_mnd_l_1b_df_calculated_al_mm, 

CASE
    WHEN OHX21LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21LAM AS FLOAT64) 
 END as loa_mnd_l_1b_mdf_calculated_al_mm, 

CASE
    WHEN OHX21LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21LAS AS FLOAT64) 
 END as loa_mnd_l_1b_mf_calculated_al_mm, 

CASE
    WHEN OHX21LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21LAP AS FLOAT64) 
 END as loa_mnd_l_1b_dl_calculated_al_mm, 

CASE
    WHEN OHX21LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21LAL AS FLOAT64) 
 END as loa_mnd_l_1b_mdl_calculated_al_mm, 

CASE
    WHEN OHX21LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21LAA AS FLOAT64) 
 END as loa_mnd_l_1b_ml_calculated_al_mm, 

CASE
    WHEN OHX22CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22CJD AS FLOAT64) 
 END as loa_mnd_l_c_df_fgm_cej_mm, 

CASE
    WHEN OHX22CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22CJM AS FLOAT64) 
 END as loa_mnd_l_c_mdf_fgm_cej_mm, 

CASE
    WHEN OHX22CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22CJS AS FLOAT64) 
 END as loa_mnd_l_c_mf_fgm_cej_mm, 

CASE
    WHEN OHX22CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22CJP AS FLOAT64) 
 END as loa_mnd_l_c_dl_fgm_cej_mm, 

CASE
    WHEN OHX22CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22CJL AS FLOAT64) 
 END as loa_mnd_l_c_mdl_fgm_cej_mm, 

CASE
    WHEN OHX22CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22CJA AS FLOAT64) 
 END as loa_mnd_l_c_ml_fgm_cej_mm, 

CASE
    WHEN OHX22PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22PCD AS FLOAT64) 
 END as loa_mnd_l_c_df_fgm_sulcus_mm, 

CASE
    WHEN OHX22PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22PCM AS FLOAT64) 
 END as loa_mnd_l_c_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX22PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22PCS AS FLOAT64) 
 END as loa_mnd_l_c_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX22PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22PCP AS FLOAT64) 
 END as loa_mnd_l_c_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX22PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22PCL AS FLOAT64) 
 END as loa_mnd_l_c_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX22PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22PCA AS FLOAT64) 
 END as loa_mnd_l_c_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX22LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22LAD AS FLOAT64) 
 END as loa_mnd_l_c_df_calculated_al_mm, 

CASE
    WHEN OHX22LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22LAM AS FLOAT64) 
 END as loa_mnd_l_c_mdf_calculated_al_mm, 

CASE
    WHEN OHX22LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22LAS AS FLOAT64) 
 END as loa_mnd_l_c_mf_calculated_al_mm, 

CASE
    WHEN OHX22LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22LAP AS FLOAT64) 
 END as loa_mnd_l_c_dl_calculated_al_mm, 

CASE
    WHEN OHX22LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22LAL AS FLOAT64) 
 END as loa_mnd_l_c_mdl_calculated_al_mm, 

CASE
    WHEN OHX22LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22LAA AS FLOAT64) 
 END as loa_mnd_l_c_ml_calculated_al_mm, 

CASE
    WHEN OHX23CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23CJD AS FLOAT64) 
 END as loa_mnd_l_li_df_fgm_cej_mm, 

CASE
    WHEN OHX23CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23CJM AS FLOAT64) 
 END as loa_mnd_l_li_mdf_fgm_cej_mm, 

CASE
    WHEN OHX23CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23CJS AS FLOAT64) 
 END as loa_mnd_l_li_mf_fgm_cej_mm, 

CASE
    WHEN OHX23CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23CJP AS FLOAT64) 
 END as loa_mnd_l_li_dl_fgm_cej_mm, 

CASE
    WHEN OHX23CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23CJL AS FLOAT64) 
 END as loa_mnd_l_li_mdl_fgm_cej_mm, 

CASE
    WHEN OHX23CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23CJA AS FLOAT64) 
 END as loa_mnd_l_li_ml_fgm_cej_mm, 

CASE
    WHEN OHX23PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23PCD AS FLOAT64) 
 END as loa_mnd_l_li_df_fgm_sulcus_mm, 

CASE
    WHEN OHX23PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23PCM AS FLOAT64) 
 END as loa_mnd_l_li_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX23PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23PCS AS FLOAT64) 
 END as loa_mnd_l_li_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX23PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23PCP AS FLOAT64) 
 END as loa_mnd_l_li_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX23PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23PCL AS FLOAT64) 
 END as loa_mnd_l_li_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX23PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23PCA AS FLOAT64) 
 END as loa_mnd_l_li_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX23LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23LAD AS FLOAT64) 
 END as loa_mnd_l_li_df_calculated_al_mm, 

CASE
    WHEN OHX23LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23LAM AS FLOAT64) 
 END as loa_mnd_l_li_mdf_calculated_al_mm, 

CASE
    WHEN OHX23LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23LAS AS FLOAT64) 
 END as loa_mnd_l_li_mf_calculated_al_mm, 

CASE
    WHEN OHX23LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23LAP AS FLOAT64) 
 END as loa_mnd_l_li_dl_calculated_al_mm, 

CASE
    WHEN OHX23LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23LAL AS FLOAT64) 
 END as loa_mnd_l_li_mdl_calculated_al_mm, 

CASE
    WHEN OHX23LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23LAA AS FLOAT64) 
 END as loa_mnd_l_li_ml_calculated_al_mm, 

CASE
    WHEN OHX24CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24CJD AS FLOAT64) 
 END as loa_mnd_l_ci_df_fgm_cej_mm, 

CASE
    WHEN OHX24CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24CJM AS FLOAT64) 
 END as loa_mnd_l_ci_mdf_fgm_cej_mm, 

CASE
    WHEN OHX24CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24CJS AS FLOAT64) 
 END as loa_mnd_l_ci_mf_fgm_cej_mm, 

CASE
    WHEN OHX24CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24CJP AS FLOAT64) 
 END as loa_mnd_l_ci_dl_fgm_cej_mm, 

CASE
    WHEN OHX24CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24CJL AS FLOAT64) 
 END as loa_mnd_l_ci_mdl_fgm_cej_mm, 

CASE
    WHEN OHX24CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24CJA AS FLOAT64) 
 END as loa_mnd_l_ci_ml_fgm_cej_mm, 

CASE
    WHEN OHX24PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24PCD AS FLOAT64) 
 END as loa_mnd_l_ci_df_fgm_sulcus_mm, 

CASE
    WHEN OHX24PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24PCM AS FLOAT64) 
 END as loa_mnd_l_ci_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX24PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24PCS AS FLOAT64) 
 END as loa_mnd_l_ci_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX24PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24PCP AS FLOAT64) 
 END as loa_mnd_l_ci_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX24PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24PCL AS FLOAT64) 
 END as loa_mnd_l_ci_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX24PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24PCA AS FLOAT64) 
 END as loa_mnd_l_ci_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX24LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24LAD AS FLOAT64) 
 END as loa_mnd_l_ci_df_calculated_al_mm, 

CASE
    WHEN OHX24LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24LAM AS FLOAT64) 
 END as loa_mnd_l_ci_mdf_calculated_al_mm, 

CASE
    WHEN OHX24LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24LAS AS FLOAT64) 
 END as loa_mnd_l_ci_mf_calculated_al_mm, 

CASE
    WHEN OHX24LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24LAP AS FLOAT64) 
 END as loa_mnd_l_ci_dl_calculated_al_mm, 

CASE
    WHEN OHX24LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24LAL AS FLOAT64) 
 END as loa_mnd_l_ci_mdl_calculated_al_mm, 

CASE
    WHEN OHX24LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24LAA AS FLOAT64) 
 END as loa_mnd_l_ci_ml_calculated_al_mm, 

CASE
    WHEN OHX25CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25CJD AS FLOAT64) 
 END as loa_mnd_r_ci_df_fgm_cej_mm, 

CASE
    WHEN OHX25CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25CJM AS FLOAT64) 
 END as loa_mnd_r_ci_mdf_fgm_cej_mm, 

CASE
    WHEN OHX25CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25CJS AS FLOAT64) 
 END as loa_mnd_r_ci_mf_fgm_cej_mm, 

CASE
    WHEN OHX25CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25CJP AS FLOAT64) 
 END as loa_mnd_r_ci_dl_fgm_cej_mm, 

CASE
    WHEN OHX25CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25CJL AS FLOAT64) 
 END as loa_mnd_r_ci_mdl_fgm_cej_mm, 

CASE
    WHEN OHX25CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25CJA AS FLOAT64) 
 END as loa_mnd_r_ci_ml_fgm_cej_mm, 

CASE
    WHEN OHX25PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25PCD AS FLOAT64) 
 END as loa_mnd_r_ci_df_fgm_sulcus_mm, 

CASE
    WHEN OHX25PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25PCM AS FLOAT64) 
 END as loa_mnd_r_ci_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX25PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25PCS AS FLOAT64) 
 END as loa_mnd_r_ci_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX25PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25PCP AS FLOAT64) 
 END as loa_mnd_r_ci_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX25PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25PCL AS FLOAT64) 
 END as loa_mnd_r_ci_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX25PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25PCA AS FLOAT64) 
 END as loa_mnd_r_ci_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX25LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25LAD AS FLOAT64) 
 END as loa_mnd_r_ci_df_calculated_al_mm, 

CASE
    WHEN OHX25LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25LAM AS FLOAT64) 
 END as loa_mnd_r_ci_mdf_calculated_al_mm, 

CASE
    WHEN OHX25LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25LAS AS FLOAT64) 
 END as loa_mnd_r_ci_mf_calculated_al_mm, 

CASE
    WHEN OHX25LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25LAP AS FLOAT64) 
 END as loa_mnd_r_ci_dl_calculated_al_mm, 

CASE
    WHEN OHX25LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25LAL AS FLOAT64) 
 END as loa_mnd_r_ci_mdl_calculated_al_mm, 

CASE
    WHEN OHX25LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25LAA AS FLOAT64) 
 END as loa_mnd_r_ci_ml_calculated_al_mm, 

CASE
    WHEN OHX26CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26CJD AS FLOAT64) 
 END as loa_mnd_r_li_df_fgm_cej_mm, 

CASE
    WHEN OHX26CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26CJM AS FLOAT64) 
 END as loa_mnd_r_li_mdf_fgm_cej_mm, 

CASE
    WHEN OHX26CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26CJS AS FLOAT64) 
 END as loa_mnd_r_li_mf_fgm_cej_mm, 

CASE
    WHEN OHX26CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26CJP AS FLOAT64) 
 END as loa_mnd_r_li_dl_fgm_cej_mm, 

CASE
    WHEN OHX26CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26CJL AS FLOAT64) 
 END as loa_mnd_r_li_mdl_fgm_cej_mm, 

CASE
    WHEN OHX26CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26CJA AS FLOAT64) 
 END as loa_mnd_r_li_ml_fgm_cej_mm, 

CASE
    WHEN OHX26PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26PCD AS FLOAT64) 
 END as loa_mnd_r_li_df_fgm_sulcus_mm, 

CASE
    WHEN OHX26PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26PCM AS FLOAT64) 
 END as loa_mnd_r_li_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX26PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26PCS AS FLOAT64) 
 END as loa_mnd_r_li_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX26PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26PCP AS FLOAT64) 
 END as loa_mnd_r_li_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX26PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26PCL AS FLOAT64) 
 END as loa_mnd_r_li_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX26PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26PCA AS FLOAT64) 
 END as loa_mnd_r_li_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX26LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26LAD AS FLOAT64) 
 END as loa_mnd_r_li_df_calculated_al_mm, 

CASE
    WHEN OHX26LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26LAM AS FLOAT64) 
 END as loa_mnd_r_li_mdf_calculated_al_mm, 

CASE
    WHEN OHX26LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26LAS AS FLOAT64) 
 END as loa_mnd_r_li_mf_calculated_al_mm, 

CASE
    WHEN OHX26LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26LAP AS FLOAT64) 
 END as loa_mnd_r_li_dl_calculated_al_mm, 

CASE
    WHEN OHX26LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26LAL AS FLOAT64) 
 END as loa_mnd_r_li_mdl_calculated_al_mm, 

CASE
    WHEN OHX26LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26LAA AS FLOAT64) 
 END as loa_mnd_r_li_ml_calculated_al_mm, 

CASE
    WHEN OHX27CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27CJD AS FLOAT64) 
 END as loa_mnd_r_c_df_fgm_cej_mm, 

CASE
    WHEN OHX27CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27CJM AS FLOAT64) 
 END as loa_mnd_r_c_mdf_fgm_cej_mm, 

CASE
    WHEN OHX27CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27CJS AS FLOAT64) 
 END as loa_mnd_r_c_mf_fgm_cej_mm, 

CASE
    WHEN OHX27CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27CJP AS FLOAT64) 
 END as loa_mnd_r_c_dl_fgm_cej_mm, 

CASE
    WHEN OHX27CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27CJL AS FLOAT64) 
 END as loa_mnd_r_c_mdl_fgm_cej_mm, 

CASE
    WHEN OHX27CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27CJA AS FLOAT64) 
 END as loa_mnd_r_c_ml_fgm_cej_mm, 

CASE
    WHEN OHX27PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27PCD AS FLOAT64) 
 END as loa_mnd_r_c_df_fgm_sulcus_mm, 

CASE
    WHEN OHX27PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27PCM AS FLOAT64) 
 END as loa_mnd_r_c_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX27PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27PCS AS FLOAT64) 
 END as loa_mnd_r_c_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX27PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27PCP AS FLOAT64) 
 END as loa_mnd_r_c_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX27PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27PCL AS FLOAT64) 
 END as loa_mnd_r_c_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX27PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27PCA AS FLOAT64) 
 END as loa_mnd_r_c_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX27LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27LAD AS FLOAT64) 
 END as loa_mnd_r_c_df_calculated_al_mm, 

CASE
    WHEN OHX27LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27LAM AS FLOAT64) 
 END as loa_mnd_r_c_mdf_calculated_al_mm, 

CASE
    WHEN OHX27LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27LAS AS FLOAT64) 
 END as loa_mnd_r_c_mf_calculated_al_mm, 

CASE
    WHEN OHX27LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27LAP AS FLOAT64) 
 END as loa_mnd_r_c_dl_calculated_al_mm, 

CASE
    WHEN OHX27LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27LAL AS FLOAT64) 
 END as loa_mnd_r_c_mdl_calculated_al_mm, 

CASE
    WHEN OHX27LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27LAA AS FLOAT64) 
 END as loa_mnd_r_c_ml_calculated_al_mm, 

CASE
    WHEN OHX28CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28CJD AS FLOAT64) 
 END as loa_mnd_r_1b_df_fgm_cej_mm, 

CASE
    WHEN OHX28CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28CJM AS FLOAT64) 
 END as loa_mnd_r_1b_mdf_fgm_cej_mm, 

CASE
    WHEN OHX28CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28CJS AS FLOAT64) 
 END as loa_mnd_r_1b_mf_fgm_cej_mm, 

CASE
    WHEN OHX28CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28CJP AS FLOAT64) 
 END as loa_mnd_r_1b_dl_fgm_cej_mm, 

CASE
    WHEN OHX28CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28CJL AS FLOAT64) 
 END as loa_mnd_r_1b_mdl_fgm_cej_mm, 

CASE
    WHEN OHX28CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28CJA AS FLOAT64) 
 END as loa_mnd_r_1b_ml_fgm_cej_mm, 

CASE
    WHEN OHX28PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28PCD AS FLOAT64) 
 END as loa_mnd_r_1b_df_fgm_sulcus_mm, 

CASE
    WHEN OHX28PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28PCM AS FLOAT64) 
 END as loa_mnd_r_1b_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX28PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28PCS AS FLOAT64) 
 END as loa_mnd_r_1b_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX28PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28PCP AS FLOAT64) 
 END as loa_mnd_r_1b_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX28PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28PCL AS FLOAT64) 
 END as loa_mnd_r_1b_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX28PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28PCA AS FLOAT64) 
 END as loa_mnd_r_1b_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX28LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28LAD AS FLOAT64) 
 END as loa_mnd_r_1b_df_calculated_al_mm, 

CASE
    WHEN OHX28LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28LAM AS FLOAT64) 
 END as loa_mnd_r_1b_mdf_calculated_al_mm, 

CASE
    WHEN OHX28LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28LAS AS FLOAT64) 
 END as loa_mnd_r_1b_mf_calculated_al_mm, 

CASE
    WHEN OHX28LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28LAP AS FLOAT64) 
 END as loa_mnd_r_1b_dl_calculated_al_mm, 

CASE
    WHEN OHX28LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28LAL AS FLOAT64) 
 END as loa_mnd_r_1b_mdl_calculated_al_mm, 

CASE
    WHEN OHX28LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28LAA AS FLOAT64) 
 END as loa_mnd_r_1b_ml_calculated_al_mm, 

CASE
    WHEN OHX29CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29CJD AS FLOAT64) 
 END as loa_mnd_r_2b_df_fgm_cej_mm, 

CASE
    WHEN OHX29CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29CJM AS FLOAT64) 
 END as loa_mnd_r_2b_mdf_fgm_cej_mm, 

CASE
    WHEN OHX29CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29CJS AS FLOAT64) 
 END as loa_mnd_r_2b_mf_fgm_cej_mm, 

CASE
    WHEN OHX29CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29CJP AS FLOAT64) 
 END as loa_mnd_r_2b_dl_fgm_cej_mm, 

CASE
    WHEN OHX29CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29CJL AS FLOAT64) 
 END as loa_mnd_r_2b_mdl_fgm_cej_mm, 

CASE
    WHEN OHX29CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29CJA AS FLOAT64) 
 END as loa_mnd_r_2b_ml_fgm_cej_mm, 

CASE
    WHEN OHX29PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29PCD AS FLOAT64) 
 END as loa_mnd_r_2b_df_fgm_sulcus_mm, 

CASE
    WHEN OHX29PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29PCM AS FLOAT64) 
 END as loa_mnd_r_2b_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX29PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29PCS AS FLOAT64) 
 END as loa_mnd_r_2b_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX29PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29PCP AS FLOAT64) 
 END as loa_mnd_r_2b_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX29PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29PCL AS FLOAT64) 
 END as loa_mnd_r_2b_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX29PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29PCA AS FLOAT64) 
 END as loa_mnd_r_2b_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX29LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29LAD AS FLOAT64) 
 END as loa_mnd_r_2b_df_calculated_al_mm, 

CASE
    WHEN OHX29LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29LAM AS FLOAT64) 
 END as loa_mnd_r_2b_mdf_calculated_al_mm, 

CASE
    WHEN OHX29LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29LAS AS FLOAT64) 
 END as loa_mnd_r_2b_mf_calculated_al_mm, 

CASE
    WHEN OHX29LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29LAP AS FLOAT64) 
 END as loa_mnd_r_2b_dl_calculated_al_mm, 

CASE
    WHEN OHX29LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29LAL AS FLOAT64) 
 END as loa_mnd_r_2b_mdl_calculated_al_mm, 

CASE
    WHEN OHX29LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29LAA AS FLOAT64) 
 END as loa_mnd_r_2b_ml_calculated_al_mm, 

CASE
    WHEN OHX30CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30CJD AS FLOAT64) 
 END as loa_mnd_r_1m_df_fgm_cej_mm, 

CASE
    WHEN OHX30CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30CJM AS FLOAT64) 
 END as loa_mnd_r_1m_mdf_fgm_cej_mm, 

CASE
    WHEN OHX30CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30CJS AS FLOAT64) 
 END as loa_mnd_r_1m_mf_fgm_cej_mm, 

CASE
    WHEN OHX30CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30CJP AS FLOAT64) 
 END as loa_mnd_r_1m_dl_fgm_cej_mm, 

CASE
    WHEN OHX30CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30CJL AS FLOAT64) 
 END as loa_mnd_r_1m_mdl_fgm_cej_mm, 

CASE
    WHEN OHX30CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30CJA AS FLOAT64) 
 END as loa_mnd_r_1m_ml_fgm_cej_mm, 

CASE
    WHEN OHX30PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30PCD AS FLOAT64) 
 END as loa_mnd_r_1m_df_fgm_sulcus_mm, 

CASE
    WHEN OHX30PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30PCM AS FLOAT64) 
 END as loa_mnd_r_1m_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX30PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30PCS AS FLOAT64) 
 END as loa_mnd_r_1m_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX30PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30PCP AS FLOAT64) 
 END as loa_mnd_r_1m_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX30PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30PCL AS FLOAT64) 
 END as loa_mnd_r_1m_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX30PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30PCA AS FLOAT64) 
 END as loa_mnd_r_1m_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX30LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30LAD AS FLOAT64) 
 END as loa_mnd_r_1m_df_calculated_al_mm, 

CASE
    WHEN OHX30LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30LAM AS FLOAT64) 
 END as loa_mnd_r_1m_mdf_calculated_al_mm, 

CASE
    WHEN OHX30LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30LAS AS FLOAT64) 
 END as loa_mnd_r_1m_mf_calculated_al_mm, 

CASE
    WHEN OHX30LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30LAP AS FLOAT64) 
 END as loa_mnd_r_1m_dl_calculated_al_mm, 

CASE
    WHEN OHX30LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30LAL AS FLOAT64) 
 END as loa_mnd_r_1m_mdl_calculated_al_mm, 

CASE
    WHEN OHX30LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30LAA AS FLOAT64) 
 END as loa_mnd_r_1m_ml_calculated_al_mm, 

CASE
    WHEN OHX31CJD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31CJD AS FLOAT64) 
 END as loa_mnd_r_2m_df_fgm_cej_mm, 

CASE
    WHEN OHX31CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31CJM AS FLOAT64) 
 END as loa_mnd_r_2m_mdf_fgm_cej_mm, 

CASE
    WHEN OHX31CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31CJS AS FLOAT64) 
 END as loa_mnd_r_2m_mf_fgm_cej_mm, 

CASE
    WHEN OHX31CJP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31CJP AS FLOAT64) 
 END as loa_mnd_r_2m_dl_fgm_cej_mm, 

CASE
    WHEN OHX31CJL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31CJL AS FLOAT64) 
 END as loa_mnd_r_2m_mdl_fgm_cej_mm, 

CASE
    WHEN OHX31CJA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31CJA AS FLOAT64) 
 END as loa_mnd_r_2m_ml_fgm_cej_mm, 

CASE
    WHEN OHX31PCD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31PCD AS FLOAT64) 
 END as loa_mnd_r_2m_df_fgm_sulcus_mm, 

CASE
    WHEN OHX31PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31PCM AS FLOAT64) 
 END as loa_mnd_r_2m_mdf_fgm_sulcus_mm, 

CASE
    WHEN OHX31PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31PCS AS FLOAT64) 
 END as loa_mnd_r_2m_mf_fgm_sulcus_mm, 

CASE
    WHEN OHX31PCP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31PCP AS FLOAT64) 
 END as loa_mnd_r_2m_dl_fgm_sulcus_mm, 

CASE
    WHEN OHX31PCL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31PCL AS FLOAT64) 
 END as loa_mnd_r_2m_mdl_fgm_sulcus_mm, 

CASE
    WHEN OHX31PCA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31PCA AS FLOAT64) 
 END as loa_mnd_r_2m_ml_fgm_sulcus_mm, 

CASE
    WHEN OHX31LAD IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31LAD AS FLOAT64) 
 END as loa_mnd_r_2m_df_calculated_al_mm, 

CASE
    WHEN OHX31LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31LAM AS FLOAT64) 
 END as loa_mnd_r_2m_mdf_calculated_al_mm, 

CASE
    WHEN OHX31LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31LAS AS FLOAT64) 
 END as loa_mnd_r_2m_mf_calculated_al_mm, 

CASE
    WHEN OHX31LAP IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31LAP AS FLOAT64) 
 END as loa_mnd_r_2m_dl_calculated_al_mm, 

CASE
    WHEN OHX31LAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31LAL AS FLOAT64) 
 END as loa_mnd_r_2m_mdl_calculated_al_mm, 

CASE
    WHEN OHX31LAA IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31LAA AS FLOAT64) 
 END as loa_mnd_r_2m_ml_calculated_al_mm, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(OHAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Completed' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Partial' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not Done' -- categorize numeric values
WHEN OHAEXSTS IS NULL THEN NULL 
ELSE SAFE_CAST(OHAEXSTS AS STRING) 
 END as overall_oral_health_exam_status_OHAEXSTS, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(OHASCST4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Complete' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHASCST4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Partial' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHASCST4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not done' -- categorize numeric values
WHEN OHASCST4 IS NULL THEN NULL 
ELSE SAFE_CAST(OHASCST4 AS STRING) 
 END as periodontal_status_code_OHASCST4, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXURGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Gingival bleeding detected' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXURGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No evidence of gingival bleeding' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXURGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot be assessed' -- categorize numeric values
WHEN OHXURGIN IS NULL THEN NULL 
ELSE SAFE_CAST(OHXURGIN AS STRING) 
 END as gingival_bleeding_urq, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXULGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Gingival bleeding detected' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXULGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No evidence of gingival bleeding' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXULGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot be assessed' -- categorize numeric values
WHEN OHXULGIN IS NULL THEN NULL 
ELSE SAFE_CAST(OHXULGIN AS STRING) 
 END as gingival_bleeding_ulq, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXLLGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Gingival bleeding detected' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXLLGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No evidence of gingival bleeding' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXLLGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot be assessed' -- categorize numeric values
WHEN OHXLLGIN IS NULL THEN NULL 
ELSE SAFE_CAST(OHXLLGIN AS STRING) 
 END as gingival_bleeding_llq, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXLRGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Gingival bleeding detected' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXLRGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No evidence of gingival bleeding' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXLRGIN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot be assessed' -- categorize numeric values
WHEN OHXLRGIN IS NULL THEN NULL 
ELSE SAFE_CAST(OHXLRGIN AS STRING) 
 END as gingival_bleeding_lrq, 

CASE
    WHEN OHD02CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD02CJM AS FLOAT64) 
 END as loa_mid_facial_2_fgm_cej, 

CASE
    WHEN OHD02PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD02PCM AS FLOAT64) 
 END as loa_mid_facial_2_pd, 

CASE
    WHEN OHD02LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD02LAM AS FLOAT64) 
 END as loa_mid_facial_2_calculated_la, 

CASE
    WHEN OHD02CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD02CJS AS FLOAT64) 
 END as loa_mesial_2_fgm_cej, 

CASE
    WHEN OHD02PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD02PCS AS FLOAT64) 
 END as loa_mesial_2_pd, 

CASE
    WHEN OHD02LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD02LAS AS FLOAT64) 
 END as loa_mesial_2_calculated_la, 

CASE
    WHEN OHD03CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD03CJM AS FLOAT64) 
 END as loa_mid_facial_3_fgm_cej, 

CASE
    WHEN OHD03PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD03PCM AS FLOAT64) 
 END as loa_mid_facial_3_pd, 

CASE
    WHEN OHD03LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD03LAM AS FLOAT64) 
 END as loa_mid_facial_3_calculated_la, 

CASE
    WHEN OHD03CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD03CJS AS FLOAT64) 
 END as loa_mesial_3_fgm_cej, 

CASE
    WHEN OHD03PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD03PCS AS FLOAT64) 
 END as loa_mesial_3_pd, 

CASE
    WHEN OHD03LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD03LAS AS FLOAT64) 
 END as loa_mesial_3_calculated_la, 

CASE
    WHEN OHD04CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD04CJM AS FLOAT64) 
 END as loa_mid_facial_4_fgm_cej, 

CASE
    WHEN OHD04PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD04PCM AS FLOAT64) 
 END as loa_mid_facial_4_pd, 

CASE
    WHEN OHD04LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD04LAM AS FLOAT64) 
 END as loa_mid_facial_4_calculated_la, 

CASE
    WHEN OHD04CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD04CJS AS FLOAT64) 
 END as loa_mesial_4_fgm_cej, 

CASE
    WHEN OHD04PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD04PCS AS FLOAT64) 
 END as loa_mesial_4_pd, 

CASE
    WHEN OHD04LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD04LAS AS FLOAT64) 
 END as loa_mesial_4_calculated_la, 

CASE
    WHEN OHD05CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD05CJM AS FLOAT64) 
 END as loa_mid_facial_5_fgm_cej, 

CASE
    WHEN OHD05PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD05PCM AS FLOAT64) 
 END as loa_mid_facial_5_pd, 

CASE
    WHEN OHD05LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD05LAM AS FLOAT64) 
 END as loa_mid_facial_5_calculated_la, 

CASE
    WHEN OHD05CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD05CJS AS FLOAT64) 
 END as loa_mesial_5_fgm_cej, 

CASE
    WHEN OHD05PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD05PCS AS FLOAT64) 
 END as loa_mesial_5_pd, 

CASE
    WHEN OHD05LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD05LAS AS FLOAT64) 
 END as loa_mesial_5_calculated_la, 

CASE
    WHEN OHD06CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD06CJM AS FLOAT64) 
 END as loa_mid_facial_6_fgm_cej, 

CASE
    WHEN OHD06PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD06PCM AS FLOAT64) 
 END as loa_mid_facial_6_pd, 

CASE
    WHEN OHD06LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD06LAM AS FLOAT64) 
 END as loa_mid_facial_6_calculated_la, 

CASE
    WHEN OHD06CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD06CJS AS FLOAT64) 
 END as loa_mesial_6_fgm_cej, 

CASE
    WHEN OHD06PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD06PCS AS FLOAT64) 
 END as loa_mesial_6_pd, 

CASE
    WHEN OHD06LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD06LAS AS FLOAT64) 
 END as loa_mesial_6_calculated_la, 

CASE
    WHEN OHD07CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD07CJM AS FLOAT64) 
 END as loa_mid_facial_7_fgm_cej, 

CASE
    WHEN OHD07PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD07PCM AS FLOAT64) 
 END as loa_mid_facial_7_pd, 

CASE
    WHEN OHD07LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD07LAM AS FLOAT64) 
 END as loa_mid_facial_7_calculated_la, 

CASE
    WHEN OHD07CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD07CJS AS FLOAT64) 
 END as loa_mesial_7_fgm_cej, 

CASE
    WHEN OHD07PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD07PCS AS FLOAT64) 
 END as loa_mesial_7_pd, 

CASE
    WHEN OHD07LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD07LAS AS FLOAT64) 
 END as loa_mesial_7_calculated_la, 

CASE
    WHEN OHD08CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD08CJM AS FLOAT64) 
 END as loa_mid_facial_8_fgm_cej, 

CASE
    WHEN OHD08PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD08PCM AS FLOAT64) 
 END as loa_mid_facial_8_pd, 

CASE
    WHEN OHD08LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD08LAM AS FLOAT64) 
 END as loa_mid_facial_8_calculated_la, 

CASE
    WHEN OHD08CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD08CJS AS FLOAT64) 
 END as loa_mesial_8_fgm_cej, 

CASE
    WHEN OHD08PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD08PCS AS FLOAT64) 
 END as loa_mesial_8_pd, 

CASE
    WHEN OHD08LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD08LAS AS FLOAT64) 
 END as loa_mesial_8_calculated_la, 

CASE
    WHEN OHD15CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD15CJM AS FLOAT64) 
 END as loa_mid_facial_15_fgm_cej, 

CASE
    WHEN OHD15PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD15PCM AS FLOAT64) 
 END as loa_mid_facial_15_pd, 

CASE
    WHEN OHD15LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD15LAM AS FLOAT64) 
 END as loa_mid_facial_15_calculated_la, 

CASE
    WHEN OHD15CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD15CJS AS FLOAT64) 
 END as loa_mesial_15_fgm_cej, 

CASE
    WHEN OHD15PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD15PCS AS FLOAT64) 
 END as loa_mesial_15_pd, 

CASE
    WHEN OHD15LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD15LAS AS FLOAT64) 
 END as loa_mesial_15_calculated_la, 

CASE
    WHEN OHD14CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD14CJM AS FLOAT64) 
 END as loa_mid_facial_14_fgm_cej, 

CASE
    WHEN OHD14PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD14PCM AS FLOAT64) 
 END as loa_mid_facial_14_pd, 

CASE
    WHEN OHD14LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD14LAM AS FLOAT64) 
 END as loa_mid_facial_14_calculated_la, 

CASE
    WHEN OHD14CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD14CJS AS FLOAT64) 
 END as loa_mesial_14_fgm_cej, 

CASE
    WHEN OHD14PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD14PCS AS FLOAT64) 
 END as loa_mesial_14_pd, 

CASE
    WHEN OHD14LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD14LAS AS FLOAT64) 
 END as loa_mesial_14_calculated_la, 

CASE
    WHEN OHD13CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD13CJM AS FLOAT64) 
 END as loa_mid_facial_13_fgm_cej, 

CASE
    WHEN OHD13PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD13PCM AS FLOAT64) 
 END as loa_mid_facial_13_pd, 

CASE
    WHEN OHD13LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD13LAM AS FLOAT64) 
 END as loa_mid_facial_13_calculated_la, 

CASE
    WHEN OHD13CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD13CJS AS FLOAT64) 
 END as loa_mesial_13_fgm_cej, 

CASE
    WHEN OHD13PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD13PCS AS FLOAT64) 
 END as loa_mesial_13_pd, 

CASE
    WHEN OHD13LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD13LAS AS FLOAT64) 
 END as loa_mesial_13_calculated_la, 

CASE
    WHEN OHD12CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD12CJM AS FLOAT64) 
 END as loa_mid_facial_12_fgm_cej, 

CASE
    WHEN OHD12PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD12PCM AS FLOAT64) 
 END as loa_mid_facial_12_pd, 

CASE
    WHEN OHD12LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD12LAM AS FLOAT64) 
 END as loa_mid_facial_12_calculated_la, 

CASE
    WHEN OHD12CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD12CJS AS FLOAT64) 
 END as loa_mesial_12_fgm_cej, 

CASE
    WHEN OHD12PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD12PCS AS FLOAT64) 
 END as loa_mesial_12_pd, 

CASE
    WHEN OHD12LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD12LAS AS FLOAT64) 
 END as loa_mesial_12_calculated_la, 

CASE
    WHEN OHD11CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD11CJM AS FLOAT64) 
 END as loa_mid_facial_11_fgm_cej, 

CASE
    WHEN OHD11PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD11PCM AS FLOAT64) 
 END as loa_mid_facial_11_pd, 

CASE
    WHEN OHD11LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD11LAM AS FLOAT64) 
 END as loa_mid_facial_11_calculated_la, 

CASE
    WHEN OHD11CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD11CJS AS FLOAT64) 
 END as loa_mesial_11_fgm_cej, 

CASE
    WHEN OHD11PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD11PCS AS FLOAT64) 
 END as loa_mesial_11_pd, 

CASE
    WHEN OHD11LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD11LAS AS FLOAT64) 
 END as loa_mesial_11_calculated_la, 

CASE
    WHEN OHD10CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD10CJM AS FLOAT64) 
 END as loa_mid_facial_10_fgm_cej, 

CASE
    WHEN OHD10PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD10PCM AS FLOAT64) 
 END as loa_mid_facial_10_pd, 

CASE
    WHEN OHD10LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD10LAM AS FLOAT64) 
 END as loa_mid_facial_10_calculated_la, 

CASE
    WHEN OHD10CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD10CJS AS FLOAT64) 
 END as loa_mesial_10_fgm_cej, 

CASE
    WHEN OHD10PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD10PCS AS FLOAT64) 
 END as loa_mesial_10_pd, 

CASE
    WHEN OHD10LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD10LAS AS FLOAT64) 
 END as loa_mesial_10_calculated_la, 

CASE
    WHEN OHD09CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD09CJM AS FLOAT64) 
 END as loa_mid_facial_9_fgm_cej, 

CASE
    WHEN OHD09PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD09PCM AS FLOAT64) 
 END as loa_mid_facial_9_pd, 

CASE
    WHEN OHD09LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD09LAM AS FLOAT64) 
 END as loa_mid_facial_9_calculated_la, 

CASE
    WHEN OHD09CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD09CJS AS FLOAT64) 
 END as loa_mesial_9_fgm_cej, 

CASE
    WHEN OHD09PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD09PCS AS FLOAT64) 
 END as loa_mesial_9_pd, 

CASE
    WHEN OHD09LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD09LAS AS FLOAT64) 
 END as loa_mesial_9_calculated_la, 

CASE
    WHEN OHD18CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD18CJM AS FLOAT64) 
 END as loa_mid_facial_18_fgm_cej, 

CASE
    WHEN OHD18PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD18PCM AS FLOAT64) 
 END as loa_mid_facial_18_pd, 

CASE
    WHEN OHD18LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD18LAM AS FLOAT64) 
 END as loa_mid_facial_18_calculated_la, 

CASE
    WHEN OHD18CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD18CJS AS FLOAT64) 
 END as loa_mesial_18_fgm_cej, 

CASE
    WHEN OHD18PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD18PCS AS FLOAT64) 
 END as loa_mesial_18_pd, 

CASE
    WHEN OHD18LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD18LAS AS FLOAT64) 
 END as loa_mesial_18_calculated_la, 

CASE
    WHEN OHD19CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD19CJM AS FLOAT64) 
 END as loa_mid_facial_19_fgm_cej, 

CASE
    WHEN OHD19PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD19PCM AS FLOAT64) 
 END as loa_mid_facial_19_pd, 

CASE
    WHEN OHD19LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD19LAM AS FLOAT64) 
 END as loa_mid_facial_19_calculated_la, 

CASE
    WHEN OHD19CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD19CJS AS FLOAT64) 
 END as loa_mesial_19_fgm_cej, 

CASE
    WHEN OHD19PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD19PCS AS FLOAT64) 
 END as loa_mesial_19_pd, 

CASE
    WHEN OHD19LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD19LAS AS FLOAT64) 
 END as loa_mesial_19_calculated_la, 

CASE
    WHEN OHD20CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD20CJM AS FLOAT64) 
 END as loa_mid_facial_20_fgm_cej, 

CASE
    WHEN OHD20PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD20PCM AS FLOAT64) 
 END as loa_mid_facial_20_pd, 

CASE
    WHEN OHD20LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD20LAM AS FLOAT64) 
 END as loa_mid_facial_20_calculated_la, 

CASE
    WHEN OHD20CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD20CJS AS FLOAT64) 
 END as loa_mesial_20_fgm_cej, 

CASE
    WHEN OHD20PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD20PCS AS FLOAT64) 
 END as loa_mesial_20_pd, 

CASE
    WHEN OHD20LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD20LAS AS FLOAT64) 
 END as loa_mesial_20_calculated_la, 

CASE
    WHEN OHD21CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD21CJM AS FLOAT64) 
 END as loa_mid_facial_21_fgm_cej, 

CASE
    WHEN OHD21PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD21PCM AS FLOAT64) 
 END as loa_mid_facial_21_pd, 

CASE
    WHEN OHD21LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD21LAM AS FLOAT64) 
 END as loa_mid_facial_21_calculated_la, 

CASE
    WHEN OHD21CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD21CJS AS FLOAT64) 
 END as loa_mesial_21_fgm_cej, 

CASE
    WHEN OHD21PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD21PCS AS FLOAT64) 
 END as loa_mesial_21_pd, 

CASE
    WHEN OHD21LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD21LAS AS FLOAT64) 
 END as loa_mesial_21_calculated_la, 

CASE
    WHEN OHD22CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD22CJM AS FLOAT64) 
 END as loa_mid_facial_22_fgm_cej, 

CASE
    WHEN OHD22PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD22PCM AS FLOAT64) 
 END as loa_mid_facial_22_pd, 

CASE
    WHEN OHD22LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD22LAM AS FLOAT64) 
 END as loa_mid_facial_22_calculated_la, 

CASE
    WHEN OHD22CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD22CJS AS FLOAT64) 
 END as loa_mesial_22_fgm_cej, 

CASE
    WHEN OHD22PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD22PCS AS FLOAT64) 
 END as loa_mesial_22_pd, 

CASE
    WHEN OHD22LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD22LAS AS FLOAT64) 
 END as loa_mesial_22_calculated_la, 

CASE
    WHEN OHD23CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD23CJM AS FLOAT64) 
 END as loa_mid_facial_23_fgm_cej, 

CASE
    WHEN OHD23PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD23PCM AS FLOAT64) 
 END as loa_mid_facial_23_pd, 

CASE
    WHEN OHD23LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD23LAM AS FLOAT64) 
 END as loa_mid_facial_23_calculated_la, 

CASE
    WHEN OHD23CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD23CJS AS FLOAT64) 
 END as loa_mesial_23_fgm_cej, 

CASE
    WHEN OHD23PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD23PCS AS FLOAT64) 
 END as loa_mesial_23_pd, 

CASE
    WHEN OHD23LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD23LAS AS FLOAT64) 
 END as loa_mesial_23_calculated_la, 

CASE
    WHEN OHD24CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD24CJM AS FLOAT64) 
 END as loa_mid_facial_24_fgm_cej, 

CASE
    WHEN OHD24PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD24PCM AS FLOAT64) 
 END as loa_mid_facial_24_pd, 

CASE
    WHEN OHD24LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD24LAM AS FLOAT64) 
 END as loa_mid_facial_24_calculated_la, 

CASE
    WHEN OHD24CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD24CJS AS FLOAT64) 
 END as loa_mesial_24_fgm_cej, 

CASE
    WHEN OHD24PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD24PCS AS FLOAT64) 
 END as loa_mesial_24_pd, 

CASE
    WHEN OHD24LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD24LAS AS FLOAT64) 
 END as loa_mesial_24_calculated_la, 

CASE
    WHEN OHD31CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD31CJM AS FLOAT64) 
 END as loa_mid_facial_31_fgm_cej, 

CASE
    WHEN OHD31PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD31PCM AS FLOAT64) 
 END as loa_mid_facial_31_pd, 

CASE
    WHEN OHD31LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD31LAM AS FLOAT64) 
 END as loa_mid_facial_31_calculated_la, 

CASE
    WHEN OHD31CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD31CJS AS FLOAT64) 
 END as loa_mesial_31_fgm_cej, 

CASE
    WHEN OHD31PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD31PCS AS FLOAT64) 
 END as loa_mesial_31_pd, 

CASE
    WHEN OHD31LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD31LAS AS FLOAT64) 
 END as loa_mesial_31_calculated_la, 

CASE
    WHEN OHD30CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD30CJM AS FLOAT64) 
 END as loa_mid_facial_30_fgm_cej, 

CASE
    WHEN OHD30PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD30PCM AS FLOAT64) 
 END as loa_mid_facial_30_pd, 

CASE
    WHEN OHD30LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD30LAM AS FLOAT64) 
 END as loa_mid_facial_30_calculated_la, 

CASE
    WHEN OHD30CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD30CJS AS FLOAT64) 
 END as loa_mesial_30_fgm_cej, 

CASE
    WHEN OHD30PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD30PCS AS FLOAT64) 
 END as loa_mesial_30_pd, 

CASE
    WHEN OHD30LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD30LAS AS FLOAT64) 
 END as loa_mesial_30_calculated_la, 

CASE
    WHEN OHD29CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD29CJM AS FLOAT64) 
 END as loa_mid_facial_29_fgm_cej, 

CASE
    WHEN OHD29PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD29PCM AS FLOAT64) 
 END as loa_mid_facial_29_pd, 

CASE
    WHEN OHD29LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD29LAM AS FLOAT64) 
 END as loa_mid_facial_29_calculated_la, 

CASE
    WHEN OHD29CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD29CJS AS FLOAT64) 
 END as loa_mesial_29_fgm_cej, 

CASE
    WHEN OHD29PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD29PCS AS FLOAT64) 
 END as loa_mesial_29_pd, 

CASE
    WHEN OHD29LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD29LAS AS FLOAT64) 
 END as loa_mesial_29_calculated_la, 

CASE
    WHEN OHD28CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD28CJM AS FLOAT64) 
 END as loa_mid_facial_28_fgm_cej, 

CASE
    WHEN OHD28PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD28PCM AS FLOAT64) 
 END as loa_mid_facial_28_pd, 

CASE
    WHEN OHD28LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD28LAM AS FLOAT64) 
 END as loa_mid_facial_28_calculated_la, 

CASE
    WHEN OHD28CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD28CJS AS FLOAT64) 
 END as loa_mesial_28_fgm_cej, 

CASE
    WHEN OHD28PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD28PCS AS FLOAT64) 
 END as loa_mesial_28_pd, 

CASE
    WHEN OHD28LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD28LAS AS FLOAT64) 
 END as loa_mesial_28_calculated_la, 

CASE
    WHEN OHD27CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD27CJM AS FLOAT64) 
 END as loa_mid_facial_27_fgm_cej, 

CASE
    WHEN OHD27PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD27PCM AS FLOAT64) 
 END as loa_mid_facial_27_pd, 

CASE
    WHEN OHD27LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD27LAM AS FLOAT64) 
 END as loa_mid_facial_27_calculated_la, 

CASE
    WHEN OHD27CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD27CJS AS FLOAT64) 
 END as loa_mesial_27_fgm_cej, 

CASE
    WHEN OHD27PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD27PCS AS FLOAT64) 
 END as loa_mesial_27_pd, 

CASE
    WHEN OHD27LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD27LAS AS FLOAT64) 
 END as loa_mesial_27_calculated_la, 

CASE
    WHEN OHD26CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD26CJM AS FLOAT64) 
 END as loa_mid_facial_26_fgm_cej, 

CASE
    WHEN OHD26PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD26PCM AS FLOAT64) 
 END as loa_mid_facial_26_pd, 

CASE
    WHEN OHD26LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD26LAM AS FLOAT64) 
 END as loa_mid_facial_26_calculated_la, 

CASE
    WHEN OHD26CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD26CJS AS FLOAT64) 
 END as loa_mesial_26_fgm_cej, 

CASE
    WHEN OHD26PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD26PCS AS FLOAT64) 
 END as loa_mesial_26_pd, 

CASE
    WHEN OHD26LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD26LAS AS FLOAT64) 
 END as loa_mesial_26_calculated_la, 

CASE
    WHEN OHD25CJM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD25CJM AS FLOAT64) 
 END as loa_mid_facial_25_fgm_cej, 

CASE
    WHEN OHD25PCM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD25PCM AS FLOAT64) 
 END as loa_mid_facial_25_pd, 

CASE
    WHEN OHD25LAM IS NULL THEN NULL 
ELSE SAFE_CAST(OHD25LAM AS FLOAT64) 
 END as loa_mid_facial_25_calculated_la, 

CASE
    WHEN OHD25CJS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD25CJS AS FLOAT64) 
 END as loa_mesial_25_fgm_cej, 

CASE
    WHEN OHD25PCS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD25PCS AS FLOAT64) 
 END as loa_mesial_25_pd, 

CASE
    WHEN OHD25LAS IS NULL THEN NULL 
ELSE SAFE_CAST(OHD25LAS AS FLOAT64) 
 END as loa_mesial_25_calculated_la, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_oral_health_periodontal_examination') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/OHXPER_G.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2009-2010/OHXPER_F.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/OHXPERIO.htm
*/
