SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Complete' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Partial' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHAEXSTS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not Done' -- categorize numeric values
WHEN OHAEXSTS IS NULL THEN NULL 
ELSE SAFE_CAST(OHAEXSTS AS STRING) 
 END as overall_oral_health_exam_status, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX08HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX08HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX08HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX08HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX08HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX08HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX08HTC AS STRING) 
 END as tooth_count_8, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX07HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX07HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX07HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX07HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX07HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX07HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX07HTC AS STRING) 
 END as tooth_count_7, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX06HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX06HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX06HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX06HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX06HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX06HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX06HTC AS STRING) 
 END as tooth_count_6, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX05HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX05HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX05HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX05HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX05HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX05HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX05HTC AS STRING) 
 END as tooth_count_5, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX04HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX04HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX04HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX04HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX04HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX04HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX04HTC AS STRING) 
 END as tooth_count_4, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX03HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX03HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX03HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX03HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX03HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX03HTC AS STRING) 
 END as tooth_count_3, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX02HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX02HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX02HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX02HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX02HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX02HTC AS STRING) 
 END as tooth_count_2, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX01HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX01HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX01HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX01HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX01HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX01HTC AS STRING) 
 END as tooth_count_1, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX09HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX09HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX09HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX09HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX09HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX09HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX09HTC AS STRING) 
 END as tooth_count_9, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX10HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX10HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX10HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX10HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX10HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX10HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX10HTC AS STRING) 
 END as tooth_count_10, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX11HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX11HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX11HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX11HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX11HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX11HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX11HTC AS STRING) 
 END as tooth_count_11, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX12HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX12HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX12HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX12HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX12HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX12HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX12HTC AS STRING) 
 END as tooth_count_12, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX13HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX13HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX13HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX13HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX13HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX13HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX13HTC AS STRING) 
 END as tooth_count_13, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX14HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX14HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX14HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX14HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX14HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX14HTC AS STRING) 
 END as tooth_count_14, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX15HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX15HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX15HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX15HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX15HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX15HTC AS STRING) 
 END as tooth_count_15, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX16HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX16HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX16HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX16HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX16HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX16HTC AS STRING) 
 END as tooth_count_16, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX24HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX24HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX24HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX24HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX24HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX24HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX24HTC AS STRING) 
 END as tooth_count_24, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX23HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX23HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX23HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX23HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX23HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX23HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX23HTC AS STRING) 
 END as tooth_count_23, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX22HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX22HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX22HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX22HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX22HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX22HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX22HTC AS STRING) 
 END as tooth_count_22, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX21HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX21HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX21HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX21HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX21HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX21HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX21HTC AS STRING) 
 END as tooth_count_21, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX20HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX20HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX20HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX20HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX20HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX20HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX20HTC AS STRING) 
 END as tooth_count_20, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX19HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX19HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX19HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX19HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX19HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX19HTC AS STRING) 
 END as tooth_count_19, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX18HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX18HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX18HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX18HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX18HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX18HTC AS STRING) 
 END as tooth_count_18, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX17HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX17HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX17HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX17HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX17HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX17HTC AS STRING) 
 END as tooth_count_17, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX25HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX25HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX25HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX25HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX25HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX25HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX25HTC AS STRING) 
 END as tooth_count_25, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX26HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX26HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX26HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX26HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX26HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX26HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX26HTC AS STRING) 
 END as tooth_count_26, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX27HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX27HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX27HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX27HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX27HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX27HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX27HTC AS STRING) 
 END as tooth_count_27, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX28HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX28HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX28HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX28HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX28HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX28HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX28HTC AS STRING) 
 END as tooth_count_28, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX29HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Primary tooth (deciduous) present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX29HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX29HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX29HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX29HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX29HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX29HTC AS STRING) 
 END as tooth_count_29, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX30HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX30HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX30HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX30HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX30HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX30HTC AS STRING) 
 END as tooth_count_30, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX31HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX31HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX31HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX31HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX31HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX31HTC AS STRING) 
 END as tooth_count_31, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX32HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Permanent tooth present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX32HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Tooth not present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX32HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Permanent dental root fragment present' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHX32HTC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHX32HTC IS NULL THEN NULL 
ELSE SAFE_CAST(OHX32HTC AS STRING) 
 END as tooth_count_32, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXDECAY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXDECAY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXDECAY AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHXDECAY IS NULL THEN NULL 
ELSE SAFE_CAST(OHXDECAY AS STRING) 
 END as dental_decay_present, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXREST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXREST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXREST AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHXREST IS NULL THEN NULL 
ELSE SAFE_CAST(OHXREST AS STRING) 
 END as dental_restoration_present, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXSEAL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXSEAL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXSEAL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Could not assess' -- categorize numeric values
WHEN OHXSEAL IS NULL THEN NULL 
ELSE SAFE_CAST(OHXSEAL AS STRING) 
 END as dental_sealant_present, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ1 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ1 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ1 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ1 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ1 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCRZ1 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCRZ1 AS STRING) 
 END as right_zone_1, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCRZ2 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCRZ2 AS STRING) 
 END as right_zone_2, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ3 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ3 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ3 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ3 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ3 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCRZ3 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCRZ3 AS STRING) 
 END as right_zone_3, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCRZ4 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCRZ4 AS STRING) 
 END as right_zone_4, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ5 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ5 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ5 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ5 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ5 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCRZ5 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCRZ5 AS STRING) 
 END as right_zone_5, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ6 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ6 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ6 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ6 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ6 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCRZ6 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCRZ6 AS STRING) 
 END as right_zone_6, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ7 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ7 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ7 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ7 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ7 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCRZ7 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCRZ7 AS STRING) 
 END as right_zone_7, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ8 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ8 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ8 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ8 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCRZ8 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCRZ8 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCRZ8 AS STRING) 
 END as right_zone_8, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ1 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ1 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ1 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ1 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ1 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCLZ1 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCLZ1 AS STRING) 
 END as left_zone_1, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ2 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCLZ2 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCLZ2 AS STRING) 
 END as left_zone_2, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ3 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ3 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ3 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ3 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ3 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCLZ3 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCLZ3 AS STRING) 
 END as left_zone_3, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ4 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCLZ4 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCLZ4 AS STRING) 
 END as left_zone_4, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ5 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ5 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ5 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ5 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ5 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCLZ5 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCLZ5 AS STRING) 
 END as left_zone_5, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ6 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ6 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ6 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ6 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ6 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCLZ6 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCLZ6 AS STRING) 
 END as left_zone_6, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ7 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ7 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ7 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ7 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ7 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCLZ7 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCLZ7 AS STRING) 
 END as left_zone_7, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ8 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ8 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ8 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ8 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCLZ8 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCLZ8 IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCLZ8 AS STRING) 
 END as left_zone_8, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCANT AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'No anterior functional contact' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCANT AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two natural teeth' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCANT AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between a natural tooth / fixed prosthesis and a removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCANT AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Functional contact present between two removable prosthesis' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHXFCANT AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHXFCANT IS NULL THEN NULL 
ELSE SAFE_CAST(OHXFCANT AS STRING) 
 END as anterior_zone, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ410 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ410 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ410 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ410 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN OHQ410 IS NULL THEN NULL 
ELSE SAFE_CAST(OHQ410 AS STRING) 
 END as removable_complete_partial_max_denture, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN OHQ420 IS NULL THEN NULL 
ELSE SAFE_CAST(OHQ420 AS STRING) 
 END as wears_complete_partial_max_denture, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ430 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ430 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ430 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ430 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN OHQ430 IS NULL THEN NULL 
ELSE SAFE_CAST(OHQ430 AS STRING) 
 END as removable_complete_partial_mand_denture, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHQ440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN OHQ440 IS NULL THEN NULL 
ELSE SAFE_CAST(OHQ440 AS STRING) 
 END as wears_complete_partial_mand_denture, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHAPOS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHAPOS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(OHAPOS AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Cannot assess' -- categorize numeric values
WHEN OHAPOS IS NULL THEN NULL 
ELSE SAFE_CAST(OHAPOS AS STRING) 
 END as was_participant_exam_position_recumbent, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_oral_health_examination') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2007-2008/OHX_E.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/OHX_D.htm
*/
