SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ605 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ605 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ605 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ605 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ605 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ605 AS STRING) 
 END as vigorous_work_activity, 

CASE
    WHEN SAFE_CAST(PAQ610 AS FLOAT64) > 18.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAQ610 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ610 AS FLOAT64) 
 END as number_of_days_vigorous_work, 

CASE
    WHEN SAFE_CAST(PAD615 AS FLOAT64) > 851.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAD615 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD615 AS FLOAT64) 
 END as minutes_vigorous_intensity_work, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ620 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ620 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ620 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ620 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ620 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ620 AS STRING) 
 END as moderate_work_activity, 

CASE
    WHEN SAFE_CAST(PAQ625 AS FLOAT64) > 18.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAQ625 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ625 AS FLOAT64) 
 END as number_of_days_moderate_work, 

CASE
    WHEN SAFE_CAST(PAD630 AS FLOAT64) > 851.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAD630 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD630 AS FLOAT64) 
 END as minutes_moderate_intensity_work, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ635 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ635 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ635 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ635 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ635 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ635 AS STRING) 
 END as walk_or_bicycle, 

CASE
    WHEN SAFE_CAST(PAQ640 AS FLOAT64) > 18.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAQ640 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ640 AS FLOAT64) 
 END as number_of_days_walk_or_bicycle, 

CASE
    WHEN SAFE_CAST(PAD645 AS FLOAT64) > 671.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAD645 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD645 AS FLOAT64) 
 END as minutes_walk_bicycle_for_transportation, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ650 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ650 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ650 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ650 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ650 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ650 AS STRING) 
 END as vigorous_recreational_activities, 

CASE
    WHEN SAFE_CAST(PAQ655 AS FLOAT64) > 18.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAQ655 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ655 AS FLOAT64) 
 END as days_vigorous_recreational_activities, 

CASE
    WHEN SAFE_CAST(PAD660 AS FLOAT64) > 491.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAD660 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD660 AS FLOAT64) 
 END as minutes_vigorous_recreational_activities, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ665 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ665 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ665 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ665 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ665 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ665 AS STRING) 
 END as moderate_recreational_activities, 

CASE
    WHEN SAFE_CAST(PAQ670 AS FLOAT64) > 18.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAQ670 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ670 AS FLOAT64) 
 END as days_moderate_recreational_activities, 

CASE
    WHEN SAFE_CAST(PAD675 AS FLOAT64) > 551.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAD675 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD675 AS FLOAT64) 
 END as minutes_moderate_recreational_activities, 

CASE
    WHEN SAFE_CAST(PAD680 AS FLOAT64) > 1331.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAD680 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD680 AS FLOAT64) 
 END as minutes_sedentary_activity, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ706 AS FLOAT64),0) AS INT64) AS STRING) = '0' THEN '0 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ706 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN '1 day' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ706 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '2 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ706 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN '3 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ706 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN '4 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ706 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN '5 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ706 AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN '6 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ706 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN '7 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ706 AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ706 AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN PAQ706 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ706 AS STRING) 
 END as days_physically_active_at_least_60_min, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ710 AS FLOAT64),0) AS INT64) AS STRING) = '0' THEN 'Less than 1 hour,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ710 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN '1 hour,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ710 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '2 hours,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ710 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN '3 hours,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ710 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN '4 hours, or' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ710 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN '5 hours or more, or' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ710 AS FLOAT64),0) AS INT64) AS STRING) = '8' THEN '{You dont/SP does not} watch TV or videos' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ710 AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ710 AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN PAQ710 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ710 AS STRING) 
 END as hours_watch_tv_or_videos_past_30_days, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ715 AS FLOAT64),0) AS INT64) AS STRING) = '0' THEN 'Less than 1 hour,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ715 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN '1 hour,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ715 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '2 hours,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ715 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN '3 hours,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ715 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN '4 hours, or' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ715 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN '5 hours or more, or' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ715 AS FLOAT64),0) AS INT64) AS STRING) = '8' THEN '{you do not/SP does not} use a computer outside of school' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ715 AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ715 AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN PAQ715 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ715 AS STRING) 
 END as hours_use_computer_past_30_days, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ722 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ722 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ722 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ722 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ722 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ722 AS STRING) 
 END as any_physical_activities_past_7_days, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724A AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'AEROBICS/WEIGHT TRAINING/GYM/EXERCISE' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724A AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724A AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN PAQ724A IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724A AS STRING) 
 END as physical_activity_aerobics, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724B AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'BASEBALL/SOFTBALL/CATCH/PITCHING' -- categorize string values 
WHEN PAQ724B IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724B AS STRING) 
 END as physical_activity_baseball, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724C AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'BASKETBALL' -- categorize string values 
WHEN PAQ724C IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724C AS STRING) 
 END as physical_activity_basketball, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724D AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'BIKE RIDING/DIRT BIKING/MOUNTAIN BIKING' -- categorize string values 
WHEN PAQ724D IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724D AS STRING) 
 END as physical_activity_bike_riding, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724E AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'CHEERLEADING' -- categorize string values 
WHEN PAQ724E IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724E AS STRING) 
 END as physical_activity_cheerleading, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724F AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN 'DANCE' -- categorize string values 
WHEN PAQ724F IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724F AS STRING) 
 END as physical_activity_dance, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724G AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'FIELD HOCKEY/STREET HOCKEY/ROLLER HOCKEY' -- categorize string values 
WHEN PAQ724G IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724G AS STRING) 
 END as physical_activity_field_hockey, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724H AS FLOAT64),0) AS INT64) AS STRING) = '8' THEN 'FOOTBALL' -- categorize string values 
WHEN PAQ724H IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724H AS STRING) 
 END as physical_activity_football, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724I AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'GOLF' -- categorize string values 
WHEN PAQ724I IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724I AS STRING) 
 END as physical_activity_golf, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724J AS FLOAT64),0) AS INT64) AS STRING) = '10' THEN 'GYMNASTICS/TUMBLING' -- categorize string values 
WHEN PAQ724J IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724J AS STRING) 
 END as physical_activity_gymnastics, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724K AS FLOAT64),0) AS INT64) AS STRING) = '11' THEN 'HIKING' -- categorize string values 
WHEN PAQ724K IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724K AS STRING) 
 END as physical_activity_hiking, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724L AS FLOAT64),0) AS INT64) AS STRING) = '12' THEN 'ICE HOCKEY' -- categorize string values 
WHEN PAQ724L IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724L AS STRING) 
 END as physical_activity_ice_hockey, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724M AS FLOAT64),0) AS INT64) AS STRING) = '13' THEN 'ICE SKATING' -- categorize string values 
WHEN PAQ724M IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724M AS STRING) 
 END as physical_activity_ice_skating, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724N AS FLOAT64),0) AS INT64) AS STRING) = '14' THEN 'JUMPING ROPE' -- categorize string values 
WHEN PAQ724N IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724N AS STRING) 
 END as physical_activity_jumping_rope, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724O AS FLOAT64),0) AS INT64) AS STRING) = '15' THEN 'LACROSSE' -- categorize string values 
WHEN PAQ724O IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724O AS STRING) 
 END as physical_activity_lacrosse, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724P AS FLOAT64),0) AS INT64) AS STRING) = '16' THEN 'MARTIAL ARTS (KARATE/TAE KWON DO/JUDO, ETC.)' -- categorize string values 
WHEN PAQ724P IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724P AS STRING) 
 END as physical_activity_martial_arts, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724Q AS FLOAT64),0) AS INT64) AS STRING) = '17' THEN 'PLAYING GAMES (PROBE: WERE YOU PHYSICALLY ACTIVE? IF NO, DONT COUNT)' -- categorize string values 
WHEN PAQ724Q IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724Q AS STRING) 
 END as physical_activity_playing_games, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724R AS FLOAT64),0) AS INT64) AS STRING) = '18' THEN 'ROLLER BLADING/ROLLER SKATING' -- categorize string values 
WHEN PAQ724R IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724R AS STRING) 
 END as physical_activity_roller_blading, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724S AS FLOAT64),0) AS INT64) AS STRING) = '19' THEN 'RUNNING/JOGGING' -- categorize string values 
WHEN PAQ724S IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724S AS STRING) 
 END as physical_activity_running, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724T AS FLOAT64),0) AS INT64) AS STRING) = '20' THEN 'SCOOTER RIDING (PROBE: DOES IT HAVE A MOTOR? IF YES, DONT COUNT)' -- categorize string values 
WHEN PAQ724T IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724T AS STRING) 
 END as physical_activity_scooter_riding, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724U AS FLOAT64),0) AS INT64) AS STRING) = '21' THEN 'SKATEBOARDING' -- categorize string values 
WHEN PAQ724U IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724U AS STRING) 
 END as physical_activity_skateboarding, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724V AS FLOAT64),0) AS INT64) AS STRING) = '22' THEN 'SOCCER' -- categorize string values 
WHEN PAQ724V IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724V AS STRING) 
 END as physical_activity_soccer, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724W AS FLOAT64),0) AS INT64) AS STRING) = '23' THEN 'SWIMMING' -- categorize string values 
WHEN PAQ724W IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724W AS STRING) 
 END as physical_activity_swimming, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724X AS FLOAT64),0) AS INT64) AS STRING) = '24' THEN 'TENNIS' -- categorize string values 
WHEN PAQ724X IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724X AS STRING) 
 END as physical_activity_tennis, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724Y AS FLOAT64),0) AS INT64) AS STRING) = '25' THEN 'TRACK & FIELD' -- categorize string values 
WHEN PAQ724Y IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724Y AS STRING) 
 END as physical_activity_track_field, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724Z AS FLOAT64),0) AS INT64) AS STRING) = '26' THEN 'VOLLEYBALL' -- categorize string values 
WHEN PAQ724Z IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724Z AS STRING) 
 END as physical_activity_volleyball, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724AA AS FLOAT64),0) AS INT64) AS STRING) = '27' THEN 'WALKING' -- categorize string values 
WHEN PAQ724AA IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724AA AS STRING) 
 END as physical_activity_walking, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724AB AS FLOAT64),0) AS INT64) AS STRING) = '28' THEN 'WRESTLING' -- categorize string values 
WHEN PAQ724AB IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724AB AS STRING) 
 END as physical_activity_wrestling, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724AC AS FLOAT64),0) AS INT64) AS STRING) = '29' THEN 'FRISBEE/ULTIMATE FRISBEE' -- categorize string values 
WHEN PAQ724AC IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724AC AS STRING) 
 END as physical_activity_frisbee, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724AD AS FLOAT64),0) AS INT64) AS STRING) = '30' THEN 'BACKYARD/PLAYGROUND GAMES AND ACTIVITIES' -- categorize string values 
WHEN PAQ724AD IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724AD AS STRING) 
 END as physical_activity_backyard_games, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724AE AS FLOAT64),0) AS INT64) AS STRING) = '31' THEN 'TRAMPOLINE' -- categorize string values 
WHEN PAQ724AE IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724AE AS STRING) 
 END as physical_activity_trampoline, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724AF AS FLOAT64),0) AS INT64) AS STRING) = '32' THEN 'HORSEBACK RIDING' -- categorize string values 
WHEN PAQ724AF IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724AF AS STRING) 
 END as physical_activity_horseback_riding, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ724CM AS FLOAT64),0) AS INT64) AS STRING) = '91' THEN 'OTHER (SPECIFY)' -- categorize string values 
WHEN PAQ724CM IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ724CM AS STRING) 
 END as physical_activity_other, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ731 AS FLOAT64),0) AS INT64) AS STRING) = '0' THEN '0 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ731 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN '1 day' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ731 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '2 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ731 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN '3 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ731 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN '4 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ731 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN '5 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ731 AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN '6 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ731 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN '7 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ731 AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ731 AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN PAQ731 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ731 AS STRING) 
 END as days_played_active_video_games, 

CASE
    WHEN SAFE_CAST(PAD733 AS FLOAT64) > 911.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN PAD733 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD733 AS FLOAT64) 
 END as minutes_play_active_video_games, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ677 AS FLOAT64),0) AS INT64) AS STRING) = '0' THEN '0 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ677 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN '1 day' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ677 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '2 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ677 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN '3 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ677 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN '4 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ677 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN '5 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ677 AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN '6 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ677 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN '7 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ677 AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ677 AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN PAQ677 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ677 AS STRING) 
 END as past_wk_days_cardiovascular_exercise, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ678 AS FLOAT64),0) AS INT64) AS STRING) = '0' THEN '0 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ678 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN '1 day' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ678 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '2 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ678 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN '3 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ678 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN '4 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ678 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN '5 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ678 AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN '6 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ678 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN '7 days' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ678 AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ678 AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN PAQ678 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ678 AS STRING) 
 END as past_wk_days_strengthened_muscles, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ740 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ740 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ740 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ740 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ740 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ740 AS STRING) 
 END as use_school_facilities_at_lunch, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ742 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ742 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ742 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ742 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ742 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ742 AS STRING) 
 END as use_school_facilities_for_physical_activ, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ744 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ744 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ744 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ744 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ744 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ744 AS STRING) 
 END as have_pe_during_school_days, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ746 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN '1 day a week' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ746 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '2 days a week' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ746 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN '3 days a week' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ746 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN '4 days a week, or' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ746 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'Every day' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ746 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ746 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ746 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ746 AS STRING) 
 END as how_often_do_you_have_pe_or_gym, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ748 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Less than 30 minutes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ748 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '30-45 minutes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ748 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'More than 45 minutes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ748 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ748 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ748 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ748 AS STRING) 
 END as how_long_is_the_pe_or_gym_class, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ755 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ755 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ755 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ755 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ755 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ755 AS STRING) 
 END as participate_in_school_sports, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759A AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'BASEBALL/SOFTBALL' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759A AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759A AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN PAQ759A IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759A AS STRING) 
 END as participate_in_baseball, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759B AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'BASKETBALL' -- categorize string values 
WHEN PAQ759B IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759B AS STRING) 
 END as participate_in_basketball, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759C AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'BOCCE BALL' -- categorize string values 
WHEN PAQ759C IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759C AS STRING) 
 END as participate_in_bocce_ball, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759D AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'CHEERLEADING' -- categorize string values 
WHEN PAQ759D IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759D AS STRING) 
 END as participate_in_cheerleading, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759E AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'FOOTBALL' -- categorize string values 
WHEN PAQ759E IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759E AS STRING) 
 END as participate_in_football, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759F AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN 'GOLF' -- categorize string values 
WHEN PAQ759F IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759F AS STRING) 
 END as participate_in_golf, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759G AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'GYMNASTICS' -- categorize string values 
WHEN PAQ759G IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759G AS STRING) 
 END as participate_in_gymnastics, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759H AS FLOAT64),0) AS INT64) AS STRING) = '8' THEN 'HOCKEY' -- categorize string values 
WHEN PAQ759H IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759H AS STRING) 
 END as participate_in_hockey, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759I AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'LACROSSE' -- categorize string values 
WHEN PAQ759I IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759I AS STRING) 
 END as participate_in_lacrosse, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759J AS FLOAT64),0) AS INT64) AS STRING) = '10' THEN 'SOCCER' -- categorize string values 
WHEN PAQ759J IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759J AS STRING) 
 END as participate_in_soccer, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759K AS FLOAT64),0) AS INT64) AS STRING) = '11' THEN 'SWIMMING/DIVING' -- categorize string values 
WHEN PAQ759K IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759K AS STRING) 
 END as participate_in_swimming_diving, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759L AS FLOAT64),0) AS INT64) AS STRING) = '12' THEN 'TENNIS' -- categorize string values 
WHEN PAQ759L IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759L AS STRING) 
 END as participate_in_tennis, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759M AS FLOAT64),0) AS INT64) AS STRING) = '13' THEN 'TRACK AND FIELD' -- categorize string values 
WHEN PAQ759M IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759M AS STRING) 
 END as participate_in_track_and_field, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759N AS FLOAT64),0) AS INT64) AS STRING) = '14' THEN 'VOLLEYBALL' -- categorize string values 
WHEN PAQ759N IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759N AS STRING) 
 END as participate_in_volleyball, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759O AS FLOAT64),0) AS INT64) AS STRING) = '15' THEN 'WRESTLING' -- categorize string values 
WHEN PAQ759O IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759O AS STRING) 
 END as participate_in_wrestling, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759P AS FLOAT64),0) AS INT64) AS STRING) = '16' THEN 'OTHER (SPECIFY)' -- categorize string values 
WHEN PAQ759P IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759P AS STRING) 
 END as participate_in_other_specify, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759Q AS FLOAT64),0) AS INT64) AS STRING) = '17' THEN 'DANCE' -- categorize string values 
WHEN PAQ759Q IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759Q AS STRING) 
 END as participate_in_dance, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759R AS FLOAT64),0) AS INT64) AS STRING) = '18' THEN 'FRISBEE/ULTIMATE FRISBEE' -- categorize string values 
WHEN PAQ759R IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759R AS STRING) 
 END as participate_in_frisbee, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759S AS FLOAT64),0) AS INT64) AS STRING) = '19' THEN 'RUNNING' -- categorize string values 
WHEN PAQ759S IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759S AS STRING) 
 END as participate_in_running, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759T AS FLOAT64),0) AS INT64) AS STRING) = '20' THEN 'TRAMPOLINE' -- categorize string values 
WHEN PAQ759T IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759T AS STRING) 
 END as participate_in_trampoline, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759U AS FLOAT64),0) AS INT64) AS STRING) = '21' THEN 'MARTIAL ARTS' -- categorize string values 
WHEN PAQ759U IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759U AS STRING) 
 END as participate_in_martial_arts, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ762 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ762 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ762 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ762 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ762 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ762 AS STRING) 
 END as do_you_have_recess_during_school, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ764 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN '1 day a week' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ764 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '2 days a week' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ764 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN '3 days a week' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ764 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN '4 days a week, or' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ764 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'Every day' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ764 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ764 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ764 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ764 AS STRING) 
 END as how_often_do_you_have_recess, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ766 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Less than 10 minutes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ766 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '10-15 minutes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ766 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN '16-30 minutes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ766 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'More than 30 minutes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ766 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ766 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ766 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ766 AS STRING) 
 END as how_long_is_the_recess_period, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ679 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'less than 10 minutes,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ679 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN '10-15 minutes,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ679 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN '16-30 minutes,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ679 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN '31-45 minutes,' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ679 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN '46-60 minutes, or' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ679 AS FLOAT64),0) AS INT64) AS STRING) = '6' THEN 'More than 60 minutes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ679 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ679 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ679 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ679 AS STRING) 
 END as how_much_exercise_for_good_health, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ750 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Strongly agree' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ750 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Agree' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ750 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Neither agree nor disagree' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ750 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'Disagree' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ750 AS FLOAT64),0) AS INT64) AS STRING) = '5' THEN 'Strongly disagree' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ750 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ750 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ750 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ750 AS STRING) 
 END as enjoy_participating_in_pe_or_recess, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ770 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ770 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ770 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ770 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ770 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ770 AS STRING) 
 END as receive_physical_fitness_award_past_yr, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ772A AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Fitnessgram' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ772A AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ772A AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN PAQ772A IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ772A AS STRING) 
 END as fitness_award_fitnessgram, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ772B AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Presidents Challenge' -- categorize string values 
WHEN PAQ772B IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ772B AS STRING) 
 END as fitness_award_president_s_challenge, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ772C AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Other (specify)' -- categorize string values 
WHEN PAQ772C IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ772C AS STRING) 
 END as fitness_award_other_specify, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(PAQ759V AS FLOAT64),0) AS INT64) AS STRING) = '22' THEN 'WALKING' -- categorize string values 
WHEN PAQ759V IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ759V AS STRING) 
 END as participate_in_walking, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAAQUEX AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Sample Person Interview Questionnaire Targets (B(2-11) and B(16-150))' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAAQUEX AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'MEC CAPI Questionnaire Targets (B(12-15))' -- categorize numeric values
WHEN PAAQUEX IS NULL THEN NULL 
ELSE SAFE_CAST(PAAQUEX AS STRING) 
 END as questionnaire_source_flag_for_weighting, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD590 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Less than 1 hour' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD590 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '1 hour' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD590 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '2 hours' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD590 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '3 hours' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD590 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '4 hours' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD590 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '5 hours or more' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD590 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'None' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD590 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD590 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAD590 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD590 AS STRING) 
 END as hours_watch_tv_or_videos_past_30_days_PAD590, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Less than 1 hour' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '1 hour' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '2 hours' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '3 hours' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '4 hours' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '5 hours or more' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'None' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAD600 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD600 AS STRING) 
 END as hours_use_computer_past_30_days_PAD600, 

CASE
    WHEN PAQ560 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ560 AS FLOAT64) 
 END as times_per_week_play_or_exercise_hard, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Unable to do activity' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAD020 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD020 AS STRING) 
 END as walked_or_bicycled_over_past_30_days, 

CASE
    WHEN PAQ050Q IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ050Q AS FLOAT64) 
 END as times_walked_or_bicycled, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ050U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Day' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ050U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Week' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ050U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ050U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ050U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont Know' -- categorize numeric values
WHEN PAQ050U IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ050U AS STRING) 
 END as unit_of_measure_day_week_month, 

CASE
    WHEN PAD080 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD080 AS FLOAT64) 
 END as how_long_per_day_minutes, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Unable to do activity' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAQ100 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ100 AS STRING) 
 END as tasks_around_home_yard_past_30_days, 

CASE
    WHEN PAD120 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD120 AS FLOAT64) 
 END as of_times_past_30_days, 

CASE
    WHEN PAD160 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD160 AS FLOAT64) 
 END as how_long_each_time_minutes, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '{you sit/he/she sits} during the day and {do/does} not walk about very much.' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '{you stand or walk/he/she stands or walks} about a lot during the day, but {do/does}not have to carry or lift things very often' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '{you/he/she} lift(s) light load or {have/has} to climb stairs or hills often.' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '{you/he/she} {do/does} heavy work or {carry/carries} heavy loads.' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAQ180 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ180 AS STRING) 
 END as avg_level_of_physical_activity_each_day, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Unable to do activity' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAD200 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD200 AS STRING) 
 END as vigorous_activity_over_past_30_days, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD320 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD320 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD320 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Unable to do activity' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD320 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD320 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAD320 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD320 AS STRING) 
 END as moderate_activity_over_past_30_days, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Unable to do activity' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAD440 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD440 AS STRING) 
 END as muscle_strengthening_activities, 

CASE
    WHEN PAD460 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD460 AS FLOAT64) 
 END as number_of_times_past_30_days, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ500 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'more active' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ500 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'less active, or' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ500 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'About the same?' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ500 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ500 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAQ500 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ500 AS STRING) 
 END as activity_comparison_last_mo_last_yr, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'more active' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'less active, or' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'About the same?' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont Know' -- categorize numeric values
WHEN PAQ520 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ520 AS STRING) 
 END as compare_activity_w_others_same_age, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ540 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'More active now,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ540 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Less active now, or' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ540 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'About the same?' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ540 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ540 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAQ540 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ540 AS STRING) 
 END as compare_activity_with_10_years_ago, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Less than 1 hour,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '1 hour,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '2 hours,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '3 hours,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '4 hours,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '5 hours or more, or' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'None' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAD480 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD480 AS STRING) 
 END as daily_hours_of_tv_video_or_computer_use, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Less than 1 hour,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '1 hour,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '2 hours,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '3 hours,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '4 hours,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '5 hours or more, or' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'None' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ480 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAQ480 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ480 AS STRING) 
 END as daily_hours_of_tv_video_or_computer_use_PAQ480, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Less than 1 hour' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '1 hour' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '2 hours' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '3 hours' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '4 hours, or' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '5 hours or more' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'None' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAD570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAD570 IS NULL THEN NULL 
ELSE SAFE_CAST(PAD570 AS STRING) 
 END as of_hours_watch_tv_or_videos_yesterday, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Less than 1 hour' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '1 hour' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '2 hours' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '3 hours' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '4 hours' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '5 or more?' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'None' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(PAQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN PAQ580 IS NULL THEN NULL 
ELSE SAFE_CAST(PAQ580 AS STRING) 
 END as hours_use_computer_games_yesterday, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_physical_activity_questionnaire') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/PAQ_J.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_PAQ.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/PAQ_I.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/PAQ_H.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/PAQ_G.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2009-2010/PAQ_F.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2007-2008/PAQ_E.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/PAQ_D.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/PAQ_C.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/PAQ_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/PAQ.htm
*/
