SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
WHEN RHQ010 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ010 AS FLOAT64) 
 END as age_when_first_menstrual_period_occurred, 

CASE
WHEN SAFE_CAST(RHD018 AS FLOAT64) > 201.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RHD018 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD018 AS FLOAT64) 
 END as estimated_age_in_months_at_menarche, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Younger than 10' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '10 to 12' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '13 to 15' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '16 or older' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ020 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ020 AS STRING) 
 END as age_range_at_first_menstrual_period, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ031 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ031 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ031 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ031 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ031 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ031 AS STRING) 
 END as had_regular_periods_in_past_12_months, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHD043 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Pregnancy' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHD043 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'Breast feeding' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHD043 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Hysterectomy' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHD043 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Menopause/Change of life' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHD043 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Other' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHD043 AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHD043 AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN RHD043 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD043 AS STRING) 
 END as reason_not_having_regular_periods, 

CASE
WHEN RHQ060 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ060 AS FLOAT64) 
 END as age_at_last_menstrual_period, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Younger than 30' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '30 to 34' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '35 to 39' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '40 to 44' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '45 to 49' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN '50 to 54' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN '55 or older' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ070 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ070 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ070 AS STRING) 
 END as age_range_at_last_menstrual_period, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ074 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ074 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ074 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ074 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN RHQ074 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ074 AS STRING) 
 END as tried_for_a_year_to_become_pregnant, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ076 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ076 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ076 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ076 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN RHQ076 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ076 AS STRING) 
 END as seen_a_dr_b_c_unable_to_become_pregnant, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ078 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ078 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ078 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ078 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN RHQ078 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ078 AS STRING) 
 END as ever_treated_for_a_pelvic_infection_pid, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ131 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ131 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ131 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ131 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ131 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ131 AS STRING) 
 END as ever_been_pregnant, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD143 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD143 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD143 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD143 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHD143 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD143 AS STRING) 
 END as are_you_pregnant_now, 

CASE
WHEN RHQ160 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ160 AS FLOAT64) 
 END as how_many_times_have_been_pregnant, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ162 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ162 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ162 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'Borderline' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ162 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ162 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN RHQ162 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ162 AS STRING) 
 END as during_pregnancy_told_you_have_diabetes, 

CASE
WHEN SAFE_CAST(RHQ163 AS FLOAT64) > 55.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RHQ163 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ163 AS FLOAT64) 
 END as age_told_you_had_diabetes_while_pregnant, 

CASE
WHEN SAFE_CAST(RHQ166 AS FLOAT64) > 21.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RHQ166 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ166 AS FLOAT64) 
 END as how_many_vaginal_deliveries, 

CASE
WHEN SAFE_CAST(RHQ169 AS FLOAT64) > 18.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RHQ169 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ169 AS FLOAT64) 
 END as how_many_cesarean_deliveries, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ172 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ172 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ172 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ172 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN RHQ172 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ172 AS STRING) 
 END as any_babies_weigh_9_lbs_or_more, 

CASE
WHEN SAFE_CAST(RHD173 AS FLOAT64) > 53.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RHD173 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD173 AS FLOAT64) 
 END as age_when_delivered_baby_9_lbs_or_more, 

CASE
WHEN SAFE_CAST(RHQ171 AS FLOAT64) > 21.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RHQ171 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ171 AS FLOAT64) 
 END as how_many_deliveries_live_birth_result, 

CASE
WHEN SAFE_CAST(RHD180 AS FLOAT64) > 53.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RHD180 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD180 AS FLOAT64) 
 END as age_at_first_live_birth, 

CASE
WHEN SAFE_CAST(RHD190 AS FLOAT64) > 55.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RHD190 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD190 AS FLOAT64) 
 END as age_at_last_live_birth, 

CASE
WHEN SAFE_CAST(RHQ197 AS FLOAT64) > 35.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RHQ197 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ197 AS FLOAT64) 
 END as how_many_months_ago_have_baby, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ200 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ200 AS STRING) 
 END as now_breastfeeding_a_child, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD280 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD280 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD280 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD280 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHD280 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD280 AS STRING) 
 END as had_a_hysterectomy, 

CASE
WHEN RHQ291 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ291 AS FLOAT64) 
 END as age_when_had_hysterectomy, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ305 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ305 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ305 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ305 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN RHQ305 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ305 AS STRING) 
 END as had_both_ovaries_removed, 

CASE
WHEN SAFE_CAST(RHQ332 AS FLOAT64) > 70.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RHQ332 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ332 AS FLOAT64) 
 END as age_when_both_ovaries_removed, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ420 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ420 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ420 AS STRING) 
 END as ever_taken_birth_control_pills, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ540 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ540 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ540 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ540 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ540 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ540 AS STRING) 
 END as ever_use_female_hormones, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ542A AS FLOAT64),0) AS INT64) AS STRING) = '10' THEN 'Pills' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ542A AS FLOAT64),0) AS INT64) AS STRING) = '77' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ542A AS FLOAT64),0) AS INT64) AS STRING) = '99' THEN 'Dont know' -- categorize string values 
WHEN RHQ542A IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ542A AS STRING) 
 END as hormone_pills_used, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ542B AS FLOAT64),0) AS INT64) AS STRING) = '11' THEN 'Patches' -- categorize string values 
WHEN RHQ542B IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ542B AS STRING) 
 END as hormone_patches_used, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ542C AS FLOAT64),0) AS INT64) AS STRING) = '12' THEN 'Cream/suppository/injection' -- categorize string values 
WHEN RHQ542C IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ542C AS STRING) 
 END as hormone_cream_suppository_injection_used, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ542D AS FLOAT64),0) AS INT64) AS STRING) = '13' THEN 'Other' -- categorize string values 
WHEN RHQ542D IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ542D AS STRING) 
 END as other_form_of_female_hormone_used, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ554 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ554 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ554 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ554 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ554 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ554 AS STRING) 
 END as use_hormone_pills_w_estrogen_only, 

CASE
WHEN RHQ560Q IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ560Q AS FLOAT64) 
 END as how_long_taking_estrogen_only_pills, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ560U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ560U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ560U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ560U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ560U IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ560U AS STRING) 
 END as unit_of_measure_months_years, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ570 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ570 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ570 AS STRING) 
 END as used_estrogen_progestin_combo_pills, 

CASE
WHEN RHQ576Q IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ576Q AS FLOAT64) 
 END as how_long_taking_estrogen_progestin, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ576U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ576U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ576U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ576U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ576U IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ576U AS STRING) 
 END as unit_of_measure_months_years_RHQ576U, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ580 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ580 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ580 AS STRING) 
 END as used_estrogen_only_patches, 

CASE
WHEN RHQ586Q IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ586Q AS FLOAT64) 
 END as how_long_using_estrogen_only_patches, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ586U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ586U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ586U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ586U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ586U IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ586U AS STRING) 
 END as unit_of_measure_months_years_RHQ586U, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ596 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ596 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ596 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ596 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ596 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ596 AS STRING) 
 END as used_estrogen_progestin_combo_patches, 

CASE
WHEN RHQ602Q IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ602Q AS FLOAT64) 
 END as how_long_use_estrogen_progestin_patch, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ602U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ602U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ602U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ602U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ602U IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ602U AS STRING) 
 END as unit_of_measure_months_years_RHQ602U, 

CASE
WHEN SAFE_CAST(RHD167 AS FLOAT64) > 15.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN RHD167 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD167 AS FLOAT64) 
 END as total_number_of_deliveries, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD042 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Pregnancy' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD042 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Breast feeding' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD042 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Menopause/Hysterectomy' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD042 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(8 AS FLOAT64),0) AS INT64) THEN 'Medical conditions/treatments' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD042 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Other' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD042 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD042 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHD042 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD042 AS STRING) 
 END as reason_not_having_regular_periods_RHD042, 

CASE
WHEN RHD152 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD152 AS FLOAT64) 
 END as what_month_of_pregnancy_are_you_in, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ205 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ205 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ205 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ205 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN RHQ205 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ205 AS STRING) 
 END as breastfed_any_child_at_least_1_month, 

CASE
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ395 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ395 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ395 AS FLOAT64),0) AS INT64) AS STRING) = '7' THEN 'Refused' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(RHQ395 AS FLOAT64),0) AS INT64) AS STRING) = '9' THEN 'Dont know' -- categorize string values 
WHEN RHQ395 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ395 AS STRING) 
 END as experience_bulging_in_vaginal_area, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD442 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD442 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD442 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD442 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHD442 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD442 AS STRING) 
 END as taking_birth_control_pills_now, 

CASE
WHEN RHQ460Q IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ460Q AS FLOAT64) 
 END as how_long_taking_birth_control_pills, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ460U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ460U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ460U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ460U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ460U IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ460U AS STRING) 
 END as unit_of_measure_months_years_RHQ460U, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ510 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ510 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ510 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ510 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ510 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ510 AS STRING) 
 END as used_depo_provera_or_injectables, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ520 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ520 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ520 AS STRING) 
 END as now_using_depo_provera_or_injectables, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ541A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Pills' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ541A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ541A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ541A IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ541A AS STRING) 
 END as hormone_pills_used_RHQ541A, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ541B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Patches' -- categorize numeric values
WHEN RHQ541B IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ541B AS STRING) 
 END as hormone_patches_used_RHQ541B, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ541C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Cream/suppository/injection' -- categorize numeric values
WHEN RHQ541C IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ541C AS STRING) 
 END as hormone_cream_suppository_injection_used_RHQ541C, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ558 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ558 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ558 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ558 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ558 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ558 AS STRING) 
 END as taking_estrogen_only_pills_now, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ562 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ562 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ562 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ562 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ562 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ562 AS STRING) 
 END as used_hormone_pills_w_progestin_only, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ566 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ566 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ566 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ566 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ566 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ566 AS STRING) 
 END as taking_progestin_only_pills_now, 

CASE
WHEN RHQ568Q IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ568Q AS FLOAT64) 
 END as how_long_taking_progestin_only_pills, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ568U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ568U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ568U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ568U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ568U IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ568U AS STRING) 
 END as unit_of_measure_months_years_RHQ568U, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ574 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ574 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ574 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ574 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ574 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ574 AS STRING) 
 END as taking_estrogen_progestin_now, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ584 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ584 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ584 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ584 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ584 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ584 AS STRING) 
 END as using_estrogen_only_patches_now, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ600 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ600 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ600 AS STRING) 
 END as using_estrogen_progestin_patches_now, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ051 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Having it now' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ051 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Less than 2 months ago' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ051 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '3 - 5 months ago' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ051 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '6 - 8 months ago' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ051 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '9 - 11 months ago' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ051 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ051 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ051 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ051 AS STRING) 
 END as when_did_you_have_your_last_period, 

CASE
WHEN RHD080 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD080 AS FLOAT64) 
 END as days_since_last_period, 

CASE
WHEN RHQ180 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ180 AS FLOAT64) 
 END as age_at_first_live_birth_RHQ180, 

CASE
WHEN RHQ190 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ190 AS FLOAT64) 
 END as age_at_last_live_birth_RHQ190, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ210 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ210 AS STRING) 
 END as breastfed_any_of_your_children, 

CASE
WHEN RHD230 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD230 AS FLOAT64) 
 END as of_children_breastfed_at_least_1_month, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ250 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ250 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ250 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ250 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ250 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ250 AS STRING) 
 END as any_child_weigh_5_5_lbs_at_birth, 

CASE
WHEN RHQ260 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ260 AS FLOAT64) 
 END as children_weighing_5_5_lbs_at_birth, 

CASE
WHEN RHD270 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD270 AS FLOAT64) 
 END as number_of_children_born_preterm, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ300 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ300 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ300 AS STRING) 
 END as had_at_least_one_ovary_removed, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Both' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'One' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ310 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ310 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ310 AS STRING) 
 END as were_both_ovaries_removed_or_only_one, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ320 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Same time' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ320 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Different times' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ320 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ320 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ320 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ320 AS STRING) 
 END as both_ovaries_removed_at_same_time, 

CASE
WHEN RHQ330 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ330 AS FLOAT64) 
 END as age_when_first_both_ovaries_removed, 

CASE
WHEN RHQ340 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ340 AS FLOAT64) 
 END as age_when_second_ovary_removed, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ360 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ360 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ360 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ360 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ360 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ360 AS STRING) 
 END as told_by_doctor_had_endometriosis, 

CASE
WHEN RHQ370 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ370 AS FLOAT64) 
 END as age_when_first_told_had_endometriosis, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ380 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ380 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ380 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ380 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ380 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ380 AS STRING) 
 END as told_by_doctor_had_uterine_fibroids, 

CASE
WHEN RHQ390 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ390 AS FLOAT64) 
 END as age_when_first_told_had_uterine_fibroids, 

CASE
WHEN RHQ430 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ430 AS FLOAT64) 
 END as age_started_taking_birth_control_pills, 

CASE
WHEN RHD451 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD451 AS FLOAT64) 
 END as age_stopped_taking_birth_control_pills, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ550 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Still having periods' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ550 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Completely stopped having periods' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ550 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ550 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ550 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ550 AS STRING) 
 END as having_periods_when_start_hormones, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ551A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Menopause-related symptoms (hot flashes, sweating, vaginal dryness, bladder problems)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ551A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ551A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ551A IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ551A AS STRING) 
 END as used_estrogen_progesterone_for_menopause, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ551B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Depression, anxiety, emotional distress' -- categorize numeric values
WHEN RHQ551B IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ551B AS STRING) 
 END as used_estrogen_progesterone_for_emotions, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ551C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Hysterectomy or oophorectomy (ovary removal)' -- categorize numeric values
WHEN RHQ551C IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ551C AS STRING) 
 END as used_estr_progest_for_hysterct_oophorect, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ551D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'Osteoporosis, bone loss/thinning fracture prevention' -- categorize numeric values
WHEN RHQ551D IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ551D AS STRING) 
 END as used_estr_progest_for_osteoporosis, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ551E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Cardiovascular disease prevention' -- categorize numeric values
WHEN RHQ551E IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ551E AS STRING) 
 END as used_estr_progest_for_cardiovascular_dis, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ551F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Irregular menstrual periods, to regulate periods' -- categorize numeric values
WHEN RHQ551F IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ551F AS STRING) 
 END as used_estr_progest_for_irregular_periods, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ551G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(16 AS FLOAT64),0) AS INT64) THEN 'Other reasons' -- categorize numeric values
WHEN RHQ551G IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ551G AS STRING) 
 END as used_estr_progest_for_other_reasons, 

CASE
WHEN RHQ556 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ556 AS FLOAT64) 
 END as age_started_estrogen_only_pills, 

CASE
WHEN RHQ564 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ564 AS FLOAT64) 
 END as age_started_progestin_only_pills, 

CASE
WHEN RHQ572 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ572 AS FLOAT64) 
 END as age_started_estrogen_progestin_pills, 

CASE
WHEN RHQ582 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ582 AS FLOAT64) 
 END as age_started_estrogen_only_patches, 

CASE
WHEN RHQ598 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ598 AS FLOAT64) 
 END as age_started_estrogen_progestin_patches, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ740 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ740 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ740 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ740 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ740 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ740 AS STRING) 
 END as vaginal_problems_during_past_month, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ750A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Vaginal Itching' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ750A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ750A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ750A IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ750A AS STRING) 
 END as problem_with_vaginal_itching, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ750B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Unpleasant Vaginal Odor' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ750B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ750B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ750B IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ750B AS STRING) 
 END as problem_with_vaginal_odor, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ750C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Unusual Vaginal Discharge' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ750C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ750C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ750C IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ750C AS STRING) 
 END as problem_with_vaginal_discharge, 

CASE
WHEN RHD170 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD170 AS FLOAT64) 
 END as pregnancies_resulting_in_live_births, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ700 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ700 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ700 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ700 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ700 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ700 AS STRING) 
 END as used_fem_hygiene_product_in_past_month, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Tampons' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ710A IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ710A AS STRING) 
 END as used_tampons_in_past_month, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Sanitary Napkins' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ710B IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ710B AS STRING) 
 END as used_sanitary_napkins_in_past_month, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Vaginal Douches' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ710C IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ710C AS STRING) 
 END as used_vaginal_douches_in_past_month, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Feminine Spray' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ710D IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ710D AS STRING) 
 END as used_feminine_spray_in_past_month, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Feminine Powder' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ710E IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ710E AS STRING) 
 END as used_feminine_powder_in_past_month, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Feminine Cleansing Wipes/Towlettes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ710F IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ710F AS STRING) 
 END as used_feminine_wipes_towlettes_past_month, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Other Feminine Hygiene Products' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ710G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ710G IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ710G AS STRING) 
 END as used_other_fem_hygiene_products_past_mon, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ720 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ720 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ720 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ720 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ720 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ720 AS STRING) 
 END as did_sp_douche_in_past_6_months, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ730 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN '5 or more times a month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ730 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN '2 to 4 times a month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ730 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'once a month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ730 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'less than once a month' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ730 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ730 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ730 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ730 AS STRING) 
 END as frequency_sp_douched_in_past_6_months, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ030 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ030 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ030 AS STRING) 
 END as had_regular_periods_in_past_12_months_RHQ030, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Pregnant now' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Breast feeding' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Pregnant in past year' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Periods usually irregular' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN 'Going-gone through menopause' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN 'Medical conditions-treatments' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ040 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ040 AS STRING) 
 END as reason_not_having_regular_periods_RHQ040, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Having it now' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Less than 2 months ago' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN '3 - 5 months ago' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN '6 - 8 months ago' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(5 AS FLOAT64),0) AS INT64) THEN '9 - 11 months ago' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(6 AS FLOAT64),0) AS INT64) THEN '12 or more months ago' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ050 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ050 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ050 AS STRING) 
 END as when_did_sp_have_last_period, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'More regular,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Less regular, or' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'About the same?' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ090 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ090 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ090 AS STRING) 
 END as menstrual_cycle_regularity_last_5_years, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Heavier,' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Lighter, or' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'About the same?' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ100 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ100 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ100 AS STRING) 
 END as menstrual_bleeding_rate_last_5_years, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ110 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ110 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ110 AS STRING) 
 END as hot_flashes_night_sweats_last_6_mos, 

CASE
WHEN RHD120 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD120 AS FLOAT64) 
 END as monthly_frequency_of_hot_flashes, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD130 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD130 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD130 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD130 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHD130 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD130 AS STRING) 
 END as ever_been_pregnant_RHD130, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ141 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ141 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ141 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ141 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ141 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ141 AS STRING) 
 END as think_that_you_are_pregnant_now, 

CASE
WHEN RHQ151 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ151 AS FLOAT64) 
 END as what_month_of_pregnancy_are_you_in_RHQ151, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ240A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(10 AS FLOAT64),0) AS INT64) THEN 'Job-scheduling difficulties' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ240A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(77 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ240A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(99 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ240A IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ240A AS STRING) 
 END as reason_not_breastfed_job_schedule, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ240B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(11 AS FLOAT64),0) AS INT64) THEN 'Mothers physical-medical difficulties' -- categorize numeric values
WHEN RHQ240B IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ240B AS STRING) 
 END as reason_not_breastfed_mother_s_phys_med, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ240C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(12 AS FLOAT64),0) AS INT64) THEN 'Childs physical-medical difficulties' -- categorize numeric values
WHEN RHQ240C IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ240C AS STRING) 
 END as reason_not_breastfed_child_s_phys_med, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ240D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(13 AS FLOAT64),0) AS INT64) THEN 'Preferred bottle feeding' -- categorize numeric values
WHEN RHQ240D IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ240D AS STRING) 
 END as reason_not_breastfed_preferred_bottle, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ240E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(14 AS FLOAT64),0) AS INT64) THEN 'Didnt know how to breast-feed' -- categorize numeric values
WHEN RHQ240E IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ240E AS STRING) 
 END as reason_not_breastfed_didn_t_know_how, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ240F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(15 AS FLOAT64),0) AS INT64) THEN 'Other reasons' -- categorize numeric values
WHEN RHQ240F IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ240F AS STRING) 
 END as reason_not_breastfed_other, 

CASE
WHEN RHQ290 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ290 AS FLOAT64) 
 END as age_when_had_hysterectomy_RHQ290, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD350 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD350 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD350 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD350 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHD350 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD350 AS STRING) 
 END as fallopian_tubes_ever_cut_tied_removed, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHD440 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHD440 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD440 AS STRING) 
 END as taking_birth_control_pills_now_RHD440, 

CASE
WHEN RHQ450 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ450 AS FLOAT64) 
 END as age_when_stopped_taking_birth_pills, 

CASE
WHEN REPLACE(RHD470,'.0','') = 'Brand name of contraceptives' THEN 'Value was recorded' -- categorize string values 
WHEN RHD470 IS NULL THEN NULL 
ELSE SAFE_CAST(RHD470 AS STRING) 
 END as brand_name_of_contraceptives, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(RHQ140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN RHQ140 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ140 AS STRING) 
 END as think_that_you_are_pregnant_now_RHQ140, 

CASE
WHEN RHQ150 IS NULL THEN NULL 
ELSE SAFE_CAST(RHQ150 AS FLOAT64) 
 END as what_month_of_pregnancy_are_you_in_RHQ150, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_reproductive_health_questionnaire') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/RHQ_J.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_RHQ.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/RHQ_I.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/RHQ_H.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/RHQ_G.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2009-2010/RHQ_F.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2007-2008/RHQ_E.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/RHQ_D.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/RHQ_C.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/RHQ_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/RHQ.htm
*/
