SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ020 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ020 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ020 AS STRING) 
 END as smoked_at_least_100_cigarettes_in_life, 

CASE
    WHEN SMD030 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD030 AS FLOAT64) 
 END as age_started_smoking_cigarettes_regularly, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Every day' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Some days' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not at all' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ040 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ040 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ040 AS STRING) 
 END as do_you_now_smoke_cigarettes, 

CASE
    WHEN SMQ050Q IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ050Q AS FLOAT64) 
 END as how_long_since_quit_smoking_cigarettes, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ050U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Days' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ050U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Weeks' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ050U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Months' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ050U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Years' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ050U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ050U AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ050U IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ050U AS STRING) 
 END as unit_of_measure_day_week_month_year, 

CASE
    WHEN SMD055 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD055 AS FLOAT64) 
 END as age_last_smoked_cigarettes_regularly, 

CASE
    WHEN SMD057 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD057 AS FLOAT64) 
 END as cigarettes_smoked_per_day_when_quit, 

CASE
    WHEN SMD070 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD070 AS FLOAT64) 
 END as cigarettes_smoked_per_day_now, 

CASE
    WHEN SMD075 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD075 AS FLOAT64) 
 END as how_many_years_smoked_this_amount, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ077 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Within 5 minutes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ077 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'From 6 to 30 minutes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ077 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'From more than 30 minutes to one hour' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ077 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'More than one hour' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ077 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ077 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ077 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ077 AS STRING) 
 END as how_soon_after_waking_do_you_smoke, 

CASE
    WHEN SAFE_CAST(SMD641 AS FLOAT64) > 41.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN SMD641 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD641 AS FLOAT64) 
 END as days_smoked_cigs_during_past_30_days, 

CASE
    WHEN SAFE_CAST(SMD650 AS FLOAT64) > 81.0 THEN NULL -- remove missing, dont know, categories in float field  
WHEN SMD650 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD650 AS FLOAT64) 
 END as avg_cigarettes_day_during_past_30_days, 

CASE
    WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(SMD093 AS FLOAT64),0) AS INT64) AS STRING) = '1' THEN 'Yes' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(SMD093 AS FLOAT64),0) AS INT64) AS STRING) = '2' THEN 'No' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(SMD093 AS FLOAT64),0) AS INT64) AS STRING) = '3' THEN 'No usual brand' -- categorize string values 
WHEN SAFE_CAST(SAFE_CAST(ROUND(SAFE_CAST(SMD093 AS FLOAT64),0) AS INT64) AS STRING) = '4' THEN 'Rolls own' -- categorize string values 
WHEN SMD093 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD093 AS STRING) 
 END as may_i_please_see_the_pack_of_cigarettes, 

CASE
    WHEN REPLACE(SMDUPCA,'.0','') = 'Cig 12-digit Universal Product Code-UPC' THEN 'Value was recorded' -- categorize string values 
WHEN SMDUPCA IS NULL THEN NULL 
ELSE SAFE_CAST(SMDUPCA AS STRING) 
 END as cig_12_digit_universal_product_code_upc, 

CASE
    WHEN REPLACE(SMD100BR,'.0','') = 'Cigarette Brand/sub-brand' THEN 'Value was recorded' -- categorize string values 
WHEN SMD100BR IS NULL THEN NULL 
ELSE SAFE_CAST(SMD100BR AS STRING) 
 END as cigarette_brand_sub_brand, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD100FL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Non-filter' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD100FL AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Filter' -- categorize numeric values
WHEN SMD100FL IS NULL THEN NULL 
ELSE SAFE_CAST(SMD100FL AS STRING) 
 END as filter_type, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD100MN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'Non-menthol' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD100MN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Menthol' -- categorize numeric values
WHEN SMD100MN IS NULL THEN NULL 
ELSE SAFE_CAST(SMD100MN AS STRING) 
 END as menthol_indicator, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD100LN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Regular (68-72 mm)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD100LN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'King (79-88 mm)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD100LN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Long (94-101 mm)' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD100LN AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Ultra long (110-121 mm)' -- categorize numeric values
WHEN SMD100LN IS NULL THEN NULL 
ELSE SAFE_CAST(SMD100LN AS STRING) 
 END as length, 

CASE
    WHEN SMD100TR IS NULL THEN NULL 
ELSE SAFE_CAST(SMD100TR AS FLOAT64) 
 END as ftc_tar_content, 

CASE
    WHEN SMD100NI IS NULL THEN NULL 
ELSE SAFE_CAST(SMD100NI AS FLOAT64) 
 END as ftc_nicotine_content, 

CASE
    WHEN SMD100CO IS NULL THEN NULL 
ELSE SAFE_CAST(SMD100CO AS FLOAT64) 
 END as ftc_carbon_monoxide_content, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ120 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ120 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ120 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ120 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ120 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ120 AS STRING) 
 END as smoked_a_pipe_at_least_20_times_in_life, 

CASE
    WHEN SMD130 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD130 AS FLOAT64) 
 END as age_started_pipe_smoking_regularly, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Every day' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Some days' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not at all' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ140 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ140 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ140 AS STRING) 
 END as do_you_now_smoke_a_pipe, 

CASE
    WHEN SMQ143 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ143 AS FLOAT64) 
 END as pipefuls_of_tobacco_smoked_per_day, 

CASE
    WHEN SMQ145 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ145 AS FLOAT64) 
 END as years_smoked_this_amount_of_pipes, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ150 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ150 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ150 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ150 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ150 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ150 AS STRING) 
 END as smoked_cigars_at_least_20_times_in_life, 

CASE
    WHEN SMD160 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD160 AS FLOAT64) 
 END as age_started_cigar_smoking_regularly, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ170 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Every day' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ170 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Some days' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ170 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not at all' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ170 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ170 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ170 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ170 AS STRING) 
 END as do_you_now_smoke_cigars, 

CASE
    WHEN SMQ173 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ173 AS FLOAT64) 
 END as cigars_smokes_per_day, 

CASE
    WHEN SMQ175 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ175 AS FLOAT64) 
 END as years_smoked_this_amount_of_cigars, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ180 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ180 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ180 AS STRING) 
 END as used_snuff_at_least_20_times_in_life, 

CASE
    WHEN SMD190 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD190 AS FLOAT64) 
 END as age_started_using_snuff_regularly, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Every day' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Some days' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not at all' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ200 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ200 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ200 AS STRING) 
 END as do_you_now_use_snuff, 

CASE
    WHEN SMD203 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD203 AS FLOAT64) 
 END as snuff_pinches_dips_rubs_per_day, 

CASE
    WHEN SMQ205 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ205 AS FLOAT64) 
 END as years_used_this_amount_of_snuff, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ210 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ210 AS STRING) 
 END as used_chewing_tobacco_20_times_in_life, 

CASE
    WHEN SMD220 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD220 AS FLOAT64) 
 END as age_started_chewing_tobacco_regularly, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ230 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Every day' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ230 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'Some days' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ230 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'Not at all' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ230 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMQ230 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN SMQ230 IS NULL THEN NULL 
ELSE SAFE_CAST(SMQ230 AS STRING) 
 END as do_you_now_use_chewing_tobacco, 

CASE
    WHEN SMD233 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD233 AS FLOAT64) 
 END as chewing_plugs_wads_chaws_per_day, 

CASE
    WHEN SMD235 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD235 AS FLOAT64) 
 END as years_used_this_chewing_tobacco_amount, 

CASE
    WHEN SMD080 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD080 AS FLOAT64) 
 END as days_smoked_cigs_during_past_30_days_SMD080, 

CASE
    WHEN SMD090 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD090 AS FLOAT64) 
 END as avg_cigarettes_day_during_past_30_days_SMD090, 

CASE
    WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD092 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD092 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD092 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(3 AS FLOAT64),0) AS INT64) THEN 'No usual brand' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(SMD092 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(4 AS FLOAT64),0) AS INT64) THEN 'Rolls own' -- categorize numeric values
WHEN SMD092 IS NULL THEN NULL 
ELSE SAFE_CAST(SMD092 AS STRING) 
 END as may_i_please_see_the_pack_of_cigarettes_SMD092, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_smoking_cigarette_tobacco_use_adult_questionnaire') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/SMQ_C.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/SMQ_B.htm
https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/SMQ.htm
*/
