SELECT
SEQN as respondent_sequence_number, -- could not identify transformation logic 

CASE
WHEN WTSVOC2Y IS NULL THEN NULL 
ELSE SAFE_CAST(WTSVOC2Y AS FLOAT64) 
 END as voc_subsample_weight, 

CASE
WHEN LBXV1A IS NULL THEN NULL 
ELSE SAFE_CAST(LBXV1A AS FLOAT64) 
 END as blood_1_1_dichloroethane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV1ALC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV1ALC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV1ALC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDV1ALC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDV1ALC AS STRING) 
 END as blood_1_1_dichloroethane_comment_code, 

CASE
WHEN LBXV1D IS NULL THEN NULL 
ELSE SAFE_CAST(LBXV1D AS FLOAT64) 
 END as blood_1_2_dichlorobenzene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV1DLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV1DLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV1DLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDV1DLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDV1DLC AS STRING) 
 END as blood_1_2_dichlorobenzene_comment_code, 

CASE
WHEN LBXV1E IS NULL THEN NULL 
ELSE SAFE_CAST(LBXV1E AS FLOAT64) 
 END as blood_1_1_dichloroethene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV1ELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV1ELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV1ELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDV1ELC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDV1ELC AS STRING) 
 END as blood_1_1_dichloroethene_comment_code, 

CASE
WHEN LBXV2A IS NULL THEN NULL 
ELSE SAFE_CAST(LBXV2A AS FLOAT64) 
 END as blood_1_2_dichloroethane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2ALC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2ALC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2ALC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDV2ALC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDV2ALC AS STRING) 
 END as blood_1_2_dichloroethane_comment_code, 

CASE
WHEN LBXV2C IS NULL THEN NULL 
ELSE SAFE_CAST(LBXV2C AS FLOAT64) 
 END as blood_cis_1_2_dichloroethene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2CLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2CLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2CLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDV2CLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDV2CLC AS STRING) 
 END as blood_cis_1_2_dichloroethene_comt_code, 

CASE
WHEN LBXV2E IS NULL THEN NULL 
ELSE SAFE_CAST(LBXV2E AS FLOAT64) 
 END as blood_1_1_2_trichloroethane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2ELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2ELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2ELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDV2ELC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDV2ELC AS STRING) 
 END as blood_1_1_2_trichloroethane_comt_code, 

CASE
WHEN LBXV2P IS NULL THEN NULL 
ELSE SAFE_CAST(LBXV2P AS FLOAT64) 
 END as blood_1_2_dibromo_3_chloropropane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2PLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2PLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2PLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDV2PLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDV2PLC AS STRING) 
 END as blood_1_2_dibromo_3_chloropropane_comt, 

CASE
WHEN LBXV2T IS NULL THEN NULL 
ELSE SAFE_CAST(LBXV2T AS FLOAT64) 
 END as blood_trans_1_2_dichloroethene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2TLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2TLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV2TLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDV2TLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDV2TLC AS STRING) 
 END as blood_trans_1_2_dichloroethene_comt_code, 

CASE
WHEN LBXV3B IS NULL THEN NULL 
ELSE SAFE_CAST(LBXV3B AS FLOAT64) 
 END as blood_1_3_dichlorobenzene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV3BLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV3BLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV3BLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDV3BLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDV3BLC AS STRING) 
 END as blood_1_3_dichlorobenzene_comment_code, 

CASE
WHEN LBXV4E IS NULL THEN NULL 
ELSE SAFE_CAST(LBXV4E AS FLOAT64) 
 END as blood_1_1_2_2_tetrachloroethane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV4ELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV4ELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV4ELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDV4ELC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDV4ELC AS STRING) 
 END as blood_1_1_2_2_tetrachloroethane_com_code, 

CASE
WHEN LBXV4C IS NULL THEN NULL 
ELSE SAFE_CAST(LBXV4C AS FLOAT64) 
 END as blood_tetrachloroethene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV4CLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV4CLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDV4CLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDV4CLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDV4CLC AS STRING) 
 END as blood_tetrachloroethene_comment_code, 

CASE
WHEN LBXVBZ IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVBZ AS FLOAT64) 
 END as blood_benzene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVBZLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVBZLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVBZLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVBZLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVBZLC AS STRING) 
 END as blood_benzene_comment_code, 

CASE
WHEN LBXVCB IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVCB AS FLOAT64) 
 END as blood_chlorobenzene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVCBLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVCBLC AS STRING) 
 END as blood_chlorobenzene_comment_code, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBX4CE AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0.0283 AS FLOAT64),0) AS INT64) THEN '0.0283' -- categorize numeric values
WHEN LBX4CE IS NULL THEN NULL 
ELSE SAFE_CAST(LBX4CE AS STRING) 
 END as blood_1_1_1_2_tetrachloroethane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBD4CELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBD4CELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBD4CELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBD4CELC IS NULL THEN NULL 
ELSE SAFE_CAST(LBD4CELC AS STRING) 
 END as blood_1_1_1_2_tetrachloroethane_cmt_code, 

CASE
WHEN LBXVCT IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVCT AS FLOAT64) 
 END as blood_carbon_tetrachloride_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCTLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCTLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCTLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVCTLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVCTLC AS STRING) 
 END as blood_carbon_tetrachloride_comment_code, 

CASE
WHEN LBXVDB IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVDB AS FLOAT64) 
 END as blood_1_4_dichlorobenzene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVDBLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVDBLC AS STRING) 
 END as blood_1_4_dichlorobenzene_comment_code, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXVDE AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0.0106 AS FLOAT64),0) AS INT64) THEN '0.0106' -- categorize numeric values
WHEN LBXVDE IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVDE AS STRING) 
 END as blood_1_2_dibromoethane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVDELC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVDELC AS STRING) 
 END as blood_1_2_dibromoethane_comment_code, 

CASE
WHEN LBXVDM IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVDM AS FLOAT64) 
 END as blood_dibromomethane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDMLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDMLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDMLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVDMLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVDMLC AS STRING) 
 END as blood_dibromomethane_comment_code, 

CASE
WHEN LBXVDP IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVDP AS FLOAT64) 
 END as blood_1_2_dichloropropane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDPLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDPLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVDPLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVDPLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVDPLC AS STRING) 
 END as blood_1_2_dichloropropane_comment_code, 

CASE
WHEN LBXVEB IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVEB AS FLOAT64) 
 END as blood_ethylbenzene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVEBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVEBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVEBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVEBLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVEBLC AS STRING) 
 END as blood_ethylbenzene_comment_code, 

CASE
WHEN LBXVFN IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVFN AS FLOAT64) 
 END as blood_furan_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVFNLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVFNLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVFNLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVFNLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVFNLC AS STRING) 
 END as blood_furan_comment_code, 

CASE
WHEN LBXVHE IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVHE AS FLOAT64) 
 END as blood_hexachloroethane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVHELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVHELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVHELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVHELC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVHELC AS STRING) 
 END as blood_hexachloroethane_comment_code, 

CASE
WHEN LBXVIPB IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVIPB AS FLOAT64) 
 END as blood_isopropylbenzene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVIPLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVIPLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVIPLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVIPLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVIPLC AS STRING) 
 END as blood_isopropylbenzene_comment_code, 

CASE
WHEN LBXVMC IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVMC AS FLOAT64) 
 END as blood_methylene_chloride_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVMCLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVMCLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVMCLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVMCLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVMCLC AS STRING) 
 END as blood_methylene_chloride_comment_code, 

CASE
WHEN LBXVOX IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVOX AS FLOAT64) 
 END as blood_o_xylene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVOXLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVOXLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVOXLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVOXLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVOXLC AS STRING) 
 END as blood_o_xylene_comment_code, 

CASE
WHEN LBXVST IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVST AS FLOAT64) 
 END as blood_styrene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVSTLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVSTLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVSTLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVSTLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVSTLC AS STRING) 
 END as blood_styrene_comment_code, 

CASE
WHEN LBXVTC IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVTC AS FLOAT64) 
 END as blood_trichloroethene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTCLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTCLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTCLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVTCLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVTCLC AS STRING) 
 END as blood_trichloroethene_comment_code, 

CASE
WHEN LBXVTE IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVTE AS FLOAT64) 
 END as blood_1_1_1_trichloroethane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVTELC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVTELC AS STRING) 
 END as blood_1_1_1_trichloroethane_comment_code, 

CASE
WHEN LBXVTO IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVTO AS FLOAT64) 
 END as blood_toluene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTOLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTOLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTOLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVTOLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVTOLC AS STRING) 
 END as blood_toluene_comment_code, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBXVTP AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0.0283 AS FLOAT64),0) AS INT64) THEN '0.0283' -- categorize numeric values
WHEN LBXVTP IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVTP AS STRING) 
 END as blood_1_2_3_trichloropropane_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTPLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTPLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVTPLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVTPLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVTPLC AS STRING) 
 END as blood_1_2_3_trichloropropane_comt_code, 

CASE
WHEN LBXVXY IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVXY AS FLOAT64) 
 END as blood_m_p_xylene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVXYLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVXYLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVXYLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVXYLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVXYLC AS STRING) 
 END as blood_m_p_xylene_comment_code, 

CASE
WHEN LBX2DF IS NULL THEN NULL 
ELSE SAFE_CAST(LBX2DF AS FLOAT64) 
 END as blood_2_5_dimethylfuran_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBD2DFLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBD2DFLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBD2DFLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBD2DFLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBD2DFLC AS STRING) 
 END as blood_2_5_dimethylfuran_comment_code, 

CASE
WHEN LBXVNB IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVNB AS FLOAT64) 
 END as blood_nitrobenzene_ng_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVNBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVNBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVNBLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVNBLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVNBLC AS STRING) 
 END as blood_nitrobenzene_comment_code, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ210 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ210 IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ210 AS STRING) 
 END as attached_garage, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ220 AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ220 IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ220 AS STRING) 
 END as private_well, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ200A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ200A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ200A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ200A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ200A IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ200A AS STRING) 
 END as store_paints_or_fuels_inside_home, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ230A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ230A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ230A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ230A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ230A IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ230A AS STRING) 
 END as toilet_bowl_deodorizers, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ230B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ230B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ230B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ230B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ230B IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ230B AS STRING) 
 END as moth_balls_or_crystals, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ240A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ240A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ240A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ240A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ240A IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ240A AS STRING) 
 END as pump_gas_into_a_car_or_motor_vehicle, 

CASE
WHEN VTQ240B IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ240B AS FLOAT64) 
 END as how_long_ago_did_you_pump_gas, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ250A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ250A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ250A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ250A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ250A IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ250A AS STRING) 
 END as spend_time_at_swimming_pool, 

CASE
WHEN VTQ250B IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ250B AS FLOAT64) 
 END as how_long_ago_at_swimming_pool, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ260A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ260A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ260A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ260A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ260A IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ260A AS STRING) 
 END as visit_a_dry_cleaning_shop, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ260B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ260B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ260B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ260B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ260B IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ260B AS STRING) 
 END as spend_10_minutes_near_cigarette_smoke, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ270A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ270A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ270A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ270A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ270A IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ270A AS STRING) 
 END as take_a_hot_shower, 

CASE
WHEN VTQ270B IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ270B AS FLOAT64) 
 END as how_long_since_hot_shower, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280A AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ280A IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ280A AS STRING) 
 END as breathe_fumes_from_paints, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280B AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ280B IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ280B AS STRING) 
 END as breathe_fumes_from_degreasing_cleaners, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280C AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ280C IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ280C AS STRING) 
 END as breathe_fumes_from_diesel_fuel, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280D AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ280D IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ280D AS STRING) 
 END as breathe_fumes_from_paint_thinner, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280E AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ280E IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ280E AS STRING) 
 END as breathe_fumes_from_drycleaning_fluid, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280F AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ280F IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ280F AS STRING) 
 END as breathe_fumes_from_fingernail_polish, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280G AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ280G IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ280G AS STRING) 
 END as breathe_fumes_from_glue, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280H AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'Yes' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280H AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'No' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280H AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(7 AS FLOAT64),0) AS INT64) THEN 'Refused' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(VTQ280H AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(9 AS FLOAT64),0) AS INT64) THEN 'Dont know' -- categorize numeric values
WHEN VTQ280H IS NULL THEN NULL 
ELSE SAFE_CAST(VTQ280H AS STRING) 
 END as breathe_fumes_from_varnish, 

CASE
WHEN LBXVBF IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVBF AS FLOAT64) 
 END as blood_bromoform_pg_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVBFLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVBFLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVBFLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVBFLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVBFLC AS STRING) 
 END as blood_bromoform_comment_code, 

CASE
WHEN LBXVBM IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVBM AS FLOAT64) 
 END as blood_bromodichloromethane_pg_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVBMLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVBMLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVBMLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVBMLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVBMLC AS STRING) 
 END as blood_bromodichloromethane_comment_code, 

CASE
WHEN LBXVCF IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVCF AS FLOAT64) 
 END as blood_chloroform_pg_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCFLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCFLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCFLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVCFLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVCFLC AS STRING) 
 END as blood_chloroform_comment_code, 

CASE
WHEN LBXVCM IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVCM AS FLOAT64) 
 END as blood_dibromochloromethane_pg_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCMLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCMLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVCMLC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVCMLC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVCMLC AS STRING) 
 END as blood_dibromochloromethane_comment_code, 

CASE
WHEN LBXVME IS NULL THEN NULL 
ELSE SAFE_CAST(LBXVME AS FLOAT64) 
 END as blood_mtbe_pg_ml, 

CASE
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVMELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(0 AS FLOAT64),0) AS INT64) THEN 'detectable result' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVMELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(1 AS FLOAT64),0) AS INT64) THEN 'below detectable limit' -- categorize numeric values
WHEN SAFE_CAST(ROUND(SAFE_CAST(LBDVMELC AS FLOAT64),0) AS INT64) = SAFE_CAST(ROUND(SAFE_CAST(2 AS FLOAT64),0) AS INT64) THEN 'detectable result and exceeds the calibrated range of assay' -- categorize numeric values
WHEN LBDVMELC IS NULL THEN NULL 
ELSE SAFE_CAST(LBDVMELC AS STRING) 
 END as blood_mtbe_comment_code, 

start_year,
end_year,
last_updated,
published_date,
parquet_filename,
data_file_url,
doc_file_url,
dataset,
 FROM {{ ref('stg_volatile_organic_compounds_blood_related_questionnaire_items_laboratory') }}

/* 
Docs utilized to generate this SQL can be found at:
https://wwwn.cdc.gov/Nchs/Nhanes/2007-2008/VOCWB_E.htm
https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/VOCWB_D.htm
*/
